### ISSUE TITLE
warning on no rule to process header file

### ISSUE THREAD

**Issue by anonrig** [OneSignal/OneSignal-Cordova-SDK#101]
warning: no rule to process file '/Plugins/onesignal-cordova-plugin/OneSignalPush.h' of type sourcecode.c.h for architecture arm64

**Comment by JKalash** [comment]
Hi there,

You should make sure that there is no header files in your **Build Phases**. Clean and build again and you should be good to go!

**Comment by TheStalwart** [comment]
I can reproduce this. Regenerating platform doesn't resolve the issue.
