### ISSUE TITLE
[Bug]: "The archive did not include a dSYM for the OneSignalUser.framework" (Distributing Archive to App Store from Organizer)

### ISSUE THREAD

**Issue by dwengs** [OneSignal/OneSignal-Cordova-SDK#1027]
### What happened?

This could be expected behaviour, but maybe there is something you can do about this.

- When I tried to send/distribute the Archive from Organizer window on Xcode, the sending process **succesfully completes** with warnings.
- The warning is like: "Upload Symbols Failed - The archive did not include a dSYM for the OneSignalUser.framework with the UUIDs [{uuids here}]. Ensure that the archive's dSYM folder includes a DWARF file for OneSignalUser.framework with the expected UUIDs.
- I got the same warning 10 times only with different UUID's.
- App works with no problems, Push notifications etc. working.

Same behavior examples in past 2 weeks (Apple Engineer also replied):
- https://forums.developer.apple.com/forums/thread/763972
- https://developer.apple.com/forums/thread/761589?page=1#802692022
- https://developer.apple.com/forums/thread/761589?answerId=806733022#806733022

### Steps to reproduce?

```Markdown
1. Update Xcode to v16
2. Create Cordova App with iOS platform
3. Add onesignal-cordova-plugin 5.2.6
4. Open iOS platform folder/project with Xcode
5. Enter app details & version, select certs and profiles, update icons
6. Clean Build folder and Archive
7. Open Organizer window
8. Select the newly created Archive and click Distribute App
9. Select "Test Flight Internal Only" and "Distribute"
10. Get warnings.
```

### What did you expect to happen?

No warnings, just green OK checkbox would do ok :)

### OneSignal Cordova SDK version

5.2.6

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
Upload Symbols Failed
The archive did not include a dSYM for the OneSignalUser.framework with the UUIDs [***]. Ensure that the archive's dSYM folder includes a DWARF file for OneSignalUser.framework with the expected UUIDs.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gelinger777** [comment]
bump

**Comment by gelinger777** [comment]
@dwengs  did you found any solution to this ?

**Comment by dwengs** [comment]
No, but on the Apple forums, they say it can be ignored by users like us so I ignored it and build without any other issues and errors. According to them, this warnings messages are normal on newer Xcode versions and only be fixed by plugin authors.

**Comment by nan-li** [comment]
Thanks for reporting, yes this is a new warning as of Xcode 16, and can be safely ignored.
We did include debug symbols starting in the latest [Release 5.2.8](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.2.8).
