### ISSUE TITLE
Method 'enableNotificationsWhenActive:' not defined in Plugin 'OneSignalPush'

### ISSUE THREAD

**Issue by sjorsroelofs** [OneSignal/OneSignal-Cordova-SDK#103]
Hi,

I'm using the OneSignal plugin inside my Ionic 2 (RC0) application. When I use the code provided by the Ionic docs (updated today), I get the following error:
```
ERROR: Method 'enableNotificationsWhenActive:' not defined in Plugin 'OneSignalPush'
```

It looks like the OneSignal plugin doesn't implement a method. For more info, view this message: https://github.com/driftyco/ionic-native/issues/649#issuecomment-253169194

Thanks.

Offtopic: this is another notification I see in the console when running on iOS:
```
THREAD WARNING: ['OneSignalPush'] took '28.413086' ms. Plugin should use a background thread.
```

**Comment by jkasten2** [comment]
@sjorsroelofs @ramonornela `enableNotificationsWhenActive` was removed in the 2.0 SDK and has been replaced with [inFocusDisplaying](https://documentation.onesignal.com/docs/cordova-sdk#section--infocusdisplaying-).

The warning is normal as Cordova is very picky about even the shortest startup delay.

Thanks.

**Comment by ramonornela** [comment]
Then the method can be deleted 😉 https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/www/OneSignal.js#L129

Thanks

**Comment by sjorsroelofs** [comment]
Awesome, thanks!
