### ISSUE TITLE
[question]: How do I do identity verification?

### ISSUE THREAD

**Issue by MysticalX21** [OneSignal/OneSignal-Cordova-SDK#1030]
### How can we help?

`window.plugins.OneSignal.setExternalUserId` is not defined but `window.plugins.OneSignal.login` is.

However, only the `setExternalUserId` method seems to support [identity verification according to the OneSignal docs.](https://documentation.onesignal.com/v9.0/docs/identity-verification#:%7E:text=Security%20feature%20to%20authenticate%20your,server%2C%20if%20you%20have%20one.)

So how am I supposed to do identity verification (as in, `OneSignal.setExternalUserId(external_id, external_id_hash)`)? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @MysticalX21 thanks for your patience. We recently released identity verification betas for our native SDKs and are working on getting out a beta for Cordova this month as well. Be sure to check out our future [releases](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases) for when it is available!

**Comment by leonluc-dev** [comment]
@jennantilla Has there been any update on this? I see a beta has been released for iOS back in june, but I haven't been able to find one yet for Cordova and/or Android.

**Comment by nan-li** [comment]
Hi @leonluc-dev, we have the latest Android native beta version that supports Identity Verification in [5.2.0-beta-06](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.2.0-beta-06).

There is no update for Cordova yet.
