### ISSUE TITLE
[Bug]: Ionic Cordova onesignal Asset validation failed iOS upload issue

### ISSUE THREAD

**Issue by GauravGosai20** [OneSignal/OneSignal-Cordova-SDK#1031]
### What happened?

facing issue to upload on ios TestFlight xcode version 16.1 macOS 15.0

xcrun bitcode_strip -r platforms/ios/YourApp/Plugins/YourFramework.framework/YourFramework -o platforms/ios/YourApp/Plugins/YourFramework.framework/YourFramework

already tried bitcode_strip command but also that didn't work.

The following issues occurred while distributing your application.
       Asset validation failed
                Invalid Executable. The executable 'Lynch Syndrome.app/Frameworks/OneSignal.framework/ OneSignal' contains bitcode. (ID: fda6a528-a835-4b16-8252-893d8d16acbd)

### Steps to reproduce?

```Markdown
create build , upload it on testflight and you'll get error
```

### OneSignal Cordova SDK version

Release 3.3.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

![Screenshot 2024-11-11 at 8 28 53 PM](https://github.com/user-attachments/assets/4aef014f-c163-40c8-9398-2d0c567ea586)

**Comment by repotoolsapps** [comment]
same error

**Comment by GauravGosai20** [comment]
i have fixed the issue just update the onesignal plugin to latest version.
