### ISSUE TITLE
NotificationReceivedHandler doesn't work properly

### ISSUE THREAD

**Issue by AlessandroBuoscio** [OneSignal/OneSignal-Cordova-SDK#104]
Hello,
I installed the latest version of OneSignal (2.0.6). Unfortunately there is a problem: NotificationReceivedHandler doesn't work properly. 

Handler execute the function only if the app is in the foreground but i would like to execute the function also the app is in the background or closed.

**Comment by jkasten2** [comment]
@AlessandroBuoscio This a limitation of Cordova. You will need to add your own native code to handle the received event of notifications when your app is closed.

Android: See [Background Data and Notification Overriding](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding).

iOS: `content-available` or `mutable-content` can be used.

**Comment by AlessandroBuoscio** [comment]
@jkasten2 Now it works but when i close and reopen the app, NotificationReceivedHandler doesn't work in background.

**Comment by jkasten2** [comment]
@AlessandroBuoscio `NotificationReceivedHandler` was designed to only work in the foreground. Could you let us know the steps you are taking where it was working in the background? Include the OS version you are testing on as well.

Thanks.

**Comment by jkasten2** [comment]
@AlessandroBuoscio Feel free to reopen if you are seeing the callback not firing when your app is in focus. Or if you need any additional information on processing data in the background with native code.
