### ISSUE TITLE
IPv6 Support in Plugin

### ISSUE THREAD

**Issue by eugenedw** [OneSignal/OneSignal-Cordova-SDK#105]
One of the requirements recently announced by Apple was to ensure that IPv6 capabilities are enabled in apps deployed to the app store. 

The guidance provided in https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html (about halfway down the page) stipulates removal of IPv4-specific APIs. 

It also states that developers should ensure IPv6 address types are handled properly. Our app was recently rejected because of failures in the IPv6 negotiation. I could find no other place than the OneSignal plugin that would point to a networking incompatibility issue. 

When setting up the "OneSignalReachabilty" configuration (in the OneSignalReachability.m) file, it appears that the code specifically defines capabilities for IPv4 handling, but not IPv6 (in the reachabilityForInternetConnection method). Are there plans to address this?

**Comment by jkasten2** [comment]
@eugenedw We haven't received any other reports of this from our developers. The readability code is just for detecting network types. It isn't used to establish a connection, we use [`NSURLConnection`](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/2.0.6/src/ios/OneSignalHelper.m#L688) which works for both IPv4 and IPv6 connections.

Thanks.

**Comment by jkasten2** [comment]
@eugenedw Feel free to reopen this issue if you are still encountering a problem.
