### ISSUE TITLE
OneSignal cordova plugin gives error on Android permission

### ISSUE THREAD

**Issue by basvdijk** [OneSignal/OneSignal-Cordova-SDK#106]
When running ionic build android --release it gives an error on the OneSignal plugin

I've reported this issue at Ionic: https://github.com/driftyco/ionic-native/issues/707 They stated that it is not an Ionic problem.

Short description of the problem:
```
ionic-app/platforms/android/AndroidManifest.xml:21: Error: The <uses-permission> element must be a direct child of the <manifest> root element [WrongManifestParent]

        <uses-permission android:name="com.amazon.device.messaging.permission.RECEIVE" />
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


   Explanation for issues of type "WrongManifestParent":
   The <uses-library> element should be defined as a direct child of the
   <application> tag, not the <manifest> tag or an <activity> tag. Similarly,
   a <uses-sdk> tag must be declared at the root level, and so on. This check
   looks for incorrect declaration locations in the manifest, and complains if
   an element is found in the wrong place.


   http://developer.android.com/guide/topics/manifest/manifest-intro.html
```
Which is on line 55 in ionic-app/plugins/onesignal-cordova-plugin/plugin.xml

**Comment by jkasten2** [comment]
@basvdijk Can you make sure you are running the latest 2.0.6 version of our SDK? We fixed this issue in 2.0.

**Comment by basvdijk** [comment]
@jkasten2 I tried via:
```
bash-3.2$ ionic plugin add onesignal-cordova-plugin                                                                                                                                                      
Fetching plugin "onesignal-cordova-plugin@~1.13.2" via npm
```

It looks like it is grabbing an older version or something

**Comment by jkasten2** [comment]
@basvdijk Can you try the following.
```
ionic plugin update onesignal-cordova-plugin
ionic plugin list
```

If it doesn't show the new version try removing it and re-adding it.
```
ionic plugin rm onesignal-cordova-plugin
ionic plugin add onesignal-cordova-plugin
```

**Comment by basvdijk** [comment]
@jkasten2 Thanks! running `ionic plugin update onesignal-cordova-plugin` gives me `onesignal-cordova-plugin 1.13.2 "OneSignal Push Notifications"` is this the correct version?

**Comment by jkasten2** [comment]
@basvdijk It should be 2.0.6. It seems npm maybe just pulling from a cache version. You can try the following to get a specific version.
```
cordova plugin add onesignal-cordova-plugin@2.0.6
```

If that doesn't work you may need to look into updating npm and Cordova on your system. Also note that the 2.0 version of our plugin has new setup instructions.
https://documentation.onesignal.com/docs/cordova-sdk-setup

**Comment by basvdijk** [comment]
Thanks! It looks like I now have the correct version :)
