### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by Notifium** [OneSignal/OneSignal-Cordova-SDK#108]
Hi,
I've tried updating the plugin (as per your instructions: "ionic plugin update onesignal-cordova-plugin"), and also removing and re-adding the plugin, but I'm getting version 1.13.2, not the latest version. I've update the CLI and the android platform, but no change.

Any ideas why this might be happening?

Regards,
Andy

**Comment by jkasten2** [comment]
@Notifium You many need to remove and re-add the plugin.
```
cordova plugin rm onesignal-cordova-plugin
cordova plugin add onesignal-cordova-plugin
```

Then check the version.
```
cordova plugin list
```

**Comment by Notifium** [comment]
Hi, I tried that as well, although I did that and then upgraded the CLI and android platform. I'll try removing and adding the plugin again tonight now that the platform is upgraded.

Thinking about it, if that doesn't work, I'll add the plugin via the git URL and see what happens.

I'll report back on once I've had time to do this.

**Comment by Notifium** [comment]
Tried rm / add again after updating the platform / CLI yesterday, still no change. However, I added via the .git URL, and it's updated to the latest version. So I've got the in the end, but still no idea why "ionic plugin update" didn't work.

**Comment by jkasten2** [comment]
@Notifium Not sure, but glad you were able to get up and running with it.
