### ISSUE TITLE
moving to newer version

### ISSUE THREAD

**Issue by vespino** [OneSignal/OneSignal-Cordova-SDK#109]
I'm updating an app and found out the workings of the plugin have changed. I figured most of it out right now but am still wondering about the following:

This is my new init:

```
window.plugins.OneSignal
    .startInit("app_id", "")
    .handleNotificationReceived(function(jsonData) {
        alert(JSON.stringify(jsonData));
    })
    .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
    .endInit();
```

What should I add to handleNotificationReceived to display the notification?

```
navigator.notification.alert(jsonData.message, nothing, 'Hardstyle', 'Close'); ??
```

or

```
navigator.notification.alert(jsonData.payload.body, nothing, 'Hardstyle', 'Close'); ??
```

In the old version I used jsonData.isActive===true to check if the app was open. How can I do this in the new version? I'm basically looking for a new version of the following :)

```
didReceiveRemoteNotificationCallBack : function(jsonData) {
    //set redirect
    if(jsonData.additionalData.page) {
        redirect=jsonData.additionalData.page;
        title=jsonData.additionalData.title;
        label1=jsonData.additionalData.label1;
        label2=jsonData.additionalData.label2;

        //slug
        slug=getParameter('slug', redirect);
    }

    check();

    if(jsonData.isActive===true) {
        if(redirect && label1 && label2) {
            navigator.notification.confirm(
                jsonData.message,
                function(button) {
                    if(button==1) {
                        $.mobile.changePage(redirect, { transition: 'fade' });
                    }
                },
                title,
                [label1,label2]
            );
        }else navigator.notification.alert(jsonData.message, nothing, 'Pannenkoekenhuizen', 'Sluiten');
    }else $.mobile.changePage(redirect, { transition: 'fade' });
}
```

Another question: is the payload the same on all platforms and can I find documentation on the contents of the payload?

**Comment by vespino** [comment]
Any news on this?

**Comment by jkasten2** [comment]
You will want to use `jsonData.payload.body` in the [NotificationReceivedHandler](https://documentation.onesignal.com/docs/cordova-sdk#section--notificationreceivedhandler-) as you get a [OSNotification](https://documentation.onesignal.com/docs/cordova-sdk#section--osnotification-) which contains a nested `payload` object.

You can now use `jsonData.shown` instead of `jsonData.isActive`. If `shown` is `false` you will need to display it in your app otherwise the user will never see it.

The payload will be the same on all versions of iOS and Android.

**Comment by vespino** [comment]
Can I find a complete overview of the jsonData object somewhere?

**Comment by vespino** [comment]
Shouldn't it be something like this?

    if(jsonData.isAppInFocus===true) {
        //show message inside app
    }

**Comment by vespino** [comment]
The following does nothing when the app is opened:

	window.plugins.OneSignal
		.startInit('<id>', '')
		.handleNotificationReceived(function(jsonData) {
			if(jsonData.shown===false) {
				navigator.notification.alert(
					(jsonData.payload.body ? jsonData.payload.body : jsonData.payload.title),
					nothing,
					(jsonData.payload.body ? jsonData.payload.title : 'Hardstyle'),
					'Close'
				);
			}
		})
		.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
		.endInit();

Why did you have to change it? It used to work fine! Why use title when content is not used? This is all so unclear.

When I alert the jsonData object I don't see the "isAppInFocus" value. It seems like it isn't there. "shown" always seems to be true, so what you said 3 posts back doesn't seem to be correct.

Help?

**Comment by jkasten2** [comment]
@vespino In your example code above `jsonData.shown` will always be `true` since you have the following set.
```javascript
.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
```

The only time `jsonData.show` will be `false` if is if you set `inFocusDisplaying` to `None`.
```javascript
.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
```

There is an open issue for `isAppInFocus` (issue #102) which we will update when this value is correctly set for both Android and iOS.

**Comment by vespino** [comment]
@jkasten2 when using the following code, there is no "shown" in the jsonData object:

	window.plugins.OneSignal
		.startInit('<id>', '')
		.handleNotificationReceived(function(jsonData) {
			alert("Notification received:\n" + JSON.stringify(jsonData));

			if(jsonData.additionalData.page) {

			}

			if(jsonData.shown===false) {
				navigator.notification.alert(
					(jsonData.payload.body ? jsonData.payload.body : jsonData.payload.title),
					nothing,
					(jsonData.payload.body ? jsonData.payload.title : 'Hardstyle'),
					'Close'
				);
			}else navigator.notification.alert('Notification when app was closed', nothing, 'Hardstyle', 'Close');
		})
		.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
		.endInit();

But no alert is shown within:

    if(jsonData.shown===false) { }

I really don't get it anymore. Why change a perfectly good working system? This is costing me so much time on trial and error.

**Comment by vespino** [comment]
I see a new version has just been released which brings "isAppInFocus". Nice, but in my case the notification shows or it doesn't, there is now way to catch the notification and do with it what I would like. This is the code I'm using:

	//OneSignal
	window.plugins.OneSignal
		.startInit('appid', 'googleid')
		.handleNotificationReceived(function(jsonData) {
			//alert("Notification received:\n" + JSON.stringify(jsonData));
			
			if(jsonData.additionalData.page) {
				
			}
			
			if(jsonData.isAppInFocus===true) {
				navigator.notification.alert(
					jsonData.payload.body,
					nothing,
					(jsonData.payload.title ? jsonData.payload.title : 'Hardstyle'),
					'Close'
				);
			}
		})
		.handleNotificationOpened(function(jsonData) {
			//Use to process a OneSignal notification the user just tapped on.
		})
		.endInit();

This shows the native "InAppAlert". Even when I comment out the isAppInFocus part, the InAppAlert is shown. When adding the following, nothing is done:

    .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)

When adding the following, only the statusbar notification is shown:

    .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)

What do I need to do to use my own way of showing the notification?

**Comment by vespino** [comment]
So I guess this doesn't work?

"If you will be displaying your own in app message when a notification is received make sure to call inFocusDisplaying with None to disable OneSignal's in app AlertBox."

**Comment by jkasten2** [comment]
@vespino Adding the following will keep our SDK from displaying a notification when your app **is in focus** on both Android and iOS with our 2.0.7 version.
```javascript
.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
```

Full code I used to confirm it omits the SDK alert and notification.
("notif received by app's javascript" will print as an alert to confirm the callback is working)
```javascript
  window.plugins.OneSignal
    .startInit("b2f7f966-d8cc-11e4-bed1-df8f05be55ba")
    .handleNotificationOpened(notificationOpenedCallback)
    .handleNotificationReceived(function(jsonData) {
      alert("notif received by app's javascript : " + JSON.stringify(jsonData));
      console.log('Did I receive a notification: ' + JSON.stringify(jsonData));
    })
    .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
    .endInit();
```

Can you confirm your project has this version by running the following?
`cordova plugin list`

**Comment by vespino** [comment]
@jkasten2 strange, I don't see the difference with my code compared to yours, but yours works so I'll go with that. Thanks!

**Comment by vespino** [comment]
@jkasten2 oh F me... it was this piece of code:

    if(jsonData.additionalData.page) {
				
    }

**Comment by vespino** [comment]
The following give undefined:

    alert("Notification received:\n" + JSON.stringify(jsonData.additionalData));

I am passing this data using your interface. What could this be?

**Comment by jkasten2** [comment]
@vespino You will want to use `jsonData.payload.additionalData` in the [NotificationReceivedHandler](https://documentation.onesignal.com/docs/cordova-sdk#section--notificationreceivedhandler-) as you get a [OSNotification](https://documentation.onesignal.com/docs/cordova-sdk#section--osnotification-) which contains a nested `payload` object.

**Comment by vespino** [comment]
@jkasten2 is it just me or is the documentation unclear on this?

**Comment by vespino** [comment]
@jkasten2 so I got the additionalData to work, but the following doesn't:

	.handleNotificationOpened(function(jsonData) {
		//alert("Notification received:\n" + JSON.stringify(jsonData));
		alert(jsonData.payload.additionalData.page);
									   
		//redirect
		if(jsonData.payload.additionalData.page) {
			$.mobile.changePage(jsonData.payload.additionalData.page, { transition: 'slide' });
		}
	})

The following does show the additionalData in the payload but it seems to have an extra "noticatication":

    alert("Notification received:\n" + JSON.stringify(jsonData));

The following does nothing:

    alert(jsonData.payload.additionalData.page);

I have also tried the following, which also doesn't do anything:

    alert(jsonData.notification.payload.additionalData.page);

I must be doing wrong, but I'm afraid your documentation doesn't help me.

**Comment by jkasten2** [comment]
@vespino Let us know if you have any feedback on how we can import it. Thanks.

**Comment by vespino** [comment]
@jkasten2 what do you mean by "how we can import it."? My issues are solved now, I would suggest you put an example of the payloads in your documentation for the "handleNotificationOpened" and "handleNotificationReceived" handlers, this would clear up a lot I think.

**Comment by fermocar1025** [comment]
Try this, it worked

alert("" + jsonData.notification.payload.body);
window.location.replace( jsonData.notification.payload.additionalData.targetUrl );

**Comment by ekambarrao** [comment]
@jkasten2, the jsonData of notificationcallback has "action":{"type":0},.... Now this integer value without double quote is not getting parsed by Json.Parse(). do I have to write my own code of parsing stringify of json object with substrings operations? What would you suggest me to do!?
