### ISSUE TITLE
Can't seem to get clearOneSignalNotifications() to work

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#111]
Hi,

We want to clear **ALL** OneSignal notifications from our app after it starts up. On IOS the app seems to do this automatically which is fine. On Android, notifications appear to be left when the app starts. 

We have searched through this plugin and can see references to clearOneSignalNotifications() in release notes and stuff #63 and #65 but we can't seem to work out how to call the function.

Googling shows us

https://github.com/OneSignal/OneSignal-Cordova-SDK/search?utf8=%E2%9C%93&q=clearOneSignalNotifications&type=Code

We've tried window.plugins.OneSignal.clearOneSignalNotifications() which gives the error message 
TypeError: window.plugins.OneSignal.clearOneSignalNotifications is not a function

I'm sure we've missed something simple but we're puzzled and admit defeat. Any suggestions welcomed.

Thanks

Rob

**Comment by rwillett** [comment]
After digging into the code some more we can see that 

plugins/onesignal-cordova-plugin/www/OneSignal.js

holds the function definitions and that 

./src/android/com/plugin/gcm/OneSignalPush.java

holds the actual Java source for the Android version. 

We can see that clearOneSignalNotifications is defined in ./src/android/com/plugin/gcm/OneSignalPush.java

but is not defined in OneSignal.js

We tried to add the code definition for clearOneSignalNotifications to OneSignal.js with 

```
OneSignal.prototype.clearOneSignalNotifications = function(onSuccess, onFailure) {
    if (onSuccess == null)
        onSuccess = function() {};

    if (onFailure == null)
        onFailure = function() {};

    cordova.exec(onSuccess, onFailure, "OneSignalPush", "clearOneSignalNotifications", []);
};
```
but not surprisingly this didn't work :) 

Is there a reason for clearOneSignalNotifications not being in OneSignal.js?

Rob

**Comment by rwillett** [comment]
After looking through the code and the commits (or rather the lack of commits), it appears that 
```
clearOneSignalNotifications()
```
was/is not part of the official release and was offered as a patch which was not committed.

So questions:

1. Is there anyway to remove all OneSignal notifications when the Android app starts up? We've read the docs and the client and server API's and can't see anything. We though that there might be a way of using a side effect such as setting the badge count to 0, but that function doesn't seem to exist.

2. If the above isn't possible is there anyway to implement clearOneSignalNotifications() in the 'official' release?

3. Any other way to replicate the iOS behaviour on Android?

Thanks

Rob

**Comment by rwillett** [comment]
We now have got clearOneSignalNotifications to work by editing every OneSignal.js file and adding in 
```
OneSignal.prototype.clearOneSignalNotifications = function() {
    cordova.exec(function(){}, function(){}, "OneSignalPush", "clearOneSignalNotifications", []);
};
```

Our approach is not the right one, but it's got us over this hump whilst we work out what to do next.

Our question of can clearOneSignalNotifications() be implemented still stands.

Rob

**Comment by jkasten2** [comment]
@rwillett Thanks for looking into this. We will add a `clearAllNotifications` function in  a future update. It will clear all notifications as iOS can not clear only OneSignal notifications like Android can.

Thanks.

**Comment by rwillett** [comment]
Thats fine. I understand that,.

Rob
