### ISSUE TITLE
Android - Missing groupedNotifications 

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Cordova-SDK#113]
`groupedNotifications` is part of the Android native notification opened event but is missing from the Cordova callback.

**Comment by Aehrraid** [comment]
Need that a lot!

Is it safe to use the notification-object and notification.payload-object so long? The content is the same for every message in one group, so that should work out, right?

**Comment by jkasten2** [comment]
@Aehrraid Correct, that won't change. Those values will be from the latest message in the group.

**Comment by jkasten2** [comment]
@Aehrraid Just released 2.0.7 which includes a fix for this issue.
