### ISSUE TITLE
All notifications are cleared after selecting one in IOS

### ISSUE THREAD

**Issue by ChadHelbling** [OneSignal/OneSignal-Cordova-SDK#118]
We've encountered a minor bug where if a user has any notifications for our app and then opens the app, all notifications for that app are cleared from the notifications tray in iOS. We've tested other apps to ensure this isn't default iOS behavior. We're currently on version 2.0.7 of the Cordova SDK.

**Comment by jkasten2** [comment]
@ChadHelbling Are you setting a badge value in your app or with a push notification? Our SDK automatically clears the badge value when the app is opened / resumed. This has a side effect on iOS which clears all notifications for the app however.

**Comment by ChadHelbling** [comment]
@jkasten2 We are. We got your reply in your support chat on the onesignal site. We will try setting OneSignal_disable_badge_clearing in the plist. Thanks.

**Comment by jkasten2** [comment]
@ChadHelbling Sounds like this solution works for you. Feel free to open this issue if there is anything else related unsolved.
