### ISSUE TITLE
Notifications with media can't be cleared in iOS 10

### ISSUE THREAD

**Issue by felipecousin** [OneSignal/OneSignal-Cordova-SDK#120]
All notifications that are sent in iOS 10 can't be cleared. When we tap the clear button, the notification disappears for some seconds, but then shows up again.. The only way to clear it is opening the notification, which opens the app and shows an inAppAlert with the notification (that also is not right)

We are just sending to the test users setting the title, ios10 subtitle, content and an image url as media

**Comment by jkasten2** [comment]
@felipecousin Are you using Cordova locally or a cloud build system like PhoneGap Build (PGB)? If you are doing so local what version of Xcode are you using? Please also include the exact version of iOS you are seeing the issue on. 10.1.1?

Lastly make sure you don't have any other notification plugins in your project by running the following.
`cordova plugin list`

Thanks.

**Comment by felipecousin** [comment]
@jkasten2 I am using Cordova locally.. Xcode version 8.1 and iOS 10.1.1.. I am using the plugin cordova-plugin-dialogs 1.3.0 "Notification" too show some dialogs inside the app, should that be a problem? 

Thanks!

**Comment by Neto-Pavanini** [comment]
I have the same problem

**Comment by jkasten2** [comment]
@felipecousin @Neto-Pavanini We fixed this issue in our native SDK and will be adding it to our next Cordova SDK update which is scheduled to be released next week.

**Comment by juergengunz** [comment]
Any news about the release to fix this issue?

**Comment by jkasten2** [comment]
Fixed in commit 5e6afa1a37fadf227c58ab46369b8dd7685aa907 and included in the 2.0.9 release.
