### ISSUE TITLE
Notification opened callback additionalData returns String vs JSON

### ISSUE THREAD

**Issue by sundbry** [OneSignal/OneSignal-Cordova-SDK#122]
Hi,

Thank you for providing this cordova plugin 💯 

The Android implementation differs from iOS for the "notification opened" callback. On Android this callback returns a string for the notification.payload.additionalData, which is inconsistent with the iOS platform, which returns the additionalData parsed as JSON.

**Comment by jkasten2** [comment]
@sundbry This was the case for Android before our [2.07 SDK](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.0.7). Can you make sure you are using our latest 2.0.8 SDK?

**Comment by atorgfr** [comment]
Same issue and it was the problem of sdk. 2.0.6 -> 2.0.8 fix the problem. Thx @jkasten2

**Comment by jkasten2** [comment]
@atorgfr Good to hear! Thanks for verifying.

@sundbry Feel free to reopen this thread if you continue to see any issues related to the JSON format between iOS and Android.
