### ISSUE TITLE
[intelxdk] Error: Plugin OneSignal Push Notifications cannot be added. The plugin contains Gradle scripts.

### ISSUE THREAD

**Issue by runbb** [OneSignal/OneSignal-Cordova-SDK#123]
message error :
"
Error: Plugin OneSignal Push Notifications cannot be added. The plugin contains Gradle scripts.
"

platform android
intel xdk

**Comment by jkasten2** [comment]
@runbb Do to this specific Intel XDK limitation you must use our branch below.
https://github.com/one-signal/OneSignal-Cordova-SDK.git#PGB-Compat

Full Intel XDK instructions below.
https://documentation.onesignal.com/docs/intel-xdk-setup

**Comment by runbb** [comment]
i follow install step by step and problem not fixed
