### ISSUE TITLE
Windows Phone does not register

### ISSUE THREAD

**Issue by widonwaker** [OneSignal/OneSignal-Cordova-SDK#124]
I tried with a blank project, usind latest version of SDK. Initialization works on ios and android, not on windows phone 8.1

you can test the project here: https://github.com/widonwaker/test

I use Phonegap Build.

**Comment by jkasten2** [comment]
@widonwaker We have updated our Windows Phone 8.1 instructions for PhoneGap Build (PGB). The changes are as follows for your `config.xml`.

```xml
<preference name="phonegap-version" value="cli-6.1.0" />
<preference name="windows-appx-target" value="8.1-phone" />
<preference name="WindowsToastCapable" value="true" />
```

https://documentation.onesignal.com/docs/phonegap-sdk-setup

**Comment by jkasten2** [comment]
@widonwaker Closing to due in activity, Feel free to reopen if you are still seeing an issue.
