### ISSUE TITLE
iOS Media Notifications not received in force-quite state

### ISSUE THREAD

**Issue by juergengunz** [OneSignal/OneSignal-Cordova-SDK#126]
On some iOS devices, I do not receive any media notifications (image). 
I've installed the latest Update (2.0.9) and hoped it would be fixed, but it is not.

On my iPhone6s with iOS 10.1 Media Notifications are working fine. On my iPhone 5s tested with iOS 10.2 beta and 10.1 Notifications with attachments are not received as push but when I open the app they get displayed as inAppAlert.

**Comment by jkasten2** [comment]
For the devices you don't receive a notification at all when you add iOS 10 media attachments see this troubleshooting guide.
https://documentation.onesignal.com/docs/troubleshooting-ios#section-notifications-with-action-buttons-or-ios-10-media-not-displaying

The iPhone 5s doesn't have 3d touch however I believe you can slide left on the notification and press the view button to see the media attachment.

Can you explain the inAppAlert part in more detail? Are you not seeing a notification then as soon as you open the app an in app alert shows up? Or you sending a 2nd notification since the first did not display?

**Comment by juergengunz** [comment]
I know that guide and everything is set up correct. I have some other apps installed that uses media attachments on notifications and they do work on my iPhone 5s.

Yes you are right, you can slide left and then open them like you said.

I send a notification with an image attached, and it does not show up after couple of minutes, I open the app and the notification shows up as an in app alert.

I had one case yesterday - I sent a notification in the morning and like 10 hours later I actually received it (iPhone 5s).

**Comment by juergengunz** [comment]
@jkasten2  I did some more tests and it seems that when I restart my phone I receive some notification with media but after a while they probably get stuck and if I restart the phone again, I receive some.

**Comment by jkasten2** [comment]
@juergengunz Odd, what if you just disconnect and reconnect to your wifi / cell connection? I have seen an issue where the network connect get in a state were this fixes it.

**Comment by juergengunz** [comment]
i tested it and it doesnt seem to fix it. as said, i do receive them as in app alert when i open the app. it is weird. i wonder that nobody reported that problem before, or am i wrong?

**Comment by juergengunz** [comment]
it is working on other apps on my phone so i assumed that there is an issue with onesignal

**Comment by AshPowell** [comment]
One of my users is also experiencing this... Without Media attachment he receives them fine, but with - no luck.

Works fine for me however & all settings on his device has been checked. The only difference is hes on a newer device, though same software version.

**Comment by mikestalker** [comment]
iPhone 6 the same problem. Sending from New Message without Media url - receive notification. With Media - no notification.

**Comment by juergengunz** [comment]
@jkasten2 any update about this ?

**Comment by jkasten2** [comment]
@juergengunz Work is still being done on the iOS native SDK which is used by this SDK.
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/112

Once it is complete we will be updating our wrapper SDKs including this one.

**Comment by juergengunz** [comment]
@jkasten2 any news when it will be implemented for cordova ?

**Comment by jkasten2** [comment]
@juergengunz We are working on a few more native updates and then will start updating this SDK after.

**Comment by jkasten2** [comment]
@juergengunz @AshPowell @mikestalker This limitation has been resolved in our [latest Cordova 2.1.1 SDK](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.1.1).
