### ISSUE TITLE
Confilcit with the cordova health plugin

### ISSUE THREAD

**Issue by iAdil** [OneSignal/OneSignal-Cordova-SDK#128]
Plugin url: https://github.com/dariosalvi78/cordova-plugin-health

Attaching log:
[build.txt](https://github.com/OneSignal/OneSignal-Cordova-SDK/files/639385/build.txt)

I cant remove this plugin, so hope for your help

**Comment by jkasten2** [comment]
@iAdil Did their latest change fix this issue for you?
https://github.com/dariosalvi78/cordova-plugin-health/issues/27

**Comment by iAdil** [comment]
@jkasten2 Unfortunately not..

I also try to use you older releases, like:
	<plugin name="onesignal-cordova-plugin" source="npm"  spec="2.0.3" />

but it also doest fix my issue.

I am building my app by build.phonegap.com and i doesn't know how can i fix that problem, even older verions also doesnt help.

Any suggestions?

Thank you for your quick reply!

**Comment by iAdil** [comment]
I built my app earlier with that config without any problems

**Comment by iAdil** [comment]
Can u use the lates version of playservice?

> com.google.android.gms:play-services-fitness:+

**Comment by jkasten2** [comment]
@iAdil Looks like they have updated the plugin with `+` as well the versions will match up.
