### ISSUE TITLE
Issues in Winphone 8.1

### ISSUE THREAD

**Issue by Zapmobilegames** [OneSignal/OneSignal-Cordova-SDK#129]
Hello,
first issue:
- using 2.0.10, when I force close the app, on the online dashboard I read: device not subscribed.
When I restart the app, it appears as subscribed again.

second issue:
- Moreover, when subscribed, even if the dashboard show the message as sent, I got no notifications on my device. I also put an alert in the didReceiveRemoteNotificationCallBack but it doesn't fire.

**Comment by jkasten2** [comment]
@Zapmobilegames 

### Issue 1
I recommend removing the app from your device, checking toasts are enabled on your project, and lastly that you have successfully Associated the App with the Store. See the below link to confirm this.
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-6-windows-phone-8-1-wp8-1-

I have seen issues where subscription problems can carry over to the new build so I recommend fully uninstalling the app from the device before deploying the new build.

### Issue 2
The [handleNotificationReceived](https://documentation.onesignal.com/docs/cordova-sdk#section--handlenotificationreceived-) does not currently work for WP8.1 on our SDK. Only [handleNotificationOpened](https://documentation.onesignal.com/docs/cordova-sdk#section--handlenotificationopened-) will trigger. Make sure your app is not in focus when you send the notification.

Lastly note that the javascript function `alert` does not work on WP8.1 projects and will crash the app. You must use the following instead or a plugin that adds support for it.
```javascript
 (new Windows.UI.Popups.MessageDialog(JSON.stringify(jsonData), "Alert Body goes here!")).showAsync().done();
```

**Comment by jkasten2** [comment]
@Zapmobilegames Closing to due inactivity, feel free to reopen if you are still seeing an issue.
