### ISSUE TITLE
handleNotificationOpened not triggered after app is killed on iOS when there are buttons on notification.

### ISSUE THREAD

**Issue by Neto-Pavanini** [OneSignal/OneSignal-Cordova-SDK#130]
Following situation :
I register handleNotificationOpened with OneSignal registration after user logged into app.

Upon recieve a notification with additional data when there are buttons

Following not working situation:
I kill my app through the task switcher or the iOS is ending the app.  If I get a new notification with buttons, the handleNotificationOpened does't work. When i remove the buttons, it works normally.
In Android it Works perfectly though.

In my environment I´m using:
cordova 6.4.0 and Ionic
IOS 10.1.1
OneSignal 2.0.10

**Comment by jkasten2** [comment]
@Neto-Pavanini Is this different from your comment on [issue 121](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/121#issuecomment-265992874) where the notification is not showing at all?

**Comment by Neto-Pavanini** [comment]
@jkasten2 This is another issue.
The notifications aren´t coming only when I set it to a button and the app is closed, that is, killing it in the task switcher.
according to your answer in the 121 issue is this behaviour expected?
