### ISSUE TITLE
IOS: Reask for permission - registerForPushNotifications

### ISSUE THREAD

**Issue by oggyindahouse** [OneSignal/OneSignal-Cordova-SDK#132]
My App asks for permission via
`window.plugins.OneSignal.registerForPushNotifications();`
and a prompt modal is being shown.

When user does not grant permission once and my app asks later again via 
`window.plugins.OneSignal.registerForPushNotifications();`
modal is not shown.

**Comment by jkasten2** [comment]
@oggyindahouse Unfortunately this isn't possible, it's the iOS native notification prompt shown by iOS it self and can only prompt once. If they stay no, [getIds](https://documentation.onesignal.com/docs/cordova-sdk#section--getids-) will return a `null` `pushToken` and you know they did not accept it. You will then need to instruct the user to enable it for your app in the setting.

Thanks.
