### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by alexandreafc** [OneSignal/OneSignal-Cordova-SDK#134]
I'm trying to integrate my Platform (Outsytems) to use OneSignal but when I send my project to my cloud build my app everything works for Android version, but for iOS I receive the messsage bellow, can anyone help me?

ld: 4 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jkasten2** [comment]
@alexandreafc I haven't tried OutSystems's cloud build yet but this plugin works correctly with Adobe PhoneGap Build (PGB) and Intel XDK as well as local Cordova builds.

It looks like you created a demo project?
https://www.outsystems.com/forge/component/1698/OneSignalDemo/

Were you able to get it working with iOS?

**Comment by jkasten2** [comment]
@alexandreafc Closing to due inactivity, feel free to reopen if you are still seeing an issue.
