### ISSUE TITLE
IOS 10 not clearing notifications on startup - What are we missing?

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#135]
We're trying to get OneSignal working with our app.

We're having no problem sending notifications to our app through the OneSignal server API. 

Our simple test case is, indeed, simple.

1. Start App up 

2. Stop app by swiping up.

3. Send notifications from our server through the OneSignal server. 

4. Check that notifications are displayed on the app. 

5. Start the app up. Do not select any of the notifications that appear to be correctly displayed.

What we expect to see is:

1. Notifications appear when the app is terminated - Yes they do, they are correct.

2. When the app is started,  that ALL the notifications for our app are cleared. However they are still in the Notification Drawer. We can swipe left with them to reveal buttons and clear them, but we cannot clear them automatically when the app starts up or manually as there's no function to do this. 

We cannot believe that all OneSignal notifications have to be manually cleared one by one, so we must be missing something. We can't see a function, we can't see an option in the Server REST API to set some sort of autoclear flag. 

We've spent the last few hours going through this and can't find anything we need to do. Are we supposed to use the setBadge(1), setBadge(0) 'hack' other plugins use. There's nothing in any of the issues before (that we can find) so we assume it must be us.

Apologies if we have missed something obvious but we have looked. 

Thanks

Rob

**Comment by rwillett** [comment]
We now have some idea about the issue. We were NOT setting the badge parameters in the create notification on the server API.

```
    SendOneSignalFullNotification($ios_full_notification_array_p ,
	                          {
             	                      app_id => "<<REDACTED>>" ,
                                      include_player_ids => [] , # Device will be inserted by SendOneSignalFullNotification
                                      contents => "" , # Device will be inserted by SendOneSignalFullNotification
                                      data => {} , # Device will be inserted by SendOneSignalFullNotification
                                      ios_badgeType => "Increase" ,
	                              ios_badgeCount => 1
                                  } ,
                                  $options{"dryrun"});
```

If we set the badge parameters to "increase" and 1 then we get notifications sent, the badge parameter is set and when we open the app up, the notifications are removed. 

We think that this tells us that the setBadge side effect is used to remove the notifications from the notification drawer. 

We don't actually want to set the badge at all, is there any way to get the notifications to clear on app startup and NOT have the badge set?

Thanks

**Comment by rwillett** [comment]
Any update on this? Have we missed something fundamental? is there anyway to clear all OneSignal notifications from an IOS app without setting the badge at the server API?

Thanks

Rob

**Comment by jkasten2** [comment]
@rwillett There currently isn't a function to clear all notifications. OneSignal does clear badges when the app is opened / resumed which will clear all notifications for the app as you have noted.

However to always clear all notifications you will need to set the badge value to 1 then to 0 in your code locally.
We are planning on creating a function in a future update to do this for iOS and as well as an implantation for Android.

**Comment by rwillett** [comment]
Josh,

Thanks for this. The issue for us is that the setbadge(1) and the setbadge(0) only works IFF you have set a badge number (or an increase) in the server API request. 

If you don't set the badge during the server API call, then calling setBadge(1) and setBadge(0) doesn't actually have any affect on notifications in the notification drawer on IOS. It took a long time to find that out :)

Rob

**Comment by jkasten2** [comment]
@rwillett Setting the badge value to 1 then 0 no matter if it is done locally or through the a notification every time in our testing. This is the only way to clear notifications in iOS 9 and older and still works in iOS 10 (a new native method was added in 10).

What plugin are you using to set the badge value in Cordova? It may have additional logic which could be omitting or batching native calls which might be why it isn't working for you.

Thanks.

**Comment by rwillett** [comment]
Josh,

We use the plugin 

cordova-plugin-badge 0.7.2 "Badges"

The plugin does set the badge numbers for us when we call it (which we no longer do), but the only reason we have it at the moment is for clearing badges as needed.

We looked through the OneSIgnal documentation again and couldn't see anything that had this sort of functionality in your docs on the client side. We know we can set the badge through the OneSignal server REST interface but we don't want to set any badge number at all. Only clear the notifications out.

Thanks

Rob.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
