### ISSUE TITLE
Not receiving pushToken on iOS 10 if kOSSettingsAutoPrompt is false initially and I manually call window.plugins.OneSignal.registerForPushNotifications()

### ISSUE THREAD

**Issue by vivekpd15** [OneSignal/OneSignal-Cordova-SDK#136]
I am facing this error since upgrading to the v2 of the sdk. I used to check for notification permission using the isRemoteNotificationsEnabled() function exposed by the "cordova-diagnostic-plugin" plugin.

Now, I always receive the result as notifications not enabled. Researching a little more on it, I figured that the diagnostic plugin is doing the permission check perfectly, but the cordova onesignal plugin on calling window.plugins.OneSignal.registerForPushNotifications() and clicking on allow doesn't register the variable properly and the diagnostic plugin fails the check next time it is run.

I have also checked the diagnostic plugin in a vanilla project without onesignal and it works perfectly over there.

I am currently on v2.0.10 of onesignal plugin and v3.3.2 of the diagnostic plugin.

Tested on an iPhone 6 with iOS 10.1.1

**Comment by vivekpd15** [comment]
Hey, I digged this further and noticed that even if I allow notification prompt on iOS, I get a "Missing Push Capability" error as seen in the attached image.
![capture](https://cloud.githubusercontent.com/assets/14350316/21193841/aa6e1998-c253-11e6-837d-01c9d2c582ff.PNG)
 

I have ensured that push notifications are switched on in xcode capabilities before building.

**Comment by mohitagarwal124** [comment]
Facing the same issue, please fix it soon.

**Comment by jkasten2** [comment]
@vivekpd15 @vivekpd15 Can you also ensure you are using a new version of Cordova to build your app? Make sure you are using 6.4.0 or newer.

The `"Missing Push Capability"` status should be accurate as we check the response code and description from APNs before reporting this status on the OneSignal dashboard.

It subscribes correctly as soon as you remove `kOSSettingsAutoPrompt`?

**Comment by vivekpd15** [comment]
Thanks. That sorted the issue. Had to update the iOS platform to 4.3.1 and cordova to 6.4.0.

**Comment by jkasten2** [comment]
@vivekpd15 Thanks for the information, looks like this issue is solved now so closing.

@mohitagarwal124 Feel free to reply if this did not work for you.
