### ISSUE TITLE
ionic run failed after remove/add platform

### ISSUE THREAD

**Issue by kazsharp** [OneSignal/OneSignal-Cordova-SDK#137]
1. ionic plugin add onesignal-cordova-plugin
2. ionic platform remove ios
3. ionic platform add ios
4. ionic build

The following error occurred
(Of course, there is no error that execute "ionic build" before 2)

** ARCHIVE FAILED **

The Following build commands failed:
            Check dependencies
(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconifg, ....

**Comment by jkasten2** [comment]
@kazsharp Can you try running the following after 3. to see if it fixes this state.

- `ionic plugin rm onesignal-cordova-plugin`
- `ionic plugin add onesignal-cordova-plugin`

Include your Ionic and cordova version if this doesn't fix it.

**Comment by BobBDE** [comment]
@kazsharp 
Hi,

We had the same problem when we remove and add the ios plateform.

We managed to solve it by changing the version of the ios plateform.
See the versions here : https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html

The solution was solved with the version 4.1.0 of ios plateform.
Try running :
-  ionic platform rm ios
- ionic platform add ios@4.1.0

We think that the command :  ionic platform add ios install the last version (6.x) and this version caused an error. 
You can test with version 4.1.0 and see if it work. If yes you can upgrade this version and test if the project run.

**Comment by walfro** [comment]
Thanks @BobBDE, downgrading to ios@4.2.0 solved the issue.

**Comment by kazsharp** [comment]
@BobBDE

I also solved the issue.
Thank you!
