### ISSUE TITLE
Using the plugin on Android, are Amazon ADM permissions needed?

### ISSUE THREAD

**Issue by tehmaestro** [OneSignal/OneSignal-Cordova-SDK#138]
Hi, I installed the plugin and using it only on the cordova android platform. Why does the plugin add Amazon ADM permissions and intent handlers. Are these needed?
`<uses-permission android:name="com.amazon.device.messaging.permission.RECEIVE" />`

I didn't really understand where does Amazon fit into the project and if it is safe to remove there references from AndroidManifest . Are there entries just for convenience, in case I would use Amazon for push notifications?

**Comment by jkasten2** [comment]
The Amazon entries in the Android target are for PhoneGap Build since there isn't a Amazon target like Cordova CLI. They can be removed if your app isn't on the Amazon app store.

**Comment by tehmaestro** [comment]
Thank you for the quick response. I read the documentation again and it became a bit clearer.
