### ISSUE TITLE
iOS 10 image url

### ISSUE THREAD

**Issue by videmort** [OneSignal/OneSignal-Cordova-SDK#139]
In iOS 10 I don't receive the image. I set it in media the URL but I don't receive the push.

If I send one simple push without image works fine

**Comment by mcyz** [comment]
Hi, we also have this problem with ios sdk. How did you fix this issue ?

**Comment by videmort** [comment]
Hello, well, my problem was the Image Type. Some types are not allowed like SVG

**Comment by paulopinda** [comment]
Hi!
What types?

Thanks

**Comment by jkasten2** [comment]
@paulopinda The following types will work.
```
"aiff", "wav", "mp3", "mp4", "jpg", "jpeg", "png", "gif", "mpeg", "mpg", "avi", "m4a", "m4v"
```

If the notification is still showing without an image see the troubleshooting guide below.
https://documentation.onesignal.com/docs/troubleshooting-ios#section-notification-is-shown-but-media-attachments-are-not-displayed
