### ISSUE TITLE
OneSignal 2.0.5+ can't work together with j3k0/cordova-plugin-purchase

### ISSUE THREAD

**Issue by pedivo** [OneSignal/OneSignal-Cordova-SDK#140]
As an issue reported in another repository (https://github.com/j3k0/cordova-plugin-purchase/issues/537) that is related with OneSignal.

Any OneSignal version after 2.0.4 works with cordova-plugin-purchase. I don't know if that is an exclusivity of that plugin or if happens also if other plugins.

**Comment by bboldi** [comment]
I can confirm the same issue, cordova purchase plugin and onesignal 2.0.5 - 2.0.10 (current latest) will crash the ios app fairly frequently when trying to initiate purchase. When I downgraded onesignal to 2.0.4 the problem disappeared.

**Comment by jkasten2** [comment]
@pedivo @bboldi 
Can you attach the full crash log as a txt file? You can get it from the device by going to Window>Devices. Then select the iOS device on the left and press the "View Device Logs" button. You can store by Data/Time to get the latest crash log.

**Comment by bboldi** [comment]
Hey @jkasten2!

I have been trying to produce crash log with no success - I have tried to crash the app several times (running with debug from xcode / running on its own) , but no crash report is saved ...

**Comment by jkasten2** [comment]
@bboldi You are able to reproduce the crash still but just no log? Try doing so with this device disconnected from your mac. This will ensure it writes it to the device. Then reconnect the device and the log should show up.

**Comment by bboldi** [comment]
I have tried to disconnect the phone, managed to crash the app and still there's no device log entry :( maybe @pedivo can help with this ...

**Comment by jkasten2** [comment]
@bboldi @pedivo Just added a compatibility fix for iOS IAPs to our 2.0.11 version. Can you let us know if this fixes your issue?

**Comment by bboldi** [comment]
@jkasten2 that's good news :) I upgraded the plugin to 2.0.11 and cordova-plugin-inapppurchase (which had the same issue with onesignal) and everything looks on for now (I'll do some more testing today and will report if I find anything) - thanks for taking the time to work on this issue.

@pedivo can you please try with the j3k0/cordova-plugin-purchase ?

**Comment by pedivo** [comment]
Guys, sorry for the late delay. I was really busy last weeks.
 
I'll work on that today and I'll give a feedback asap.

**Comment by pedivo** [comment]
I've also upgraded and that works really fine. I've faced any problem. I'll keep watching that.

**Comment by jkasten2** [comment]
@bboldi @pedivo Thanks for confirming the fix. Feel free to reopen this issue if you see any future issues.

**Comment by bboldi** [comment]
@jkasten2 thank you!
