### ISSUE TITLE
HandleNotificationOpened does not fire on iOS

### ISSUE THREAD

**Issue by luis-ordering** [OneSignal/OneSignal-Cordova-SDK#145]
I have a problem with iOS notifications, I can not trigger the event when I click the notification, it just does not open the application and I can not opt for the notification data, this is my configuration.

**Token registration:**

`if (window.plugins && window.plugins.OneSignal){
    window.plugins.OneSignal
        .startInit(ONE_SIGNAL_ID, GCM_SENDER_ID)
        .handleNotificationOpened(notificationOpenedCallback)
        .endInit();
    window.plugins.OneSignal.getIds(function(ids) {
        GCM_DEVICE_TOKEN = ids.pushToken;
        console.log(GCM_DEVICE_TOKEN);
    });
    window.plugins.OneSignal.enableInAppAlertNotification(true);
}`

**Event:**

`var notificationOpenedCallback = function(jsonData) {
    console.log(jsonData);
}`

**The test environment is:**
- Phonegap cli-6.3.0 (4.2.0 iOS / 5.2.1 Android / 4.4.1 Windows) in Phonegap Build
- iPhone 7 (iOS 10.2.1)

**Additional Information:**
- On Android works perfectly.
- In iOS it receives the notification but does not fire the event.

**Comment by jkasten2** [comment]
@luis-ordering Can you try updating to cli 6.4.0? When tapping on the iOS notification it should always start or resume the app unless there was a crash. Can you check the XCode crash logs for one?

Also `console.log` does not always show in the Xcode log so you may wan to try `alert` instead in your `handleNotificationOpened`.

Thanks.

**Comment by luis-ordering** [comment]
I just updated it and tried with the same result, I can not opten the data of the notification, I did it with both console.log and alert, I can not get it to work, I can not understand that it is wrong.

Thanks for the reply.

**Comment by luis-ordering** [comment]
I just upgraded and tested it with the same result, I can not get the notification data, I did it with both console.log and alert, I can not get it to work, I can not understand that it is not correct.

Thanks for the reply.

**Comment by luis-ordering** [comment]
Sorry it was a mistake in JS within the event.
