### ISSUE TITLE
COLLAPSE_ID not working using Phongap Build + Android/iOS

### ISSUE THREAD

**Issue by capaccio** [OneSignal/OneSignal-Cordova-SDK#149]
Dear Support, 
i'm a Phongap Build developer and i'd like use COLLAPSE_ID in order to avoid too many notification icons. 

I use 'collapse_id' => 'MOODS' in my PHP create message function, but all my testing devices (Android and iOS) get messages NOT collapsed->many icons in the notification area.

What can I do?

TIA, Giorgio.

**Comment by jkasten2** [comment]
@capaccio `collapse_id` on Android only works server side before the device receives the notification. We will be supporting this client side in the future with an update so notification are replaced even if they have already been displayed.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/147

For iOS `collapse_id` is only supported on iOS 10 devices.

Thanks.

**Comment by jkasten2** [comment]
@capaccio This is now implemented with the 2.1.0 version of this SDK.
