### ISSUE TITLE
Feature request: provide a pauseSubscription method

### ISSUE THREAD

**Issue by fikkatra** [OneSignal/OneSignal-Cordova-SDK#150]
Currently, the setSubscription method allows to opt in or out of notifications. A great feature, but we are unable to temporarily opt out of notifications, i.e. opting out for a given period of time. Opting out is easy enough. Opting back in however, is a problem: due to the limitations of background activity of apps (especially on iOS), we are not able to opt back in, because the moment we need to opt in, the app might not be running, or the device might be offline. Therefore, it won't be possible to send the opt in request to OneSignal. This means we are opted out indefinitely, which is unacceptable.

Solution: pass a 'timeout' parameter to setSubscription, or provide a pauseSubscription method with a time frame during which notifications should be suspended.

Any workarounds are welcome too.

Additional Info:
Client uses Ionic SDK v2.0.10
Server uses REST API

**Comment by jkasten2** [comment]
@fikkatra Thanks for the suggestion. Would a daily quiet time range also work for your uses case? We have had some request for this before quiet times before and want to count this as a request as well if this works.

It would be best to handle the on the server side so the device is not woken up to process a notification that would be displayed. Also as you noted it would be more difficult to filter client side with iOS than Android.

#### Work around 1
This workaround would basically be implementing your feature on your own server but it is best for the devices battery as noted above.
Send the OneSignal userId / playerId to your server from the `OneSignal.getIds` function with your quiet time. Store these in your server's database so you can query them later. Use `include_player_ids` to send your notifications using our [create notification REST API](https://documentation.onesignal.com/reference#create-notification) call only if it has passed the quiet time.

#### Work around 2
You can filters these client side. However it would need to be done with native code by creating a plugin. For iOS 10 you can look into using [UNNotificationContentExtension](https://developer.apple.com/reference/usernotificationsui/unnotificationcontentextension) or [UNNotificationServiceExtension](https://developer.apple.com/reference/usernotifications/unnotificationserviceextension). For Android you can use our `NotificationExtenderService` by following our [Background Data and Notification Overriding](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) instructions.

#### Work around 3
Both iOS and Android have a "Do Not Disturb" setting. You can instruct your users on how to enable this. For iOS it is a global on or off unfortunately. For Android specific apps can be allowed through the "Priority only" mode.

Thanks.

**Comment by fikkatra** [comment]
Hi John @jkasten2 ,

thanks a lot for looking into it! At the moment, we're implementing Work around 1 (sort of). However, it's quiet a complicated solution when implemented server-side, which would otherwise be so elegantly solved with a simple pauseSubscription method client-side. In addition, it's not really about daily quiet time. Let me explain our use case a little more in depth.

We want our app to be available offline, so people can use it even if they don't have an internet connection. This includes offline availability of notifications (we use notifications to remind them to take their medicin). Every day, users download their daily medication plan. Of course, this can only be done if they open the app. A push notification at the time of their first medication intake, helps reminding them to open the app.

Once the app is opened and the daily medication plan is downloaded, all subsequent notifications must also be sent when the user is offline. We take care of this by using local push notifications, with a plugin called cordova-plugin-local-notifications. Local notifications are scheduled for the entire medication plan, once it is downloaded. Of course, once this is done, we need to pause the remote OneSignal notifications for the rest of the day, to avoid duplicates.

So we really need both types of notifications: online (push) in case the user hasn't opened the app yet, and offline in case he has. But no duplicates should occur. Dealing with this server-side implies setting up an API, storing notifications in a database and cancelling notifications whenever necessary and re-sending the same notifications to devices for which they shouldn't be cancelled (in case a user uses multiple devices). In addition, it requires the server to be 'device-aware', something we'd hoped to avoid. A simple `pauseSubscription`, with a timeout for the remainder of the day, would me much easier and cleaner.

We've looked into silent notifications (I believe work around 3 is suggesting this?), but they require the app to run in the background, which is neither easy nor reliable.

**Comment by jkasten2** [comment]
@fikkatra Thanks for the details, from what I understand the user first opens the app and signs in but there may not be a medication plan to schedule for with only local notifications for? Once their plan is setup on your back end you then use OneSignal notifications to send pushes to remind them to open the app? After the open the OneSignal notification you could schedule your local notifications and use sendTags to set a flag so you don't send future notifications to open the app. This way you won't have worry about duplicates and trying to juggle sending the daily medication reminders from both local and push notifications.

Let me know if I didn't understand correctly.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
