### ISSUE TITLE
App stopped error when I close it

### ISSUE THREAD

**Issue by luis-ordering** [OneSignal/OneSignal-Cordova-SDK#151]
Hello,

When I open the application and then close it from the task manager, I miss an error message.

"Unfortunately, Appname has stopped"

If I remove the plugin from the list, and recompile it, it does not show me the error when closing.

Environment:
- Android 5 and 6 (ASUS Zenfone 2 and Moto G).
- Phonegap Build (Phonegap cli-6.5.0, cli-6.4.0, cli-6.3.1).
- Onesignal cordova 2.0.11

Thanks for the help.

**Comment by jkasten2** [comment]
@luis-ordering Since your getting this prompt it will show crash entry in the logcat. Can you add it as a comment to this thread? You can also screenshot it from the device or get it on your Google Play Developer console by sending the crash.

Thanks.

**Comment by jkasten2** [comment]
@luis-ordering Closing to due inactivity, feel free to reopen if you are still seeing an issue.
