### ISSUE TITLE
kOSSettingsKeyInAppLaunchURL does not work on cold start of the app

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Cordova-SDK#153]
Setting `kOSSettingsKeyInAppLaunchURL` to `false` is ignored if opening a notification cold starts the app. 

This due to the following line not using a saved value from the last time init was called.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/2.0.11/src/ios/OneSignalPush.m#L138

**Comment by rodrigoreis22** [comment]
I'm having the same problem, but with ios native sdk.

**Comment by Nightsd01** [comment]
This issue was fixed in #317
