### ISSUE TITLE
Request to include priority field in Dashboard for Android platform

### ISSUE THREAD

**Issue by pablo-gonzalez** [OneSignal/OneSignal-Cordova-SDK#154]
Hi

I have recently added this great plugin to my Ionic application.

I was able to send Push notifications using big picture and showing big text style via REST API setting priority = 10.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/10

The notification is shown on top and it is auto-expanded without user interaction.

1. Could you add the field "priority" to the Android section in Dashboard?
Most of the notiications I plan to send have big text or big picture and without PRIORITY_MAX users will not realize that they I have to expand the notification to read the whole text or view the picture.

2. Another question: is it possible to include emojis when you send notifications via REST API? How?

Thanks in advance,
Pablo

**Comment by jkasten2** [comment]
@pablo-gonzalez The auto-expansion behavior does depend on how many notifications are already shown.

1. I have added this to feature tracking system.
2. Yes, you can directly copy them into your code. Example you can copy them from this site getemoji.com

Thanks.

**Comment by pablo-gonzalez** [comment]
Thank you very much. Having that feature in Dashboard will be very helpul.

Best regards,
Pablo

**Comment by jkasten2** [comment]
@pablo-gonzalez Both the priority and ttl options have been added to the OneSignal dashboard.
