### ISSUE TITLE
silent message when app in background

### ISSUE THREAD

**Issue by dennis-b** [OneSignal/OneSignal-Cordova-SDK#156]
Hi,
I have started to use this plugin in my Ionic2 application. and its awesome.

in our app we want to have silent push message in background, meaning: when user gets message  and the app is in background then handle it by application and not show it in device messages.

can it be achieved with cordova sdk?

Thanks in advance,
Dennis

**Comment by jkasten2** [comment]
@dennis-b It is recommend to use OneSignal's tags or other filters to prevent the notification from being send to the device in the first place. This is to prevent the device from waking to just omit a notification and it will give you more meaning full open rates on the dashboard.

If you must do work on the client side before the notification is display please see this open issue for iOS.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/30

For Android the same limitation applies however if you are looking to handle this with native Java code see the below link.
https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

Thanks.

**Comment by jkasten2** [comment]
@dennis-b Closing to merge with issue #30.
