### ISSUE TITLE
getTags has possible race condition, callback is called only for the last call

### ISSUE THREAD

**Issue by NoNameProvided** [OneSignal/OneSignal-Cordova-SDK#158]
Running 
```ts
plugins.OneSignal.getTags(console.log, console.error);
plugins.OneSignal.getTags(console.warn, console.error);
```

Will write the tags to the console twice with `console.warn`.

![screen shot 2017-02-20 at pm 4 45 26](https://cloud.githubusercontent.com/assets/4706265/23131882/027e5770-f78c-11e6-9a51-bc824f49f2cb.png)

The expected behaviour would be to call both callbacks with the result not only the last one.

**Comment by jkasten2** [comment]
@NoNameProvided All functions in OneSignal only have a single callback stored for simplicity. This includes both javascript and native code. Marking this an enhancement but we won't have a chance to look into in the near future.

You will need to make sure you wait for the first call before starting another for the time being.

**Comment by NoNameProvided** [comment]
A quick look on the source of the js part, I see only 4 function which uses callbacks. So this can be easily patched on the js side. Is this open for PR?

Something like a queue manager can be a quick and dirty fix, which will call the native side in series.

```js
OneSignal.prototype.getTags = function(tagsReceivedCallBack) {
    QueueManager.push('getTags' cordova.exec.bind(this, tagsReceivedCallBack, function(){}, "OneSignalPush", "getTags", []));
};
```
 Thoughts?

**Comment by jkasten2** [comment]
@NoNameProvided For `getTags` this will work as the results are going to be the same. Just implement multiple callback handling in javascript work work in this case. Guessing `QueueManager` is your array to store functions that you will be push `tagsReceivedCallBack` on to?

This won't work for callbacks that are transactional specifically, `postNotification`. The correct function would have to be call for matching result. This would require both native and javascript changes.

I would accept a pull request for just a `getTags` and the other 3 with just javascript changes if you need support for multiple callbacks.

**Comment by NoNameProvided** [comment]
> Guessing QueueManager is your array to store functions that you will be push tagsReceivedCallBack on to?

I was thinking of a simple object / class to implement the functionality once and require it where it's needed.

> I would accept a pull request for just a getTags and the other 3 with just javascript changes if you need support for multiple callbacks.

In my opinion being consistent is more important, than patching a function. So I think making a note about this behaviour in the docs is a better option. What do you think?

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
