### ISSUE TITLE
IOS  App crash

### ISSUE THREAD

**Issue by DipakBCS** [OneSignal/OneSignal-Cordova-SDK#159]
How can I remove One Signal Object?
In my app We have multiple users in same device. For each user, I called register notification. But when I logout , other user is logged, that time other user will got notification, but crashed when tapped On Notification in IOS 10.1

Might it cause to two times registration.

**Comment by jkasten2** [comment]
@DipakBCS The device will only be registered with OneSignal once even if you call [`registerForPushNotifications`](https://documentation.onesignal.com/docs/cordova-sdk#section--registerforpushnotifications-) more than once.

I recommend calling [`setSubscription`](https://documentation.onesignal.com/docs/cordova-sdk#section--setsubscription-) with `false` to stop notifications to the device when they logout. Remember to set it to `true` when a user logs in however.

**Comment by jkasten2** [comment]
@DipakBCS Closing to due inactivity, feel free to reopen if you are still seeing an issue.
