### ISSUE TITLE
Dismiss Callback

### ISSUE THREAD

**Issue by murliatdure** [OneSignal/OneSignal-Cordova-SDK#16]
Can we have the Notification dismiss callback?

**Comment by jkasten2** [comment]
Android does have a dismiss event for a notification however I do not believe you can call into the Cordova runtime without displaying an Activity.

**Comment by murliatdure** [comment]
Rather can we have some hooks whenever the notification comes to tray, we can do some activity (for bizz handling); rather only on the tap of the item.

I seen something we do can if background=true is given; that time we can do some native coding. Do we have some options in JS rather native controls.

**Comment by jkasten2** [comment]
You can setup [Background Data notifications](https://documentation.onesignal.com/docs/android-notification-customizations#background-data-silent-notifications) with your app however you will need to write the handling code in native Java code. We don't plan on implementing background handling in Cordova as spinning up Cordova each time would put too much drain on battery.

I am not sure if it is possible to get an event in Cordova when a notification is dismissed as I don't know if Cordova allows running javascript in the background or prevent it from showing when starting the app.

Thanks.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
