### ISSUE TITLE
Google Play Services Library Error

### ISSUE THREAD

**Issue by akuljana** [OneSignal/OneSignal-Cordova-SDK#161]
Hi,

just updated my ionic app and plugins, this is the list of all plugins:
```
cordova-plugin-calendar 4.5.5 "Calendar"
cordova-plugin-camera 2.3.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-file-transfer 1.6.1 "File Transfer"
cordova-plugin-geolocation 2.4.1 "Geolocation"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.6 "SocialSharing"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.0.11 "OneSignal Push Notifications"
org.pbernasconi.progressindicator 1.1.0 "Progress Indicator"
```

Testing app on real device (ionic run android -device)
and there is an error in Onesignal (Android) users dashboard:

> Google Play Services Library Error
>  Google Play services library initialization error. Check for conflicting plugins and make sure "com.google.android.gms.version" is in your AndroidManifest.xml. Check the logcat for more details.

Are there some conflicts with some of my other plugins?
How can I solve this?

**Comment by jkasten2** [comment]
@akuljana Could you try a clean build? `onesignal-cordova-plugin` should include all parts of Google Play services it needs through gradle.
https://documentation.onesignal.com/docs/troubleshooting-cordova-variants#section-clean-build

**Comment by akuljana** [comment]
@jkasten2 tried but still not helping, changed back to my old onesignal version (1.13.2) and everything is working.

**Comment by jkasten2** [comment]
@akuljana That is very odd. Going from 1.13.2 to  2.0.11 of this plugin the Google play services `plugin.xml` lines haven't changed.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blame/master/plugin.xml#L30-L35

It should be include the exact same sets of gradle entries. Did you change anything else in your project at the same time? Upgrade the Ionic versions or change anything in the Android SDK?

**Comment by ricolo** [comment]
Just to share:

my case is opposite - I had the same error starting from a few days ago when the SDK version was still 1.13.1. I suspect it had to do with the latest Google play services update (version 10.2.98) being pushed by google to my users' phones. After updating the SDK to 2.0.11, my phone no longer has the same error.

**Comment by jkasten2** [comment]
@akuljana @ricolo Could you attach a full logtcat? `"com.google.android.gms.version"` may not be the root of the issue. Optionally you can send the log to OneSignal support along with a link to this issue.

Thanks.

**Comment by cusspvz** [comment]
Same here.

Fresh installs over `2.0.11` does not subscribe, but if the user downgrads to an app version that includes `1.13.1` it subscribes. Things keep working when upgrading again to an app with `2.0.11`.

**Comment by jkasten2** [comment]
@cusspvz Thanks for the report. If you can reproduce the issue on your device could you attach a full logcat from your device here? Alternatively you can send it to OneSignal support and include a link to this thread.

**Comment by cusspvz** [comment]
@jkasten2 For sure! Just tell me what do you need to filter. Full logcat has lots of garbage on it.

**Comment by jkasten2** [comment]
@cusspvz We prefer getting everything with no filters including VERBOSE logs. We can filter on our end. Attach it as a file as it could be a few hundred KB in size.

**Comment by cusspvz** [comment]
On the previous major version, your documentation asked for the google registration ID, but on the current documentation it seems there is no API to insert it. 
Could this be the culprit behind this issue?
```
E/OneSignal(24319): Error Getting Google Registration ID
E/OneSignal(24319): java.io.IOException: INVALID_SENDER
E/OneSignal(24319): 	at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
E/OneSignal(24319): 	at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
E/OneSignal(24319): 	at com.onesignal.PushRegistratorGPS$2.run(PushRegistratorGPS.java:151)
E/OneSignal(24319): 	at java.lang.Thread.run(Thread.java:841)
```

Could you please reach me on my personal email (available on my profile)? Or provide an email so I can send the full log.

**Comment by jkasten2** [comment]
@cusspvz We added a requirement to our dashboard to add the Google Project number / Sender ID when you configure Android on OneSignal. If you configured this before Nov you will need to add this under App Setting on the OneSignal dashboard which should fix your issue.

**Comment by cusspvz** [comment]
@akuljana @ricolo Would you mind to share how are you initializing OneSignal (please hide credentials)

**Comment by cusspvz** [comment]
It worked!! Thanks!

**Comment by akuljana** [comment]
It works, thank you!

**Comment by YaroslavG** [comment]
works for me also, thanks!

**Comment by anthonyawuley** [comment]
I deleted a subscribed Dropsource Android user from one signal. When i tried to re-connect the user, it shows "Google Play Services Library Error" on onesignal. Is there a way to fix this?

**Comment by adirzoari** [comment]
@jkasten2  i added my senderId and google server api key from firebase and I'm still facing this error. how to solve it?

**Comment by jkasten2** [comment]
@akuljana Double check the app_id in the JS code in your app. Then bring this app up on the OneSignal dashboard. Make sure you have the Android platform configured with a Google Project number / Sender id on OneSignal under Settings.

**Comment by adirzoari** [comment]
I opened new react native project and new firebase project and did step by step. still facing issue.

**Comment by adirzoari** [comment]
that's the error I get
![image](https://user-images.githubusercontent.com/20258998/40207329-9cec8b7e-5a3c-11e8-8736-fe29d9914898.png)

**Comment by yaseralimardany** [comment]
I got this error in logcat:
E/OneSignal: Unknown error getting FCM Token
java.lang.NoSuchMethodError: No static method isDeviceProtectedStorage(Landroid/content/Context;)Z in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.motoshubapp-2/base.apk)
at com.google.firebase.FirebaseApp.zza(Unknown Source)
at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
at com.onesignal.PushRegistratorFCM.initFirebaseApp(PushRegistratorFCM.java:64)
at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:50)
at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
at java.lang.Thread.run(Thread.java:818)

**Comment by athariqbal009** [comment]
Nexus (Android on Nexus 6 7.1.1 Google Play Services Library Error)

**Comment by jkasten2** [comment]
@yaseralimardany Can you make sure you are using Cordova CLI 8.0.0 as well as cordova-android@7.0.0 or newer. Also make sure you are using the latest OneSignal SDK.

You can run `cordova info` to check this.

If you are up to date already then please run `cordova plugin list` so we can try reproducing the issue.

**Comment by damonsomu** [comment]
@jkasten2 I have an Ionic 3 app and have already added the Google/Firebase Project number / Sender ID when I configured Android on OneSignal. But seeing Google Play Services Library Error on Onesignal platform for many devices. Any solution on this??
