### ISSUE TITLE
Notification not being handled when app is in focus

### ISSUE THREAD

**Issue by likemike2** [OneSignal/OneSignal-Cordova-SDK#162]
So I'm trying to handle a notification when its received AND the app is in focus.
```
var notif_opened = function(jsonData) 
	{
		alert("data:" + JSON.stringify(jsonData.notification.payload.additionalData.id));
	};
	
	var notif_received = function(jsondata)
	{
		alert("data:" + JSON.stringify(jsonData));
		console.log("data:" + JSON.stringify(jsonData)); //Not getting logged
	};
	
	window.plugins.OneSignal
		.startInit("<APP_ID>")
		.handleNotificationOpened(notif_opened)
		.handleNotificationReceived(notif_received)
		.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
		.endInit();
```
Do note that I'm calling the above on another page.
When I'm sending a notification to my device, I get the following text in Android Logcat:
`D JsMessageQueue: Dropping Native->JS message due to disabled bridge`

I'm using the latest version of Phonegap and I'm building for android 6.0, the notifications do work if the app is out of focus.

Hopefully, somebody would be kind enough to help. Huge thanks in advance!

**Comment by jkasten2** [comment]
@likemike2 You must call OneSignal.startInit().handleNotificationReceived(...).endInit() on each page load to setup the callbacks again.

**Comment by likemike2** [comment]
That fixed it. Thank you!
