### ISSUE TITLE
Notifications received when changing subscription from false -> true.

### ISSUE THREAD

**Issue by web-slinger** [OneSignal/OneSignal-Cordova-SDK#163]
Cordova SDK - 2.0.11
Android Version 7.0
HTC 10
The plugin uses Android SDK 3.4.3

The behaviour is the same on a Samsung J5 6.0.1, so it can not be isolated to OS or device.

I believe that when a user changes their subscription level the notifications that were sent whilst the user's subscription level was false then 'flood' in when they change subscription level to true.

**Comment by jkasten2** [comment]
@web-slinger This shouldn't be the case. `setSubcription` actually unsubscribes the device from the OneSignal server so it won't send new notifications to the device.

You may be seeing old notifications restored that the user never interacted with (never dismissed or opened them) when the app is cold started. Can you try swiping away the app and opening it again to confirm this?

**Comment by web-slinger** [comment]
@jkasten2 this occurred when the user was offline and set subscription to false, I would've thought this would disregard any incoming notifications in between the user changing their subscription status.

The flow of what happened is below, just in case I didn't explain it very well.

1. User unsubscribed when offline
2. Push notifications sent to device
3. User back online
4. User subscribes to notifications
5. User then receives the notifications that were sent in (2)

5 I believe shouldn't happen, I believe that the notifications won't send when subscription is false and the user is online. I think a little more logic would be required on device/SDK in the above eventuality

**Comment by jkasten2** [comment]
@web-slinger Thanks for the detailed steps, that cleared things up.

It is possible for the OneSignal Android SDK to drop them if this was set. However it would create inconsistencies with iOS since normally the app isn't run when a notification is received if the app isn't in the foreground.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
