### ISSUE TITLE
.then on iOS

### ISSUE THREAD

**Issue by vaibhavn1** [OneSignal/OneSignal-Cordova-SDK#165]
Hi 

How can we use .then function with registration of push notification. eg: I only want to go to next screen when user taps on Allow or Cancel Notification Popup.

Regards

Vaibhav

**Comment by jkasten2** [comment]
@vaibhavn1 You can call [`getIds`](https://documentation.onesignal.com/docs/cordova-sdk#section--getids-) in your app. If `pushToken` is not `null` then the user is subscribed for push.

**Comment by jkasten2** [comment]
@ricolo @oggyindahouse @aurbina83 You can now call [`promptForPushNotificationsWithUserResponse`](https://documentation.onesignal.com/docs/cordova-sdk#section--promptforpushnotificationswithuserresponse-) which will call the passed in function as soon as the user answers the permission prompt.

This was added in the Cordova 2.1.0 SDK release.
