### ISSUE TITLE
Why isn't there an isPushNotificationsEnabled method?

### ISSUE THREAD

**Issue by Birowsky** [OneSignal/OneSignal-Cordova-SDK#169]
What is the way to check whether notifications are allowed or disallowed or not asked?

**Comment by jkasten2** [comment]
@Birowsky You can use [`OneSignal.getIds`](https://documentation.onesignal.com/docs/cordova-sdk#section--getids-) and check if `pushToken` is not `null`. This means that use has enabled notifications and is successfully subscribed to OneSignal.
