### ISSUE TITLE
Platform "browser" support

### ISSUE THREAD

**Issue by vandres** [OneSignal/OneSignal-Cordova-SDK#170]
It would be really nice if the plugin would support the platform "browser". Maybe trough webpush?!

**Comment by jkasten2** [comment]
@vandres Thanks for the suggestion, the webpush SDK works different in a number of ways so we do not plan to integrate it into the Cordova SDK at this time.

However we plan to create stub functions so you don't have to wrap OneSignal calls to prevent errors.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/175
