### ISSUE TITLE
Double Notifications

### ISSUE THREAD

**Issue by jpmsegurado** [OneSignal/OneSignal-Cordova-SDK#172]
When using the rest API, if sent with the `headings` options, it generates another notification with the `headings` only, and another one with everything correct.

**Comment by jkasten2** [comment]
@jpmsegurado This will happen if another push notification plugin is installed in your app as it will parse and display the GCM / FCM message again. Run `cordova plugin list` and remove any other push notification plugins.

**Comment by jpmsegurado** [comment]
I actually had another, but I've tried this already and it didn't worked.

**Comment by Jeyakumarrathnaselvi** [comment]
We are facing the same issue. Any findings
