### ISSUE TITLE
Unexpected request for background location

### ISSUE THREAD

**Issue by Birowsky** [OneSignal/OneSignal-Cordova-SDK#173]
When certain conditions are met, the SDK requests background location, which opens permissions prompt:

<img width="303" alt="screen shot 2017-03-31 at 15 05 27" src="https://cloud.githubusercontent.com/assets/3199950/24578388/f0c10514-16df-11e7-831f-532786a6b6eb.png">

To reproduce:

1. User requires when-in-use location so the app prompts the user for permissions
2. User provides permissions
3. Restart the app

What i've noticed is that if the app doesn't have background location as a capability, this wouldn't happen.

<img width="634" alt="screen shot 2017-04-01 at 13 41 09" src="https://cloud.githubusercontent.com/assets/3199950/24578455/ead8fe8a-16e0-11e7-9675-d1e3f1eac064.png">

Here's demo: https://youtu.be/qEUpoFQeELs

And then i noticed [this issue](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/164), which points out that OneSignal SDK does do some unexpected stuff in the background.

Is there a way to disable all location stuff for OneSignal? At least as an intermediate solution for the time being?

**Comment by jkasten2** [comment]
@Birowsky Do you have any other plugins in your app that could use the location permission? Please run `cordova plugin list` and attach the full list.

Your app would only request background location if `NSLocationAlwaysUsageDescription` was set in your Xcode `.plist`

**Comment by Birowsky** [comment]
Yes, [cordova-background-geolocation](http://www.transistorsoft.com/shop/products/cordova-background-geolocation).

That's the plugin that adds the background location capability.

But to test, I removed the plugin and added the capability by hand, with OneSignal being the only suspicious plugin installed. That's when I noticed the popup.

Since then, the project got restructured, and we moved to firebase for notifications. So I can assist you only by memory.

**Comment by iliraga** [comment]
Is there any update on this? We're facing the same issue. We are using `cordova-background-geolocation` in our project.
Somehow it leads to lot of issues when the onesignal cordova plugin requests the location before the cordova-background-geolocation plugin does. Is it possible to disable the location-relevat part of the onesignal plugin completly? We don't need location-aware push notifications in this case.

**Comment by Nightsd01** [comment]
I have updated the SDK with a `setLocationShared()` function that will disable location sharing. You may want to call this function _before_ you call `endInit()`.

If anyone is still encountering this issue please feel free to reply (with a list of your plugins) and I'll be happy to investigate.

**Comment by canadaka** [comment]
We were trying to use Onesignal with our app, which also uses `cordova-background-geolocation`. The app has already been given iOS location access, but after I add the OneSignal plugin, it prompts the user again for location access. If i remove the OneSignal plugin, it doesn't.

I tried adding the `setLocationShared(false)` but it has no affect on the permission popup.

```
window.plugins.OneSignal
        .startInit(ONE_SIGNAL_APP_ID)
        .setLocationShared(false)
        .iOSSettings({kOSSettingsKeyAutoPrompt: false})
        .handleNotificationOpened(notificationOpenedCallback)
        .endInit();
```

This seems to only happen when i'm upgrading/overwriting the app with a Testflight version. If I install the app fresh from Testflight I only get a location permission dialog once, as it should be.

We wouldn't mind using the location feature, but having the app ask for permission again when users have already given it, is a non-starter for us. So unless there is a fix or solution, we can't use OneSignal.
