### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by halkoy** [OneSignal/OneSignal-Cordova-SDK#174]
hii,
I try to use it with IntelXDK as plugin. For android plugin does not build.
Error is: "plugin contains gradle scripts ?"

how can I build it?

**Comment by jkasten2** [comment]
@halkoy You need to use the PGB-Compat branch instead. Add the following Git repo.
https://github.com/one-signal/OneSignal-Cordova-SDK.git#PGB-Compat

You also need the following plugin.
https://github.com/OneSignal/OneSignal-Cordova-Dependencies-Compat

Full setup instructions for the Intel XDK below.
https://documentation.onesignal.com/docs/intel-xdk-setup#section-setup-sdk

Note that Intel XDK's build servers will be shutting down in June and will need to start building locally or with PhoneGap Build. After this won't we won't be updating the PGB-Compat version so you will need to switch back to the main branch which is the `onesignal-cordova-plugin` npm plugin.
