### ISSUE TITLE
Add stubs for "browser" target to prevent errors

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Cordova-SDK#175]
Currently app developers need to check if `window.plugins` exists before calling OneSignal when building for the browser target. This step could be eliminated if stub functions are created for the target.

**Comment by caipivara** [comment]
@jkasten2 can you explain how to avoid error on this if I have browser platform already installed?

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
