### ISSUE TITLE
branch-cordova-sdk may interfere with getting an iOS push token

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Cordova-SDK#176]
`cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=YOUR_KEY_HERE --variable URI_SCHEME=uri_scheme`

The following error is thrown by OneSignal even through it is set in the Xcode project when the above plugin is added.

```
ERROR! 'Push Notification' capability not turned on! Enable it in Xcode under 'Project Target' -> Capability.
```

**Comment by dpoquet** [comment]
I have the same error, please I need fix it!!

**Comment by jkasten2** [comment]
@dpoquet We have made a number of iOS change in our 2.1.1 SDK which may have fixed this issue. Can you try this latest version?
