### ISSUE TITLE
[iOS] Receiving a push notification during app load triggers popup

### ISSUE THREAD

**Issue by apparition47** [OneSignal/OneSignal-Cordova-SDK#177]
If you direct a APN push notification to an iOS device while it's loading (i.e. before `deviceready`, when my splashscreen is showing), a native popup will appear even though I'm using `OSInFocusDisplayOption.None`. Ideally, I don't want a popup at all.

Any ideas on how to fix this?

```javascript
// somewhere on load...
        platform.ready().then(() => {
                window.plugins.OneSignal
                .startInit(K.ONESIGNAL_APP_ID_DEV)
                .iOSSettings({
                    kOSSettingsKeyAutoPrompt: false,
                    kOSSettingsKeyInAppLaunchURL: false
                })
                .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
```

Received push notification while splashscreen showing. Notice the OneSignal SDK showing a native popup.
![image uploaded from ios](https://cloud.githubusercontent.com/assets/3298414/24878547/74dbd6f8-1de8-11e7-8126-c558ce84f169.jpg)

Using: 

* `https://github.com/OneSignal/OneSignal-Cordova-SDK.git#42483b7`
* `cordova-ios` 4.3.1
* iOS 10.3

**Comment by jkasten2** [comment]
@apparition47 Thanks for the report. We will look into default it to `Notification` while the app is starting before `OneSignal.startInit` is called.

**Comment by apparition47** [comment]
CC @Jun711 @andrewvmail

**Comment by rgomezp** [comment]
Closing this issue for now. Please let me know if you are encountering this still and we will reopen
