### ISSUE TITLE
Installation Error - Unexpected token t in JSON at position 2136

### ISSUE THREAD

**Issue by thalesware** [OneSignal/OneSignal-Cordova-SDK#178]
Greetings! please help. this error just started today (04/16/2017)

i run this command: sudo ionic plugin add onesignal-cordova-plugin --save

im trying to install the onesignal plugin in my ionic2 app but i get this error message:

**Error: Unexpected token t in JSON at position 2136**

_versions of what im using_:
mac osx el capitan 10.11.6 and xcode 8.2.1
cordova -v  =  6.5.0
ionic -v = 2.2.2
npm -v = 4.4.4

thanks in advance, thalesware !

**Comment by jkasten2** [comment]
@thalesware I recommend however doing a clean build of your project as it normally solves odd build errors.
https://documentation.onesignal.com/docs/troubleshooting-cordova-variants#section-clean-build

Please attach the full error if if provides it if you are still seeing an issue.

**Comment by jkasten2** [comment]
@thalesware Closing this issue due inactivity. Please feel free to reopen if the above solution didn't work for you.

**Comment by Gert25** [comment]
Hi I have been struggling with this issue. I opened up  a new issue but haven't been getting any attention to it. see here https://github.com/ionic-team/ionic-cli/issues/3076

**Comment by Gert25** [comment]
I have been struggling to get Ionic plugins installed correctly. But only for this one project. Seems to be working for other Ionic projects
