### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by NoNameProvided** [OneSignal/OneSignal-Cordova-SDK#186]
The latest version of the plugin cannot be installed on my Mac. The error messages is the following:

```bash
Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/attila/budacode/beauty-app/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: pod: Command failed with exit code 1
```

My environment info: (from running `ionic info` command)

```bash
global packages:

    @ionic/cli-utils : 1.0.0-rc.2
    Cordova CLI      : 7.0.0 
    Ionic CLI        : 3.0.0-rc.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0-rc.2
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.2
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 


```

**Comment by NoNameProvided** [comment]
Trying to install via cordova gives this error:
```
cordova platform add --save onesignal-cordova-plugin
Using cordova-fetch for onesignal-cordova-plugin
Adding onesignal-cordova-plugin project...
Error: Your onesignal-cordova-plugin platform does not have Api.js
```

**Comment by NoNameProvided** [comment]
Looking at the release notes, (seeing 2.1.0 was release few hours ago) its seems cocoapod support was just added. So I suspect the issue is in the plugin, not with Cordova 7.

**Comment by NoNameProvided** [comment]
And yes I can confirm, I can install the `2.1.0` version without any trouble.

**Comment by danielehrhardt** [comment]
Same here 
```
Installing "onesignal-cordova-plugin" for ios
        Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 31
            at ChildProcess.whenDone (/Users/vagrant/git/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
            at emitTwo (events.js:106:13)
            at ChildProcess.emit (events.js:194:7)
            at maybeClose (internal/child_process.js:899:16)
            at Socket.<anonymous> (internal/child_process.js:342:11)
            at emitOne (events.js:96:13)
            at Socket.emit (events.js:191:7)
            at Pipe._handle.close [as _onclose] (net.js:511:12)
        Failed to restore plugin "onesignal-cordova-plugin" from config.xml. You might need to try adding it again. Error: Error: pod: Command failed with exit code 31
```

**Comment by jkasten2** [comment]
@NoNameProvided @danielehrhardt The 2.1.1 version of the OneSignal Cordova SDK now requires CocoaPods to be installed if building for iOS.
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-ios-requirements

**Comment by mustaphaaassab** [comment]
Hi guys, 
Me too, I'm fighting with a problem like yours, there is what i get on my terminale : 
ionic platform add ios 
||
||
Installing "onesignal-cordova-plugin" for ios
Failed to install 'onesignal-cordova-plugin':undefined
Error: Version should contain only numbers and dots

**Comment by mustaphaaassab** [comment]
@danielehrhardt Try to look on OneSignal site, here : 
[https://documentation.onesignal.com/v3.0/docs/troubleshooting-cordova-variants](url)

**Comment by levarberry** [comment]
Fixed my problem by install CocoPods
`sudo gem install cocoapods`
`pod repo update`

**Comment by sonicwong** [comment]
when I run 'pod repo update', it show me:

Updating spec repo `master`
[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down

**Comment by coolvasanth** [comment]
Hi @sonicwong  Even I'm getting the same error.

**Comment by sonicwong** [comment]
@coolvasanth 
I follow Adem answer in this link, and success to install finally:
[https://stackoverflow.com/questions/38993527/cocoapods-failed-to-connect-to-github-to-update-the-cocoapods-specs-specs-repo](url)

**Comment by coolvasanth** [comment]
@sonicwong  thanks for the reply,
 but Above link is redirecting to GitHub URL with 404 status.

**Comment by sonicwong** [comment]
@coolvasanth updated link tab. try again.

**Comment by NewtonMan** [comment]
By know Sep 2018 if you face same issue, try do:
```
brew reinstall cocoapods
brew link --overwrite cocoapods
```

**Comment by jeurymejia** [comment]
> Fixed my problem by install CocoPods
> `sudo gem install cocoapods`
> `pod repo update`

Where should I execute this command? Inside the root project folder or the /platforms/ios/ directory?

Thanks

**Comment by smakinson** [comment]
I was not able to get the plugin to install with pod updates, the things in the Adem link above, etc. It finally worked after manually removing things that cordova plugin rm missed ( it did not fully complete ). I removed the plugin under node_modules and searched onesignal-cordova-plugin in my project and manually removed it from various places it was specifying the previous version. Hope this helps someone.

**Comment by ThiagoLovatine** [comment]
> By now Sep 2018 if you face same issue, try do:
> 
> ```
> brew reinstall cocoapods
> brew link --overwrite cocoapods
> ```

Still works in 2019! Thanks!

**Comment by jkasten2** [comment]
For anyone who still sees this issue or find this thread please see this https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/186#issuecomment-302207182I just updated.
