### ISSUE TITLE
Why CocoaPods?

### ISSUE THREAD

**Issue by peterel** [OneSignal/OneSignal-Cordova-SDK#187]
Hey,

Ive been having some serious issues the last few hours trying to get a pretty simple app (cordova) to build as well as to get the onesignal plugin to install. I use your plugin for another 3 apps without these issues (last one was a few weeks ago). Now I see that there was a commit with "Switched to CocoaPods for native iOS SDK" which Im assuming is the cause for my problems. Im sure you have som good reason for this but is there some way where I can continue to use you without this version that forces CocoaPods? 

I keep getting "You cannot run CocoaPods as root." which makes life really tricky...

Thanks.

Peter

**Comment by jkasten2** [comment]
@peterel We switched to Cocoapods to make this SDK easier to maintain and it is official supported through Cordova. Also the iOS OneSignal native SDK now requires a Notification Service Extension target to support iOS 10 action buttons and media attachments. However the Objective-C code base can't be compiled directly to the target, it just be a pre-build framework to link with the target. Which exists are part of the CocoaPods repo.

Could you list the command that triggered your error?

**Comment by peterel** [comment]
Thanks for a quick reply! 

For me, any command which has "sudo" and onesignal-cordova-plugin breaks. E.g. when adding the plugin. I also messed up at one point and had to remove the iOS platform and then add it again with "sudo cordova platfrom add ios" which in turn then also added your plugin but broke since "You cannot run CocoaPods as root."

I have now been able to move on by using your old release from January. Is that OK or will that be deprecated and broken soon?

**Comment by jkasten2** [comment]
@peterel `sudo` isn't needed to run any of basic cordova commands to add platforms, plugins, build, etc. If you ran sudo already you might need to run chown and chmod to fix the permissions however based on any access errors you might get.

**Comment by peterel** [comment]
@jkasten2 Ok. Thanks for the info. Closing this issue.
