### ISSUE TITLE
When i set the group, the sound sometimes plays more than once

### ISSUE THREAD

**Issue by centrual** [OneSignal/OneSignal-Cordova-SDK#188]
Hello;

I talked with support ten days ago about that and they said `this problem probably about cordova sdk, we will update in next month.`

When i set group key for messages in android sound plays two times most of the time (sometimes not). My sound file is: https://transfer.sh/wdZYB/onesignal_default_sound.mp3

I am using Samsung Galaxy S4 with android 5.0
This problem happening on every phone i tested.

Have a great day!

**Comment by jkasten2** [comment]
@centrual Thanks for reporting this issue. It has been fixed in the 2.1.2 release.
