### ISSUE TITLE
iOS build conflict with cordova-plugin-flurryanalytics (OneSignal.h not found)

### ISSUE THREAD

**Issue by zarko-tg** [OneSignal/OneSignal-Cordova-SDK#191]
Posting the issue here though it relates to cordova-plugin-flurryanalytics (https://github.com/blakgeek/cordova-plugin-flurryanalytics).

A basic Cordova project that uses onesignal-cordova-plugin builds just fine for iOS but if it also depends on cordova-plugin-flurryanalytics then we get a fatal failure:

```
In file included from flurryConflict/platforms/ios/HelloCordova/Plugins/onesignal-cordova-plugin/OneSignalPush.m:31:
flurryConflict/platforms/ios/HelloCordova/Plugins/onesignal-cordova-plugin/OneSignalPush.h:32:9: fatal error: 'OneSignal/OneSignal.h' file not found
#import <OneSignal/OneSignal.h>
        ^
1 error generated.
```

Steps to reproduce:
1. Download and unpack https://1drv.ms/u/s!AjM7j9WqGSJrgap3V7KxdB4v_PoXLg
2. cordova prepare ios && cordova build ios

Environment:
cordova 6.5.0
cordova-ios 4.4.0
onesignal-cordova-plugin 2.1.1
cordova-plugin-flurryanalytics 1.2.1
cocoapods 1.2.1
NodeJs 6.10.3, XCode 8.3.2 on Sierra 10.12.5

cc @blakgeek

**Comment by jkasten2** [comment]
@zarko-tg Are you able to reproduce the issue with a new Cordova project? The error is referring to `OneSignal.h` not being found which seems like the OneSignal plugin didn't get added correctly. `cordova-plugin-flurryanalytics` could be changing Xcode paths but if it did this it would create conflicts with other plugins as well.

**Comment by zarko-tg** [comment]
@jkasten2 Yes, it's a new Cordova (test) project.
Did you try the steps from above? I can reproduce it 100%/100% attempts.

On a real project which uses a bunch of other plugins the situation is the same - we get the build conflict with OneSignal only when the Flurry plugin is also present.

**Comment by JohnRambo90** [comment]
I'm facing a similar problem.  (+1)

Whenever i try to build my iOS Version of my ionic project on a mac pc it shows me OneSignal.h not found because the imports doesn't exist.
I've tried a clean build -> no changes
Then i found this plugin onesignal-cordova-plugin-pgb-compat which allows me to build the project. It also shows me that it has registered an device on the dashboard... 

Problem with this plugin is that android won't work anymore always getting errors like : Missing Google Play Services Library or (No Push Token) on Dashboard.

**Comment by rogeliotrejo13** [comment]
Same Issue 

global packages:

    @ionic/cli-plugin-proxy : 1.3.1
    @ionic/cli-utils        : 1.4.0
    Cordova CLI             : 7.0.1 
    Ionic CLI               : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.1.0 
    npm        : 5.0.0

**Comment by Nightsd01** [comment]
It appears to be a bug with Cordova. 

To resolve it, you need to edit the `Podfile` file in `/platforms/ios/` and add `pod 'OneSignal'` like this:

```
platform :ios, '7.0'
target 'OneSignalExample' do
	pod 'Flurry-iOS-SDK/FlurrySDK'
	pod 'OneSignal' 
end
```

Once you've saved the podfile after you add OneSignal, run `pod install` from the `/platforms/ios` directory and it will add the OneSignal SDK.

I don't really know why this is happening but it appears to be a bug.
