### ISSUE TITLE
Getting warning while uploading app to app store

### ISSUE THREAD

**Issue by nive745** [OneSignal/OneSignal-Cordova-SDK#192]
We have discovered one or more issues with your recent delivery for "App Name". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

**Comment by jkasten2** [comment]
@nive745 You must enable "Push Notifications" under Capabilities in your Xcode project as Apple notes. See the link below for full details on enabling this.
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-5-ios-part-1-required-
