### ISSUE TITLE
How to manage Action Buttons 

### ISSUE THREAD

**Issue by mazzimi** [OneSignal/OneSignal-Cordova-SDK#194]
Hello,

I'm using OneSignal plugin in Ionic1 project and I'm using some Action buttons in order to allow the user to take some immediate action directly from the notification.
For example an Action button can be "Read" to mask a message as read, or "Call" and so on.

I'm wondering if it could be technically possible to make an extension to the code so that the Action button could be managed without launching the App.
I see some App that allows to do such things.

In case it is technically possibile, where could I find a developer able to make such development?

Thank you,
Michele

**Comment by jkasten2** [comment]
@mazzimi Notification action buttons are support through OneSignal however they open the app by default. Preventing the app from opening is possible, however it will take native code to do this.

For Android follow the [Changing the open action of a notification](https://documentation.onesignal.com/docs/android-customizations#section-changing-the-open-action-of-a-notification) guide. You will need to however fork or create your own plugin to setup a open handler to process the button press.

For iOS you will need to create and register your own notification category with native Objective-C / Swift. 
https://developer.apple.com/documentation/usernotifications/unnotificationcategory
