### ISSUE TITLE
Check if device is subscribed

### ISSUE THREAD

**Issue by neoassyrian** [OneSignal/OneSignal-Cordova-SDK#195]
Hi guys, 
How can we check if the device is subscribed to receive notifications or not? 
Would like to display a settings to indicate if the user is subscribed or not (which we can do using the setSubscription(enable) method)

is there "getSubscription" like a method?

**Comment by jkasten2** [comment]
@neoassyrian We actually just added  [`getPermissionSubscriptionState`](https://documentation.onesignal.com/docs/cordova-sdk#section--getpermissionsubscriptionstate-) part of the 2.1.0 release that will do just this!

Thanks!

**Comment by neoassyrian** [comment]
Will the Ionic Native NPM be updated accordingly?

**Comment by neoassyrian** [comment]
Yes, that's what I meant. 
What is required to get that updated? I will open a request with them?

**Comment by jkasten2** [comment]
@neoassyrian The repo isn't maintained by OneSignal. However I recommend opening an issue with their repo or a pull request with the required changes. 
The following file needs additional made to it for these new functions.
https://github.com/ionic-team/ionic-native/blob/v3.12.1/src/%40ionic-native/plugins/onesignal/index.ts
