### ISSUE TITLE
Changing tags and putting ios app in background doesn't update on backend

### ISSUE THREAD

**Issue by trueicecold** [OneSignal/OneSignal-Cordova-SDK#197]
I have this bit of code:
`
window.plugins.OneSignal.sendTag("PushPrivate", Config.getParam("pushPrivate"));
window.plugins.OneSignal.sendTag("PushTagging", Config.getParam("pushTagging"));
`

when I run this code by clicking a button and immediately going to background, tags are not updated in the backend. As soon as I put it on foreground again, it updates.

Tested iOS 9.3.5, iPhone 4S

**Comment by jkasten2** [comment]
@trueicecold iOS pauses all network requests when the app is back grounded by default. We will look into seeing if we can allow the in-flight requests to finish and mark this as an enhancement.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
