### ISSUE TITLE
Media not seen on rich notification on PhoneGap CLI app

### ISSUE THREAD

**Issue by lakshmana** [OneSignal/OneSignal-Cordova-SDK#198]
Hi I am having trouble sending images  in the push notification using onesignal-cordova-plugin. The plugin failed to send media on both the android (lolipop & kitkat) and ios device (iphone 6s). The image satisfies the 3 basic rule as in documentation: 
- the media can be opened directly browser
- The media used is https https://www.procab.ch/assets/content/news/news-thumb-auditseo.jpg with 'https'
- The media url ends with .jpg

Can you please confirm the issue? 

Thx

**Comment by lakshmana** [comment]
BTW, I didnot used the Phonegap cloud build, instead I am using command line phonegap. The issue also occurred with Android Studio & XCode builds.

Thx

**Comment by jkasten2** [comment]
@lakshmana I have test your image with Android Lollipop (5.0) and Android 7.1.1 without any issues. Make sure if there are a few other notifications in the shade that you swipe down on it to expanded it. It may not be expanded by default.

​For iOS 10 please double check the steps in [5. iOS - Part 2](https://documentation.onesignal.com/docs/cordova-sdk-setup#section-5-ios-part-2-recommend-) as the extender is most likely not firing if the image is not showing on the right side of the notification.

Thanks.

**Comment by lakshmana** [comment]
@jkasten2 Thx for the help. It is not working on the ios. It was fixed using [This extra steps](https://documentation.onesignal.com/docs/cordova-sdk-setup#section-5-ios-part-2-recommend-) as you have mentioned. I think it would be good if this info was mentioned on the documentation for phonegapSDK. Currently this info is available on cordovaSDK only. 

For android, I am sorry but I really do not understand what you mean by 'Make sure if there are a few other notifications in the shade that you swipe down on it to expanded it....' How do I expand it by default?

Thx

**Comment by jkasten2** [comment]
@lakshmana Thanks, we have updated our iOS PhoneGap CLI instructions for this.

The app can't control if the notification will be expanded by default in the shade. The user must swipe down on it to expand it. You can set the priority of the notification to 10 (High) so it display as a heads-up notification expanded for a short time however. You can use the priority in testing but only do so in production if it is really an urgent message the user must see right away.

**Comment by lakshmana** [comment]
Thanks @jkasten2 for all the support. I am closing this issue. (Y)
