### ISSUE TITLE
Can not receive notification when app is closed

### ISSUE THREAD

**Issue by vahidvdn** [OneSignal/OneSignal-Cordova-SDK#199]
I have trouble with getting notification when the app is closed. It works fine in background mode. Also I had the same issue with phonegap push plugin.

I guess may be this a problem with that plugin. But now it also happens with `OneSignal`. Tested in android 6 (Huawei device)

**NOTE:** This is duplicated issue, but I don't close the app by force closing from setting. Simply close from recent apps list.

**Comment by jkasten2** [comment]
@vahidvdn Huawei (Pre-EMUI 5.0 / Android 7), Xiaomi, and a few other manufactures have made customization to Android to put apps into a force-stopped state after swiping them away or after some time. For Go to Settings > "Protected apps", check your app. See this guide for [full details](http://phandroid.com/2017/02/02/huawei-honor-emui-first-thing/).

See OneSignal's [Notifications not shown](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown) troubleshooting for a full list of other devices.

**Comment by vahidvdn** [comment]
Thank you so much. When I tick the app as protected, it worked fine. Is there anyway to make the app protected by default in cordova/ionic ?

**Comment by jkasten2** [comment]
@vahidvdn For Xiaomi there isn't and dont' think there would be for Huawei either. However I know for Xiaomi you can direct the user to the settings page for this. Their might be for Huawei as well but haven't looked into it. It will require native Java code to do so however.
