### ISSUE TITLE
Property 'getPermissionSubscriptionState' does not exists on type 'OneSignal'

### ISSUE THREAD

**Issue by AntonioMenti** [OneSignal/OneSignal-Cordova-SDK#200]
Good Morning, 

i've created an ionic 3 app with One Signal. Notification correctly received but i can't access getPermissionSubscriptionState method. 

ionic info tell me that i have the latest version installed. 
Costructor

`private _SIGNAL : OneSignal`

and then: 
`this._SIGNAL.getPermissionSubscriptionState()
	  .then((msg) {
			console.log(JSON.stringify(msg));
	  });`

ionic info command: 

`global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.7.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.3`

Any ideas? What's i'm wrong?

**Comment by jkasten2** [comment]
@AntonioMenti This is a new function that doesn't have it's TypeScript definitions released yet. Please see the following thread for updates on it's release.
https://github.com/ionic-team/ionic-native/pull/1678
https://github.com/ionic-team/ionic-native/releases

Thanks.
