### ISSUE TITLE
Save device token to external database

### ISSUE THREAD

**Issue by vahidvdn** [OneSignal/OneSignal-Cordova-SDK#201]
I am able to send push notification to all users. But I want to save each user's token in my own database and use api to send push. How should I get the token? I simply do this:

```
var notificationOpenedCallback = function(jsonData) {
      alert('notificationOpenedCallback: ' + JSON.stringify(jsonData));
    };

    window.plugins.OneSignal
      .startInit("7059956z-b04e-536f-b2dc-48905a52298e")
      .handleNotificationOpened(notificationOpenedCallback)
      .endInit();
```

Of course this not an issue, but didn't find anywhere to ask. Thanks.

**Comment by jkasten2** [comment]
@vahidvdn I recommend using the [`addPermissionObserver`](https://documentation.onesignal.com/docs/cordova-sdk#section--addsubscriptionobserver-) function to get the OneSignal user / player id.

```javascript
window.plugins.OneSignal.addPermissionObserver(function(state) {
   if (state.from.userId != state.to.userId && state.to.userId != null) {
      // Your send to server code here
   }
});
```

The observer ensures your callback is only fired when a change happens so you don't have to add additional checks.

**Comment by vahidvdn** [comment]
@jkasten2 Thanks. And there is one note in docs which you mentioned:

> The passed in function will be fired when a notification subscription property changes.

As I know and also mentioned in the note, the token will be changed form Google/Apple periodically. Then we must update the token in out database. So, native developers writes some services that run even the user doesn't open the app. What should we do in cordova? (Or maybe OneSignal handles it in it's own server!?)

**Comment by vahidvdn** [comment]
Also `userId` is undefined in both state.from and state.to . Here is the result of state (value of callback:

```
{
  to: {
    status:0,
    hasPrompted: true
  },
  from: {
    status:1,
    hasPrompted: false
  }
}
```

And then to.status becomes 2.

**Comment by vahidvdn** [comment]
I could be able to get the id with this code:

```
window.plugins.OneSignal.getIds(function(ids) {
    alert(JSON.stringify(ids));
});
```

But it only works once. (in the next time, when I open the app, doesn't run). Any idea?

**Comment by YaroslavG** [comment]
@vahidvdn, thanks
