### ISSUE TITLE
Does not subscribe to android push

### ISSUE THREAD

**Issue by gerciljunio** [OneSignal/OneSignal-Cordova-SDK#202]
After updating the cordova, the plugin and node, Android no subscribe in OneSignal, is anyone experiencing the same problem?

```
Cordova: 7.0.1
Node: 6.11.0
NPM: 3.10.10
Plugin Cordova OneSignal: 2.1.2
Android: 6.0
```

What I did and did not work:

- I removed the android platform and added again, I did this three times already
- Removed all platforms and added again, including ios
- I reinstalled the plugin several times
- Deletes the ```node_modules``` folder completely and re-creates the entire process from the beginning
- I used chrome inspect devices and everything is ok, it shows no errors

In OneSignal everything is set correctly in Firebase, I have already removed an application and created another from scratch and it still is not working. In ios everything is ok, no problem.

Thanks

**Comment by jkasten2** [comment]
@gerciljunio Are you getting an Android user the in the OneSignal dashboard under All Users as unsubscribed? Or no Android user entries at all?

Can you check the device's logcat for any errors or warnings? You can enable additional long by calling [`setLogLevel`](https://documentation.onesignal.com/docs/android-native-sdk#section--setloglevel-).

You can also contact OneSignal support sending them a link to this issue and they can check somethings on your account as well.

**Comment by gerciljunio** [comment]
@jkasten2 there are no Android user entries, but with its tip on ```setLogLevel``` (thank you) i managed to find two problems, they are:

- ActivityManager | Scheduling restart of crashed service com.app.grcard.client/com.onesignal.SyncService in 1000ms

- PluginManager | THREAD WARNING: exec() call to OneSignalPush.init blocked the main thread for 79ms. Plugin should use CordovaInterface.getThreadPool().

**Comment by gerciljunio** [comment]
I just created a new cordova project, from scratch and the same errors occur, I removed the cordova completely from my machine, reinstalled everything again and also did not solve! :(

**Comment by gerciljunio** [comment]
The problem has been resolved after uninstalling all the features on my machine and starting all over again, including the application I'm developing. I can not tell where the problem was, but I believe it was local. Thanks!
