### ISSUE TITLE
How to use rest api

### ISSUE THREAD

**Issue by anivaisu** [OneSignal/OneSignal-Cordova-SDK#203]
Hi,

  I am using ionic 2.

 I tried to this plugin for pushnotifications.
 
 How to send push notifications using rest API using this plugin.

 I tried to post man

Here is my URL
https://onesignal.com/api/v1/notifications

Here is my header
[{"key":"Authorization","value":"Basic  NDJhZDg0NWQtYjM0NS00YzUzLTgwNjktMDgyNThlMmUxNDYy","description":""}]

This is a body msg
{
  "app_id": "821e3c9a-aee4-45c7-9b1d-41bb67c9280b",
  "included_segments": ["All"],
  "contents": {"en": "English Message"}
}

I am getting this err

{
    "errors": [
        "app_id not found. You may be missing a Content-Type: application/json header."
    ]
}

How can i fix this issue.

**Comment by jkasten2** [comment]
@anivaisu You are most likely missing `Content-Type: application/json` in the HTTP header. Please follow our Postman specific guide below to make sure you have everything set correctly.

https://documentation.onesignal.com/docs/using-postman

**Comment by ulgens** [comment]
@jkasten2 That example doesn't work.

**Comment by ulgens** [comment]
@jkasten2 I found the problem. It's not the key is missing or corrupted somehow, it was just the wrong key. In this case i expect an error like "wrong key" or "permission denied" but instead it gives "app_id is missing".

**Comment by Kasirajan7** [comment]
@anivaisu Check the type of body msg before your sending the post request if the type is not JSON it would return the same error.

**Comment by isaacMuniz** [comment]
I am having this same issue and not using postman, just straight php.
