### ISSUE TITLE
BADGE ios 10.3.2

### ISSUE THREAD

**Issue by scrnet** [OneSignal/OneSignal-Cordova-SDK#207]
We are having problems on iOS 10.3.2 using cordova. The badges are not showing.  This is working in older version of iOS like 9. Thanks.

**Comment by jkasten2** [comment]
@scrnet We have tested our SDK with iOS 10.3 without any issues. Can you ensure you don't have any other notification plugins in your app that could be interfering? Please run `cordova plugin list` to check for this.

Also make sure the permission is enable in the iOS Setting for your app. Making sure `Badge App Icon" is enabled.

Lastly make sure your app is in the background or closed when you send your push so the badge can be updated.

**Comment by chapuzzo** [comment]
This is or current plugin list, none of them but this one has to do with push notifications, the notifications arrive to the target devices perfectly, but the badge with the closed app is not showing up.

cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-save-image 0.2.4 "SaveImage"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
onesignal-cordova-plugin 2.1.2 "OneSignal Push Notifications"

**Comment by jkasten2** [comment]
@scrnet @chapuzzo Are you setting badges through the OneSignal REST API or dashboard? If doing so through the REST API please print out the full JSON payload you are sending so we can confirm it is correct.

I also recommend updating to our latest SDK.

Feel free to reply and I can reopen this issue if you are still seeing this problem. Thanks
