### ISSUE TITLE
IdsAvailable is deprecated, registerForPushNotification is deprecated

### ISSUE THREAD

**Issue by RomainDev25** [OneSignal/OneSignal-Cordova-SDK#210]
Hello, I have this issue, when I install and build ios project.

Thanks in advance.

![capture d ecran 2017-07-11 a 08 55 40](https://user-images.githubusercontent.com/24386544/28054831-ca98f726-6616-11e7-8a40-3752f20ce06d.png)
![capture d ecran 2017-07-11 a 08 55 50](https://user-images.githubusercontent.com/24386544/28054836-ccd55818-6616-11e7-9c02-c4b3c06def7f.png)

**Comment by jkasten2** [comment]
@RomainDev25 Thanks for reporting, you can safely ignore these Objective-C warnings. They will be converted to newer method calls internally in the future.

**Comment by pierrot10** [comment]
Hello @jkasten2 

`Thanks for reporting, you can safely ignore these Objective-C warnings. They will be converted to newer method calls internally in the future.`

I have the same issue and following your writing, I am surprise to have this same warning, now in 2021.

Is there any way to solve that?
