### ISSUE TITLE
ionic 3, How to get notification additionaldata?

### ISSUE THREAD

**Issue by LtotheWT** [OneSignal/OneSignal-Cordova-SDK#211]
this is the fucntion i got from [https://ionicframework.com/docs/native/onesignal/](url)
`this.oneSignal.handleNotificationReceived().subscribe(() => {
     // do something when notification is received

    });
    this.oneSignal.handleNotificationOpened().subscribe(() => {
      // do something when a notification is opened
    });`
how can i get the notification additional data in ionic 3?

below code is how i get data from previous using ionic 2.
`var notificationOpenedCallback = function(result) {
                var link = result.notification.payload.additionalData.targetUrl;
       };
.handleNotificationOpened(notificationOpenedCallback)
`

**Comment by Blanketsniffer** [comment]
How was your solution?
