### ISSUE TITLE
404, Not Found when Cancel notification

### ISSUE THREAD

**Issue by peterel** [OneSignal/OneSignal-Cordova-SDK#212]
Seems Ive tried each way here but I keep getting a 404, Not Found error when trying to remove a notification. Any help would be appreciated. 

Note 1: The notification is created, and I can see it in the console.
Note 2: Ive compared the notificationID that I am sending in through the API with the notification that is already create and visible in the console (ID is visible via the url in the console). They match.

Does anyone have a working example of a python "cancel notification" request?

Ive tried combinations of below:

HEADER:
header = {"Authorization": "MY_AUTH"}

PAYLOAD:
1. 
payload = {"app_id": "APP_ID", "id": NOTIFICATION_ID }
2. 
payload = {}
payload['app_id'] = "APP_ID"
payload['id'] = NOTIFICATION_ID

REQUEST:
1.
req = requests.delete("https://onesignal.com/api/v1/notifications", headers=header, data=json.dumps(payload))
2.
req = requests.delete("https://onesignal.com/api/v1/notifications", headers=header, params=json.dumps(payload))
3.
req = requests.delete("https://onesignal.com/api/v1/notifications", headers=header, params=payload)

**Comment by gdeglin** [comment]
Please try the following:
```
header = {"Authorization": "Basic MY_AUTH"} # Make sure to include "Basic" before your app auth key
requests.delete("https://onesignal.com/api/v1/notifications/YOUR_NOTIFICATION_ID?app_id=YOUR_APP_ID", headers=header)
```

For future non-SDK related questions, please contact us at support@onesignal.com.

**Comment by peterel** [comment]
Thanks, that works!

Will do!
