### ISSUE TITLE
Customizing action button for direct reply to notifications

### ISSUE THREAD

**Issue by WaSa42** [OneSignal/OneSignal-Cordova-SDK#217]
I must implement direct reply as it is explained in [android documentation](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#direct) for native application.

I've seen that it's possible to customize action buttons and handle those events with NotificationOpenedHandler, but nothing like a direct reply action.

What should I do to implement a such feature ?

Thanks for your help,

**Comment by jkasten2** [comment]
@WaSa42 The [OneSignal Android SDK](https://github.com/OneSignal/OneSignal-Android-SDK) that is used by this SDK does not currently support this feature. It could be added to the native SDK or you can create your own Cordova Android plugin that uses the [Background Data and Notification Overriding](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) OneSignal SDK feature to override the notification being displayed to add this.

Thanks.

**Comment by baskin** [comment]
Just checking if there was any progress on this or any better approaches in the ~4months since the ticket was cut. Otherwise I was planning to do as @jkasten2 suggests -- 'create your own Cordova Android plugin that uses the Background Data and Notification Overriding OneSignal SDK'

**Comment by jkasten2** [comment]
@baskin We don't plan to get to this in the near future, there are a number of other higher priority tasks we have on our roadmap before this one. Thanks.

**Comment by canibal1** [comment]
It's been 6 years, is there any progress on this?

**Comment by j4hangir** [comment]
Onesignal still doesn't support direct replies!?
