### ISSUE TITLE
Support Android N inline reply actions

### ISSUE THREAD

**Issue by videmort** [OneSignal/OneSignal-Cordova-SDK#218]
Any plans to include this feature to SDK?
https://developer.xamarin.com/guides/android/platform_features/introduction-to-nougat/Images/notifications-inline-reply.png

**Comment by WaSa42** [comment]
Asking the same  question yesterday: #217

**Comment by jkasten2** [comment]
@videmort Let move the discussion to #217 since it was submitted first.
