### ISSUE TITLE
Silent pushes now show a blank message with icon and app name and no next in android

### ISSUE THREAD

**Issue by epetre** [OneSignal/OneSignal-Cordova-SDK#220]
I have those plugins in an ionic 3.5 app.

`cordova-plugin-firebase 0.1.22`
`onesignal-cordova-plugin 2.1.2`

The problem that I am starting to see is that silent pushes display our logo and app name but with no content in them on android and it works well on iOS. This also happens when the app is in foreground.

I am wondering if it could be some sort of conflict between Firbebase and OneSignal.

**Update Jul 29**
I have removed the firebase plugin and it is still happening, I am not sure about what the issue could be at this point since it happens for silent pushes **even when the app is in foreground** and OneSignal was configured to not show them when app is in foreground (this config works with non silent pushes).

This still works today in our production environment where we have 2.0.11 installed with an older version of firebase that I don't remember (I forked it on may 5th to comment out their handling of pushes, I could get the version at the time if it helps).

**Comment by epetre** [comment]
Hello, I don't mean to rush you guys, I was just wondering: 

- Was this reported elsewhere in the past? 
- Do you have any pointers on what I could be looking at or trying while waiting for a more official response?

**Comment by jkasten2** [comment]
@epetre Our SDK should not be showing blank notifications in any case. If you send a notification without a message body the SDK won't display the notification.

Can list all plugins in your project by running `cordova plugin list`? Another one could be still be displaying one.

You could show full payload your are sending to the OneSignal REST API? Or the dashboard options you are setting if you are sending it from there.

You can also link OneSignal support to this thread along with the notification id and they can check the exact notifications you seen an issue with.

**Comment by epetre** [comment]
I don't think another plugin is displaying a push notification, the only one I'm worried about is still Firebase.
But I removed it and have still seen the issue, so unless it wasn't cleaned up well when it was removed, it shouldn't be Firebase.

The payload is the same as the working version in production. Here it is, it's coming from our server, not from the dashboard.

Payload data:
```
{
      app_id: ONESIGNAL_APP_ID,
      include_android_reg_ids: android_tokens,
      include_ios_tokens: ios_tokens,
      headings: { en: "" },
      contents: { en: "" },
      data: data,
      ios_sound: 'www/assets/sounds/notification.caf',
      android_sound: 'notification',
      android_visibility: -1,
      small_icon: 'notification',
      priority: 10,
      collapse_id: group_id,
      android_group: group_id,
      content_available: true,
    }
```

Plugins:
```
branch-cordova-sdk 2.6.5 "branch-cordova-sdk"
com-sarriaroman-photoviewer 1.1.10 "PhotoViewer"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-apprate 1.2 "AppRate"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-cocoalumberjack 0.0.1 "CocoaLumberjack"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-crosswalk-webview 2.1.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 4.3.1 "File"
cordova-plugin-firebase 0.1.22 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.5 "Globalization"
cordova-plugin-google-analytics 1.8.2 "Google Universal Analytics Plugin"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-network-information 1.3.1 "Network Information"
cordova-plugin-splashscreen 4.0.4-dev "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-vibration 2.1.5 "Vibration"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-wkwebview-engine 1.1.3-dev "Cordova WKWebView Engine"
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
cordova-plugin-x-toast 2.5.2 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.1.2 "OneSignal Push Notifications"
```

**Comment by jkasten2** [comment]
@epetre I don't know all the plugins off hand but I doesn't see any know ones that have notification support in them other than firebase which you tried to remove already.

Can you try removing the following from your payload?

```
 headings: { en: "" },
  contents: { en: "" },
```

Since you have `content_available: true` `contents` isn't required.

**Comment by epetre** [comment]
@jkasten2 

Yeah non of the other plugins are supposed to play with push notifications. 
Same thing happens when removing headings and contents. Maybe something that remained after cleaning up Firebase.

**Comment by jkasten2** [comment]
@epetre It is possible that there is something left over from firebase. Can you try a reproducing the issue in a new project?

The 2.1.2 version of this SDK uses 3.5.7 of the OneSignal Android SDK which has the following `null` and blank string check on body (sent as alert from OneSignal) to omit displaying it.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.5.7/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java#L391

**Comment by epetre** [comment]
@jkasten2 I removed the platform and removed firebase, reinstalled everything but firebase and the issue still happened, it's starting to look like it's something in OneSignal, no other plugin handles pushes since firebase is out. 

I removed OneSignal, added Firebase back and the issue doesn't happen.

I did not start a blank project because it requires too much setup and it is starting to point towards something in OneSignal.

**Comment by epetre** [comment]
Here is the output of `adb logcat *:W` with a little log I added in OneSignalPush.java 
`public void notificationReceived(OSNotification notification) {` to see if it gets there and what it gets in the push. One thing I noticed is that I only see OneSignal logs and also shown is true the second time. I am also not sure why it's called twice but this was my attempt to provide as much info as possible.

Also, I changed the project ID and bundle.

```
08-03 12:32:58.227  7048  7048 E OneSignal: Error saving notification record!
08-03 12:32:58.227  7048  7048 E OneSignal: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
08-03 12:32:58.227  7048  7048 E OneSignal: 	at com.onesignal.NotificationBundleProcessor.saveNotification(NotificationBundleProcessor.java:164)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at com.onesignal.NotificationBundleProcessor.saveNotification(NotificationBundleProcessor.java:112)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at com.onesignal.NotificationBundleProcessor.processBundle(NotificationBundleProcessor.java:395)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:95)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at com.onesignal.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:61)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3041)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1562)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at android.os.Looper.loop(Looper.java:154)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at java.lang.reflect.Method.invoke(Native Method)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-03 12:32:58.227  7048  7048 E OneSignal: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-03 12:32:58.229  7048  7440 W =========> : GOT A PUSHHH
08-03 12:32:58.229  7048  7440 W =========> : notification data: {"isAppInFocus":true,"shown":false,"androidNotificationId":0,"displayType":0,"payload":{"notificationID":"64b07a84-55b1-415e-8288-8faed442cb3c","additionalData":{"type":"checkin"},"smallIcon":"notification","sound":"notification","lockScreenVisibility":-1,"groupKey":"checkin","fromProjectNumber":"99771175678","collapseId":"checkin","priority":10,"rawPayload":"{\"google.sent_time\":1501777978331,\"custom\":\"{\\\"a\\\":{\\\"type\\\":\\\"checkin\\\"},\\\"i\\\":\\\"64b07a84-55b1-415e-8288-8faed442cb3c\\\"}\",\"grp\":\"checkin\",\"pri\":\"10\",\"vis\":\"-1\",\"from\":\"99771175678\",\"sicon\":\"notification\",\"sound\":\"notification\",\"google.message_id\":\"0:1501777978342625%58874d152c3ed02d\",\"collapse_key\":\"checkin\"}"}}
08-03 12:32:58.241  7888  7888 W GCM-DMM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=co.mypackage.mypakcage (has extras) }
08-03 12:32:58.276  7048  7441 E OneSignal: Error saving notification record!
08-03 12:32:58.276  7048  7441 E OneSignal: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
08-03 12:32:58.276  7048  7441 E OneSignal: 	at com.onesignal.NotificationBundleProcessor.saveNotification(NotificationBundleProcessor.java:164)
08-03 12:32:58.276  7048  7441 E OneSignal: 	at com.onesignal.NotificationBundleProcessor.Process(NotificationBundleProcessor.java:88)
08-03 12:32:58.276  7048  7441 E OneSignal: 	at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:75)
08-03 12:32:58.276  7048  7441 E OneSignal: 	at com.onesignal.GcmIntentService.onHandleIntent(GcmIntentService.java:60)
08-03 12:32:58.276  7048  7441 E OneSignal: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
08-03 12:32:58.276  7048  7441 E OneSignal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-03 12:32:58.276  7048  7441 E OneSignal: 	at android.os.Looper.loop(Looper.java:154)
08-03 12:32:58.276  7048  7441 E OneSignal: 	at android.os.HandlerThread.run(HandlerThread.java:61)
08-03 12:32:58.278  7048  7441 W =========> : GOT A PUSHHH
08-03 12:32:58.278  7048  7441 W =========> : notification data: {"isAppInFocus":true,"shown":true,"androidNotificationId":-1873555104,"displayType":0,"payload":{"notificationID":"64b07a84-55b1-415e-8288-8faed442cb3c","additionalData":{"type":"checkin"},"smallIcon":"notification","sound":"notification","lockScreenVisibility":-1,"groupKey":"checkin","fromProjectNumber":"99771175678","collapseId":"checkin","priority":10,"rawPayload":"{\"google.sent_time\":1501777978331,\"custom\":\"{\\\"a\\\":{\\\"type\\\":\\\"checkin\\\"},\\\"i\\\":\\\"64b07a84-55b1-415e-8288-8faed442cb3c\\\"}\",\"grp\":\"checkin\",\"pri\":\"10\",\"vis\":\"-1\",\"from\":\"99771175678\",\"sicon\":\"notification\",\"sound\":\"notification\",\"google.message_id\":\"0:1501777978342625%58874d152c3ed02d\",\"collapse_key\":\"checkin\",\"notificationId\":-1873555104}"}}
08-03 12:32:58.307  3768  7348 W AMessage: failed to post message as target looper for handler 0 is gone.
08-03 12:32:58.367  3765 20262 E OMXNodeInstance: setConfig(eb50179:google.mp3.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
08-03 12:32:58.367  3765 13316 E OMXNodeInstance: setConfig(eb5017a:google.mp3.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
08-03 12:32:58.382  3768  7445 W AMessage: failed to post message as target looper for handler 0 is gone.
08-03 12:32:58.716 18153 18192 W bt_btif : bta_dm_rm_cback:3, status:7
08-03 12:32:58.752 18153 18192 W bt_btif : bta_dm_rm_cback:3, status:0
08-03 12:32:58.752 18153 18192 W bt_btif : bta_dm_rm_cback:3, status:7
08-03 12:32:58.753 18153 18209 W bt_btif : pcm bytes per tick 3528
08-03 12:33:01.658  3767  3767 E MP3Extractor: Unable to resync. Signalling end of stream.
08-03 12:33:02.522  3767  6637 E MP3Extractor: Unable to resync. Signalling end of stream.
08-03 12:33:06.231  7888  5457 W ConfigurationChimeraProvider: Got null configs for com.google.android.gms.update
08-03 12:33:06.272 18153 18192 E bt_btif : bta_av_str_stopped:audio_open_cnt=1, p_data e052d370
08-03 12:33:06.272 18153 18192 W bt_btif : bta_dm_rm_cback:3, status:6
08-03 12:33:06.423 18153 18209 W bt_btif : poll timeout (10 ms)
```

**Comment by epetre** [comment]
@jkasten2  Is it possible that it's missing a check for null at [NotificationBundleProcessor.java#L164](https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.5.7/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationBundleProcessor.java#L164).

```
if (notifiJob.getTitle() != null)
  values.put(NotificationTable.COLUMN_NAME_TITLE, notifiJob.getTitle().toString());
values.put(NotificationTable.COLUMN_NAME_MESSAGE, notifiJob.getBody().toString());
```

It checks for title but not body...
```
if (notifiJob.getBody() != null)
```

**Comment by epetre** [comment]
oh well, solution is using com.onesignal:OneSignal:3.5.6 because of the reasons mentioned above In case anyone runs into it, which should be anyone using silent pushes with version com.onesignal:OneSignal:3.5.7 and above. 

I'll just create an issue on the other project, not sure if it's the same team working on it.

**Comment by floydus** [comment]
What is the fix ? I don't see. I am also running into the same issue, always shown but only on Android, not problem on the iOs side.
Here is my complete question on SO.
[https://stackoverflow.com/questions/46392556/notificationextenderservice-not-firing-handlenotificationreceived](url)
Does that ring any bell to you, I'm so stuck right now, it is always showing, shown is true, displayType 1 !

**Comment by epetre** [comment]
Well the fix is probably what I mentioned above, but apparently they don't take this issue too seriously. So the fix you could use right now is to revert their Android SDK to a version that doesn't include that bug.

in `platforms/android.properties`, using `cordova.system.library.9=com.onesignal:OneSignal:3.5.6`
fixes the issue above.

**Comment by floydus** [comment]
Men I would kiss you !  Thanks so much, spent 3 days on that.

**Comment by jkasten2** [comment]
@epetre Sorry for the delay on this. The 2.2.1 of OneSignal Cordova SDK has been released which updates to the OneSignal Android SDK version 3.6.2 to fix this issue.

**Comment by sido420** [comment]
@epetre @floydus can you comment on https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/416 plz?
