### ISSUE TITLE
Failed to install 'onesignal-cordova-plugin':

### ISSUE THREAD

**Issue by AsimNet** [OneSignal/OneSignal-Cordova-SDK#223]
Hello

when I try to add ios platform in ionic, I got this message:

![screen shot 2017-08-02 at 7 16 51 pm](https://user-images.githubusercontent.com/3624441/28884310-083edae6-77ba-11e7-93e6-55570c4b7b2f.png)

**Comment by jkasten2** [comment]
@AsimNet Make sure Cocoapods is up to date on your system by running the following 2 commands
```
sudo gem install cocoapods
pod repo update
```

Make sure you run the following without `sudo`
```
cordova plugin add onesignal-cordova-plugin --save
```

**Comment by AsimNet** [comment]
thanks

**Comment by eddskt** [comment]
Thanks @jkasten2 

My procediments:

cordova platform remove ios
cordova platform remove onesignal-cordova-plugin
sudo gem install cocoapods
pod repo update
pod setup (I needed to sync the CocoaPods repository)
cordova plugin add onesignal-cordova-plugin --save
cordova platform add ios

**Comment by zouhair2015** [comment]
i do not work for me this : 
cordova platform remove ios
cordova platform remove onesignal-cordova-plugin
sudo gem install cocoapods
pod repo update
pod setup (I needed to sync the CocoaPods repository)
cordova plugin add onesignal-cordova-plugin --save
cordova platform add ios

problem is : 
Failed to install 'onesignal-cordova-plugin': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dest81** [comment]
@zouhair2015 check the pod version
`pod --version`
I had something 1.6.0.beta... 

Then I deleted all pods versions with command
`sudo gem uninstall -n /usr/local/bin cocoapods`
and installed only 1.5.3

Now it works for me :)

**Comment by mjy12** [comment]
@dest81  thanks

**Comment by sctouch** [comment]
Don't use 1.8.0.beta.1 it is not work
- use cocoapods-1.7.5 instead.

**Comment by marensas** [comment]
This is working only with local cordova SDK, not Phonegap.
