### ISSUE TITLE
Apple Mach-O Linker (id) Error

### ISSUE THREAD

**Issue by Slind14** [OneSignal/OneSignal-Cordova-SDK#226]
Hi there,
I'm getting this error with Release 2.1.1+, 2.1.0 and 2.0.x is working fine.
I'm using meteor 1.5.1.

**Comment by jkasten2** [comment]
@Slind14 Can you rerun the following to make sure it CocoaPods was installed correctly?
```
sudo gem install cocoapods
pod repo update
```

Also if you are building from Xcode make sure to open the new `.xcworkspace` instead of the `.xcproj` file.

**Comment by Slind14** [comment]
Ahh, thanks. The first one I did, the second one I did not, I'll try that 👍

**Comment by Slind14** [comment]
This was the issue.. That I/the builder opened the wrong file.
