### ISSUE TITLE
Include setting to disable the sending of the user location

### ISSUE THREAD

**Issue by saimon24** [OneSignal/OneSignal-Cordova-SDK#227]
The function to disable this feature was already implemented inside the iOS SDK, see [this issue](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/136) and [the according commit](https://github.com/OneSignal/OneSignal-iOS-SDK/commit/d28928d0afed4b4bfd8c519a5e9817a15779c92b).

This feature should be included in the Cordova Plugin as well!

**Comment by Nightsd01** [comment]
I have implemented this with #ef7f295.
