### ISSUE TITLE
Not able to getids of onesignal in ionic

### ISSUE THREAD

**Issue by ankush1990** [OneSignal/OneSignal-Cordova-SDK#228]
I am not able to get ids in my ionic cordova application please help me to out this

window.plugins.OneSignal.getIds(function(ids) {
					//console.log('getIds: ' , ids);
					//self.deviceToken    =   ids.pushToken;
					onesignal_ids         =   ids.userId;
					onesignal_ids1 = JSON.stringify(ids);
					onesignal_ids2 = ids;
				});

**Comment by diegomachado1** [comment]
I had this issue when I was configuring OneSignal. I was putting getIds() before endInit(). I put after endInit() and it worked.

**Comment by jkasten2** [comment]
@ankush1990 Feel free to reopen this issue if diegomachado1's answer above didn't help.

**Comment by SrijithK** [comment]
@diegomachado1  can you please share the code snippet?

**Comment by ismatoro** [comment]
I hope it helps:
`window["plugins"].OneSignal
      .startInit("-------------------------------", "------------------")
      .handleNotificationOpened(callbackForNotifications)
      .endInit();
window['plugins'].OneSignal.getIds((id)=>console.log(id));`

**Comment by latifurrofik** [comment]
this is work for me.. i hope this can help..

`this.oneSignal.getIds().then(ids => {
        console.log(JSON.stringify(ids.userId));
        // this.storage.set('playersID',  ids.userId);
});`

**Comment by ruben06** [comment]
@latifurrofik thanks for your help, this exactly what I did but it dosen't work...
I can show woth the console.log the playerID but I am unable to store it .
when I try : console.log(this.storage.get('playersID', ids.userId)) to test if the playerID is correctly storred, it's blank...

Any idea?
