### ISSUE TITLE
handleNotificationOpened some times does not trigger on android

### ISSUE THREAD

**Issue by v-bodnar** [OneSignal/OneSignal-Cordova-SDK#229]
Hi. We have made some tests on few android devices. And when we have application killed(normally by swipe), and we get push notification - clicking on it opens app but does not trigger handleNotificationOpened method. Problem is random. When app is on background - works fine. Could you suggest a workaround?

Push notification always has some payload in data. 

``` deviceReady(function () {
window.plugins.OneSignal
                    .startInit("xxxxxxxxxxxxxxxxxxxx")
                    .handleNotificationReceived(function (jsonData) {
                          applicationLoggingService.debug('Did I receive a notification: ' + JSON.stringify(jsonData));
                    })
                    .handleNotificationOpened(function (jsonData) {
applicationLoggingService.debug('didOpenRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
                      })
                    .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
                    .endInit();
})```

**Comment by www005531** [comment]
We also have this problem. It happens randomly on high speed phones and for example the HTC Desire always works OK. We had to implement a workaround bypassing data retrieval from payload:(

**Comment by Flaviocrtt** [comment]
Hi, is it ok now? my old phone android 4.4.4 works perfectly, call the handleNotificationOpened everytime, but on another devices with android 6,7 doesn't call the handleNotificationOpened when the app is killed, it just call when the app is opened.

**Comment by Nightsd01** [comment]
We have attempted to reproduce this issue in the latest versus of the SDK in Android 6/7 and have been unable to do so, so I am assuming this issue has been resolved @v-bodnar @Flaviocrtt .

Please feel free to reply if you are still encountering this issue and I would be happy to reopen the issue and investigate. 

If you could, please make sure to post some details, such as how you _know_ that the `handleNotificationOpened` callback is not being called, and so on.
