### ISSUE TITLE
Missing onNotificationProcessing for background data

### ISSUE THREAD

**Issue by BenjaminKauer** [OneSignal/OneSignal-Cordova-SDK#232]
Is there any way to send and receive background data as described in [Cordova Docs - Android Customizations](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) using `onNotificationProcessing()`?

**Comment by Nightsd01** [comment]
Hi @BenjaminKauer . 

Good question! None of the OneSignal wrapper SDK's currently support background notification processing. You can still do it, but you would have to implement it natively for both iOS and Android (separately). You would have to do it in the generated Android project in Java as if it were a native Android application. 

Here is a guide on how to do background notification processing in [Android](https://github.com/OneSignal/OneSignal-Android-SDK/issues/302) and [in iOS (using the OneSignalNotificationServiceExtension)](https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension)
