### ISSUE TITLE
Cannot get to show popup/heads up notifications on Amazon Fire OS ?

### ISSUE THREAD

**Issue by ciaoben** [OneSignal/OneSignal-Cordova-SDK#233]
# Description
Can't get to show the popup/heads up notification on my Amazon Fire 7

# Step to reproduce
Send through the interface a new notification with High Priority.

# Expected behavior
Like on android, I expect to see a heads up notification.

# Actual behavior
I only get the icon directly in the status bar and I need to open the notification center to see the notification.

**Comment by jkasten2** [comment]
@ciaoben Thanks for reporting, the priority flag was missing from payload sent to the device. It was corrected on OneSignal's backend so this should be working correctly on any future notifications.
