### ISSUE TITLE
Android build failed Configuration on demand is an incubating feature. null org.xwalk:xwalk_core_library:19+

### ISSUE THREAD

**Issue by surgianto** [OneSignal/OneSignal-Cordova-SDK#235]
Build Date: 2017-09-04 13:51:44 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-crosswalk-webview@1.8.0" via npm
Installing "cordova-plugin-crosswalk-webview" at "1.8.0" for android
Fetching plugin "cordova-plugin-legacy-whitelist@1.1.1" via npm
Installing "cordova-plugin-legacy-whitelist" at "1.1.1" for android
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Configuration on demand is an incubating feature.
null
org.xwalk:xwalk_core_library:19+

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not resolve org.xwalk:xwalk_core_library:19+.
     Required by:
         :project:unspecified
      > Could not resolve org.xwalk:xwalk_core_library:19+.
         > Failed to list versions for org.xwalk:xwalk_core_library.
            > Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
               > Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.634 secs
undefined

please help me

**Comment by jkasten2** [comment]
@surgianto The crosswalk plugin is not used by this SDK. If you are still seeing this issue you may want to post this on their issue tracker.
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview

Thanks.
