### ISSUE TITLE
phonegap ios integration

### ISSUE THREAD

**Issue by thamer898** [OneSignal/OneSignal-Cordova-SDK#236]
Hello

I tried to integrate my phonegap ios with onesignal but the message appear 

Read the documentation to learn how to fill in the fields below.
Your production certificate was rejected by Apple. It may be expired, revoked, or invalid. Double-check your file or use our provisionator tool to auto-generate a valid certificate.

**Note** : i tried the provision tool still the same problem .

Regards

**Comment by gdeglin** [comment]
We experienced a bug that caused this problem. It's now resolved so you should be able to upload your certificate.

**Comment by MuhammadAsher** [comment]
it is still giving the same issue
