### ISSUE TITLE
IOS notification not showing when app is closed

### ISSUE THREAD

**Issue by jrmartins** [OneSignal/OneSignal-Cordova-SDK#243]
I'm having a problem for notifications on IOS, when these contains buttons and the app is closed.
The notifications do not show if they contain buttons, only when app is closed. When the app is open or in background all works as expected.
If the notification doesn't have buttons that works fine as well.

I saw Onesignal mentioning that on the native IOS sdk that's fixe on 2.4.0 version, but doesn't seem to be an update yet for cordova.

Is that right? Is there a workaround for this?

**Comment by jkasten2** [comment]
@jrmartins This force-quit limitation was fixed in version 2.2.1 of this SDK.
https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.1.1

However make sure to follow the new setup instructions using the `Notification Service Extension` from the release notes above.
