### ISSUE TITLE
iOS 11 UI API called from background thread: -[UIApplication currentUserNotificationSettings] must be used from main thread only

### ISSUE THREAD

**Issue by ish3lan** [OneSignal/OneSignal-Cordova-SDK#244]
<img width="839" alt="screen shot 2017-09-22 at 4 59 23 pm" src="https://user-images.githubusercontent.com/7420284/30748039-af248cdc-9fb7-11e7-9823-e67c8c1f5e33.png">

**Comment by Nightsd01** [comment]
@ish3lan I cannot find this line of code anywhere in the iOS SDK or the Cordova SDK so I am assuming this issue has been resolved. Please let me know if you are still encountering this issue and I'll be happy to reopen an investigate if you can ***add more details***. Thank you.
