### ISSUE TITLE
Set Android badge manually like ios_badgeType/ios_badgeCount

### ISSUE THREAD

**Issue by aljosabilic** [OneSignal/OneSignal-Cordova-SDK#245]
Is there any way to manually set the Android badge count with a push notification, as is possible for iOS? Or are there any plans to implement this?

**Comment by jkasten2** [comment]
@aljosabilic OneSignal sets badges automatically on Android based on the number of notifications in the shade. There currently isn't a way to override this for Android.
https://documentation.onesignal.com/docs/appearance#section-setting-and-clearing-badge-numbers

We considering on support custom values in the future for Android.

Thanks.

**Comment by mubasshir** [comment]
Hi,
when can we expect this feature? 

Is there any alternative for now?

**Comment by JorgeZapa** [comment]
I am also very interested in this feature. As it is now, it is only possible to set the badge number in IOS. But if you really want to custom what the badge number means (not just the number of notifications) you can only do it in IOS and it would be interesting in both platforms.

**Comment by keithdmoore** [comment]
I would also like to see this feature.   I am building a ticketing system and I would like for the badge count to be the number of open tickets.  I can do this for iOS but not for Android.

**Comment by mubasshir** [comment]
Unfortunately, I removed this plugin and using FCM for now

**Comment by keithdmoore** [comment]
@mubasshir Does FCM support this?  I was considering just using a separate plugin to set the badge number for both iOS and Android. And configure OneSignal to not set the badge for Android.

**Comment by Naveen1612** [comment]
@keithdmoore Were you able to achieve this.

**Comment by mubasshir** [comment]
@keithdmoore hey, really sorry for late reply
I moved from FCM to OneSignal. Here is what I did to achieve this

In data params, I'm sending current badge count (you can use increment etc but you will need to handle code at Java level)
I've used https://github.com/leolin310148/ShortcutBadger

1. Add dependencies for ShortcutBadger, it's available from maven now.

```
dependencies {
        compile "me.leolin:ShortcutBadger:1.1.21@aar"
    }
``` 

2. Add this to Menifest to disable Android Badge count
`<meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />`

3. Copy this class to Main package (platform/android/src/com/somepackage/BadgeHelper.java
```
package com.somepackage;

import android.content.Context;
import android.util.Log;
import android.util.StringBuilderPrinter;

import com.onesignal.NotificationExtenderService;
import com.onesignal.OSNotificationReceivedResult;

import org.json.JSONException;

import me.leolin.shortcutbadger.ShortcutBadgeException;
import me.leolin.shortcutbadger.ShortcutBadger;

/**
 * Created by Mubasshir on 21/12/17.
 */

public class BadgeHelper extends NotificationExtenderService {
    private static String TAG = "FCM_BADGE_HELPER";
    public final static String CONST_BADGE_KEY = "badge";

    public static void setBadgeCount(String badge, Context ctx){
        try {
            //String badge = (String) remoteMessage.get("badge");
            int badgeCount = 0;
            if(badge!=null && !badge.isEmpty()){
                badgeCount = tryParseInt(badge);
            }
            if(badgeCount>0)
            {
                ShortcutBadger. applyCountOrThrow(ctx, badgeCount);
                Log.d(TAG, "showBadge worked!");
            }

        } catch (ShortcutBadgeException e) {
            Log.e(TAG, "showBadge failed: " + e.getMessage());
        }
    }
    static int tryParseInt(String value) {
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {
        try {
            String badge = notification.payload.additionalData.getString("badge");
            setBadgeCount(badge, this.getApplicationContext());
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return false;
    }
}
```

4. Copy following to Menifest to link BadgeHelper to onesignal
```
<service
   android:name=".BadgeHelper"
   android:permission="android.permission.BIND_JOB_SERVICE"
   android:exported="false">
   <intent-filter>
      <action android:name="com.onesignal.NotificationExtender" />
   </intent-filter>
</service>
```

**Comment by keithdmoore** [comment]
@Naveen1612 I have not tried to achieve this yet

**Comment by geoffreybr** [comment]
@mubasshir Do you think it is feasible to make a cordova plugin out of that?

**Comment by Nightsd01** [comment]
The OneSignal Android SDK does not currently include this functionality but we are considering adding it soon.

In the mean time, you can use the Notification Extender Service (android) or the Notification Extension Service (iOS) to process the `additionalData` field of a push notification and you can manually set the badge count using some custom package. You would want to disable OneSignal badge incrementing in `AndroidManifest.xml` by adding:

```
<application ...>
   <meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />
</application>
```

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration

**Comment by thianlopezz** [comment]
Still waiting for this

**Comment by thianlopezz** [comment]
> @keithdmoore hey, really sorry for late reply
> I moved from FCM to OneSignal. Here is what I did to achieve this
> 
> In data params, I'm sending current badge count (you can use increment etc but you will need to handle code at Java level)
> I've used https://github.com/leolin310148/ShortcutBadger
> 
> 1. Add dependencies for ShortcutBadger, it's available from maven now.
> 
> ```
> dependencies {
>         compile "me.leolin:ShortcutBadger:1.1.21@aar"
>     }
> ```
> 
> 1. Add this to Menifest to disable Android Badge count
>    `<meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />`
> 2. Copy this class to Main package (platform/android/src/com/somepackage/BadgeHelper.java
> 
> ```
> package com.somepackage;
> 
> import android.content.Context;
> import android.util.Log;
> import android.util.StringBuilderPrinter;
> 
> import com.onesignal.NotificationExtenderService;
> import com.onesignal.OSNotificationReceivedResult;
> 
> import org.json.JSONException;
> 
> import me.leolin.shortcutbadger.ShortcutBadgeException;
> import me.leolin.shortcutbadger.ShortcutBadger;
> 
> /**
>  * Created by Mubasshir on 21/12/17.
>  */
> 
> public class BadgeHelper extends NotificationExtenderService {
>     private static String TAG = "FCM_BADGE_HELPER";
>     public final static String CONST_BADGE_KEY = "badge";
> 
>     public static void setBadgeCount(String badge, Context ctx){
>         try {
>             //String badge = (String) remoteMessage.get("badge");
>             int badgeCount = 0;
>             if(badge!=null && !badge.isEmpty()){
>                 badgeCount = tryParseInt(badge);
>             }
>             if(badgeCount>0)
>             {
>                 ShortcutBadger. applyCountOrThrow(ctx, badgeCount);
>                 Log.d(TAG, "showBadge worked!");
>             }
> 
>         } catch (ShortcutBadgeException e) {
>             Log.e(TAG, "showBadge failed: " + e.getMessage());
>         }
>     }
>     static int tryParseInt(String value) {
>         try {
>             return Integer.parseInt(value);
>         } catch (NumberFormatException e) {
>             return 0;
>         }
>     }
> 
>     @Override
>     protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {
>         try {
>             String badge = notification.payload.additionalData.getString("badge");
>             setBadgeCount(badge, this.getApplicationContext());
>         } catch (JSONException e) {
>             e.printStackTrace();
>         }
>         return false;
>     }
> }
> ```
> 
> 1. Copy following to Menifest to link BadgeHelper to onesignal
> 
> ```
> <service
>    android:name=".BadgeHelper"
>    android:permission="android.permission.BIND_JOB_SERVICE"
>    android:exported="false">
>    <intent-filter>
>       <action android:name="com.onesignal.NotificationExtender" />
>    </intent-filter>
> </service>
> ```

Thanks! crack! This worked for me, I tried this solution on Ionic Framework 3, and works like charm! Thank u!
