### ISSUE TITLE
Ionic3 - Why android open notification have to use web browser, but IOS can open in apps

### ISSUE THREAD

**Issue by YuyangHYY** [OneSignal/OneSignal-Cordova-SDK#246]
After I set up OneSignal Cordova plugin in my ionic3 project, when I sent notification, IOS and Android both of them can received notification, but when open android notification cannot go into app and view news. IOS can go into app and open the news URL.
I set Launch URL before I push which I put my new URL here.
![2017-09-26 16 45 36](https://user-images.githubusercontent.com/19391002/30851180-70c03a74-a2da-11e7-971f-9d32fee89057.png)
So, I want to know, how to set android platform like IOS can go into apps and view news instead of open in google chrome or other web browser.

**Comment by YuyangHYY** [comment]
This is my ionic info
![2017-09-26 21 45 21](https://user-images.githubusercontent.com/19391002/30863762-681d892e-a304-11e7-976c-093693b0a23a.png)

**Comment by jkasten2** [comment]
@YuyangHYY The native OneSignal Android SDK does not have a built in webview currently like the native OneSignal iOS SDK does at this time.

In the mean time you can direct users to your own in app webview or page. To do this you will need to use additional data instead and handle the usage of this in the [handleNotificationOpened](https://documentation.onesignal.com/docs/cordova-sdk#section--handlenotificationopened-) in your app's code.

**Comment by YuyangHYY** [comment]
Iam using ionic3 not native
