### ISSUE TITLE
Questions: disable notification based on its data

### ISSUE THREAD

**Issue by CoderSquirrel** [OneSignal/OneSignal-Cordova-SDK#250]
Hi i am using cordova/ionic onesignal and i havent found anywhere content about what i wanting. So why not asking here :)
Well explaning myself:
I have and app that will recieve push notification for the user, but i will also sending a couple of 'update' notifications that must be almost invisble for the user.
The problem i'm having: when the app is running i can make notigication not appear, by the flag `inFocusDisplaying` but when the app is in background this notification appears. 
There a way that i can manage which notifications show when my app is running in the background?
Thanks

**Comment by jkasten2** [comment]
@CoderSquirrel It is highly recommend to instead prevent the notification from going to the device by using [setSubscription](https://documentation.onesignal.com/docs/cordova-sdk#section--handlenotificationopened-). This will prevent the device from waking up to just discard the notification.

However it sounds like you are looking to send silent background data that will do background processing, not something that will result in displaying a notification? Could you provide more details on the kind of immediate background processing that needs to be done? Could instead your background work be delayed until the user opens your app again?

`inFocusDisplaying` only effects displaying of the notification when your app is in the foreground. It as no effect when your app is in the background or closed.

**Comment by CoderSquirrel** [comment]
> However it sounds like you are looking to send silent background data that will do background processing, not something that will result in displaying a notification

What i want i exactly that.

One of the problems of waiting for the user to wake phones up again is that
i cant not manage 'groups' of user that will reciever by the onesignal categories...
For reasons that i cant explain
Therefore, when i send the notification, i send the groups that are allowed to get the message, the oters discard.
So, this background notificatino bring also the groups, when the update and add a new user... so if i wait the user to open the app, in the mean time he can be add to the groupd, e.g. 'Doctors', and a new message for the gorups doctors be sent... in that way my user would get this message

I'm kind bad to put idea into words, but i hope that i can pass you my situation.
Thanks

**Comment by CoderSquirrel** [comment]
What i mean is like:
There's something i can change in: `https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/src/android/com/plugin/gcm/OneSignalPush.java `, that i can manually manage when notification appeas on the notification bar and when it souldn't?

**Comment by CoderSquirrel** [comment]
https://documentation.onesignal.com/docs/android-customizations#background-data-and-notification-overriding 
i found this for java
but theres a way to make this in js?
or i have to do both android and ios manually?
**Receive data in the background with or without displaying a notification.**

**Comment by jkasten2** [comment]
@CoderSquirrel It must be down with native Java code on Android or with Swift or Objective-c on iOS. It can't be run in the Cordova / js runtime.
