### ISSUE TITLE
v2.1.2 auto prompts for iOS 11 push registration at the start of app even if kOSSettingsAutoPrompt is set to false

### ISSUE THREAD

**Issue by erdimeola** [OneSignal/OneSignal-Cordova-SDK#251]
Hi,

When I initialize the onesignal plugin at **deviceready** callback like

`window.plugins.OneSignal
.startInit("APPID")
.iOSSettings({
    kOSSettingsKeyAutoPrompt:false,
    kOSSettingsKeyInAppLaunchURL: false
})
.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.InAppAlert)
.handleNotificationReceived(function(jsonData) {
    //RECEIVED HANDLING
})
.handleNotificationOpened(function(jsonData) {
    //OPENED HANDLING
})
.endInit();`

It works like a charm on iOS 9.3.5. But when try it at iOS 11. It automatically asks for push registration.

**Comment by erdimeola** [comment]
You can delete this issue I've found that, if I call getPermissionSubscriptionState, it automatically prompts at iOS 11

**Comment by kylepierce** [comment]
@erdimeola can you share more? I didnt think that this plugin had any dependencies, but I am getting the auto prompt. How did you resolve this issue?

**Comment by erdimeola** [comment]
@kylepierce It doesn't have, I was using cordova-plugin-notification for updating the app icon, to update app icon, this plugin was asking for permission as the user starts the app. I removed the plugin and it works ok right now. Make sure you are using the latest version
