### ISSUE TITLE
Notification Click

### ISSUE THREAD

**Issue by vyacheslav-lonschakov** [OneSignal/OneSignal-Cordova-SDK#252]
Hi, i have application with informative notifications on iOS. Application don't handle click on notification. But notification dismiss by click on it, with opening application.

How i can diactivate notification dismiss by click?

**Comment by jkasten2** [comment]
@vyacheslav-lonschakov If you have set a badge it will be cleared when the app is open. If a badge value is cleared on iOS all notifications for the app will be removed. To prevent the badge clearing by the OneSignal SDK see the instructions below.
https://documentation.onesignal.com/docs/appearance#section-badges

If this wasn't what you were asking please give an example.
