### ISSUE TITLE
Ionic 1, Onesignal Coldstart not firing Notification Open Callback on iOS 11

### ISSUE THREAD

**Issue by gopalaiahvinay** [OneSignal/OneSignal-Cordova-SDK#253]
Hi,

In our app, when we are trying to open a notification, when the app is not in background or force killed. 
The Open notification callback is not getting called on iOS 11. 
It works totally fine on android. 
**One Signal Init Function**
```
var init = function() {
       $cordovaToast.showLongBottom('Onesignal Initialized');
       
       if ($rootScope.isIOS) {
         // Set your iOS Settings
         var iosSettings = {};
         iosSettings["kOSSettingsKeyAutoPrompt"] = true;
         iosSettings["kOSSettingsKeyInAppLaunchURL"] = false;
         window.plugins.OneSignal
           .startInit("API KEY")
           .handleNotificationOpened(notificationOpenedCallback)
           .iOSSettings(iosSettings)
           .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
           .endInit();
         // window.plugins.OneSignal.registerForPushNotifications();
       } else {
         window.plugins.OneSignal
           .startInit("API KEY")
           .handleNotificationOpened(notificationOpenedCallback)
           .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
           .endInit();
       }

       returnOneSingalIDs();
     };

```
**One Signal Notification Open Callback**
```
var notificationOpenedCallback = function(jsonData) {
       $cordovaToast.showLongBottom('Onesignal Notification Opened Callback');
       console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
      
       $rootScope.curNotification = {};
       $rootScope.curNotification = jsonData;
       $log.debug('The Notification Received Is:', $rootScope.curNotification);
       
       $ionicHistory.nextViewOptions({
         disableAnimate: true,
         disableBack: true
       });
       $rootScope.image = $rootScope.curNotification.notification.payload.additionalData.picture;
       $state.go('menu.post');
       
       $rootScope.storage.preventCheck = true;
     
     };
```

Here is a screen recording: 

https://drive.google.com/open?id=0BxIXDOsrwoW9RnU2WDU1dWZtQ3M 

## In the first scenario (1 second - 12 second): 
The App cold starts on clicking a received notification. 
But instead of going to the notification screen or 'menu.post' state in Ionic, 
It is going to the home screen. 
I think this is because the Onesignal openNotification callback logic was not fired and hence the logic not executed. 
Also you can see in the toast message that onesignal was initialized but notification open callback was not fired. 

## In the second scenario(13th second- End) 
When the app is running in the background everything works as expected.
As evident from the toast messages at the bottom, where we can see two toast messages: 
1. Onesignal Initialized
2. Open Notification callback called 

The second scenario is the ideal scenario. 
This issue started after I built an ipa for iOS 11 using XCode 9. 
I have cocoa pods installed. 

**Cordova Plugins Installed**
![cordovaplugins](https://user-images.githubusercontent.com/4154510/31237013-5c2997f0-aa13-11e7-8f5d-fecd18cda51a.PNG)

**Ionic Local Information**
![ionicinfo](https://user-images.githubusercontent.com/4154510/31237032-69f544e2-aa13-11e7-9fdb-72351d1bafa1.PNG)

We need this issue to be fixed ASAP, so any kind of help will be appreciated.

**Comment by jkasten2** [comment]
@gopalaiahvinay Thanks for reporting with all the details. We just released version 2.2.2 to address this open event issue with iOS 11 on cold start.

https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.2.2
