### ISSUE TITLE
Build Fail for Cordova

### ISSUE THREAD

**Issue by fabianglace** [OneSignal/OneSignal-Cordova-SDK#254]
I've just updated to cordova 7 to include onesignal push. This is the error i'm getting..

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.onesignal:OneSignal:3.6.2] /home/fabianglace/Dropbox/mobile/MoWally/platforms/android/build/intermediates/exploded-aar/com.onesignal/OneSignal/3.6.2/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.onesignal" to force usage

**Comment by jkasten2** [comment]
@fabianglace We just added a new troubleshooting section to resolve this error.
https://documentation.onesignal.com/v3.0/docs/troubleshooting-cordova-variants#section-manifest-merger-failed-uses-sdk-minsdkversion-14-cannot-be-smaller-than-version-15-declared-in-library-com-onesignal-onesignal-3-6-2-

Feel free to reopen this issue if the above does not help.

**Comment by jkasten2** [comment]
@pavlo Thanks for letting us know, just updated the link
