### ISSUE TITLE
OneSignal-Cordova-SDK fails when added on ionic 2 project

### ISSUE THREAD

**Issue by anegash** [OneSignal/OneSignal-Cordova-SDK#255]
Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (APP_LOCATION/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

Failed to restore plugin "onesignal-cordova-plugin" from config.xml. You might need to try adding it again. Error: Error: pod: Command failed with exit code 31

**Comment by harlin-setiadarma** [comment]
I have the same issue.
Maybe latest release have broken something?
@anegash have you tried to use older release, like
https://github.com/OneSignal/OneSignal-Cordova-SDK#2.0.11

**Comment by anegash** [comment]
I actually figured out the problem.

if you add(or upgrade) one signal, it uses the latest dependencies that have to be downloaded using cocoapods.

running "pod repo update"

should fix the problem.

@harlin-setiadarma try this ^

**Comment by jkasten2** [comment]
@anegash Thanks for replying with a solution to this issue.

@harlin-setiadarma Feel free to reply if the above didn't help.
