### ISSUE TITLE
Issue with com.android.support:multidex:26.1.+

### ISSUE THREAD

**Issue by jlariza** [OneSignal/OneSignal-Cordova-SDK#258]
Good day,

I am trying to use the plugin on an ionic2 app. The problem is that when I run "run android" I get the following message:

Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not find any version that matches com.android.support:multidex:26.1.+.
     Versions that do not match:
         1.0.1
         1.0.0
         1.0.2
multidex does not have a bigger version than 1.0.2 (from what I found). 

The issue is produced by https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/build-extras-onesignal.gradle#L29

What should I do? is something bad with my configuration?

Thank you,

**Comment by jlariza** [comment]
I could make it work modifying platforms/android/onesignal-cordova-plugin/duety864312-build-extras-onesignal.gradle and replacing 'version':'26.1.+' for 1.+

 'com.android.support': [
       'version': '1.+',

The problem is that that file is generated automatically, is not a file you usually add to a repository; so it is not a long term solution.

Thank you

**Comment by jkasten2** [comment]
@jlariza Thanks for reporting, we will update the `build-extras-onesignal.gradle` to exclude the `multidex` module from the `com.android.support` in the alignment logic.

**Comment by BenjaminWatts** [comment]
I am still getting this issue - any progress made/?

**Comment by ananmelkonyan** [comment]
@jkasten2 Same for me, yet nothing updated?

**Comment by jkasten2** [comment]
@BenjaminWatts @ananmelkonyan Just released version [2.2.3](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.2.3) this includes this fix.

**Comment by ananmelkonyan** [comment]
@jkasten2 Thanks can you update also npm to 2.2.3

**Comment by jkasten2** [comment]
@ananmelkonyan 2.2.3 had a gradle issue so it was unpublished. Just fixed this and released 2.2.4 and it is available on npm now.
