### ISSUE TITLE
[Linker failed] ld: ## duplicate symbols for architecture armv7

### ISSUE THREAD

**Issue by polfernandez** [OneSignal/OneSignal-Cordova-SDK#259]
After installing cocoapods and ionic cordova plugin add onesignal-cordova-plugin --save
following: https://documentation.onesignal.com/v3.0/docs/ionic-sdk-setup

With iOS (XCode) I run into the following issue:

**ld: 191 duplicate symbols for architecture armv7**

Similar to: https://stackoverflow.com/questions/16427024/duplicate-symbols-for-architecture-armv7
and: https://stackoverflow.com/questions/46173762/running-ionic-3-app-on-iphone-throws-error-2-duplicate-symbols-for-architecture

with the following trace of (multiple) errors:

`duplicate symbol _OBJC_IVAR_$_CDVWKWebViewEngine._engineWebView in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_IVAR_$_CDVWKWebViewEngine._webServer in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_IVAR_$_CDVWKWeakScriptMessageHandler._scriptMessageHandler in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_IVAR_$_CDVWKWebViewEngine._weakScriptMessageHandler in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_CLASS_$_CDVWKWeakScriptMessageHandler in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_METACLASS_$_CDVWKWeakScriptMessageHandler in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_IVAR_$_CDVWKWebViewEngine._uiDelegate in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_CLASS_$_CDVWKWebViewEngine in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_METACLASS_$_CDVWKWebViewEngine in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_IVAR_$_CDVWKWebViewEngine._frame in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-7F247B71F9C2086B.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewEngine-BC284022B1E86E8B.o

duplicate symbol _OBJC_CLASS_$_CDVWKWebViewUIDelegate in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewUIDelegate-6C61C0957A8C9455.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewUIDelegate-E53BECD21D9FD2B3.o

duplicate symbol _OBJC_METACLASS_$_CDVWKWebViewUIDelegate in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewUIDelegate-6C61C0957A8C9455.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewUIDelegate-E53BECD21D9FD2B3.o

duplicate symbol _OBJC_IVAR_$_CDVWKWebViewUIDelegate._title in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewUIDelegate-6C61C0957A8C9455.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKWebViewUIDelegate-E53BECD21D9FD2B3.o

duplicate symbol _OBJC_CLASS_$_CDVWKProcessPoolFactory in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKProcessPoolFactory-8AF388680C6B675C.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKProcessPoolFactory-ECC6676A8970259E.o

duplicate symbol _OBJC_METACLASS_$_CDVWKProcessPoolFactory in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKProcessPoolFactory-8AF388680C6B675C.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKProcessPoolFactory-ECC6676A8970259E.o

duplicate symbol _OBJC_IVAR_$_CDVWKProcessPoolFactory._sharedPool in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKProcessPoolFactory-8AF388680C6B675C.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/CDVWKProcessPoolFactory-ECC6676A8970259E.o

duplicate symbol _OBJC_IVAR_$_GCDWebServer._dispatchQueuePriority in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/GCDWebServer-7A66B32399DB9F5F.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/GCDWebServer-D7524ACFBEC1C181.o

duplicate symbol _OBJC_IVAR_$_GCDWebServer._disconnectDelay in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/GCDWebServer-7A66B32399DB9F5F.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/GCDWebServer-D7524ACFBEC1C181.o

duplicate symbol _OBJC_IVAR_$_GCDWebServer._bindToLocalhost in:

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/GCDWebServer-7A66B32399DB9F5F.o

    /Users/asolutions/Library/Developer/Xcode/DerivedData/Medxat-hbhloutodohrgedevnbdtnzwktgn/Build/Intermediates.noindex/Medxat.build/Debug-iphoneos/Medxat.build/Objects-normal/armv7/GCDWebServer-D7524ACFBEC1C181.o`

...
+ info:
`    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v8.1.2
    npm               : 5.4.2
    OS                : macOS Sierra
    Xcode            : Xcode 9.0 Build version 9A235`

Using **Xcode 9.0**

Any hint?

**Comment by jkasten2** [comment]
@polfernandez None of the duplicated symbol listed above are used by OneSignal. Can you try a clean build of iOS project by removing the platform and re-adding it?

```
ionic cordova platform remove ios
ionic cordova platform add ios
```

**Comment by taegyunum** [comment]
@polfernandez 

It was not due to OneSignal, but I experienced similar issue.
I tried remove node_modules platform/ios and reinstall several times, downgraded packages didn't help.

After spending many hours, I solved the issue reinstalling 

cordova-plugin-wkwebview-engine

```
ionic cordova plugin remove cordova-plugin-wkwebview-engine
ionic cordova plugin add cordova-plugin-wkwebview-engine
```

Solved my problem.

Hope this help you.

**Comment by jkasten2** [comment]
@taegyunum Thanks for leaving the solution to this issue.

@polfernandez Feel free to reply if the answer above did not help.

**Comment by polfernandez** [comment]
@taegyunum  sorry for late response, but it did not help...

**Comment by jkasten2** [comment]
@polfernandez I recommend trying a clean build instructions below.
https://documentation.onesignal.com/docs/troubleshooting-cordova-variants#section-clean-build

This will nuke your `platforms/ios` folder where it sounds like you may have duplicated files in.

Since the issue is related to something with Cordova / Ionic itself I recommend posting a thread on their forum as they will be able to help you better there.
https://forum.ionicframework.com/

**Comment by anurag0707** [comment]
Hi,
     did anybody find solution for this issue
