### ISSUE TITLE
do i need to whitelist any domains to use this ?

### ISSUE THREAD

**Issue by dmastag** [OneSignal/OneSignal-Cordova-SDK#260]
In my company all urls have to be whitelisted before they can be used. Are there any urls that I need to whitelist in order for OneSignal to be working properly?

**Comment by gdeglin** [comment]
Yes, you should whitelist onesignal.com and cdn.onesignal.com.

For receiving notifications, you should make sure the necessary ports are open:

For iOS: https://support.apple.com/en-us/HT203609
For Android: The ports to open are: 5228, 5229, and 5230. FCM typically only uses 5228, but it sometimes uses 5229 and 5230. FCM doesn't provide specific IPs, so you should allow your firewall to accept outgoing connections to all IP addresses contained in the IP blocks listed in Google's ASN of 15169.

For follow up questions, please reach out to our support team at support@onesignal.com
