### ISSUE TITLE
Xcode crashed when adding pods onesignal framewoks to "Link Binary With Libraries"

### ISSUE THREAD

**Issue by lakshmana** [OneSignal/OneSignal-Cordova-SDK#261]
Hi there,

I recently updated the Xcode so that I can compile cordova app on my ios 11.0.3 iphone 6s.
But when I tried to add "Pods/Pods/OneSignal/Frameworks/OneSignal.framework" to " Link Binary With Libraries" as explained in iOS part 2 https://documentation.onesignal.com/docs/cordova-sdk-setup#section-5-ios-part-2-recommend- 

I restarted the xCode and even the mac, so I always have this problem. The xCode crashes when I add onesignal framework. btw it does not crash when I add SystemConfiguration.framework and UIKit.framework into "Lnk Binary with Lib.." 

Do I need to perform any extra steps to get rid of this problem?

Thx
Laxman

**Comment by lakshmana** [comment]
BTW, the version of Xcode is 9.0.1 (9A1004).

Thx
Laxman

**Comment by lakshmana** [comment]
The video of the problem is : https://photos.app.goo.gl/7tSzQH8wp65xG1nQ2
Let me know if you need the crash report too.

Thx
Laxman

**Comment by myrsk** [comment]
Same issue.

**Comment by lakshmana** [comment]
@myrsk  please share if you have fixed on your side.

**Comment by myrsk** [comment]
Unfortunately I still haven’t managed to get it to work. 

Regards,
R. Alkhaili

**Comment by lakshmana** [comment]
I hope someone take a look on this issue.

**Comment by jkasten2** [comment]
@lakshmana Does this issue only happen on Xcode 9.0.1? Are you able to reproduce the issue on 9.0.0?

**Comment by lakshmana** [comment]
@jkasten2 The issue occured after I updated the Xcode to version 9.0.1 Prior to it, the sdk was working fine but I do not remember the exact version of earlier Xcode.

**Comment by lakshmana** [comment]
@myrsk which version of xcode are you using ?

**Comment by RanaProgrammer** [comment]
I resolved it. by clicking on + (plus) sign on bottom and selecting add another and selecting onesignal.framework by path.
click plus(+) sign --> click add another/more on left bottom of pop-up --> selecting onesignal.framework in your project/platforms/ios/Pods/something sdk/onesognal.framework

tell me if it solves your issue.

**Comment by RanaProgrammer** [comment]
@lakshmana and kindly tell me the method of how you created that video and shared via google photos?

**Comment by lakshmana** [comment]
@RanaProgrammer hi thans for the help. It worked for me. And the OneSignal documentation has also been updated with the same solution. :) About the video, I used QuickTime player to record the screen. http://prntscr.com/h76sys :)
