### ISSUE TITLE
build failed on ios

### ISSUE THREAD

**Issue by sombriks** [OneSignal/OneSignal-Cordova-SDK#264]
In file included from

```
/Users/sombriks/git/aplicativo-catolico/app-usuario/dist/platforms/ios/Paroquia Virtual/Plugins/onesignal-cordova-plugin/OneSignalPush.m:31:
/Users/sombriks/git/aplicativo-catolico/app-usuario/dist/platforms/ios/Paroquia Virtual/Plugins/onesignal-cordova-plugin/OneSignalPush.h:32:9: fatal error:
      'OneSignal/OneSignal.h' file not found
#import <OneSignal/OneSignal.h>
        ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **

================

using cordova 7.1.0, cordova-ios@4.5.3 and the following plugins:

[sombriks@eiko dist]$ cordova plugin list
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-media 3.0.1 "Media"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
onesignal-cordova-plugin 2.2.2 "OneSignal Push Notifications"
```

any guidance is welcome.

**Comment by jkasten2** [comment]
@sombriks Can you ensure cocoapods was successfully installed on your system. Make sure you don't get any errors when running the following.

```
sudo gem install cocoapods
pod repo update
```

Then try reinstalling the OneSignal plugin on your project.
```
cordova plugin rm onesignal-cordova-plugin --save
cordova plugin add onesignal-cordova-plugin --save
```

**Comment by luchusnet** [comment]
Same problem to! Fix above not working.

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:
    cordova (Cordova CLI) : 7.1.0 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:
    @ionic/app-scripts : 1.3.12
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.5.0

System:
    ios-deploy : 1.9.2 
    ios-sim    : 5.0.8 
    Node       : v8.7.0
    npm        : 5.5.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:
    ANDROID_HOME : not set

Misc:
    backend : pro

**Comment by fatihky** [comment]
Hi @luchusnet, can you try to open `.xcworkspace` file and build again?

**Comment by shripad20** [comment]
I am also facing the same error when installed **onesignal-cordova-plugin 2.2.1**
@jkasten2 I followed your step given in above comment. Also updated things:

ruby - 2.5
cocoapods - 1.4
XCode - 9.0
OS - macOS Sierra 10.12.6


![screen shot 2018-03-05 at 7 43 52 pm](https://user-images.githubusercontent.com/14152297/36979479-a7af77c4-20ad-11e8-8820-3caf4ccca038.png)

**Comment by sombriks** [comment]
Hi @jkasten2  i started to open the .xcworkspace file and then it worked. Many thanks.

**Comment by Nightsd01** [comment]
@shripad20 are you sure you’re opening the `.xcworkspace` and not the `.xcodeproj` file?

**Comment by shripad20** [comment]
I am working on cordova project. I don’t have .xcworkspace file in my project. Installed one signal sdk with cordova command. 
Cordova plugin add onesignal-cordova-plugin --save

**Comment by sombriks** [comment]
@shripad20 inside the platforms folder you will find an ios project. there you will get the .xcworkspace file.

also, IIRC, the error message on ios platforms tells how to properly install cocoa pods

**Comment by Nightsd01** [comment]
@shripad20 please make sure to very carefully read the setup guide. Making sure to open the `YourProjectName.xcworkspace` should resolve your issue.

If you encounter any further problems please feel free to ask.

@sombriks thank you!

**Comment by shripad20** [comment]
@Nightsd01 when I open `YourProjectName.xcworkspace` it shows project file in red color and containing no files in it. Please see below image:
![screen shot 2018-03-06 at 10 08 47 am](https://user-images.githubusercontent.com/14152297/37014542-6532c502-2127-11e8-875b-30c089b134f3.png)

**Comment by shripad20** [comment]
I resolved this issue by upgrading iOS platform (version 4.4.0) to the latest. Though I was using greater version (4.3.1) than required (4.3.0), it was not getting installed correctly.

**Comment by abisaiA** [comment]
whenever i try to install the plugin 'cordova plugin rm onesignal-cordova-plugin --save' i get spawn EPERM from my terminal

**Comment by jkasten2** [comment]
@abisaiA Thanks for reporting, do you get this same error when adding or removing other plugins in your project? Can you try running with `--verbose` to provide more details on the error.

**Comment by abisaiA** [comment]
@jkasten2 Yes I get the same error,  here is what i get with --verbose
<img width="940" alt="Screen Shot 2022-05-18 at 08 14 23" src="https://user-images.githubusercontent.com/40404286/168962331-df53d8ea-29f1-4285-984f-a328045adc83.png">

**Comment by jkasten2** [comment]
@abisaiA Thanks, however I don't see anything that stands out here on the issue. Can you open a new issue with details on the exact version of cordova you are using and steps to reproduce on a new project?

**Comment by abisaiA** [comment]
@jkasten2 thanks, let me open new issue
