### ISSUE TITLE
Feature request: Return player id after init

### ISSUE THREAD

**Issue by yingliangzhang** [OneSignal/OneSignal-Cordova-SDK#267]
It would be great to have the player id returned after init so that I can save it to the backend. I my case, I'm using parse-server, the device is registered on OneSignal but since I don't have the info of the registered player, my parse-server knows nothing about OneSignal, this makes sending push notification to a specific user seems impossible.

**Comment by jkasten2** [comment]
@yingliangzhang The recommend way to get the player id is to use the 
[`addSubscriptionObserver`](https://documentation.onesignal.com/docs/cordova-sdk#section--addsubscriptionobserver-) function. This fires the passed in callback fires when any subscription property changes. This makes it easy to be efficient as you can directly add your network calls here, you just to need to check whats changed is what you are looking for. Example, when the user becomes subscribed.
```javascript
window.plugins.OneSignal.addSubscriptionObserver(function (state) {
  if (!state.from.subscribed && state.to.subscribed) {
    console.log("Subscribed for OneSignal push notifications!")
    // get player ID
    state.to.userId
  }
  console.log("Push Subscription state changed: " + JSON.stringify(state));
});
```

**Comment by jkasten2** [comment]
Feel free to reply if the above did not help.
