### ISSUE TITLE
Duplicate notifications on using headings/title of notification

### ISSUE THREAD

**Issue by baskin** [OneSignal/OneSignal-Cordova-SDK#268]
Hi Team,
I'm getting duplicate notifications on android if I use the 'headings' options in createNotification api.
Duplicity doesn't go away even on using same 'collapse_id'.
It goes away if I remove the 'headings' option.
It doesn't occur every single time.

Actually it is not exactly a duplicate - rather an extra message.
The extra message appears with only the heading but without the original body. It is missing the original launch URL too.

env info:
I'm using onesignal via the Ionic framework

>     onesignal-cordova-plugin: 2.2.2
>     cordova (Cordova CLI) : 7.1.0 
>     Cordova Platforms  : android 6.2.3
>     Ionic Framework    : ionic-angular 3.8.0
>     Android SDK Tools : 25.2.4
>     Node              : v7.10.0
>     npm               : 5.5.1 
>     Build OS        : OS X El Capitan
> 

Tried this on Android 5 & 6 and getting the extra message on both.

**Comment by jkasten2** [comment]
@baskin This sounds like another SDK might be trying to parse and display the notification payload from OneSignal. Can you run `ionic cordova plugin list` and attach the full list? Then if you see any another notification plugins can you try removing them?

**Comment by baskin** [comment]
```
onesignal-cordova-plugin 2.2.2 "OneSignal Push Notifications"
cordova-plugin-firebase 0.1.24 "Google Firebase Plugin"
cordova-admob-sdk 0.8.0 "AdMob SDK"
cordova-plugin-admob-free 0.10.0 "Cordova AdMob Plugin"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-code-push 1.9.8-beta "CodePush"
code-push 2.0.1-beta "CodePushAcquisition"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

Could the firebase plugin be interfering with this? I'm using it only for event logging and remote config management.

**Comment by jkasten2** [comment]
@baskin It might be, it does try to parse the an FCM payload when investigating the source of the plugin.
https://github.com/arnesson/cordova-plugin-firebase/blob/213e9c0d2e7101887055f5eb610c4804a6c24cdb/src/android/FirebasePluginMessagingService.java

Can you try to reproducing problem after removing `cordova-plugin-firebase` temporary to see if it resolves the issue?

**Comment by baskin** [comment]
Looks like I'm not receiving the second notification on removing the firebase plugin. 

It's strange that it occurs only if I specify the title/headings in the message. I skimmed over the firebase plugin code, couldn't find anything that could explain this.

**Comment by jkasten2** [comment]
@baskin I believe it is from this line.
https://github.com/arnesson/cordova-plugin-firebase/blob/213e9c0d2e7101887055f5eb610c4804a6c24cdb/src/android/FirebasePluginMessagingService.java#L52

OneSignal notifications are data type payloads. If you include a heading on OneSignal it will be included as "title" in the FCM payload. This is triggering that plugin to display a notification since title is not empty now.

**Comment by baskin** [comment]
@jkasten2 how is 'contents' handled by onesignal? Does it pass on as 'text' in FCM payload?

The code you point to treats 'text' and 'title' in the same stride i.e. one of 'text' or 'title' needs to be present in order for the firebase plugin to display the notification. In my case, if I omit 'title' and keep only the 'text' ('contents' in onesignal api), I stop getting the extra message.

**Comment by jkasten2** [comment]
OneSignal sends "alert" instead of "text" in the payload for 'contents'. This is why only "title" triggers the extra notification.

**Comment by baskin** [comment]
Got it! thanks for the explanation.

I see that folks created cordova-plugin-firebase-analytics to handle such conflicts with cordova-plugin-firebase. However, I'm using remote config capabilities bundled with cordova-plugin-firebase and cannot forego its use.

@jkasten2 Can you suggest any "fix" based on your experience, besides the hack of not using 'headings' in my onesignal calls? Otherwise please close the request. You've been of great help :)

**Comment by jkasten2** [comment]
@baskin There isn't an option to change the payload format send by OneSignal so the only way would be for `cordova-plugin-firebase` to be modified to prevent the display of the notification. 

This would need to be changed in their `FirebasePluginMessagingService.java` to disable displaying the notification. Based on a flag that could be set in the AndroidManifest.xml or through some other method. I would recommend forking and creating a pull request to their repo so it can be integrated so you don't have to keep using your own custom fork and have to maintain it.

**Comment by baskin** [comment]
Thanks, I'll followup with the firebase plugin repo separately.

**Comment by rodrigoreal** [comment]
Hey @baskin 
Did you find a way to keep `cordova-plugin-firebase` and don't get the duplicated notification?

**Comment by guyman** [comment]
Any updates about that ?

**Comment by jkasten2** [comment]
@rodrigoreal @guyman Can you try the latest `onesignal-cordova-plugin` 2.4.1 version? Also make sure you have the latest Google Play services app installed on the device you are testing on.

Let us know the version of Android you are testing on if you continue seeing issues.
