### ISSUE TITLE
Change setSubscription to false doesn't change anything in ionic

### ISSUE THREAD

**Issue by ThomasAtome** [OneSignal/OneSignal-Cordova-SDK#269]
Hi,

I've got a problem. When i try to change the setSubscription in order to stop the user to receive notifications, nothing append. The user still receive notif and in onesignal dashboard in the user par i can see that the subscription flag is set to yes..

Well, is this normal ? I let you some code for how i init the plugin in my app.component.ts

`this.notification.startInit("d1d3f0d9-576a-4d0c-8cfe-9dde084fe47e", "71737652635");
this.notification.inFocusDisplaying(this.notification.OSInFocusDisplayOption.Notification);
this.notification.setSubscription(false);
this.notification.endInit();`

Thanks

**Comment by ThomasAtome** [comment]
Well it seems that the setSubscription should be set after the endInit..

**Comment by jkasten2** [comment]
@ThomasAtome Correct, `setSubscription` must be called after `endInit` otherwise it will be ignored. Only the few functions noted in the Initialization section should be used before endInit.
https://documentation.onesignal.com/docs/cordova-sdk
