### ISSUE TITLE
App Crashing only on Google Pixle XL Oreo 8.0

### ISSUE THREAD

**Issue by YasirAmeen** [OneSignal/OneSignal-Cordova-SDK#270]
My App was working fine but since Android Oreo has come to Google Pixel XL it keeps Crashing following is the Exception stack-trace

`Fatal Exception: java.lang.AbstractMethodError: abstract method "boolean android.app.job.JobServiceEngine.onStartJob(android.app.job.JobParameters)" at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108) at android.os.Handler.dispatchMessage(Handler.java:105) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6541) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

Can anyone help me with this ?

**Comment by Aihabam** [comment]
@YasirAmeen  I have the same issue did you find the solutions
