### ISSUE TITLE
ios install problem

### ISSUE THREAD

**Issue by patrickboulay** [OneSignal/OneSignal-Cordova-SDK#274]
I installed the plugin and everything was working fine.
After I did a 
`ionic cordova platform remove ios`
and after I did 
`ionic cordova  platform add ios`
I got an error with the onesignal plugin.

I removed and readd the plugin and I got this error:
```
cordova plugin add onesignal-cordova-plugin --save
✖ Running command - failed!
[ERROR] An error occurred while running cordova plugin add onesignal-cordova-plugin --save (exit code 1):        
        Installing "onesignal-cordova-plugin" for android
        Subproject Path: CordovaLib
        Installing "onesignal-cordova-plugin" for ios
        Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 1
             at ChildProcess.whenDone 
        (/Users/patrickboulay/NetBeansProjects/ionic/LotterySociety/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
             at emitTwo (events.js:106:13)
             at ChildProcess.emit (events.js:191:7)
             at maybeClose (internal/child_process.js:891:16)
             at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        Error: pod: Command failed with exit code 1
```
cordova --version  = ionic 7.1.0
Im on MacOs Sierra 10.12.6

any idea someone?

Thanks

**Comment by jkasten2** [comment]
@patrickboulay Can you run the following and make sure it finishes with any errors.
```
sudo gem install cocoapods
pod repo update
```

**Comment by patrickboulay** [comment]
Now I can install the plugin but I have an other error.
I have a linker problem... 
If I didnt do the iOS installation part, is it normal that I cant build my project?

Why my project was built correctly before and not now what out any changes? (my project was running before without the notification but was working...)

**Comment by jkasten2** [comment]
@patrickboulay If you were building your Cordova app through XCode make sure you are opening the new ` <project-root>/platform/ios/YourAppName.xcworkspace` file. The .project file won't work to build with Xcode.

If you are building through the command line please share the exact command. Also please share the full linker error.

**Comment by fatihky** [comment]
Hi, could you install cocoapods 1.1.1 and try again? I was having a similar problem and solved it after installing cocoapods 1.1.1.
Here is my reference: https://github.com/phonegap/phonegap-plugin-push/issues/1465#issuecomment-267711740

**Comment by patrickboulay** [comment]
@jkasten2 Great, I was trying to compile the .xcodeproj file. 
Thanks a lot!

**Comment by kapilSoni101** [comment]
@fatihky: sir i checked that link but can you tell me which path we have to pass inside     
`  > **[ /usr/local/bin]**`
 this path i am confused please tell me?

**Comment by fatihky** [comment]
@kapilSoni101 sorry, I've just seen your comment. Sorry but I couldn't fully understand your question. You don't have to put anything inside `/usr/local/bin` directory. Instead, point that directory to `gem` so it'll install cocoapods inside that directory as I understand.
