### ISSUE TITLE
can't send Tags 

### ISSUE THREAD

**Issue by osterland** [OneSignal/OneSignal-Cordova-SDK#275]
Hi Folks, 

im sure i am missing something easy, but i cant send Tags. I can send Tags between 

this.oneSignal.startInit
       
 this.oneSignal.sendTags({test: '0'});

this.oneSignal.endInit() 

but nowhere else in my code. Do i have to init OneSignal every time i wanne change tags??

ty

**Comment by jkasten2** [comment]
@osterland OneSignal must be initialized each time a page is loaded in your app. Otherwise sendTags and other functions on OneSignal will not work
