### ISSUE TITLE
Annoying iOS only popups when the app is in the front and getting push

### ISSUE THREAD

**Issue by Ziv-Barber** [OneSignal/OneSignal-Cordova-SDK#282]
I'm getting annoying iOS only popups when the app is in the front and getting push.
Any way to disable these popups?

**Comment by jkasten2** [comment]
@Ziv-Barber You can use [`inFocusDisplaying`](https://documentation.onesignal.com/docs/cordova-sdk#section--infocusdisplaying-) to change how notifications will be displayed in the foreground.

**Comment by Ziv-Barber** [comment]
Perfect. Thanks!
