### ISSUE TITLE
Move the button to the right!

### ISSUE THREAD

**Issue by M4ttscx** [OneSignal/OneSignal-Cordova-SDK#286]
Move the button to the right, move the "ok" to the right, not to the left when you receive a message inside the application.

![p8ecvwywt3ovfusemrwmqa](https://user-images.githubusercontent.com/26545901/34401616-81ab695c-eb83-11e7-8cc9-cf48637f9542.png)

**Comment by Nightsd01** [comment]
This is a system UI. OneSignal does not have control over it
