### ISSUE TITLE
Android - What is the small icon in the bottom right corner of the notification icon?

### ISSUE THREAD

**Issue by dfibuch** [OneSignal/OneSignal-Cordova-SDK#293]
This is more of a question than an issue. I got everything working in my app with OneSignal but noticed that whenever I receive a notification on a Android device, it has a small round icon with a white square in the bottom right corner of my actual icon.

I can see that other notifications also have this, for example Google Maps notification has the maps icon in there.

My question is how do I customise this little icon or even remove it?

**Comment by jkasten2** [comment]
@dfibuch See our documentation below on customizing the small notifications icon and examples of what it will look like on different Android versions.
https://documentation.onesignal.com/docs/customize-notification-icons

If you are running into issue after following the guide I recommend contacting OneSignal support while signed into the OneSignal dashboard as they can provide some suggestions quicker.
