### ISSUE TITLE
Build on IOS does not activate automatically push notif capability in xcworkspace

### ISSUE THREAD

**Issue by hugoblanc** [OneSignal/OneSignal-Cordova-SDK#294]
When I add onesignal-cordova-sdk to my Ionic/Cordova, that should automatically activate the push notification capability in the XCode project. 
Particularly in case of continuous integration where I stuck because I need to open the xcworkspace and then click on the button in "**Capabilities**" section.

**Comment by jkasten2** [comment]
@hugoblanc We have enable "Capabilities" step in our instructions as it is required that you do so once per iOS bundle id. Xcode actually makes modifications on your provisioning profile on Apple's server to do this. After that you shouldn't have to do so manually. The [`plugin.xml`](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/2.2.5/plugin.xml#L73-L84) tells Cordova to add this to the plist so clean builds should work from a CI environment.

**Comment by hugoblanc** [comment]
As you said, we need to activate the capability at least one time per bundle id. On the following ionic build, even if the capability is shown as disabled, the push notification work well.
But I need to avoid the first time activation to have  a full automatic build process ...

**Comment by Nightsd01** [comment]
@hugoblanc I don't believe the OneSignal SDK actually _can_ address this issue, you would need to modify your project's `config.xml` to add an entitlements file to the iOS project.

First, enable the Push Notifications entitlement (and any other entitlements your app needs). Then, you need to go into Finder and copy this `yourAppName.entitlements` file to the root of the Cordova project. Once you've done this, you can edit your `config.xml` file to include this:

```xml
<platform name="ios">
    <resource-file src="[yourProjectName].entitlements" />
</platform>
```

This should automatically copy the `yourProjectName.entitlements` file to the iOS project directory whenever the iOS platform is added.

If you have any further issues please feel free to ask and I'll be happy to reopen the issue.
