### ISSUE TITLE
One signal plugin throws error for ionic cordova build android command

### ISSUE THREAD

**Issue by nidhi1612** [OneSignal/OneSignal-Cordova-SDK#300]
one signal plugin gives an error while ionic cordova build android after npm update. all the angular dependencies are upgraded to 5.. versions.

Plugin version:  ^2.2.5

Platform: android

OS version: android 26 api level (oreo)

Cordova version (cordova -v): 7.0.1

Cordova platform version (cordova platform ls): android 6.2.3

Ionic Version (if using Ionic): 3.19.1

Expected Behaviour:
ionic cordova build android should be successful, since it works well with older versions of dependencies.

```
 "dependencies": {
        "@angular/common": ""4.1.2",
        "@angular/compiler": ""4.1.2",
        "@angular/compiler-cli": ""4.1.2",
        "@angular/core": ""4.1.2",
        "@angular/forms": ""4.1.2",
        "@angular/http": ""4.1.2",
        "@angular/platform-browser": ""4.1.2",
        "@angular/platform-browser-dynamic": ""4.1.2",
        "@ionic-native/core": "3.10.2",
        "@ionic-native/onesignal": "^3.12.1",
        "@ionic-native/splash-screen": "3.10.2", 
        "@ionic-native/status-bar": "3.10.2", 
        "@ionic/storage": "^2.0.4", 
        "cordova-android": "^6.2.3", 
        "cordova-plugin-device":  "^1.1.6", 
        "cordova-plugin-splashscreen": "^4.0.3", 
        "cordova-plugin-whitelist": "^1.3.2", 
        "ionic-angular":  "3.5.3", 
        "ionic-plugin-keyboard":  "^2.2.1", 
        "ionicons": "3.0.0",
        "onesignal-cordova-plugin": "^2.2.2", 
        "rxjs": "5.1.1", 
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.11" 
    },
```
after npm update dependencies versions are as below,

```
"dependencies": {
        "@angular/common": "5.0.3",
        "@angular/compiler": "5.0.3",
        "@angular/compiler-cli": "5.0.3",
        "@angular/core": "5.0.3",
        "@angular/forms": "5.0.3",
        "@angular/http": "5.0.3",
        "@angular/platform-browser": "5.0.3",
        "@angular/platform-browser-dynamic": "5.0.3",
        "@ionic-native/core": "4.4.0",
        "@ionic-native/onesignal": "^4.5.3",
        "@ionic-native/splash-screen": "4.4.0",
        "@ionic-native/status-bar": "4.4.0",
        "@ionic/storage": "2.1.3",
        "cordova-android": "^6.2.3",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-ionic-webview": "^1.1.11",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-whitelist": "^1.3.1",
        "ionic-angular": "3.9.2",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "onesignal-cordova-plugin": "^2.2.5",
        "rxjs": "5.5.2",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.18"
    },
```

and when ionic cordova build android command is run, it throws below error.
A problem occurred configuring root project 'android'.

> Could not resolve com.onesignal:OneSignal:3.7.1.
>      Required by:
>          project :
>       > Could not resolve com.onesignal:OneSignal:3.7.1.
>          > Could not get resource 'https://repo1.maven.org/maven2/com/onesignal/OneSignal/3.7.1/OneSignal-3.7.1.pom'.
>             > Could not GET 'https://repo1.maven.org/maven2/com/onesignal/OneSignal/3.7.1/OneSignal-3.7.1.pom'.
>                > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I notice that, after the update, when one signal plugin is added and this plugin is causing the error.

Steps to Reproduce:
create new ionic project.
install cordova-plugin-local-notifications
try building project for android - it throws the above error.

**Comment by mtshare** [comment]
Have you tried these commands?
```
sudo gem install cocoapods
pod repo update
```

**Comment by nidhi1612** [comment]
@mtshare I am facing the issue on android, and not on ios.

**Comment by jkasten2** [comment]
@nidhi1612 The error means your system is having issues connecting to maven where the OneSignal SDK is hosted. This noted from your error above.
```
Could not get resource 'https://repo1.maven.org/maven2/com/onesignal/OneSignal/3.7.1/OneSignal-3.7.1.pom'.
```
The is a valid URL, make sure you don't have a proxy or firewall blocking this URL.
https://repo1.maven.org/maven2/com/onesignal/OneSignal/3.7.1/OneSignal-3.7.1.pom

You should be able to view this file in your web browser if everything is working.

**Comment by nidhi1612** [comment]
@jkasten2 that is the surprising part, i am able to open the URL in my web browser. But getting the error while build.

**Comment by jkasten2** [comment]
@nidhi1612 I also noticed this error just below the URL.

> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Can you make sure your Java version is up to date? I see there are a number of entires when Googling this error. They seem to either be related to a proxy issue or a cert issue with Java on the system.

**Comment by nidhi1612** [comment]
@jkasten2 I checked. my java version is latest. How can i check the cause for the error now?

> C:\Users>java -version
> java version "1.8.0_161"
> Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by Nightsd01** [comment]
@nidhi1612 Apologies for the delayed response. Are you still encountering this issue? I am closing the issue due to inactivity but please feel free to respond if you are still having this problem and I'd be happy to reopen and investigate.

**Comment by NiiVAN** [comment]
Hello, having problems with the onesignal build plugin whenever i try to build my app through PGB. Can someone help please

**Comment by jkasten2** [comment]
@NiiVAN There is a PGB build error here for Android, issue #375. If it is a different error / issue then I recommend creating an new ticket.

**Comment by jkasten2** [comment]
@martinlewas We recommend Cordova CLI version 8.0 and Cordova Android 7.1 for OneSignal 3.7.1 but it should work with older versions of Cordova still. See this comment for more details.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/375#issuecomment-395314351

If you continue to see an issue I recommend opening a new issue with as much detail as possible on the error your seeing and the steps to reproduce. Thanks.
