### ISSUE TITLE
Cordova + OneSignal + Wordpress

### ISSUE THREAD

**Issue by mad2kx** [OneSignal/OneSignal-Cordova-SDK#301]
Hi there,

I was wondering if there's a workaround to launch OneSignal Push Notifications within a Cordova Wordpress App?

The moment the user opens the app he/she will be registered for notifications. Normal PushMessages through OneSignal will trigger the app to open but articles sent through Wordpress will cause the normal browser to open.

I am aware that according to OneSignal it's not working but maybe someone actually had an idea of how it works?

**Comment by Nightsd01** [comment]
@mad2kx I am not entirely sure what you mean. What do you mean when you say "articles sent through WordPress will cause the normal browser to open"...?

You have total control of what happens with the Cordova OneSignal SDK.

If you want a push notification to open a URL in a web browser, you can set the `url` parameter of the push notification. You can control if this URL is opened in the default browser or in an in-app webview using the `kOSSettingsKeyInAppLaunchURL` property.

I hope that answers your question?

This Issues section is for bug reports for the SDK and I don't think you are reporting a bug. If you are, please feel free to respond and ***add more details*** and I would be happy to help.
