### ISSUE TITLE
Cordova Android Platform 7.0.0 not building with custom notification sound, and custom sound not playing on Android 8 Oreo

### ISSUE THREAD

**Issue by LukeHartcher** [OneSignal/OneSignal-Cordova-SDK#303]
**UPDATE 2**
Refer last close comment. Custom Notification Sound will work under Cordova Android 7.0.0 and Android 8 Oreo - but additional configuration is required.

**UPDATE 1**

I can confirm that this plugin custom notification sound works with "cordova android platform 6.4.0" on devices running Android 7.

There are two issues:
1. plugin does not build android with custom notification under Cordova Android Platform 7.0.0 (after placing notification file in platforms/android/res/raw) - refer below for details.
2. plugin does not support custom notifications under Android 8 (default sound will play).

**ORIGINAL ENTRY**

I am trying to add a custom notification sound to my Cordova App (cordova 8.0.0) and I cannot get cordova to compile the Android version (cordova android 7.0.0) once I add a WAV sound to the `platforms/android/res/raw` folder as instructed here  https://documentation.onesignal.com/docs/customize-notification-sounds#section-android-and-derivatives-like-amazon-. 

If I build cordova **without** the "platforms/android/res/raw/notification.wav" it builds fine.
Cordova iOS build and plays the sound notification correctly, just not android.

**Steps to reproduce:** 
_(Windows 10, Cordova 8.0.0, Cordova Android 7.0.0)_

```
cordova create onesignaltest com.mycompany.onesignaltest onesignaltest
cd onesignaltest
cordova platform add android --save
cordova plugin add onesignal-cordova-plugin --save
md platforms\android\res
md platforms\android\res\raw
cp my-notification.wav platforms\android\res\raw\notification.wav
cordova build android
```

**UPDATE:** performing `cordova platform add android@6.4.0 --save` will build. But the sound will only play on devices running Android 7, not Android 8.

-------- CORDOVA BUILD ERROR ----------

```
cp: copyFileSync: could not write to dest file (code=ENOENT):C:\Projects\onesignaltest\platforms\android\res\xml\config.xml

Parsing C:\Projects\onesignaltest\platforms\android\res\xml\config.xml failed
(node:12796) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Projects\onesignaltest\platforms\android\res\xml\config.xml'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.parseElementtreeSync (C:\Projects\onesignaltest\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new ConfigParser (C:\Projects\onesignaltest\platforms\android\cordova\node_modules\cordova-common\src\ConfigParser\ConfigParser.js:30:24)
    at updateConfigFilesFrom (C:\Projects\onesignaltest\platforms\android\cordova\lib\prepare.js:106:18)
    at Api.module.exports.prepare (C:\Projects\onesignaltest\platforms\android\cordova\lib\prepare.js:42:20)
    at Api.prepare (C:\Projects\onesignaltest\platforms\android\cordova\Api.js:192:45)
    at C:\Users\lukeh.CIBIS\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:106:36
    at _fulfilled (C:\Users\lukeh.CIBIS\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\lukeh.CIBIS\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
(node:12796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

Versions:
```
> cordova -v
8.0.0

> cordova platforms
Installed platforms:
  android 7.0.0
```

**Attempted Workaround 1**

If I manually create the `platforms\android\res\xml` folder, then it just moves on to the next failure, `res\values\strings.xml` and so on...just continually trying to manually fix the issues..

```
C:\>cordova build android

(node:20252) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Projects\ChooserBetting\ChooserBetting.CordovaApp\platforms\and
roid\res\values\strings.xml'                                                                                                                                     
    at Object.fs.openSync (fs.js:663:18)                                                                                                                         
    at Object.fs.readFileSync (fs.js:568:33)                                                                                                                     
    at Object.parseElementtreeSync (C:\Projects\ChooserBetting\ChooserBetting.CordovaApp\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpe
rs.js:180:27)                                                                                                                                                    
    at updateProjectAccordingTo (C:\Projects\ChooserBetting\ChooserBetting.CordovaApp\platforms\android\cordova\lib\prepare.js:171:30)                           
    at C:\Projects\ChooserBetting\ChooserBetting.CordovaApp\platforms\android\cordova\lib\prepare.js:47:16                                                       
    at _fulfilled (C:\Projects\ChooserBetting\ChooserBetting.CordovaApp\platforms\android\cordova\node_modules\q\q.js:854:54)                                    
    at self.promiseDispatch.done (C:\Projects\ChooserBetting\ChooserBetting.CordovaApp\platforms\android\cordova\node_modules\q\q.js:883:30)                     
    at Promise.promise.promiseDispatch (C:\Projects\ChooserBetting\ChooserBetting.CordovaApp\platforms\android\cordova\node_modules\q\q.js:816:13)               
    at C:\Projects\ChooserBetting\ChooserBetting.CordovaApp\platforms\android\cordova\node_modules\q\q.js:570:49                                                 
    at runSingle (C:\Projects\ChooserBetting\ChooserBetting.CordovaApp\platforms\android\cordova\node_modules\q\q.js:137:13)                                     
(node:20252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch 
block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)                                                                          
(node:20252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
```

**Attempted Workaround 2**

If I do not manually copy the file but use the `config.xml` to copy the file to the `platforms/android/res/raw` folder I can then see the file in the `.apk` file, but then the notifcation does not fire.

config.xml
```
<platform name="android">
   <resource-file src="res/raw/notification.wav" target="res/raw/notification.wav" />
</platform name="android">
```

payload:

```
let payload = {
      app_id: environment.OpenSignal.AppID,
      included_segments: ["All"],
      headings: { "en": "CHOOSER Selections" },
      contents: { "en": this.GetNotificationMessageText() },
      ios_sound: "notification.wav",
      android_sound: "notification"
    };
```

**Resolution??**

Any tips?

Am I doing something incorrectly?

Or is Cordova 8.0.0 / Cordova Android 7.0.0 broken?

What is the last known working version I can use/test with?

**Comment by jkasten2** [comment]
@LukeHartcher Can you try removing the following from your `config.xml`?
```XML
<platform name="android">
   <resource-file src="res/raw/notification.wav" target="res/raw/notification.wav" />
</platform name="android">
```

Since you are already manually putting `notification.wav` into `platforms/android/res/raw` Cordova might be getting an error since the file is already there.

**Comment by LukeHartcher** [comment]
@jkasten2 my initial try was **without** this entry and it fails to compile! 

I only added the config.xml resource as a test, as manually placing the file in platforms/android/res/raw/notification.wav causes cordova build to fail.

So my main issue is that `cordova build android` fails when manually placing the file in `platforms/android/res/raw/notification.wav`

**Comment by LukeHartcher** [comment]
Steps to reproduce: 
(Windows 10, Cordova 8.0.0, Cordova Android 7.0.0)

```
cordova create onesignaltest com.mycompany.onesignaltest onesignaltest
cd onesignaltest
cordova platform add android --save
cordova plugin add onesignal-cordova-plugin --save
md platforms\android\res
md platforms\android\res\raw
cp my-notification.wav platforms\android\res\raw\notification.wav
cordova build android
```

-------- CORDOVA BUILD ERROR ----------

```
cp: copyFileSync: could not write to dest file (code=ENOENT):C:\Projects\onesignaltest\platforms\android\res\xml\config.xml

Parsing C:\Projects\onesignaltest\platforms\android\res\xml\config.xml failed
(node:12796) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Projects\onesignaltest\platforms\android\res\xml\config.xml'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.parseElementtreeSync (C:\Projects\onesignaltest\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new ConfigParser (C:\Projects\onesignaltest\platforms\android\cordova\node_modules\cordova-common\src\ConfigParser\ConfigParser.js:30:24)
    at updateConfigFilesFrom (C:\Projects\onesignaltest\platforms\android\cordova\lib\prepare.js:106:18)
    at Api.module.exports.prepare (C:\Projects\onesignaltest\platforms\android\cordova\lib\prepare.js:42:20)
    at Api.prepare (C:\Projects\onesignaltest\platforms\android\cordova\Api.js:192:45)
    at C:\Users\lukeh.CIBIS\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:106:36
    at _fulfilled (C:\Users\lukeh.CIBIS\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\lukeh.CIBIS\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
(node:12796) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12796) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by LukeHartcher** [comment]
@jkasten2 did you have any thoughts on this? I will try a previous version of Cordova Android and see how I go.

**Comment by LukeHartcher** [comment]
Using Android Cordova 6.4.0 does compile without the issues listed above (i.e `cordova platform add android@6.4.0`) BUT the notification sounds does not play. :(

File is in the .apk `res/raw/notification.wav` and my payload includes `android_sound: "notification"`.

How is it best to diagnose what the issue could be?

**Comment by LukeHartcher** [comment]
It would appear that Cordova Custom Sound notifications do not work.

**Comment by LukeHartcher** [comment]
UPDATE:

Only relevant thing I could find in `adb logcat` was:

```
02-01 14:26:09.204 30578 30578 W Notification: Use of stream types is deprecated for operations other than volume control
02-01 14:26:09.204 30578 30578 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
```

Note sure if that is relevant?

**Comment by LukeHartcher** [comment]
I can confirm that the "cordova android platform 6.4.0" custom notification works on Android 7.

So there are two issues:

1. plugin does not build with custom notification under Cordova Android Platform 7.0.0 (after placing notification file in platforms/android/res/raw)

2. plugin does not support custom notifications under Android 8 (default sound will play).

Will update main entry.

**Comment by LukeHartcher** [comment]
@jkasten2 I have updated the main entry with my findings. It would be great to see this plugin updated to have custom notifications supported under both Cordova Android 7.0.0 and devices running Android 8. I appreciate you guys are very busy, so I will remain subscribed  for any future updates.

Love the product though - great work!

**Comment by jkasten2** [comment]
@LukeHartcher Thanks for digging in to these issues.

### Issue 1, build error
It sounds like Cordova may have a bug or may no longer allow files to be directly placed into the platforms folder in Cordova version 8.0.0.

Can you try putting the following in your `config.xml`?
```XML
<platform name="android">
   <resource-file src="my-notification.wav" target="res/raw/notification.wav" />
</platform name="android">
```
This should copy `my-notification.wav` into the folder for you which should result in `res/raw/notification.wav` being added to your 
I haven't tested this so let us know if this resolves the build error.

### Issue 2, Android Ore
For your 2nd issue, Android 8.0 custom sounds as well as a number of other notifications setting have been moved into Notification Channels / Categories. These means you must start to add these to all your notifications to customize these setting if your app targets API level 26 or newer. See our docs below on setting one up and how to use it.
https://documentation.onesignal.com/docs/android-notification-categories

**Comment by LukeHartcher** [comment]
@jkasten2 it worked! Simply creating a "Notification Channel" within the OneSignal as documented, and then adding the `android_channel_id` to my rest api call - and the custom sound started working. I can also see the Notification Chanel in the Android Oreo settings.

Great stuff! 👍 

However the doco (https://documentation.onesignal.com/docs/customize-notification-sounds#section-android-and-derivatives-like-amazon-) could be updates to mention this for Android 8/Oreo.

**Comment by LukeHartcher** [comment]
Closing as more of a documentation issue for https://documentation.onesignal.com/docs/customize-notification-sounds#section-android-and-derivatives-like-amazon- where it should cover the 
1. Cordova Android Platform 7.0.0 should use a config.xml resource copy of the custom notification sound, into the `platforms/android/res/raw` folder; and
2. Android 8 Oreo requires Notification Categories created  (https://documentation.onesignal.com/docs/customize-notification-icons) referencing the custom sound (without extension) for custom sounds to work on the device.

**Comment by kamalsamra** [comment]
In android 7 location of wav file is platforms/android/app/src/main/res/raw

**Comment by jkasten2** [comment]
We just updated our docs for this new path today
https://documentation.onesignal.com/docs/customize-notification-icons#section-2-create-project-paths
