### ISSUE TITLE
OneSignal Version 2.1.0 still working for IOS device?

### ISSUE THREAD

**Issue by linhbd** [OneSignal/OneSignal-Cordova-SDK#308]
I have one question that for some reason i am not able to install latest version because of CocoaPods. OneSignal version 2.1.0 still working for IOS device?

**Comment by Nightsd01** [comment]
Please make sure to provide some details....

Can you copy and paste the error you are getting with cocoapods?

Also, are you able to install somewhat newer versions of the SDK (ie. 2.6.2)? As far as I am aware, there are no breaking changes from 2.1.0 to 2.6.2

**Comment by Nightsd01** [comment]
Closing this issue due to (A) no response and (B) complete lack of detail...
