### ISSUE TITLE
How to use onesignal template?

### ISSUE THREAD

**Issue by stojankukrika** [OneSignal/OneSignal-Cordova-SDK#310]
How can I use onesignal template when get a push notification?

**Comment by Nightsd01** [comment]
@stojankukrika I am not entirely sure what you mean. What template are you asking about? Are you asking about the demo project?

Closing because this is not an issue with the SDK but please feel free to ask questions.

**Comment by stojankukrika** [comment]
@Nightsd01 I thinking about Message Template which I see in webpage of One Signal->Messages->Message Template. How do I use it do you maybe know?
