### ISSUE TITLE
IOS Build Error Onesignal: Build Failed

### ISSUE THREAD

**Issue by ar27111994** [OneSignal/OneSignal-Cordova-SDK#311]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Hi, IOS build for our Ionic 3.9.x app fails with the following error:
```
The following build commands failed:
	CompileC /Users/marwan/Library/Developer/Xcode/DerivedData/laundry-locker-clzftnllrsejucbksvpalphooadk/Build/Intermediates/laundry-locker.build/Release-iphonesimulator/laundry-locker.build/Objects-normal/i386/OneSignalPush-702A499D8E6CA9B1.o 
```
`cocoapods` is already installed and `pod repo update` has also been tried, but to no avail.
Please Help!

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ionic info

cli packages: (/usr/local/lib/node_modules)

@ionic/cli-utils : 1.19.1
ionic (Ionic CLI) : 3.19.1

global packages:

cordova (Cordova CLI) : 8.0.0 

local packages:

@ionic/app-scripts : 3.1.8
Cordova Platforms : browser 5.0.3 ios 4.5.4
Ionic Framework : ionic-angular 3.9.2

System:

Node : v8.9.4
npm : 5.6.0 
OS : macOS Sierra
Xcode : Xcode 8.3.3 Build version 8E3004b 

Environment Variables:

ANDROID_HOME : not set

Misc:

backend : pro
```

**Comment by Nightsd01** [comment]
@ar27111994 thanks for the excellent bug report. 

As a troubleshooting step, can you try running the app on a real iOS device? Do you still see the same compiler issue?

**Comment by ar27111994** [comment]
@Nightsd01  You're welcome :) You'll have to wait a bit as my colleague handles ios and mac and is in a different timezone. I'll let him know when he wakes up.

**Comment by ar27111994** [comment]
Hi @Nightsd01 my colleague has tried it and it fails to build for ios device too. Please Help!

**Comment by ar27111994** [comment]
Hi @Nightsd01 @gdeglin @nickpunt @janpio @jkasten2 any updates on this issue? Please help as our app greatly depends on it. Thanks.

**Comment by janpio** [comment]
And you mention random people from the internet here why exactly? That's rude and impolite.

**Comment by ar27111994** [comment]
Oh I'm really sorry, thought github was suggesting because they're all related to this repo. Beg your pardon. Extremely Sorry.

**Comment by Nightsd01** [comment]
Hi @ar27111994

I’ll be investigating this issue today - in the mean time, have you tried compiling your application with Xcode 9?

Also, are you using cocoa pods for the iOS Cordova project?

**Comment by ar27111994** [comment]
@Nightsd01  Thanks, Ok so, just received the news that this worked:

new project
install cocopods
open workspace
drag and drop onesignal.framework , clean and build
build succeded had to be a new project

**Comment by Nightsd01** [comment]
Depending on how you created/got the framework you may run into issues with switching between simulator and real iOS devices. You may also run into issues submitting to the App Store. 

How did you get this framework, did you compile the native iOS sdk by yourself?

**Comment by ar27111994** [comment]
by simply 
ionic cordova add command
