### ISSUE TITLE
build.phonegap error when use onesignal cordova sdk 2.3.0

### ISSUE THREAD

**Issue by Dnainw** [OneSignal/OneSignal-Cordova-SDK#319]
i use intel xdk to create app and use onesignal-cordova-sdk 2.3.0. Last month I was able to build it on build.phonegap.com.but today i can not build it.
that the problem is errror below.

Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: OneSignalPush.java - You can fix this here

Please help me, thank you very much.

**Comment by pravinpsa** [comment]
I also getting the same error while build.  Iam using phonegap cli-6.5.0 

Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: OneSignalPush.java - You can fix this

In Log:
/project/src/com/plugin/gcm/OneSignalPush.java:108: error: cannot find symbol
  private static OSEmailSubscriptionObserver emailSubscriptionObserver;
                 ^
  symbol:   class OSEmailSubscriptionObserver
  location: class OneSignalPush
/project/src/com/plugin/gcm/OneSignalPush.java:215: error: cannot find symbol
        emailSubscriptionObserver = new OSEmailSubscriptionObserver() {
                                        ^
  symbol:   class OSEmailSubscriptionObserver
  location: class OneSignalPush
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**Comment by pravinpsa** [comment]
I have downgraded my onesignal its working fine
	<plugin name="onesignal-cordova-plugin"				source="npm" 		spec="2.1.1"	/>

**Comment by mxkeke** [comment]
+1, same problem

**Comment by Nightsd01** [comment]
This is now fixed in version 2.3.1

**Comment by Dnainw** [comment]
it's work! Thank you very much.
