### ISSUE TITLE
Weird result as setting pages in the NotificationOpened event

### ISSUE THREAD

**Issue by gisngocthach** [OneSignal/OneSignal-Cordova-SDK#322]
I am consuming OneSignal in our iOnic project. It has a simple workflow like: HomeScreen with buttons -> List screens -> Edit screen having boolean-typed ui components like checkbox or radio. Everything is ok if I go through the workflow manually. However, a weird thing occurred in case the list page is opened by:
`this.oneSignal.handleNotificationOpened().subscribe((notificationOpenedResult) => {
                    this.navCtrl.setPages([HomePage, ListAPage]);
        });`
and open the Edit screen from the ListA screen, the checkboxes are completely not reacting to the touching action. I tried with the setPages code above directly inside a observable and it works. 
Thanks for looking at my problem!!!

**Comment by Nightsd01** [comment]
@gisngocthach I am not sure how this issue relates to OneSignal? While the `handleNotificationOpened()` callback is triggering the event, that's all its doing. This sounds more like an Ionic UI issue.

Please feel free to respond with more information if you feel this is a OS issue and I'll be happy to reopen and investigate.
