### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by eficaz** [OneSignal/OneSignal-Cordova-SDK#326]
Hi,
I faced an issue while building a project in xcode 9.1.  My ionic version is 3 and cordova 8.
Below please find the issue.
Showing Recent Messages
CodeSign /Users/apple/Library/Developer/Xcode/DerivedData/myApp-enxsxjualjftndalkfrfqlrvyhzf/Build/Intermediates.noindex/ArchiveIntermediates/myApp/InstallationBuildProductsLocation/Applications/myApp.app
    cd /Users/apple/Desktop/Divya/onesignal/myApp/platforms/ios
    export CODESIGN_ALLOCATE=/Users/apple/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Users/apple/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/apple/Downloads/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Developer: Harishanker Venugopal (68YSV382SJ)"
Provisioning Profile: "iOS Team Provisioning Profile: com.eficazonsignal.com"
                      (23f61ddf-cb36-4c0b-82a2-141f02275ef5)

    /usr/bin/codesign --force --sign 7ED0A00015B541B4496036113B9AC2DD6CAB6AB0 --entitlements /Users/apple/Library/Developer/Xcode/DerivedData/myApp-enxsxjualjftndalkfrfqlrvyhzf/Build/Intermediates.noindex/ArchiveIntermediates/myApp/IntermediateBuildFilesPath/myApp.build/Release-iphoneos/myApp.build/myApp.app.xcent --timestamp=none /Users/apple/Library/Developer/Xcode/DerivedData/myApp-enxsxjualjftndalkfrfqlrvyhzf/Build/Intermediates.noindex/ArchiveIntermediates/myApp/InstallationBuildProductsLocation/Applications/myApp.app

/Users/apple/Library/Developer/Xcode/DerivedData/myApp-enxsxjualjftndalkfrfqlrvyhzf/Build/Intermediates.noindex/ArchiveIntermediates/myApp/InstallationBuildProductsLocation/Applications/myApp.app: unknown error -1=ffffffffffffffff
Command /usr/bin/codesign failed with exit code 1.

Thank you

**Comment by zargox** [comment]
Yep same here. It tooks me really a lot of time (days) by investigating this. On my end, when we try to compile it a couple of times, then it will work. Hope that this can be solved asap

**Comment by Nightsd01** [comment]
@eficaz This looks like a general code signing issue. I’m not sure why you’re posting it in relation to the OneSignal SDK?

**Comment by Nightsd01** [comment]
I would suggest researching this crash because it doesn't have much to do with the OneSignal SDK.

I might suggest using this link for troubleshooting ideas:
https://stackoverflow.com/questions/2017756/command-usr-bin-codesign-failed-with-exit-code-1
