### ISSUE TITLE
Missing Push Capability

### ISSUE THREAD

**Issue by kierandesmond** [OneSignal/OneSignal-Cordova-SDK#327]
Hi,

I've followed the Ionic SDK instructions and am using the Ionic Native Plugin in coordination with OneSignal-Cordova-SDK. On All users we are getting "(Missing Push Capability)" - Even though I've added the push capability already to the project.

Can't seem to register anyone.

Help!

**Comment by Nightsd01** [comment]
@kierandesmond This would be an issue with your bundle ID, it is not an issue with the SDK.

Please feel free to go to the OneSignal dashboard (https://www.onesignal.com) and click on the Support button, usually at the bottom right.
