### ISSUE TITLE
How do i use my restAPI key in pushNotification?

### ISSUE THREAD

**Issue by XBLDev** [OneSignal/OneSignal-Cordova-SDK#328]
I want to use pushNotification with tags, and according to the official website: https://documentation.onesignal.com/reference#create-notification, I need to include my restAPI key if I want to send messages with tags.

How do I actually do this? I've been searching for a while now, none of the answers I found online uses restAPI key.

Thanks in advance for all the answers!

**Comment by Nightsd01** [comment]
@XBLDev under no circumstances should you _ever_ use your OneSignal REST API key in your application. Instead, it should only ever be used in your backend server (if you have one).

I am not sure what you mean when you talk about tags. Do you mean you want to filter using tags?

You should _definitely_ not be implementing this functionality on your app itself, it would be highly insecure.

**Comment by XBLDev** [comment]
hi @Nightsd01 thanks for the answer! 

Yes by tags I meant filters.

By backend server do you mean a dedicated server just for API calls? Can I let my frontend call a backend function which uses the REST API key?
