### ISSUE TITLE
Ionic IOS not working for me...

### ISSUE THREAD

**Issue by kotran88** [OneSignal/OneSignal-Cordova-SDK#330]
Hello:)

I get alert 1 but not 3....and xcode don't say any of error...
I think code is perfect because I get it from ionic document. 

alert("1");

this.oneSignal.startInit('3ccd720d-dd44-41dd-9a72-3224fe45d756');
      
      this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.InAppAlert);
      
      this.oneSignal.handleNotificationReceived().subscribe(() => {
       // do something when notification is received
      });
      
      this.oneSignal.handleNotificationOpened().subscribe(() => {
        // do something when a notification is opened
      });
      
      this.oneSignal.endInit();
              
      alert("3")

**Comment by Nightsd01** [comment]
@kotran88 Can you post the entire file? I am not sure what you mean by "ionic document"?

**Comment by Nightsd01** [comment]
I am closing this issue due to lack of details....please reply if you're still seeing this issue, ***provide more information*** (such as what version of the SDK you are using, what platforms this issue occurs on, etc...), and I'll be happy to reopen and investigate the problem.

**Comment by Nightsd01** [comment]
@kotran88  I am closing this issue due to lack of details....please reply if you're still seeing this issue, ***provide more information*** (such as what version of the SDK you are using, what platforms this issue occurs on, etc...), and I'll be happy to reopen and investigate the problem.
