### ISSUE TITLE
Android Badge does not appears - Ionic

### ISSUE THREAD

**Issue by ecomunicarte** [OneSignal/OneSignal-Cordova-SDK#332]
Hello,
your documentation says: "Note: Android badges are automatically handled by OneSignal".
However, I'm using Ionic, and when my devices receives a push, the badge does never appear.
I have followed all setup indications, and I don't find any related issue or indications.
The app does not throw any error, and in general push works like a charm.
Have I to do anything more like something related to permissions or this is a plugin issue?

Thanks in advance

My environment:
```
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.8
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: macOS High Sierra
```

All Plugins: 
```
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.2.1 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.3.1 "OneSignal Push Notifications"
```

Additionally for more details, I have tested  it In two Genymotion simulators, (Android 5 and 7) and two Samsung Galaxy real devices (Android 5 and 7 too)

**Comment by Nightsd01** [comment]
@ecomunicarte You are saying badges don't work only on one particular device, or is it not working on any device/simulator?

On this same device, do you see badges on _other_ apps? Some launchers don't support badges at all.

**Comment by ecomunicarte** [comment]
@Nightsd01  It does not work with this app with this plugin on any device I have could tested. The same devices and simulators show badges of other developments using [cordova-plugin-badge](https://github.com/katzer/cordova-plugin-badge).
In addition the real devices shows badges of normal apps like whatsapp, telegram, etc.

I have updated to the latest version and the same thing keeps happening. Do you recommend trying to use the plugin I have indicated? Or can it be problematic to use both?

**Comment by Nightsd01** [comment]
@ecomunicarte Can you reproduce this issue in our demo project?

**Comment by devartstudio** [comment]
Hi, I have same issue, on real device:
Huawei p8 android 5.0.1 badge is ok.
LG android 5.5.1 badge doesn't show
Nexus android 7 badge doesn't show

my ionic info:
`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.2.0
    npm        : 6.1.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro`

any suggests?
Many thanks!

**Comment by jkasten2** [comment]
@ecomunicarte LG devices should be supported, are you using the default Android Launcher? Or did you install a 3rd party one?

Badges were not an official feature until Android Oreo 8.0 and they are called notification dots. The launcher still has to support it though even on Android 8. Example the default Google Launcher does not however the Pixel launcher does.

The only way to see badges on Nexus devices to use a 3rd party launcher such as ADW, APEX, or NOVA.
https://documentation.onesignal.com/docs/appearance#section-badges
