### ISSUE TITLE
Alert Notification on App Resume

### ISSUE THREAD

**Issue by jakevis** [OneSignal/OneSignal-Cordova-SDK#340]
Hi there,

So i do suspect this is user error... but I can not get handleNotificationOpened to function.  What I want to achive is, when the user clicks on the notification in the tray/draw, the app is opened, and an alert notification is displayed. I am testing on Android (but will go to iOS as well soon), and using Ionic 3.

This code works - running within app.component.ts, in platform.ready  (although will only display the alert notification, if the app is already open - if the OS has closed it, or a user force closed it, the push clicked on, opening the app results in no alert):

```
		window["plugins"].OneSignal
        	.startInit('xxxx','xxxx')
	        .iOSSettings(iosSettings) // only needed if added Optional OneSignal code for iOS above
	        .inFocusDisplaying(window["plugins"].OneSignal.OSInFocusDisplayOption.Notification)
			.handleNotificationReceived(function(jsonData) {
				let popup = AlertController.create();
				popup.setTitle(jsonData.payload.title);
				popup.setSubTitle(jsonData.payload.body);
				popup.addButton("OK");
				popup.present();
				console.log('Did I receive a notification: ' + JSON.stringify(jsonData));
			  })
			.endInit();

```

if I change to handleNotificationOpened i get nothing.

**Comment by jkasten2** [comment]
@jakevis `handleNotificationOpened` is what you will need to handle when a notification is tapped on. `handleNotificationReceived` will only be called when a notification is received when the app is in focus.

Do you get anything in the deivce's logcat with `handleNotificationOpened`? In either the closed or in focus state when tapping on a notification?

**Comment by jakevis** [comment]
thanks for the response @jkasten2 - it was a user mistake... i rewrote the method and I was looking in the wrong spot for json data.

If anyone finds this in the future... and copies and pastes code ;) - .h`andleNotificationReceived(function(jsonData)` looks for title in `jsonData.payload.title`
If you use the example `var notificationOpenedCallback = function(jsonData)` - you need to look in `jsonData.notification.payload.title`
