### ISSUE TITLE
cancelNotification method not implemented

### ISSUE THREAD

**Issue by oscaringit** [OneSignal/OneSignal-Cordova-SDK#344]
Any plan to implement/map this method?

In a notification service there are many situations, in client side, where an specific notification for that client needs to be canceled on the fly. I think this method is a must. 

Thanks

**Comment by jkasten2** [comment]
@oscaringit Thanks for the suggestion, we will look into it

**Comment by serhiiporaiko** [comment]
@jkasten2

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
