### ISSUE TITLE
Problem with Cordova. "Failed to connect to GitHub to update the CocoaPods/Specs"

### ISSUE THREAD

**Issue by MasTeh** [OneSignal/OneSignal-Cordova-SDK#345]
Hello!

I can't corrent install onesignal cordova plugin on iOS.

**sudo gem install cocoapods**
Successfully installed cocoapods-1.4.0
Parsing documentation for cocoapods-1.4.0
1 gem installed

**pod repo update**
Updating spec repo `master`
[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down

There was no such problem before.

**Comment by jkasten2** [comment]
@MasTeh This is an issues with Cocoapods, not OneSignal. I recommend trying the below solutions to fix this issue:
https://stackoverflow.com/questions/38993527/cocoapods-failed-to-connect-to-github-to-update-the-cocoapods-specs-specs-repo
