### ISSUE TITLE
How to get Player ID ?

### ISSUE THREAD

**Issue by AnandKumar2610** [OneSignal/OneSignal-Cordova-SDK#347]
I'm using
`let me = this;
window["plugins"].OneSignal
        .startInit("XXXXXXXXX", "XXXXXXX")
        .handleNotificationOpened(notificationOpenedCallback)
        .addSubscriptionObserver(function (state) {
        if (!state.from.subscribed && state.to.subscribed) {
          me.showAlertDialog('userId',state.to.userId);
        }
          me.showAlertDialog('state',JSON.stringify(state));
      }).endInit();`

addSubscriptionObserver function never return any data.
Thank in advance
-Anand

**Comment by Nightsd01** [comment]
You should not chain the `addSubscriptionObserver()` function in your init call.

You should remove your call to `addSubscriptionObserver()` from the init chain and call it separately like this:

```
let me = this; window["plugins"].OneSignal .startInit("XXXXXXXXX", "XXXXXXX") .handleNotificationOpened(notificationOpenedCallback).endInit();

window["plugins"].OneSignal.addSubscriptionObserver(function (state) { if (!state.from.subscribed && state.to.subscribed) { me.showAlertDialog('userId',state.to.userId); } me.showAlertDialog('state',JSON.stringify(state)); })
```

**Comment by AnandKumar2610** [comment]
Hi @Nightsd01 Thanks for your reply. 
Below code is working fine for me.,
`this.oneSignal.endInit();
this.oneSignal.getIds().then((id) => {
       // id.userId
});`

**Comment by techClick** [comment]
Please what language is this and how can I use the above code to get the user Id. Im a newbie with Onesignal please

**Comment by lakshmana** [comment]
> Hi @Nightsd01 Thanks for your reply.
> Below code is working fine for me.,
> `this.oneSignal.endInit(); this.oneSignal.getIds().then((id) => { // id.userId });`

But using getIds to get the playerId on first 'ever' launch take more than 30sec. Do you have any idea to get the playerId asap. 
Thx

**Comment by jleira** [comment]
> > Hi @Nightsd01 Thanks for your reply.
> > Below code is working fine for me.,
> > `this.oneSignal.endInit(); this.oneSignal.getIds().then((id) => { // id.userId });`
> 
> But using getIds to get the playerId on first 'ever' launch take more than 30sec. Do you have any idea to get the playerId asap.
> Thx


friend,

this is the solution, I hope that help you

          window["plugins"].OneSignal.getIds(function (state) {
            console.log("estate ids",state);
          },err=>{
            console.log("err estate ids",err);
          });

**Comment by jleira** [comment]
> > Hi @Nightsd01 Thanks for your reply.
> > Below code is working fine for me.,
> > `this.oneSignal.endInit(); this.oneSignal.getIds().then((id) => { // id.userId });`
> 
> But using getIds to get the playerId on first 'ever' launch take more than 30sec. Do you have any idea to get the playerId asap.
> Thx
this is the solution, I hope that help you

          window["plugins"].OneSignal.getIds(function (state) {
            console.log("estate ids",state);
          },err=>{
            console.log("err estate ids",err);
          });
