### ISSUE TITLE
You cannot run CocoaPods as root.

### ISSUE THREAD

**Issue by greceanii** [OneSignal/OneSignal-Cordova-SDK#351]
sudo cordova plugin add onesignal-cordova-plugin

/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. 

Please help to resolve this problem

**Comment by Nightsd01** [comment]
Why are you using `sudo`? As the error indicates, cocoapods cannot be run using `sudo`, and when you install the OneSignal Cordova plugin, it launches cocoapods to install the iOS OneSignal dependency.

It should work if you try it without using sudo.

**Comment by Panako77** [comment]
Nightsd01, te mereces un premio Novel por saber leer. Si lo hace con sudo es porque si no da error de permisoso, lumbrera.

**Comment by jcmendes9898** [comment]
same issue. did u find a solution?

**Comment by skiperlay** [comment]
> Nightsd01, te mereces un premio Novel por saber leer. Si lo hace con sudo es porque si no da error de permisos, lumbrera.

Pues el lumbrera tenía razón XD. Si lo ejecutas con sudo no funciona. Si lo ejecutas sin Sudo funciona.
