### ISSUE TITLE
OSPermissionSubscriptionState object uses status vs state between iOS and android

### ISSUE THREAD

**Issue by jurgen-reconcept** [OneSignal/OneSignal-Cordova-SDK#352]
When I request getPermissionSubscriptionState() on iOS I can access status.permissionStatus.status, but when I do the same thing on Android, the latter is called 'state', so status.permissionStatus.state. This should probably be unified.

So:

```
window.plugins.OneSignal.getPermissionSubscriptionState(function(status) {
  status.permissionStatus.status; // available on iOS
  status.permissionStatus.state; // available on Android
});
```

**Comment by Nightsd01** [comment]
This is not a bug. `status` and `state` mean different things. Essentially iOS has more possible values of `status` than Android does.

When using these parameters, I would suggest checking the platform (ios vs. android) and implement logic accordingly

**Comment by jurgen-reconcept** [comment]
I see. Then I guess the ionic implementation is kind of incomplete because the TypeScript type only supports status. But using permissionStatus['state'] I can still make it work :) 

I also figured out that my Android test device actually also sets state to 2 if the user denied access in the settings panel (so it's reverse of iOS where 2 means authorized and 1 means denied).

Thanks for your help anyway!
