### ISSUE TITLE
Problem managing sound and vibration 

### ISSUE THREAD

**Issue by marcoroche** [OneSignal/OneSignal-Cordova-SDK#353]
The users of my App are frustrated to have sound and vibration. The App generates lots of notifications and most people want to receive them straight away but with no sound and vibration. 

I modified the code to make the silent mode by default when installing the App and added two buttons to manage sound and vibration. 

It seems working fine on my Huawei P8 lite but not on Samsung products. 

I try to debut with a Galaxy Tab 3. Yesterday I updated the App with the production App and the sound was still working. Now I try to debut and I don't have any sound. 

Init sequence:
```
            window.plugins.OneSignal
              .startInit("XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX")
              .handleNotificationOpened(notificationOpenedCallback)
              .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
              .endInit();          
     
            window.plugins.OneSignal.enableSound(false);  
            window.plugins.OneSignal.enableVibrate(false);   

            window.plugins.OneSignal.getPermissionSubscriptionState( status => { registerDevice( status.subscriptionStatus.userId ) } );
```

In the button activate I just have : 

`    window.plugins.OneSignal.enableSound(true);`

What can be wrong?

Release: 2.3.3

**Comment by jkasten2** [comment]
@marcoroche It looks like you are calling `enableSound(false)` and `enableVibrate(false)` each time your app is started. This will disable these every time your app is started which will override `enableSound(true)` that you noted you have setup when the users presses a button.

Is that the current issue you have now? That sounds isn't being enabled when they press your in app button?

**Comment by marcoroche** [comment]
No, when I start up the App  I indicate the last state of the button. It works on some devices but not on others. 
To test in my process I keep the App running I don't put it in the background mode, I toggle the button and send some notification. 

Question: Is there a possibility to definitely switch off the sound and vibration with the manifest?

**Comment by jkasten2** [comment]
@marcoroche So the toggle in your testing doesn't work on some devices? It is always playing a sound?

Also do note that these setting won't work on Android 8+ devices. These settings must now be defaulted with a [notification category / channel](https://documentation.onesignal.com/docs/android-notification-categories). The user can change these setting from their notifications settings for your app per channel. If your not testing on Android 8 can you let us know the exact Android version and model you are setting an issue on?

There isn't a setting for OneSignal for these options in the `AndroidManifest.xml`

**Comment by marcoroche** [comment]
OK, I think I found a solution with the Category / Channel. I just did a simple test to cut off the sound and it seems working so I will try to deploy tomorrow to make a real test. 
I removed the setting from my code.
BTW, why the package is not updated with the last update of the Android-SDK?

**Comment by jkasten2** [comment]
@marcoroche Sorry I missed your reply before. Good to hear the channel / category setup fixed your issue.

There is some delay from when we make a native release to when this Cordova SDK is updated. We try to prioritize this based on the importance of the native update and it might take some additional time if there are new wrapper methods to add. Currently this Cordova SDK is using the latest native SDKs.

**Comment by jkasten2** [comment]
@DSofter OneSignal has a Notification Category / Channel editor the dashboard you can use instead of creating custom Java code to do so.
https://documentation.onesignal.com/docs/android-notification-categories

If you do need to control Android Channel's locally the only reason why I could see it not vibrating is if you also set a [Notification Group](https://documentation.onesignal.com/docs/android-customizations#section-notification-grouping). This is because a 2nd summary notification will be created which would override this.
