### ISSUE TITLE
When should .handleNotificationOpened and .handleNotificationReceived be called?

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#355]
Hi,

We're slowly converting our app to use OneSignal. 

We're noticed that both the the declared JavaScript function handlers for .handleNotificationOpened () and  .handleNotificationReceived() are called when a notification with content-available=1 is sent.

We thought that the function declared for .handleNotificationOpened() should only be opened when the user clicks on a notification in the shade. According to our logs we can see both functions being called.

We can work out from the data passed into the function what is happening, and therefore ignore the function call when its inappropriate, but we thought that the function shouldn't even be called.

Is this correct behaviour?

We can provide logs if needed of our functional being called.

Thanks

Rob

**Comment by Nightsd01** [comment]
The `content-available` flag triggers background push notification execution, meaning it will open your app in the background. Most developers _do_ want this behavior - this is how it was intended to work. As you said, you can just check to see if the app is in focus in order to change how your app responds to these callbacks if you want different behavior between background vs. in focus.

**Comment by rwillett** [comment]
Brad,

Thanks for the reply, but thats not the question I asked. 

Our question is why do BOTH functions get called when content-available=1 is set on IOS. Our reading of the docs is that handleNotificationOpened() should only be called when a user clicks on the notification in the drawer, it appears to be called regardless of whether or not the user has clicked. 

We would expect handleNotificationReceived() to be called, but if both functions are called, then that doesn't make sense to us. 

Whilst we know we can then manage the notification by looking at the content and working it out, it seems to us that logically that this is the wrong behaviour. We would expect that handleNotificationOpened() should only be called when the user clicks on it.

Thanks

Rob

**Comment by dfibuch** [comment]
Also came across this issue today, don't know why this has been closed as it clearly hasn't been addressed properly. The OneSignal documentation states

```
handleNotificationOpened:

Sets a notification opened handler. The instance will be called when a notification is tapped on from the notification shade (ANDROID) or notification center (iOS), or when closing an Alert notification shown in the app (if InAppAlert is enabled in inFocusDisplaying, below).
```

It doesn't say anything about "it will also be called in other instances where you don't expect it to be called". I am sending through a notification with `content_available=1` and no `contents` so no actual notification is shown but my `handleNotificationOpened` block is still run, as well as `handleNotificationReceived`.

Should I open a new ticket for this? Either that or update your documentation to make it clear.
