### ISSUE TITLE
Duplicate notification with latest cordova sdk

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [OneSignal/OneSignal-Cordova-SDK#357]
We are getting duplicate notification, 

We use latest Onesignal cordova sdk and not using any other push plugin

we use below plugins
```
C:\Users\user\doctorClient>cordova plugins
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-document-viewer 0.9.7 "SitewaertsDocumentViewer"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-freshchat 1.2.0 "Freshchat plugin for Phonegap"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-nativeclicksound 0.0.3 "Native Click Sound"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.3.0 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.2.2 "OneSignal Push Notifications"
```

Please let me know if you need any other details.

**Comment by Nightsd01** [comment]
@Jeyakumarrathnaselvi Can you provide some more information?

For example
- Do the duplicate notifications occur in android, iOS, both?
- Do they occur for all notifications or only under some circumstances?

**Comment by Jeyakumarrathnaselvi** [comment]
We are yet to test in iOS. It is happening only for few notifications.

We are using notification grouping and heading

---- On Thu, 19 Apr 2018 07:15:39 +0530 notifications@github.com wrote ----

@Jeyakumarrathnaselvi Can you provide some more information?

For example

Do the duplicate notifications occur in android, iOS, both?
Do they occur for all notifications or only under some circumstances?

**Comment by jkasten2** [comment]
@Jeyakumarrathnaselvi Can you provide the following details on when this issue happens so we can look into this in more detail?
1. Android versions this happens on
2. Device manufactures this happens on
3. A screenshot of the issue
4. Notification ids, you can send these to OneSignal support linking to this ticket

**Comment by Jeyakumarrathnaselvi** [comment]
[](url)

**Comment by Nightsd01** [comment]
It turns out this was a compatibility issue with Freshchat. Please feel free to respond if you have any further problems/questions about the SDK

**Comment by Jeyakumarrathnaselvi** [comment]
Freshchat team suggest us to use onesignal sdk or freshchat notification sdk. 

As per them we can handle freshchat notification using below steps in onessignal sdk as mentioned below

UpdateNotification on registration Token:
window.Freshchat.updatePushNotificationToken(data.registrationId);

HandlePushNotification on receive notification :

window.Freshchat.isFreshchatPushNotification(data, function(success, isFreshchatNotif) {
if( success && isFreshchatNotif ) {
window.Freshchat.handlePushNotification(data.additionalData);
}
});

Need your support where to add this part of onesignal sdk.
