### ISSUE TITLE
"Excessive wakeups" and "Excessive Wi-Fi scans (background)" in Android..

### ISSUE THREAD

**Issue by spinninghamster** [OneSignal/OneSignal-Cordova-SDK#361]
Our Google Play Console is showing bad behaviour due to "Excessive wakeups" and "Excessive Wi-Fi scans (background)".

I believe these problems were fixed in the Android SDK already:
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.8.4

Can you please fix them in the Cordova SDK as soon as possible, too? Any idea when this will be out?

**Comment by Nightsd01** [comment]
We will be releasing new updates soon with both Android and iOS native SDK updates. Currently the new iOS update is ready, but we are just finishing up adding GDPR support in the Android native SDK. It should be done either today or in the next few days.

**Comment by Nightsd01** [comment]
We've release a new update ([2.4.0](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.4.0)) that resolves this issue, it includes the new Android update to fix it.
