### ISSUE TITLE
New Permissions

### ISSUE THREAD

**Issue by LKDevelopment** [OneSignal/OneSignal-Cordova-SDK#363]
**Description:**
I've updated all parts of my app. Suddenly after i want to submit it to apple i get the following response from them:

```
Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationWhenInUseUsageDescription key with a string value explaining to the user how the app uses this data.
```

Since i doesn't use any location service or something other i began to search all the plugins i've updated and i found your changelog for v 2.3.3: https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.3.3.

Why do you add a breaking change like this in a minor update and doesn't write anything about it? Why do you need this?

**Environment**
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0 browser 5.0.3 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v9.6.1
    npm               : 5.7.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145 

Environment Variables:

    ANDROID_HOME : /Users/lukaskammerling/Library/Android/sdk

Misc:

    backend : pro
```

**Steps to Reproduce Issue:**
Just update to the latest version

**Comment by peterpaulis** [comment]
I have the same issue on the regular iOS SDK... looks apple changed review

**Comment by LKDevelopment** [comment]
nope, its code based. They introduced because of the GDPR some changes... Only way to solve this is to add the info to the plist...

**Comment by gdeglin** [comment]
Thanks for reporting this. Our team is investigating.

**Comment by Nightsd01** [comment]
@LKDevelopment @peterpaulis This change was released over a month ago. We didn't actually change how the SDK handles location services, we simply added support for a new Plist key (`NSLocationAlwaysAndWhenInUsageDescription`).

The fact that we've started seeing reports only in the last 24 hours indicates to me that Apple introduced some new bug in their review process. 

After all, the SDK is _not_ going to use location services _unless_ your app contains these info.plist keys. 

Also, it appears that this is more than just apps using OneSignal that are  experiencing this problem:

https://forums.developer.apple.com/thread/101367

https://forums.developer.apple.com/thread/101453

**Comment by Nightsd01** [comment]
It looks like Apple resolved this issue on their end

**Comment by eaguad1337** [comment]
Same issue with Xcode Version 10.2 (10E125)

**Comment by MatrixMatt249** [comment]
Update Cordova to 5.0.0 to resolve issue on 10.2

**Comment by JetForMe** [comment]
I've been uploading builds with my recently-integrated app, and just tonight started getting this warning.

**Comment by fischuJules** [comment]
2021, April 26 - this is still happening. it's really weird to have this in your plist, though you don't need location for the app.

**Comment by kmrinmoy07** [comment]
I am still facing this issue December, 2021. Will app store reject the app & we need to fix it or we can ignore the warning message

**Comment by khushalkhan83** [comment]
it still there in 2023, not fixed yet
