### ISSUE TITLE
compilation with cocoon impossible after Version 2.1.0... and not working with 2.1.0

### ISSUE THREAD

**Issue by vromrom** [OneSignal/OneSignal-Cordova-SDK#364]
**Description:**

i use cocoon.io to compile my projects. For Android the OneSignal Cordova SDK (2.3.3) compiles and works perfectly , but with ios no way...  i have to downgrade to v2.1.0 in order to compile, just before you had cocoa dependencies (don't know exactly what it means...) , if i use v>2.1.0 i got an error "Uh oh!
"/workspace/platforms/ios/PUSHdev8/Plugins/onesignal-cordova-plugin/OneSignalPush.m" already exists!" 

**Environment**
Cordova ios v4.5.4
plugins :
		plugin name="onesignal-cordova-plugin" spec="*" version="2.1.0"/>
		plugin name="cordova-plugin-android-permissions" spec="*"/>
		plugin name="cordova-plugin-device" spec="*"/>
		plugin name="cordova-plugin-dialogs" spec="*"/>
		plugin name="cordova-plugin-nativestorage"/>
		plugin name="cordova-plugin-network-information" version="1.3.4"/>
		plugin name="cordova-plugin-whitelist" version="1.3.3"/>
		plugin name="com.ludei.webviewplus.android" spec="*"/>

**Steps to Reproduce Issue:**

1. with onesignal cordova sdk v2.1.0 (the latest i can compile) the functions getPermissionSubscriptionState and addSubscriptionObserver  seem to work, it returns an userId, hasprompted:true etc but the "subscribed" variable stays at FALSE (i agree to receive notifications)... so i never receive notifications (cause i'm not correctly subscribed)
2. in onesignal website, when i list the users i can see my "iphone user" but not subscribed, with error : Other Apns 3000 Error

i'm pretty sure i did all provision files, app id, and p12 certificates correctly but 2 days after i still can't get it working...

so my question is :  is there a way to make it works with v2.1.0 (or no way) ?  is there a way to suceed compile the v2.3.3 without getting the 'onesignalpush.m already exists' error...

thanks by advance !

rom

**Comment by Nightsd01** [comment]
Unfortunately, Cocoon does not support cocoapods. The OneSignal Cordova SDK uses Cocoapods in order to download the iOS native SDK.

This isn't an issue with the OneSignal SDK - it's an issue with Cocoon's build system.
