### ISSUE TITLE
Using ActionButton in Ionic - check which action button is clicked

### ISSUE THREAD

**Issue by JEricaM** [OneSignal/OneSignal-Cordova-SDK#369]
**Description:**

Sorry if I hopen again the post with the same question, but my previous question was closed and I continue to have problems with this topic so I need more help about this.

First of all thank with the answer gave me here #368 but the problem is that I don't understand how I can interact with action buttons. 

I'm able to retrieve the payload from the notification and extract the body or the title of the notification but I don't know how I can retrieve informations about actionbuttons like the actionID of the action button clicked by the user.
Is this information inside the payload?

I checked this link but I don't see anything that could help me, no example, no code... 
https://documentation.onesignal.com/docs/customize-action-buttons

This is my code right now

```
import { OneSignal, OSNotificationPayload} from '@ionic-native/onesignal';
...

  constructor(
     ....
    private oneSignal: OneSignal
  ){}

......
  if (isCordovaAvailable()){
        this.oneSignal.startInit(oneSignalAppId, sender_id);
        this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.Notification);
        this.oneSignal.handleNotificationReceived().subscribe(data => this.onPushReceived(data.payload));
        this.oneSignal.handleNotificationOpened().subscribe(data => this.onPushOpened(data.notification.payload));
        this.oneSignal.endInit(); 
      }

 private onPushOpened(payload: OSNotificationPayload) {
    console.log('payload: ' + JSON.stringify(payload));  
  **//here I would do something based from the action button clicked by the user**
  }
```

Maybe it's a silly question but I really don't understand how to interact with action buttons.
Thank you in advance

**Comment by Alacon** [comment]
Hi

You are listening to the correct event but with invalid data...
Instead of 
this.oneSignal.handleNotificationOpened().subscribe(data => this.onPushOpened(**data.notification.payload**));

You should use 
this.oneSignal.handleNotificationOpened().subscribe(data => this.onPushOpened(**data**));

`
this.oneSignal.handleNotificationOpened().subscribe((result: OSNotificationOpenedResult) => {
      console.log(result.action.type);
      console.log(result.notification.payload.additionalData.type);
      if (result.action.type === OSActionType.ActionTake) {
      }
    });
`

**Comment by JEricaM** [comment]
Thank you so much

If I understood correctly, the function
```
this.oneSignal.handleNotificationOpened().subscribe((result: OSNotificationOpenedResult) => {
  console.log(result.action.type);
  console.log(result.notification.payload.additionalData.type);
  if (result.action.type === OSActionType.ActionTake) {
    console.log('Action clicked');
  }
});

```
Should go instead of my private onPushOpened(payload: OSNotificationPayload) ?
```
 private onPushOpened(payload: OSNotificationPayload) {
    console.log('payload: ' + JSON.stringify(payload));  
  **//here I would do something based from the action button clicked by the user**
  }
```

**Comment by Alacon** [comment]
You can change your function to receive parameter of type OSNotificationOpenedResult
And instead of onPushOpened(data.notification.payload)
You add data as parameter.

OSNotificationPayload does not contain action data so you will need the root object which is of type 
OSNotificationOpenedResult
