### ISSUE TITLE
Cordova build failing with latest cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by shajeeck** [OneSignal/OneSignal-Cordova-SDK#370]
**Description:**

Cordova build is failing when OneSignal plugin installed along with cordova-plugin-googlemaps latest version. I was able to make OneSignal@2.3.3 and cordova-plugin-googlemaps@2.2.9 working together. It was using Google Play service 12.0.0. Now latest cordova-plugin-googlemaps use Google Play version 15.0.1 and build started failing again with OneSignal@2.4.0

**Environment**

**Cordova Plugins**
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.1 "Cordova sqlite storage plugin"
onesignal-cordova-plugin 2.4.0 "OneSignal Push Notifications"

**Cordova Android@7.1.0**

**Steps to Reproduce Issue:**

1. create a blank ionic application
2. add cordova-plugin-googlemaps@latest
3. add onesignal-cordova-plugin@latest
4. cordova build the project

**Anything else:**

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.

Had these issues earlier for Google Play service version incompatibility for OneSignal Plugin

**Comment by pedrohills** [comment]
I'm facing the same problem.

**Comment by shajeeck** [comment]
I was able to make onesignal-cordova-plugin@2.4.0 and cordova-plugin-googlemaps@2.3.3 by doing following step as a temporary solution

1) Update Google Play services and Android Support Repository In Android Studio **if needed**!

2) ionic cordova platform remove android
3) change lines in file plugins/onesignal-cordova-plugin/build-extras-onesignal.gradle to

> // ### Google Play Services library
>     'com.google.android.gms': [
>         'version': '15.0.0+'
>     ],
>     // ### Google Firebase library
>     // Although not used by OneSignal Firebase has some dependencies on gms
>     // If present, ensuring they are aligned
>     'com.google.firebase': [
>         'version': '15.0.0+'
>     ],

make sure both are version '15.0.0+'

4) ionic cordova platform add android@latest
5) build

This is just a workaround i found working for me as a temporary solution!
Cloning OneSignal and changing same file is better.
Or wait for OneSignal to update their repository with latest Google Play service!

**Comment by ecomunicarte** [comment]
I have been experienced similar issue, and found another solution, but I think any of them are really valid solutions. You can find it in:  [this issue on maps repository](https://github.com/ionic-team/ionic-native-google-maps/issues/31)

**Comment by jkasten2** [comment]
@shajeeck @pedrohills @ecomunicarte This is now fixed the [release 2.4.1](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.4.1).
