### ISSUE TITLE
Problem installing ipa on iPhone after adding onesignal plugin

### ISSUE THREAD

**Issue by yashodeep9** [OneSignal/OneSignal-Cordova-SDK#371]
**Description:**

Hi,
I am integrating onesignal plugin in iOS with xcode version 9.2
I followed all the steps mentioned in official document : https://documentation.onesignal.com/docs/ionic-sdk-setup  **except** step  "iOS - Add App Groups (Optional but Recommended) (CLI ONLY)" 

I could see two targets on clicking the project:
i: The one with project name
ii: The newly created OneSignalNotificationServiceExtension.
For both target, display name and Bundle identifier is same.

There is no problem while building the project. I am exporting enterprise ipa and distributing ipa through google drive link for internal testing.
The problem occurs while installing the ipa on iPhone
I am getting the following popup error on iPhone : "Unable to Download App. XXX could not be downloaded at this time."

If i distribute the ipa with original code (i.e without onesignal plugin and code and without all the steps mentioned in document) everything works fine.

Please help, thank you.

**Environment**

1. What version of the Cordova SDK are you using?   **version 2.4.0**
2. Provide a list of your project dependencies (using `cordova plugin list` or copy-pasting your config.xml)

cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.1 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.0 "OneSignal Push Notifications"
 

**Steps to Reproduce Issue:**

1. Add the onesignal-cordova-plugin to your project
2. Initialize the plugin with your app ID
3. Follow all the steps mentioned in https://documentation.onesignal.com/docs/ionic-sdk-setup for iOS.
4. Build the ipa
5. Install it in iPhone

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
@yashodeep9 I am sorry no one ever got back to you on this issue - are you still having this problem?

**Comment by jkasten2** [comment]
@yashodeep9 Closing do to inactivity. I recommend checking the device's system log when you install the IPA on the device to see if there are any errors shown there. Thanks.
