### ISSUE TITLE
Webview crash happening in Android N

### ISSUE THREAD

**Issue by vhmolinar** [OneSignal/OneSignal-Cordova-SDK#373]
**Description:**
I'm looking for a webview crash cause in my app which eventually started to happen in Android N.
So I found the following logcat error regarding onesignal initialization

```java
05-19 20:48:45.375  3169  3264 D NetworkController.MobileSignalController(1/1): getMobileIconGroup(): 15
05-19 20:48:45.397  5618  6507 W AdvertisingIdClient: Error while reading from SharedPreferences 
05-19 20:48:45.397  5618  6507 W AdvertisingIdClient: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
05-19 20:48:45.397  5618  6507 W AdvertisingIdClient: 	at android.app.ContextImpl.checkMode(ContextImpl.java:2369)
05-19 20:48:45.397  5618  6507 W AdvertisingIdClient: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:383)
05-19 20:48:45.397  5618  6507 W AdvertisingIdClient: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:378)
05-19 20:48:45.397  5618  6507 W AdvertisingIdClient: 	at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
05-19 20:48:45.397  5618  6507 W AdvertisingIdClient: 	at com.onesignal.AdvertisingIdProviderGPS.getIdentifier(AdvertisingIdProviderGPS.java:45)
05-19 20:48:45.397  5618  6507 W AdvertisingIdClient: 	at com.onesignal.OneSignal$6.run(OneSignal.java:758)
05-19 20:48:45.397  5618  6507 W AdvertisingIdClient: 	at java.lang.Thread.run(Thread.java:762)
05-19 20:48:45.480 19497  5363 I EventLogSendingHelper: Sending log events.
```

I'm not sure if this might be the issue causing the crash. So I'd like some help to identify this stacktrace as a possible threat.

The android app actually doesnt fully crash. It remains opened, but webview wont load any resources.

**Environment**
Node 6.9.0
Cordova 8.0.0
Cordova Android 5.2.2
OneSignal plugin 2.1.0

**Comment by jkasten2** [comment]
@vhmolinar Version 2.1.0 of OneSignal is quite old, can you updated to the latest 2.4.0 release? You can remove and re-add OneSignal to do this.
```bash
cordova plugin rm onesignal-cordova-plugin
cordova plugin add onesignal-cordova-plugin
``` 

I also recommend updating your Cordova Android version to 7+, version 5.2.2 is out of date as well.

**Comment by Nightsd01** [comment]
Closing due to lack of response, I am assuming 2.4.0 fixes the issue. If not please feel free to let me know and we'll be happy to reopen + investigate the issue.
