### ISSUE TITLE
Freshchat notification handling with onesginal sdk

### ISSUE THREAD

**Issue by Jeyakumarrathnaselvi** [OneSignal/OneSignal-Cordova-SDK#374]
We are getting duplicate notification If we use onesignal and freshchat sdk so

Freshchat team suggest us to use onesignal sdk or freshchat notification sdk.

As per them we can handle freshchat notification using below steps in onessignal sdk as mentioned below

UpdateNotification on registration Token:
```javascript
window.Freshchat.updatePushNotificationToken(data.registrationId);
```

HandlePushNotification on receive notification :
```javascript
window.Freshchat.isFreshchatPushNotification(data, function(success, isFreshchatNotif) {
  if (success && isFreshchatNotif) {
    window.Freshchat.handlePushNotification(data.additionalData);
  }
});
```

Need your support where to add this part of onesignal sdk.

**Comment by jkasten2** [comment]
@Jeyakumarrathnaselvi OneSignal filters notifications from other sources automatically, so a notification from freshchat's server will never be displayed by the OneSignal SDK. However it sounds like notifications sent from OneSignal are bing displayed by the FreshChat SDK as it is not filter them. I would recommend to FreshChat they filter other notifications not sent by them to avoid this issue.

In the mean time it does look like FreshChat is allowing notifications to be omitted by not calling `window.Freshchat.handlePushNotification`. Is this firing for you each time a notification is shown?
When a notification is sent from OneSignal your `isFreshchatPushNotification` function is firing? If so you can print the `data` being passed here? We can then guide you on what to check to omit the OneSignal notification from FreshChat.

**Comment by Jeyakumarrathnaselvi** [comment]
I have added **window.Freshchat.handlePushNotification** part of Freshchat sdk but it is creating duplicate notification whenever onesignal portal sent notification.

I would like to know if we can add **window.Freshchat.handlePushNotification** it in onesginal sdk so it can handle freshchat notification as well? 

Can you help me where to add it part of onesignal code?

**Comment by jkasten2** [comment]
@Jeyakumarrathnaselvi Just to confirm, the issue of duplicate notifications only started occurring when adding `window.Freshchat.handlePushNotification`? If so please print out `data` as json and we can recommend on how to filter it.

For your 2nd question, OneSignal will already correctly omit processing Freshchat notifications. No changes for this case are needed.

**Comment by Nightsd01** [comment]
Its been a week with no response so we’re assuming you fixed the issue, please feel free to reply to jkasten’s message if you’re still having this problem and we’ll reopen & investigate
