### ISSUE TITLE
One signal haven't detected any subscribed users yet for this platform.

### ISSUE THREAD

**Issue by hamdanihamza** [OneSignal/OneSignal-Cordova-SDK#376]
On android, I added One Signal plugin on my app and i added this code on the platform.ready section

```
    window["plugins"].OneSignal.setLogLevel({logLevel: 6, visualLevel: 6});
      var notificationOpenedCallback = function(jsonData) {
        console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
      };

      window["plugins"].OneSignal
        .startInit("******-****-****-****-***********", "**********")
        .handleNotificationOpened(notificationOpenedCallback)
        .endInit();
```
as i launch the app it shows a bunch of alerts sending requests to onesignal and the app suddenly closes and onesignal doesn’t detect any subscribers.

**Comment by jkasten2** [comment]
@hamdanihamza Please follow this guide to get the logcat from the device to find the specific reason why your app crashed.
https://documentation.onesignal.com/docs/troubleshooting-android#section-how-to-get-a-crash-or-error-log-from-an-android-device

**Comment by hamdanihamza** [comment]
@jkasten2 When i open the app, 2 alerts show one saying " making request to : https://onesignal.com/api/v1/apps/My_ID/android_params.js ", and the other saying " OneSignalRestClient: successfully finished request to:... " and the it closes.
and these are the last messages on the log

```
05-29 18:29:56.205  3482  4221 E WifiConfigStore: updateConfiguration freq=2462 BSSID=18:17:25:22:1b:42 RSSI=-74 "TNCAP221B42"WPA_PSK
05-29 18:29:57.547  3482  3482 I TrafficMonitor: update:rxPkts:1,txPkts:1,rxBytes:122,txBytes:65
05-29 18:29:57.548  3482  3482 I TrafficMonitor: start expired. level:-1
05-29 18:29:57.548  3482  3482 I TrafficMonitor: gettimer:interval=2000
```

**Comment by jkasten2** [comment]
@hamdanihamza This thread warning is ok, cordova is just warning on a very small startup delay of your app. If your app is closing after calling `endinit()` then there will be an exception thrown to the logcat. It should look something like this.

```java
java.lang.IllegalStateException: Message reason for crash
        at com.app.namespace.class.method_a(Unknown Source)
        at com.app.namespace.class.method_b(Unknown Source)
        at com.app.namespace.class.method_c(Unknown Source)
```

**Comment by hamdanihamza** [comment]
When i comment the `endInit()` line the app doesn't crash.

**Comment by Nightsd01** [comment]
Closing this issue - unless you can provide some type of stacktrace from this crash it’s impossible to help you. Please post the stacktrace and we’ll be happy to help and reopen the issue.

**Comment by hamdanihamza** [comment]
[onesignal_crash_logcat.txt](https://github.com/OneSignal/OneSignal-Cordova-SDK/files/2069986/onesignal_crash_logcat.txt)
I think this could be helpful

**Comment by jkasten2** [comment]
@hamdanihamza Can you make sure you are using the latest Cordova SDK version 2.4.1 in your project? In this version we fixed an issue OneSignal when using Firebase Auth.

**Comment by hamdanihamza** [comment]
Yes i do have the latest version installed ...

**Comment by jkasten2** [comment]
@hamdanihamza I see the following in your logcat which looked to be similar error in an older SDK version note here https://github.com/OneSignal/OneSignal-Android-SDK/pull/530
```java
06-04 21:02:50.150  3384  4455 I am_crash: [4014,0,com.hamdev.wydad,954777158,java.lang.IllegalStateException,Default FirebaseApp is not initialized in this process com.hamdev.wydad. Make sure to call FirebaseApp.initializeApp(Context) first.,NULL,-1]
```

However I also seen the following in your logcat which looks to be the result of this open issue https://github.com/OneSignal/OneSignal-Android-SDK/issues/552
```java
06-04 21:02:50.473  3384  4277 I am_schedule_service_restart: [0,com.hamdev.wydad/com.google.firebase.iid.FirebaseInstanceIdService,5378]
06-04 21:02:50.483  4427  5277 W PGApi_client: recv actoionId = 10000, action = com.huawei.pgmng.PGAction@50814cc actionId =10000 pkg =com.instagram.android extend1 =8785 extend2 = flag =3 type =1
```

We will update this issue once it issue above has been fix and merged into this repo.

**Comment by hamdanihamza** [comment]
Thanks a lot @jkasten2 i fixed everything its working smoothly now sorry for the trouble !

**Comment by keysiduven** [comment]
@jkasten2 How did you fix this?

**Comment by jkasten2** [comment]
@keysiduven The crash with `com.google.firebase.iid.FirebaseInstanceIdService` has not been fixed yet. However this is a work around noted below if this is your exact issue.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/552#issuecomment-391973732

**Comment by hamdanihamza** [comment]
i uninstalled the plugin and followed a detailed tutorial, apparently the google service file wasn't placed on the right path.

**Comment by jkasten2** [comment]
@hamdanihamza Could you provide more details? It might help others who run into this.

**Comment by hamdanihamza** [comment]
I'm sorry for replying so much late ... 
First you have to download the google-services.json file. and put it in the `platforms/android/app` or `platforms/android` folder, then copy this line on the project/build.gradle
```
buildscript {
  dependencies {
    // Add this line
    classpath 'com.google.gms:google-services:4.0.0'
  }
}
```
and this line on the project/app/build.gradle

```
dependencies {
  // Add this line
  compile 'com.google.firebase:firebase-core:16.0.0'
}
...
// Add to the bottom of the file
apply plugin: 'com.google.gms.google-services'

```
updating the plugin and removing/adding the platform is preferable.
