### ISSUE TITLE
Build failed "ionic cordova build"

### ISSUE THREAD

**Issue by ragavanrandy** [OneSignal/OneSignal-Cordova-SDK#377]
**Description:**

Hi, I can't build my apk using "Ionic cordova build --release android".

**Environment**

@ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.1
    npm               : 5.6.0
    OS                : Windows 8.1

Environment Variables:

    ANDROID_HOME : C:\android-sdk

Misc:

    backend : pro
 

**Trace**

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\xampp\htdocs\ionic3\oneSignalTest\platforms\android\app\build.gradle' line: 95

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99].
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99].
         > Failed to list versions for gradle.plugin.com.onesignal:onesignal-gradle-plugin.
            > Unable to load Maven meta-data from https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml.
               > Could not HEAD 'https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

[ERROR] An error occurred while running cordova build android --release (exit
        code 1).

**Comment by ragavanrandy** [comment]
downgrade onesignal-cordova-plugin - 2.4.1 to 2.4.0 resolve my problem.

**Comment by jkasten2** [comment]
@ragavanrandy Can you make sure nothing on your system or network is blocking your connection on downloading this file?
https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml
Your log is reporting a 403 error from your system.
