### ISSUE TITLE
Android Error During Build: Could not find firebase-messaging.jar (com.google.firebase:firebase-messaging:15.0.2).

### ISSUE THREAD

**Issue by mino922** [OneSignal/OneSignal-Cordova-SDK#380]
**Description:**
When building ionic Android app I received the following error...
```
Could not resolve all files for configuration ':app:arm64DebugCompileClasspath'.
Could not find firebase-messaging.jar (com.google.firebase:firebase-messaging:15.0.2).
Searched in the following locations: https://jcenter.bintray.com/com/google/firebase/firebase-messaging/15.0.2/firebase-messaging-15.0.2.jar
```

When I remove this plugin I can successfully build the app. The URL above does not exist and I assume this plugin is trying to download that binary.

**Environment**
`
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v8.9.4
    npm        : 5.6.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4 Build version 9F1027a

Environment Variables:

    ANDROID_HOME : not set

Misc:
`

```
cordova-android-play-services-gradle-release 1.4.2 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 1.4.3 "cordova-android-support-gradle-release"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-applepay 3.0.0 "Apple Pay"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-facebook4 1.10.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.4-dev "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"
```

**Steps to Reproduce Issue:**
1. Add one signal cordova plugin
2. ionic cordova platform add android 
3. ionic cordova build android

**Comment by jkasten2** [comment]
@mino922 `15.0.2` isn't a valid version for `com.google.firebase:firebase-messaging`. I think `cordova-android-play-services-gradle-release` might be trying to pick this version.

I recommend removing both `cordova-android-play-services-gradle-release` and `cordova-android-support-gradle-release` from your project. As of `onesignal-cordova-plugin@2.4.1` the plugin will already do alignment of dependency versions that these 2 plugins are doing. You must also have `cordova-android@7.0.0` or newer for the OneSignal plugin to the dependency alignment but I see you do have this version.

**Comment by mino922** [comment]
@jkasten2 I removed both `cordova-android-play-services-gradle-release` and `cordova-android-support-gradle-release`, but I am still having the same issue. 

Below are my installed plugins after removing the plugins mentioned above. Any ideas?

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-applepay 3.0.0 "Apple Pay"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-facebook4 1.10.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.5 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.4-dev "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
cordova-sms-plugin 0.1.11 "Cordova SMS Plugin"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"
```

**Comment by mino922** [comment]
@jkasten2  I'm still seeing this issue, but not really sure what to do next. Any other recommendations?

**Comment by jkasten2** [comment]
@mino922 I recommend creating a new project and make sure OneSignal works there. Then add a few plugins at a time to the new project. Add and remove them until you can find the conflicting plugin. This will help us find the root of the issue quicker for you.

**Comment by mino922** [comment]
@jkasten2  It looks to be an issue with cordova-plugin-googlemaps. When I remove this plugin or googlemaps things seem to work okay.

My app requires use of the google maps plugin. Any ideas on how to get these to play nicely together?

**Comment by mino922** [comment]
I was able to get the plugins to work together by installing 2.4.0 of this plugin and adding the following changes in plugins/onesignal-cordova-plugin/build-extras-onesignal.gradle

```
// ### Google Play Services library
'com.google.android.gms': [
'version': '15.0.0+'
],
// ### Google Firebase library
// Although not used by OneSignal Firebase has some dependencies on gms
// If present, ensuring they are aligned
'com.google.firebase': [
'version': '15.0.0+'
],
```

Is it possible to run the latest version of this plugin without this issue?

**Comment by jkasten2** [comment]
@mino922 Thanks for the details. I assumed before that `15.0.2` wasn't a valid version for `com.google.firebase:firebase-messaging` as the following url did not work.
https://jcenter.bintray.com/com/google/firebase/firebase-messaging/15.0.2/firebase-messaging-15.0.2.jar

However after some digging this seems to be an issue where a number of Google libraries are no longer being hosted on jcenter. This can be fixed by putting Google's repo before `jcenter()` in your `build.gradle`.
https://stackoverflow.com/a/50885939/1244574

For a more automated way of doing this I recommend Ionics guide on fixing this.
https://ionic.zendesk.com/hc/en-us/articles/360005529314-Android-builds-fail-due-to-missing-jcenter-dependencies
