### ISSUE TITLE
The handleNotificationReceived is not fired when app is closed

### ISSUE THREAD

**Issue by gisngocthach** [OneSignal/OneSignal-Cordova-SDK#383]
As I understand, this is the default behavior for the notification feature. My concern is how we could do similar Gmail that even is closed BUT the badge is still increased. Thanks in advance!

**Comment by jkasten2** [comment]
@gisngocthach Thanks for the suggestion. Are you referring to Android or iOS in this case?

**Android:**
Badge values are set automatically be the OneSignal SDK, based on the number of notifications in the shade.
https://documentation.onesignal.com/docs/appearance#section-setting-and-clearing-badge-numbers

**iOS:**
These badges can be set to an exact value or can use increase to increment the value.

Additional details in our docs
https://documentation.onesignal.com/docs/appearance#section-setting-and-clearing-badge-numbers

**Comment by gisngocthach** [comment]
@jkasten2 Thank you so much! It is very useful.

**Comment by gisngocthach** [comment]
As I understand, we could set the badge number for ios by using `ios_badgeType and ios_badgeCount`. I am looking for a way to do the same thing on Android. Someone said that we could put the badge number in the data object in the payload and using ShortcutBadger to set the badge manually. However, like what I said above the handleNotificationReceived event is not fired.

**Comment by gisngocthach** [comment]
Never mind I found a solution for that :-)

**Comment by abhinavparab** [comment]
> Never mind I found a solution for that :-)

Can you share the solution?

**Comment by gisngocthach** [comment]
Have a service like this:
`package com.krea.intranet;

import android.content.Context;
import android.util.Log;

import com.onesignal.NotificationExtenderService;
import com.onesignal.OSNotificationReceivedResult;

import org.json.JSONException;

import me.leolin.shortcutbadger.ShortcutBadgeException;
import me.leolin.shortcutbadger.ShortcutBadger;

/**
 * Created by Mubasshir on 21/12/17.
 */

public class CustomNotificationExtender extends NotificationExtenderService {
    private static String TAG = "FCM_BADGE_HELPER";
    public final static String CONST_BADGE_KEY = "badge";

    public static void setBadgeCount(String badge, Context ctx){
        try {
            int badgeCount = 0;
            if(badge!=null && !badge.isEmpty()){
                badgeCount = tryParseInt(badge);
            }

            ShortcutBadger. applyCountOrThrow(ctx, badgeCount);
            Log.d(TAG, "showBadge worked!");
        } catch (ShortcutBadgeException e) {
            Log.e(TAG, "showBadge failed: " + e.getMessage());
        }
    }
    static int tryParseInt(String value) {
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult notification) {
        try {
            String badge = notification.payload.additionalData.getString(CONST_BADGE_KEY);
            if (badge != null) {
                setBadgeCount(badge, this.getApplicationContext());
                // Return true to stop the notification from displaying.
                return true;
            }
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return false;
    }
}`

And update the manifest file by adding:
`<meta-data android:name="com.onesignal.BadgeCount" android:value="DISABLE" />
`
`
 <service android:exported="false" android:name="packagexxx.CustomNotificationExtender " android:permission="android.permission.BIND_JOB_SERVICE">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
        </service>
`

**Comment by abhinavparab** [comment]
Thanks for the reply. However i am using ionic can you enlighten me by
telling me a workaround in an ionic way
