### ISSUE TITLE
Delete playerId in database when uninstall app or clear cache.

### ISSUE THREAD

**Issue by nguyentien1995** [OneSignal/OneSignal-Cordova-SDK#384]
Hey there, i don't really know if this issue have been ask before as i really don't find suitable word to search, so if it have been asked before, please give me some refer.

This is my logic:
1. Customer login in app.
2. I save playerId to database so that i can send push notify to specific people at event "A".
3. When customer logout, i delete playerId in database so that i do not send push to them when event "A" happend.

Everything still good then: 

4. Customer clear cache and data of mobile app -> They are forced logout (I use an variable in mobile-app to check that if they login or not, default is not login yet) but playerId still stay in database.
5. Customer uninstall the app -> oneSignal do not send to this unsubcribe people but their playerId still stay in my database.

With situation 4, they have been forced logout but when event "A" happen, my server still crawl from database and send push notify to them. My business logic is if they are not login then they will receive nothing.
With situation 5, when they re-install app, they may still receive push notify even if they are not login yet (I haven't check yet, but I read that playerId still is the same if there is some other app use oneSignal too). Imagine that they delete app, sell or hand phone to someone and the new owner use my application too.
The question is can i detect that my customer clear cache or uninstall app so that i can delete their playerId from database through some api?. Or there is any other way to handle this situation?

Thank you for reading.

**Comment by jkasten2** [comment]
@nguyentien1995 When a user logs out you can call [`window.plugins.OneSignal.setSubscription(false);`](https://documentation.onesignal.com/docs/cordova-sdk#section--setsubscription-) to unsubscribe the device. Make sure to call `window.plugins.OneSignal.setSubscription(true);` when a user logs in if you do this.

If someone uninstalls the app then Apple / Google will report back that the device is no longer subscribed after sending a notification or 2. OneSignal will then mark them as unsubscribed on their backend so they continue making attempts for that device.

**Comment by nguyentien1995** [comment]
Oh, i can deal with user logout by press the logout button, the problem is that they don't press logout button, they just go straight to storage in phone and choose clear cache data.
Then they will be forced logout as no token, no variable show that they have been login. If they login back immediately after then its all good, but if they do not login back for a while (maybe they are forgeting about it) then when event happend they still receive push.
I want to know is there anyway to know if they clear cache data in storage or if they uninstall(meaning unsubcribe to oneSignal) so that i can change the database correspond to it.

**Comment by jkasten2** [comment]
@nguyentien1995 If the user goes to Settings > Apps > and presses "CLEAR DATA"  on Android then they will be considered unsubscribed by Google. Same goes when they uninstalled the app on either Android or iOS. The next time a notification it won't be displayed on the device. Google or Apple will report back to OneSignal the device is no longer subscribed and they will be marked as such on OneSignal.

**Comment by nguyentien1995** [comment]
Ok, thank you for clarify what happend when people "clear data".
i have though that they still subcribe when they clear data.

For whoever come later and meet the same problem to me, you may also encounter situation that they clear data, then login to another acocunt.
Then Account2 will receive notify about event "A" too, which should only send to Account1, because they subscribe again with the same playerId, and our server is not clear it yet. You can check when open app, if they are not login yet then u will delete this playerId in database.

Anyway, thank jkasten2 for your help.
Mod can close this now.

**Comment by Sahil-Choudhary-09** [comment]
@nguyentien1995, hey I'm facing the same issue that you mentioned. Could you please tell how you solved the above problem?

**Comment by nguyentien1995** [comment]
on which specific issue u are facing? I don't quite remember how i solve it
but as I re reading the issue I already give out the solution on bottom

Vào Th 4, 24 thg 11, 2021 vào lúc 14:04 Sahil-Choudhary-09 <
***@***.***> đã viết:
