### ISSUE TITLE
Stop resetting badge count to Zero on opening app in android. 

### ISSUE THREAD

**Issue by sibaquest** [OneSignal/OneSignal-Cordova-SDK#387]
Hello ,
As per my requirement i want to stop resetting my notification count to zero on opening an app.again we are using this in hybrid application(Ionic).I came across two things in client side:
1. OneSignalPush.Java
some code i found like this.
```java
  private static final String CLEAR_ONESIGNAL_NOTIFICATIONS = "clearOneSignalNotifications";

else if (CLEAR_ONESIGNAL_NOTIFICATIONS.equals(action)) {
      try {
       OneSignal.clearOneSignalNotifications();
       result = true;
	    
      }
      catch(Throwable t) {
        t.printStackTrace();
      }
    }
```
i could not understand much as i am .net Developer.

2.OneSignal.js
```javascript
OneSignal.prototype.clearOneSignalNotifications = function () {
  cordova.exec(function(){}, function(){}, "OneSignalPush", "clearOneSignalNotifications", []);
};
```

Currently am using OneSignal-cordova-plugin. Version:2.4.1

Now i need to stop resetting to Zero. I tried by commenting those section but still no changes.Can anyone give insight on this how to achieve my requirement.

Help is highly appreciated.

@jkasten2   Would be grateful to you if you can help me out on this.

Regards,
Siba Prasad

**Comment by jkasten2** [comment]
@sibaquest If you call `window.plugins.OneSignal.clearOneSignalNotifications();` in your app this will clear all notifications and badges. The OneSignal SDK sets the badge value to the number of notifications in the shade on Android. So the badge value is always cleared when all notifications are removed.

This call you linked to isn't run automatically, only if you call it from your `.js` file

**Comment by sibaquest** [comment]
@jkasten2  Thank you for your reply. I have verified about what you have said.notifications are not removed untill i call the window.plugins.OneSignal.clearOneSignalNotifications() but the the number of notification count gets reset to zero once i open the app.outside the app i could see the notification exists but the badge count over the app is reset to zero. 

For example:  I send two notifications to my app.these notification still exists outside app,badge count would be two over the app.but badge count resets to zero once i open my app.As the OneSignal SDK sets the badge value to the number of notifications in the shade on Android,so as per my knowledge the number of  notification that exists outside app  the same number should be over the app.The count should change if i click on notification or swipe over the notification.Please correct me if i am wrong.

**Comment by jkasten2** [comment]
@sibaquest That is odd, there are two things I can think of that would clear the badge when opening the app; 1. Another plugin in the app; 2. The behavior of the Android Launcher you are using. To test the 1. I recommend creating a new Cordova project to see if the issue still happens on your device.

The badge value should decrease for each notification you open or swipe away. Does the badge come back if you swipe a notification away in your case?

Lastly which model of device are you using? Are you using the default launcher or a 3rd party one?

**Comment by sibaquest** [comment]
@jkasten2  You are ryt.i was using Third party plugin called Cordova-Plugin-Badge for handling Badge count inside the app.unfortunately that was resetting to Zero. Now i need to search any other plugin to **handle app badge count inside the app**.If possible can you recommend any plugin that is fully compatible with OneSignal to fulfill my requirement(handle app badge count inside the app).

 _**The badge value should decrease for each notification you open or swipe away**_ 
Exactly it is behaving the way you have mentioned.not resetting to Zero.but **is there any way to stop decrement of badge count on Swipe/Open as well?**.

**Comment by jkasten2** [comment]
@sibaquest Sorry I haven't tried any Cordova plugins for setting badge values so can't make any recommendations.

If you want to disable OneSignal's automatic badge logic you can do so with the following:
https://documentation.onesignal.com/docs/android-native-sdk#section-disable-badges
