### ISSUE TITLE
Android app not building

### ISSUE THREAD

**Issue by kingkarki** [OneSignal/OneSignal-Cordova-SDK#390]
**Description:**

I added this plugin on my existing Ionic project. When i run Cordova build Android I get following error. 
(your description here)

**Environment**

Cordova plugin list 
```
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook-account-kit 0.1.6 "FacebookAccountKitLogin"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.2.1 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"
phonegap-plugin-multidex 1.0.0 "Multidex"
```
I am using latest version of this plugin. My cordova android version is 7.1.0. 
My Cordova version is 8. 

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**
My error log
```

:app:transformClassesWithStackFramesFixerForDebug UP-TO-DATE
:app:transformClassesWithDesugarForDebug UP-TO-DATE
:app:transformClassesWithDexBuilderForDebug UP-TO-DATE
:app:transformClassesWithMultidexlistForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
38 actionable tasks: 1 executed, 37 up-to-date
(node:69424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /Applications/apps/v2/najeek/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


```
My project.properties file on android folder

```target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-android-support-gradle-release/najeek-cordova-android-support-gradle-release.gradle
cordova.system.library.1=com.soundcloud.android:android-crop:1.0.0@aar
cordova.system.library.2=com.facebook.android:account-kit-sdk:4.+
cordova.system.library.3=com.facebook.android:facebook-android-sdk:4.+
cordova.system.library.4=com.android.support:appcompat-v7:23+
cordova.gradle.include.2=cordova-plugin-telerik-imagepicker/najeek-ignorelinterrors.gradle
cordova.gradle.include.3=cordova-plugin-telerik-imagepicker/najeek-androidtarget.gradle
cordova.system.library.5=com.android.support:support-v4:24.1.1+
cordova.gradle.include.4=phonegap-plugin-multidex/najeek-multidex.gradle
cordova.system.library.6=com.onesignal:OneSignal:3.9.1
cordova.gradle.include.5=onesignal-cordova-plugin/najeek-build-extras-onesignal.gradle```

(crash stacktraces, as well as any other information here)


<!--
  SEARCH EXISTING ISSUES FOR AN ANSWER: https://goo.gl/G4XxN2
-->

**Comment by atorgfr** [comment]
If you change platforms/android/onesignal-cordova-plugin/monpetitpronoapp-build-extras-onesignal.gradle

to 
```
def manifest = new XmlSlurper().parse(file("AndroidManifest.xml"))
android.defaultConfig {
   applicationId manifest.@package.text()
   manifestPlaceholders = [onesignal_app_id: "", // Use from code for now.
                          onesignal_google_project_number: "REMOTE"]
}

repositories {
   maven { url 'https://maven.google.com' }
}

// ## Align gms and support group versions on all dependencies 

def versionGroupAligns = [
    // ### Google Play Services library
    'com.google.android.gms': [
        'version': '11.2.+'
    ],

    // ### Google Firebase library
    // Although not used by OneSignal Firebase has some dependencies on gms
    // If present, ensuring they are aligned
    'com.google.firebase': [
        'version': '11.2.+'
    ],

    // ### Android Support Library
    'com.android.support': [
        'requiredCompileSdkVersion': 26,
        'version': '26.1.+',
        'omitModules': ['multidex', 'multidex-instrumentation'],

        // Can't use 26 of com.android.support when compileSdkVersion 25 is set
        // The following error will be thrown if there is a mismatch here.
        // "No resource found that matches the given name: attr 'android:keyboardNavigationCluster'"
        'versionFallback': '25.+'
    ]
]

def resolveVersion(def versionOverride) {
    def curCompileSdkVersion = android.compileSdkVersion.split('-')[1].toInteger()
    def requiredCompileSdk = versionOverride['requiredCompileSdkVersion']
    if (curCompileSdkVersion < requiredCompileSdk)
        return versionOverride['versionFallback']
    return versionOverride['version']
}

configurations.all { resolutionStrategy {

    // Enable to find root causes of any remaining version mismatches
    // failOnVersionConflict()

    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def versionOverride = versionGroupAligns[details.requested.group]
        if (!versionOverride)
            return

        def omitModules = versionOverride['omitModules']
        if (omitModules && omitModules.contains(details.requested.name))
            return

        details.useVersion(resolveVersion(versionOverride))
    }
}}
```

I don't knwo why they changed this file but it was the problem for me.

**Comment by kingkarki** [comment]
Thank you so much @atorgfr It worked with your gradle.

**Comment by princenishchal** [comment]
Hey, I created a new Ionic App which uses the "sample" template. Did not add any additional code to the project. It compiles without any errors when I use android@7.0.0 as well as android@7.1.0.

**Comment by princenishchal** [comment]
@atorgfr , when I use your gradle file I am getting the following error
```
java.lang.IllegalStateException: compileSdkVersion is not specified.

	at com.google.common.base.Preconditions.checkState(Preconditions.java:456)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:590)
	at com.android.build.gradle.BasePlugin.lambda$null$3(BasePlugin.java:555)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)

	at com.android.build.gradle.BasePlugin.lambda$createTasks$4(BasePlugin.java:551)

	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)

	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)

	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)

	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)

	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy23.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:
```
I just copy pasted your entire contents and replaced the values in my gradle file of "onesignal plugin"
Any help/suggestions will be deeply appreciated

**Comment by princenishchal** [comment]
Hey, I found one way that worked. It is same as what @atorgfr has suggested.

Steps:
1. Remove the existing onesignal plugin
2. Add a previous version of the plugin, in my case I added `ionic cordova add plugin onesignal-cordova-plugin@2.3.0`
3. Copied the gradle file from the location `platforms/android/onesignal-cordova-plugin` to a temporary location

**Comment by Nightsd01** [comment]
Closing because the solution was posted, if anyone else runs into this problem and the above steps don't work please feel free to reply and I'll be happy to reopen the issue and help you fix it.

**Comment by vaimeo** [comment]
> If you change platforms/android/onesignal-cordova-plugin/monpetitpronoapp-build-extras-onesignal.gradle
> 
> to
> 
> ```
> def manifest = new XmlSlurper().parse(file("AndroidManifest.xml"))
> android.defaultConfig {
>    applicationId manifest.@package.text()
>    manifestPlaceholders = [onesignal_app_id: "", // Use from code for now.
>                           onesignal_google_project_number: "REMOTE"]
> }
> 
> repositories {
>    maven { url 'https://maven.google.com' }
> }
> 
> // ## Align gms and support group versions on all dependencies 
> 
> def versionGroupAligns = [
>     // ### Google Play Services library
>     'com.google.android.gms': [
>         'version': '11.2.+'
>     ],
> 
>     // ### Google Firebase library
>     // Although not used by OneSignal Firebase has some dependencies on gms
>     // If present, ensuring they are aligned
>     'com.google.firebase': [
>         'version': '11.2.+'
>     ],
> 
>     // ### Android Support Library
>     'com.android.support': [
>         'requiredCompileSdkVersion': 26,
>         'version': '26.1.+',
>         'omitModules': ['multidex', 'multidex-instrumentation'],
> 
>         // Can't use 26 of com.android.support when compileSdkVersion 25 is set
>         // The following error will be thrown if there is a mismatch here.
>         // "No resource found that matches the given name: attr 'android:keyboardNavigationCluster'"
>         'versionFallback': '25.+'
>     ]
> ]
> 
> def resolveVersion(def versionOverride) {
>     def curCompileSdkVersion = android.compileSdkVersion.split('-')[1].toInteger()
>     def requiredCompileSdk = versionOverride['requiredCompileSdkVersion']
>     if (curCompileSdkVersion < requiredCompileSdk)
>         return versionOverride['versionFallback']
>     return versionOverride['version']
> }
> 
> configurations.all { resolutionStrategy {
> 
>     // Enable to find root causes of any remaining version mismatches
>     // failOnVersionConflict()
> 
>     resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>         def versionOverride = versionGroupAligns[details.requested.group]
>         if (!versionOverride)
>             return
> 
>         def omitModules = versionOverride['omitModules']
>         if (omitModules && omitModules.contains(details.requested.name))
>             return
> 
>         details.useVersion(resolveVersion(versionOverride))
>     }
> }}
> ```
> I don't knwo why they changed this file but it was the problem for me.

It Works for me :)

**Comment by tranzfusion** [comment]
> @atorgfr it should be
> 
> `def manifest = new XmlSlurper().parse(file("src/main/AndroidManifest.xml")) `
> If android version is heigher than 6.4

This worked for me !

**Comment by wilguevara** [comment]
> @atorgfr , when I use your gradle file I am getting the following error
> 
> ```
> java.lang.IllegalStateException: compileSdkVersion is not specified.
> 
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:456)
> 	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:590)
> 	at com.android.build.gradle.BasePlugin.lambda$null$3(BasePlugin.java:555)
> 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
> 
> 	at com.android.build.gradle.BasePlugin.lambda$createTasks$4(BasePlugin.java:551)
> 
> 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
> 
> 	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
> 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
> 
> 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
> 
> 	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
> 	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
> 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
> 	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
> 
> 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
> 	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
> 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
> 	at com.sun.proxy.$Proxy23.afterEvaluate(Unknown Source)
> 	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:
> ```
> I just copy pasted your entire contents and replaced the values in my gradle file of "onesignal plugin"
> Any help/suggestions will be deeply appreciated
> 
> If I remove your gradle contents and place the previous gradle file. I am getting the error reported by @kingkarki

i think this work's for me, but it fails now for another plugin (https://github.com/mapsplugin/cordova-plugin-googlemaps) when trying to build android project.

I will be looking for a solution, if i find something i will update my post here.

**Comment by wilguevara** [comment]
> If you change platforms/android/onesignal-cordova-plugin/monpetitpronoapp-build-extras-onesignal.gradle
> 
> to
> 
> ```
> def manifest = new XmlSlurper().parse(file("AndroidManifest.xml"))
> android.defaultConfig {
>    applicationId manifest.@package.text()
>    manifestPlaceholders = [onesignal_app_id: "", // Use from code for now.
>                           onesignal_google_project_number: "REMOTE"]
> }
> 
> repositories {
>    maven { url 'https://maven.google.com' }
> }
> 
> // ## Align gms and support group versions on all dependencies 
> 
> def versionGroupAligns = [
>     // ### Google Play Services library
>     'com.google.android.gms': [
>         'version': '11.2.+'
>     ],
> 
>     // ### Google Firebase library
>     // Although not used by OneSignal Firebase has some dependencies on gms
>     // If present, ensuring they are aligned
>     'com.google.firebase': [
>         'version': '11.2.+'
>     ],
> 
>     // ### Android Support Library
>     'com.android.support': [
>         'requiredCompileSdkVersion': 26,
>         'version': '26.1.+',
>         'omitModules': ['multidex', 'multidex-instrumentation'],
> 
>         // Can't use 26 of com.android.support when compileSdkVersion 25 is set
>         // The following error will be thrown if there is a mismatch here.
>         // "No resource found that matches the given name: attr 'android:keyboardNavigationCluster'"
>         'versionFallback': '25.+'
>     ]
> ]
> 
> def resolveVersion(def versionOverride) {
>     def curCompileSdkVersion = android.compileSdkVersion.split('-')[1].toInteger()
>     def requiredCompileSdk = versionOverride['requiredCompileSdkVersion']
>     if (curCompileSdkVersion < requiredCompileSdk)
>         return versionOverride['versionFallback']
>     return versionOverride['version']
> }
> 
> configurations.all { resolutionStrategy {
> 
>     // Enable to find root causes of any remaining version mismatches
>     // failOnVersionConflict()
> 
>     resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>         def versionOverride = versionGroupAligns[details.requested.group]
>         if (!versionOverride)
>             return
> 
>         def omitModules = versionOverride['omitModules']
>         if (omitModules && omitModules.contains(details.requested.name))
>             return
> 
>         details.useVersion(resolveVersion(versionOverride))
>     }
> }}
> ```
> I don't knwo why they changed this file but it was the problem for me.

i think this work's for me, but it fails now for another plugin (https://github.com/mapsplugin/cordova-plugin-googlemaps) when trying to build android project.

I will be looking for a solution, if i find something i will update my post here.
