### ISSUE TITLE
Notification categories question

### ISSUE THREAD

**Issue by LaloCastilla** [OneSignal/OneSignal-Cordova-SDK#391]
By reading the onesignal documentation i understand that there are two ways of creating notification categories:

1- From Onesignal Dashboard
2- By code (Dont know if its on the ionic app or inside the rest server).

Can anyone provide an example of how notification categories can be created by code?

Im using Nodejs rest server and Ionic platform. Any example from any programming language is welcome.

**Comment by jkasten2** [comment]
@LaloCastilla Is there any specific cases or features that [OneSignal's dashboard](https://documentation.onesignal.com/docs/android-notification-categories) does not cover for creating Android notification channels / categories?

The SDK does not have an API to create channels / categories from code within your app. However you can use Java native code to do this with Ionic / Cordova to do this. 
https://developer.android.com/training/notify-user/channels
OneSignal lets you set an existing channels on your notification so this can be used after you set it up in your app.

**Comment by Nightsd01** [comment]
Closing due to no response. If you have more questions please feel free to respond and I'll be happy to reopen the issue
