### ISSUE TITLE
No Permission Request in android devices

### ISSUE THREAD

**Issue by kennethwwu** [OneSignal/OneSignal-Cordova-SDK#392]
**Description:**
No Permission Request popup in android devices, the device is automatically subscribed the push notification

i found some information here https://documentation.onesignal.com/docs/permission-requests, but does't mention how the force the display Permission Request

**Environment**
> cordova -v
8.0.0

> cordova plugin ls
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.3.1 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
onesignal-cordova-plugin 2.3.3 "OneSignal Push Notifications"

**Comment by Nightsd01** [comment]
@kennethwwu Android does not have a built in permission prompt for push notifications. If you want one, you would need to implement it yourself. You can do this by calling `OneSignal.setSubscription(false)` the very first time the user opens your app (or use tags to exclude them from your push notifications). Then you can show your prompt UI. If the user answers yes, you can respond appropriately.
