### ISSUE TITLE
Android 8.0.0 the notifications' custom sounds does not work

### ISSUE THREAD

**Issue by Neto-Pavanini** [OneSignal/OneSignal-Cordova-SDK#393]
*Description:*
Standard sound on android 8.0

Environment
Example:
1. What version of the Cordova SDK are you using?
 cordova -v 
 8.0.0
2. Provide a list of your project dependencies (using `cordova plugin list` or copy-pasting your config.xml)
 $ cordova plugin list
cordova-appgroups-dates 1.0.0 "App Groups UserDefault"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-name 1.3.3 "Device-Name"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 1.4.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-vibration 3.1.0 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.2 "Toast"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"

*Steps to reproduce the issue:*

  Example:

  1. Add the onesignal-cordova-plugin to your project
  2. Initialize the plugin with your app ID
  3. Attempt to receive a push notification

  (write below this `line)`

1. Add the onesignal-cordova-plugin to your project
2. Build and run android on device version 8.0.0
3. Send push notification with custom sound

*Anything else:*

```
<preference name="android-minSdkVersion" value="17" />
<preference name="android-targetSdkVersion" value="27" />
```

In other android versions it works normally. Only in version 8.0.0 the notifications' custom sounds does not work properly because it does not respect the folder 'res/raw/'. In other words, the notification arrives but it plays the system sound and not the custom one.

**Comment by jkasten2** [comment]
@Neto-Pavanini Android 8.0 now enforces Notification categories / channels to be used for sounds and a number of other features. This means you must setup a notification category first and then add it to the notification. See our guide below on setting up and using them;
https://documentation.onesignal.com/docs/android-notification-categories

**Comment by project30003** [comment]
I did create notification categories / channels, and ensured the sound file is in res/raw. But the custom sound is not working.

Tried on iOS and android 7.0 they work perfectly but not android 8.0

**Comment by blinks32** [comment]
Any soulution on this yet?

**Comment by project30003** [comment]
Hello
With android categories, if you sent a notification with a category, then changed the options on the category, it will not update for that device if you send again. It will be updated for new devices that have not received it.
You will need to create a brand new category if you make any changes after sending it.
Thanks

**Comment by blinks32** [comment]
Hello, thanks for the answer. I did that, but I don't get any notification again, but my player id is active. previously i could get a notification without sound, but now i don't get any notification at all.

**Comment by project30003** [comment]
Would suggest you to look for assitance from onesignal chat.
