### ISSUE TITLE
Badges aren't Increased as expected in Iphone

### ISSUE THREAD

**Issue by yuvalyellin** [OneSignal/OneSignal-Cordova-SDK#394]
**Description:**

Installed the ionic sample app, changing the application id and bundle id to correspond to my settings. when Sending notifications with badges / increase by 1 to iphone, the badge remains 1 (or any other constant number I give there) 

**Environment**
  plugin name="cordova-plugin-console" spec="^1.0.5" 
    plugin name="cordova-plugin-device" spec="^1.1.4" 
   plugin name="cordova-plugin-splashscreen" spec="^4.0.3" 
    plugin name="cordova-plugin-statusbar" spec="^2.2.2" 
    plugin name="cordova-plugin-whitelist" spec="^1.3.1" 
    plugin name="ionic-plugin-keyboard" spec="^2.2.1
    plugin name="onesignal-cordova-plugin" spec="^2.4.1
    engine name="ios" spec="4.5.4" 

**Steps to Reproduce Issue:**

1. Used https://github.com/OneSignal/OneSignal-Ionic-Example
2. Change application id and bundle id, built and installed on iphone
3. opened app and clicked "Subsribe on ios" 
 
4. sent notifications from onesignal with badges/ increase by 1/2/3 
instead of increasing the badge values is replaced by the last message I send, even though I didn't ioen the app in between notifications . \

**Comment by Nightsd01** [comment]
Hi @yuvalyellin,

To support badge increment logic, you would want to implement the notification service extension:

https://documentation.onesignal.com/docs/cordova-sdk-setup#section-ios-service-extensions
