### ISSUE TITLE
Can't save tags on iOS

### ISSUE THREAD

**Issue by henryavila** [OneSignal/OneSignal-Cordova-SDK#395]
**Description:**

In my app, the user can change the site that he receive the news, for each site the app update a tag for the user.
In android, the tags on OneSignal are always changed, but in iOS it not changed. Some time the tag are saved in the first time, but after it, it's saved no more.

The debug show the message that the user was registered.

Even so, the tag is not saved.

**That's my Environment**

`com-sarriaroman-photoviewer 1.1.18 "PhotoViewer"`
`com-stionic-plugin 1.0.8 "Stionic Plugin"`
`cordova-clipboard 1.2.1 "Clipboard"`
`cordova-plugin-actionsheet 2.3.3 "ActionSheet"`
`cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"`
`cordova-plugin-app-version 0.1.9 "AppVersion"`
`cordova-plugin-cache-clear 1.3.7 "Cordova Cache Clear"`
`cordova-plugin-cocoapod-support 1.5.0 "Cordova CocoaPods Dependency Support"`
`cordova-plugin-datepicker 0.9.3 "DatePicker"`
`cordova-plugin-device 2.0.2 "Device"`
`cordova-plugin-dialogs 2.0.1 "Notification"`
`cordova-plugin-file 6.0.1 "File"`
`cordova-plugin-file-transfer 1.7.1 "File Transfer"`
`cordova-plugin-flurryanalytics 1.4.6 "Flurry Analytics"`
`cordova-plugin-geolocation 4.0.1 "Geolocation"`
`cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"`
`cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"`
`cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"`
`cordova-plugin-is-debug 1.0.0 "IsDebug"`
`cordova-plugin-network-information 2.0.1 "Network Information"`
`cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"`
`cordova-plugin-splashscreen 5.0.2 "Splashscreen"`
`cordova-plugin-statusbar 2.4.2 "StatusBar"`
`cordova-plugin-whitelist 1.3.3 "Whitelist"`
`cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"`
`cordova-plugin-x-toast 2.6.2 "Toast"`
`cordova-plugin-zip 3.1.0 "cordova-plugin-zip"`
`cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"`
`es6-promise-plugin 4.2.2 "Promise"`
`ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"`
`ionic-plugin-keyboard 2.2.1 "Keyboard"`
`onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"`
`uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.1 "Launch Navigator"`

**My code:**

Code in app start:
`this.OneSignal.startInit(oneSignalAppId);`
`this.OneSignal.inFocusDisplaying(this.OneSignal.OSInFocusDisplayOption.Notification);`

`this.OneSignal.sendTag(IasdVirtualProvider.onesingalTagId,` `IasdVirtualProvider.formatTagId(this.trans['url']));`
`// when open notifications`
`this.OneSignal.handleNotificationOpened().subscribe(res => {`
`...`
`});`
`this.OneSignal.endInit();`

When the user will change the site he will receive the news (and push), in the setup screen I remove the tag to have sure he will not receive push from the old site:
`this.OneSignal.clearOneSignalNotifications();`
`this.OneSignal.deleteTag(IasdVirtualProvider.onesingalTagId);`

After this, when the user choose the site, the app start again running the first code.

It works fine one on android, but not in iOS.

[Here](https://github.com/geektimecoil/react-native-onesignal/issues/275), one user report the same problem with an react-native-onesignal plugin (looks like be no official), the user talk to update to a 2.5.4 version that solved the problem, but for Cordova this version do not exist.

Thanks for the help

**Comment by Nightsd01** [comment]
@henryavila calling `sentTags()` before calling `endInit()` is not a good idea. Can you try moving the `sendTags()` statement below?

**Comment by henryavila** [comment]
Hi @Nightsd01, Thanks for the tip. I will try this night and post here the result.

**Comment by henryavila** [comment]
Hi @Nightsd01, I changed the sendTags() to after endInit(), but the problem persists.
The app change the tag 2 times, and in third time, I save no more.

The actual code is
`this.OneSignal.startInit(oneSignalAppId);`
`...`
`this.OneSignal.endInit();`
`setTimeout(() => {`
`this.OneSignal.sendTag(tagName, tagValue));`
`}, 3000);`


Any ideas?
Just to remember, when changing the site, before restart the app, I'm calling:
`this.OneSignal.clearOneSignalNotifications();`
`this.OneSignal.deleteTag(tagName);`

I don't know if can interfere.

**Comment by Nightsd01** [comment]
@henryavila tags can take some time to synchronize. Are you waiting at least 20 seconds before checking to see if the tags were set?

Also, can you enable verbose logging with the `OneSignal.setLogLevel:` method and send me your logs when the problem occurs? In iOS it’s

**Comment by henryavila** [comment]
Hi @Nightsd01, thanks for the reply.
Even a hours later, the tag is not updated in panel.

Here is the log on Xcode:
```
VERBOSE: HTTP Request (OSRequestSendTagsToServer) with URL: https://onesignal.com/api/v1/players/a03c81f2-3a16-422b-8a92-10489a89fbbe, with parameters: {
  "net_type" : 0,
  "app_id" : "xxxxxxxxxxxxxxxxxxxxx",
  "tags" : {
    "church" : "iasdermelinda.com.br"
  }
}
```

```
VERBOSE: network response (OSRequestSendTagsToServer): {
    success = 1;
}
```

```
VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
```

```
DEBUG: mobileProvision: {
}
```

```
VERBOSE: Calling OneSignal create/on_session
```

```
VERBOSE: HTTP Request (OSRequestRegisterUser) with URL: https://onesignal.com/api/v1/players/a03c81f2-3a16-422b-8a92-10489a89fbbe/on_session, with parameters: {
  "app_id" : "xxxxxxxxxxxxxxxx",
  "net_type" : 0,
  "as_id" : "081A3C33-95FE-4643-AA84-1C7655740E5E",
  "device_type" : 0,
  "sdk" : "020805",
  "identifier" : "61805a35298e1d9f5db7ccde56d154cad85515f81c30609746d64e27ad6a72e9",
  "language" : "en-BR",
  "device_os" : "11.4",
  "game_version" : "1.4.0",
  "timezone" : -10800,
  "ad_id" : "8B566EA6-4364-49A0-8455-5C12DC5EB6AC",
  "notification_types" : 15,
  "device_model" : "iPad5,3"
}
```



```
VERBOSE: network response (OSRequestRegisterUser): {
    id = "a03c81f2-3a16-422b-8a92-10489a89fbbe";
    success = 1;
}
```

```
VERBOSE: updateDeviceToken:onSuccess:onFailure:
```



```
VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
```

```
VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
```



```
VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
```


An ideias?

**Comment by Nightsd01** [comment]
@henryavila I suspect that you are calling `getTags` very rapidly after calling `sendTags`, because from looking at your logs, it looks like the tags **are** being sent to the server.

Please be aware that in iOS, if you call `sendTags`, it initiates an HTTP request to update the server, but not immediately, it can take up to 5 seconds. If you call `getTags` afterwards, this request executes immediately. So there are cases where your `getTags` request can return old tags.

We are planning to change iOS behavior to be more like Android, where we will return pending tags in addition to sent tags. 

In the mean time, until we build this, I would suggest that you use some sort of tags cache in your app.

**Comment by henryavila** [comment]
Hi @Nightsd01, thanks for the reply.
I found the problem when testing my app, So I was changing the tags "very rapidly".

But the problem isn't the tag displayed in the app, the problem is that the user in onesignal Dashboard update no more. Even if I wait one hour and change the tag in app and wait another one hour, in dashboard it will not update.


Anyway, I will remake all the tests waiting 5 minutes before change the tags in the app and see if the problem persists. 

After his, I will post here the results. 

Thanks

**Comment by christianekro** [comment]
I have the same problem @henryavila 

check https://onesignal.com/api/v1/players/64604118-8bcd-491d-b860-6731790899d2 there are your players (with tag {"church":"demo.iasdvirtual.com.br"} ), maybe write your app_id is a bad idea but i hope it helps

**Comment by Nightsd01** [comment]
Hi @henryavila , any updates on what happened? Let me know if you're still seeing this issue and I'd be happy to help.

**Comment by henryavila** [comment]
Hi @Nightsd01, I made some tests and the problem keeps in iOS.

I was using iOS12, so I imagine that this could be the reason, but I tryed with the lsat stable iOS 11 and the problem persist.

In the first run of the app, I call

```
this.OneSignal.startInit(oneSignalAppId);
this.OneSignal.inFocusDisplaying(this.OneSignal.OSInFocusDisplayOption.Notification);


this.OneSignal.handleNotificationOpened().subscribe(res => {
    ...
});
this.OneSignal.endInit();
setTimeout(() => {
    this.OneSignal.sendTag(tagName, tagValue);
}, 3000);
```

in Onesignal Dashboard, The user has the tag.

after 5 minutes I triger a function to remove the tag. The the following code was run:
```
this.OneSignal.clearOneSignalNotifications();
this.OneSignal.deleteTag(tagName);

// Forcing wait a bit
setTimeout(() => {
    resolve();
}, 2000);
```


After this, The ap start again and the fist code run again:
```
this.OneSignal.startInit(oneSignalAppId);
this.OneSignal.inFocusDisplaying(this.OneSignal.OSInFocusDisplayOption.Notification);


this.OneSignal.handleNotificationOpened().subscribe(res => {
    ...
});
this.OneSignal.endInit();
setTimeout(() => {
    this.OneSignal.sendTag(tagName, tagValue);
}, 3000);
```

At this point, event after hours, the Onesignal Dasboard don't update the user tag. the user come with no tag.


In Android this works, but in iOS it's not working.

**Comment by ribamartins** [comment]
Hi,

Same issue here. 

The tags are registered ok on Android but not working on IOS. 
Any news about this problem?

Tks

**Comment by henryavila** [comment]
Hi @Nightsd01 and @ribamartins. I found my problem.

Im my case, I connect to different web site to get the Onesignal app id (each site has one app id).
The problem was that, in my case, one of this sites was outdated and has the wrong app id, so the Onesignal was connecting to the wrong app.

After fixing all sites info, it's now works great.

@Nightsd01 thanks for the help, and sorry beacuse it was my mistake.
@ribamartins I sugest you to double check your code.

**Comment by alihut** [comment]
Is there a fix for this? On Android it works fine but on IOS I have to wait for 5, 6 seconds after 

OneSignal.Current.SendTags(dict);

so  OneSignal.Current.GetTags() would receive new tags. If I don't wait GetTags() receive old tags. I'm using OneSignal on my cross-platform Xamarin project.
