### ISSUE TITLE
Callbacks feature request

### ISSUE THREAD

**Issue by jaapjanfrans** [OneSignal/OneSignal-Cordova-SDK#4]
Hi!

It would be great if functions like sendTag, sendTags, setSubscription, etc would enable the use of success and error callbacks. This would help to determine if these operations succeed or fail, to be able to act correctly on any errors.

I'm guessing this is not specific to the Cordova SDK as other SDK's also don't seem to provide callbacks for these kind of operations.

kind regards,
Jaap-Jan

**Comment by jkasten2** [comment]
Hello,

Thanks for your suggestion, we plan on adding smart retrying to solve most issues with user records not getting updated due to device connection issues. If we handle this internally would you still need callback for feedback in your app's use cases?

Thanks.

**Comment by jaapjanfrans** [comment]
Yes I Think callbacks would still be usefull. See #5 for a use case for a callback on the init function :-)

**Comment by jaapjanfrans** [comment]
Other usecase, for setTags:
If i know setTags has finished succesfully and the tags are uploaded correctly, I actually know my user is registered for the correct tags. Now it's a black box, i call setTags and have no way of knowing if it succeeded, other than calling getTags afterwards and verifying the tags are really there. But that means an extra request that would be unnecessary if setTags provides a callback that tells me the result of the request to set the tags.

**Comment by jkasten2** [comment]
We will look into adding callbacks to these network based functions in the future. We will still add in the smart retrying as well so developers can still do set and forgot on tags that may not be critical.

If this is a feature you need right away feel free to create a pull request and we will merge it in after a review.

**Comment by jaapjanfrans** [comment]
Great, thanks for considering.

Smart retrying sounds interesting when you want an app to use the SDK in a fire and forget style. Personally, I would want to have control over the way my app communicates to the outside world and handle retrying myself. Maybe smart retrying could be configurable so that you can choose to use it? Then again, retrying from outside the android SDK only makes sense if you know when an SDK function succeeds or fails with callbacks ;-)

Keep up the good work!

**Comment by jkasten2** [comment]
Just to update you our progress, we now have auto retrying on tags and subscription with offline support for Android. I'll working on the iOS native SDK to bring the same logic to Cordova for iOS.

**Comment by freeriderND** [comment]
Are there any changes in this issue?

**Comment by jkasten2** [comment]
@freeriderND The [OneSignal-iOS-SDK](https://github.com/OneSignal/OneSignal-iOS-SDK) native SDK that this SDK uses does not support offline tags yet. Sorry we don't have an eta at this time.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration

**Comment by terreng** [comment]
Given that this is a pretty significant feature, it's concerning that this issue should be closed...

**Comment by rgomezp** [comment]
@terreng ,
We have simply moved this into our internal tracking system. This doesn't mean we are no longer considering it
