### ISSUE TITLE
iOS - Notification permissions - Get current and changed callback

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Cordova-SDK#40]
Feature request to add a SDK function to get the current notification permission in iOS and a callback that can fire when it changes.

**Comment by ricolo** [comment]
Would be great to have this feature. There's a [plugin](https://github.com/nrswolf/cordova-plugin-push-notifications-status) that can check the status, and it's a small plugin. According to the discussion [here](http://stackoverflow.com/questions/1535403/determine-on-iphone-if-user-has-enabled-push-notifications), different iOS versions would have different APIs to do it though.

**Comment by oggyindahouse** [comment]
This is an extremely needed feature. Currently I cannot register my IOS 10 (iphone 6s) device.

**Comment by aurbina83** [comment]
I was just going to ask if this was available. This would be perfect, similar to checking if location permissions have been granted.

**Comment by jkasten2** [comment]
@ricolo @oggyindahouse @aurbina83 You can now call [`getPermissionSubscriptionState`](https://documentation.onesignal.com/docs/cordova-sdk#section--getpermissionsubscriptionstate-) to get the current notification permission and subscription state for the device. There is also now a [`addPermissionObserver`](https://documentation.onesignal.com/docs/cordova-sdk#section--addpermissionobserver-) and [`addSubscriptionObserver`](https://documentation.onesignal.com/docs/cordova-sdk#section--addsubscriptionobserver-) so you can pass in a function to response to these events as well.

These were added in the Cordova 2.1.0 SDK release.
