### ISSUE TITLE
When running on iOS 11, the handleNotificationOpened callback doesn't fire.

### ISSUE THREAD

**Issue by whiterook6** [OneSignal/OneSignal-Cordova-SDK#403]
Edit: since posting this bug, I have been able to reproduce the issue personally. I've updated this post accordingly.

**Description:**

For iOS 11 users, a notification can successfully start the app but **no callback is called**, and the **click event isn't set in the onesignal report screen** (See screenshot below.) I am able to reproduce the error on our iOS 11 test phone, but not on Android devices or any iOS devices running 10 or lower.

The issue **does not occur when the app is running** in the foreground or background and the push notification is received. Only when the app has been closed. The issue **has never occurred on any android device**.

Are there settings or permissions in iOS that would prevent the callback from being fired?

**Click not being registered**

![screen shot 2018-08-02 at 11 23 02 am](https://user-images.githubusercontent.com/5151965/43602991-7c741ccc-9646-11e8-9aa5-20dc2ac80390.png)

That push notification **was tapped by the user, and did successfully open the app**. However, the handleNotificationCallback **did not fire**.

My code (run on app startup):

```
let service = this;
let one_signal_api_key = this.client_config.one_signal_api_key;

document.addEventListener("deviceready", () => {
	let notification_opened_callback = (json_data) => {

		let redirect = this.get_redirect(json_data)
		if (redirect){
			service.$location.url(redirect);
			service.$window.location.href = service.$location.absUrl(); // should send the user to a specific view in the app
		}
	};

	let iOSSettings = {
		kOSSettingsKeyAutoPrompt: true,
		kOSSettingsKeyInAppLaunchURL: false,
	};

	window.plugins.OneSignal
		.startInit(one_signal_api_key)
		.handleNotificationOpened(notification_opened_callback)
		.iOSSettings(iOSSettings)
		.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
		.endInit();
});
```

**Debugging**
I am able to attach to safari debugging early enough to watch debug messages:

When the callback works, on lower iOS:

![screen shot 2018-08-07 at 11 41 53 am](https://user-images.githubusercontent.com/5151965/43910789-9c711a18-9bb2-11e8-8f5a-7f43d4ac9ced.png)

When the callback doesn't work, on iOS 11 devices:

![screen shot 2018-08-07 at 11 35 19 am](https://user-images.githubusercontent.com/5151965/43910761-91558952-9bb2-11e8-8b88-24f3ad9a7274.png)

**Environment**
Cordova SDK:
cordova 8.0.0

Plugins:
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 2.3.1 "Contacts"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-ios-microphone-permissions 1.0.0 "iOS Permissions"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.1.2 "OneSignal Push Notifications"
phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"

**Steps to Reproduce Issue:**
Run the project on iOS 11.

**Comment by Nightsd01** [comment]
@whiterook6 This would be a somewhat difficult issue for us to debug since we are not seeing reports of this from other users and you have been unable to reproduce it yourself.

How do you know that the callback is not getting called, is it because they say they tapped the notification and it didn't redirect to the correct URL?

There could me multiple things causing this. For example, your `listener` isn't getting added quickly enough in your app lifecycle, or there is an error parsing the redirect from JSON, or the URL itself is invalid, or 1,000 other things.

Without more information, it is _very_ difficult to help. Please let me know if you can post more data.

I would recommend adding analytics to your app (ie. Fabric/Answers) so that you can get back some debugging information about sessions where this occurs.

**Comment by whiterook6** [comment]
Thanks for the quick reply. I know I'm grasping at straws. I'm mostly trying to learn how a PN triggers the callback, and under which situations it might skip the callback.

"How do I know that the callback isn't being called?"

I can only go off of the testing I've done with users who've reported no redirect occurring. When I send a PN to a user named Bryon, for example, and Bryon doesn't have the app open, and taps the PN, it opens the app but does nothing else. When I send the exact same PN to myself, it opens the app and navigates to the correct internal page. I'm very confident the PN is being sent from our panel properly and is properly formatted with correct additional data.

What happens if the listener isn't added quickly enough? Are there settings that would prevent an iOS from accessing the push notification?

I'm also concerned about the zero percent click recording. The app is being opened by the push notification, so the user is tapping it. However, the one signal dashboard shows the PN isn't clicked. Under what situations could that happen? Is that a known result of an iOS app rejecting a PN for some reason? (I don't know much about how the OS handles PNs, sorry.)

I have seen the listener get added late in the app lifecycle (for example, after going through a login) and then the PN is processed properly.

Thanks again for the help.

**Comment by Nightsd01** [comment]
@whiterook6 I would like to be able to look at the specific details of your case, can you contact OneSignal support (open the https://www.onesignal.com dashboard) and click the ? button to launch a support chat ticket.

**Comment by whiterook6** [comment]
I see. So, the push notification should be held until the library's callback is initialized, is that correct? I believe I have seen that happen -- if I wait for a user to log in, for example, then register the callback, normally it does work. That would suggest it's not a delay in initialization that's causing the issue.

I will open a support chat ticket, thanks.

**Comment by whiterook6** [comment]
With @Nightsd01 's help I found I was on the wrong version of the plugin. `cordova plugin update onesignal-cordova-plugin` and `cordova plugin add onesignal-cordova-plugin` only ever installed version 2.1.2 for me. Manually adding version 2.4.2 fixed the callback issue on iOS 11.
