### ISSUE TITLE
clearOneSignalNotifications works on Android but not in iOS

### ISSUE THREAD

**Issue by lscarneiro** [OneSignal/OneSignal-Cordova-SDK#404]
Hey guys,

I have an ionic project successfully running both in Android and iOS receiving push through OneSignal with no problem.

I just noticed that clearOneSignalNotifications() function is not working in iOS, but on Android works fine.

On iOS I can handle received and opened notifications without a problem, just the clearOneSignalNotifications() that I call eventually, didn't work.

Can you guys give me a hint on where to look?

Just to make it clear, on iOS I don't get any error running clearOneSignalNotifications(), it just doesn't remove the notifications from Notification Center.

```
Ionic:

   ionic (Ionic CLI)  : 4.0.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 5.0.8
   NodeJS            : v9.11.1 (/usr/local/Cellar/node/9.11.1/bin/node)
   npm               : 5.6.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

```
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 2.2.0 "Facebook Connect"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.2 "Cordova sqlite storage plugin"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"
```

Running on 
Android 6
iOS 11.4.1 on iPhone 6

**Comment by jkasten2** [comment]
@lscarneiro `clearOneSignalNotifications` is currently only implemented for Android right now. I'll mark this as an improvement

**Comment by lscarneiro** [comment]
So there's no way to clean up the notifications via code on iOS with the current API?

**Comment by jkasten2** [comment]
@lscarneiro Not currently, all iOS notifications can be cleared however if you set the badge value to 0 with another Cordova plugin

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
