### ISSUE TITLE
Error on building Ionic Project

### ISSUE THREAD

**Issue by uda1099** [OneSignal/OneSignal-Cordova-SDK#408]
**Description:**

OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:+' -> 27.+ to prevent compile errors! Recommend updating your project's compileSdkVersion!

**Environment**

Cordova Version => 8.0.0

com-sarriaroman-photoviewer 1.1.16 "PhotoViewer"
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.8.4 "LocalNotification"
cordova-plugin-music-controls 2.1.4 "MusicControls"
cordova-plugin-nativegeocoder 3.1.2 "NativeGeocoder"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.0 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
onesignal-cordova-plugin 2.4.1 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1. Add the onesignal-cordova-plugin to your project
2. Try to run "ionic cordova build android --debug --minifyjs --minifycss --optimizejs"

**Anything else:**

:app:preDebugBuild
OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:+' -> 27.+ to prevent compile errors! Recommend updating your project's compileSdkVersion!
:app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find any version that matches com.google.firebase:firebase-measurement-connector:[10.2.1,12.1.0[.
  Versions that do not match:
      17.0.0
      16.0.0
      15.0.0
  Required by:
      project :app > com.onesignal:OneSignal:3.9.1 > com.google.firebase:firebase-messaging:17.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

**Comment by jkasten2** [comment]
@uda1099 We fixed this in an updated recently. Can you try removing and re-adding the android platform to get a clean build?
```
ionic cordova platform rm android
ionic cordova platform add android
```

**Comment by uda1099** [comment]
Still nothing...
That's the code:

`android.defaultConfig {
  manifestPlaceholders = [
    onesignal_app_id: '', // Use from js code
    onesignal_google_project_number: 'REMOTE'
  ]
}

// Required for Android Support Library 26.0.0+ and Google Play services 11.+
repositories {
  maven { url 'https://maven.google.com' }
}

// Adding Onesignal-Gradle-Plugin to align gms, android support library, and firebase
//   dependencies between other plugins.
// Source for Onesignal-Gradle-Plugin: https://github.com/OneSignal/OneSignal-Gradle-Plugin
buildscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2/'}
  }
  dependencies {
    classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.2, 0.99.99]'
  }
}
apply plugin: com.onesignal.androidsdk.GradleProjectPlugin


// Local testing
// buildscript {
//   repositories {
//     maven { url uri('file:/full/paht/to/maven/repo/') }
//   }
//   dependencies {
//     classpath 'com.onesignal:onesignal-gradle-plugin:[0.10.0, 0.99.99]'
//   }
// }
// apply plugin: com.onesignal.androidsdk.GradleProjectPlugin`

**Comment by jkasten2** [comment]
@uda1099 Sorry for the delay, I tried testing with a cordova project with all the plugins and exact versions you listed but still not able to reproduce this issue.

Can you try removing the android platform and re add it? Might be some older config in your project.

If this does not help can you try reproducing this issue in a new project and attach it here?
