### ISSUE TITLE
can not get background notification data on notification received without notification opened.

### ISSUE THREAD

**Issue by mdarshath** [OneSignal/OneSignal-Cordova-SDK#409]
**Description:**

How to get background notification data on notification received without notification opened or app opened.
i want to store the received notification data into app local storage for all notification example cleared notifcation, tapped notification.

**Environment**

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v7.8.0
    npm               : 4.2.0
    OS                : Windows 7

    "onesignal-cordova-plugin": "^2.3.2",  "@ionic-native/onesignal": "^4.6.0",

**Comment by Nightsd01** [comment]
@mdarshath You can accomplish this by implementing the Notification Service Extension (for iOS) and the Notification Extender Service (for Android). However you would have to write native code (ObjC/Swift for iOS and Java for Android).

You would have to use an App Group to allow for data to be shared between the extension service and the main app (you can follow [these instructions](https://documentation.onesignal.com/docs/ios-sdk-setup) to set up the Extension Service and the App Group).

**Comment by rodolfopatane** [comment]
> @mdarshath You can accomplish this by implementing the Notification Service Extension (for iOS) and the Notification Extender Service (for Android). However you would have to write native code (ObjC/Swift for iOS and Java for Android).
> 
> You would have to use an App Group to allow for data to be shared between the extension service and the main app (you can follow [these instructions](https://documentation.onesignal.com/docs/ios-sdk-setup) to set up the Extension Service and the App Group).

This implementation never be included in Cordova SDK ?
