### ISSUE TITLE
Dependency collision in Gradle when updating to OneSignal-Cordova 2.4.2

### ISSUE THREAD

**Issue by whiterook6** [OneSignal/OneSignal-Cordova-SDK#413]
**Description:**
Since updating to 2.4.2, our Android builds fail in the final stage with the following error:

```
FAILURE: Build failed with an exception.
>
> * What went wrong:
> Execution failed for task ':transformClassesWithDexForArmv7Release'.
> > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/auth/api/signin/internal/zzo;
```

Googling for this error leads me to believe there is now a dependency collision between some other plugin or library and OneSignal-Cordova related to com.google.android.gms.auth.whatever. I am unable to determine where the collision is, where the conflicting versions are, or how to resolve them. 

We have added a build-extras.gradle file to our project to resolve a previous dependency collision:

```
configurations.all {
	resolutionStrategy {
		force 'com.android.support:support-v4:27.1.0'
		force 'com.google.android.gms:play-services-auth:11.8.0+'
		force 'com.google.android.gms:play-services-identity:11.8.0+'
		force 'com.google.android.gms:play-services-gcm:11.8.0+'
		force 'com.google.android.gms:play-services-location:11.8.0+'
	}
}
```

**Environment**

Cordova SDK: 7.1.0
Cordova Plugins:

```
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 2.3.1 "Contacts"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.5 "Device"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-googleplus 5.1.1 "Google SignIn"
cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.2 "OneSignal Push Notifications"
phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"
```

All of the search results describe modifying the gradle files or build steps, which we don't really touch since we're using cordova anyways. Which dependencies have changed since 2.1.2 that could cause this collision?

**Comment by jkasten2** [comment]
@whiterook6 You are correct that there is more than one plugin in your project including the java class `com.google.android.gms.auth`. This normally shouldn't happen as this plugin uses [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) to align version dependencies.

Can you try updating to the latest version of Cordova as well as the Android Cordova platform?

Another thing that will help us pin point the issue is if you can produce the issue with a few other Cordova plugins as possible and let us know which one breaks your project. Then can you run the following and share it's output?
```
cd platforms/android
./gradlew app:dependencies --info
```

**Comment by Nightsd01** [comment]
Closing issue due to no response, @whiterook6 if you are still having this problem please reply and we'll reopen the issue and help investigate.
