### ISSUE TITLE
dova -v

### ISSUE THREAD

**Issue by roberto-carraro** [OneSignal/OneSignal-Cordova-SDK#417]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@roberto-carraro Hello, closing this issue as it looks like it was opened by mistake. If not, please create a new issue with your details and we can take a look
