### ISSUE TITLE
Ionic 4 OneSignal not installing.

### ISSUE THREAD

**Issue by sadiqmmm** [OneSignal/OneSignal-Cordova-SDK#420]
ionic cordova plugin add onesignal-cordova-plugin
npm install --save @ionic-native/onesignal

**Error:**
npm WARN @ionic-native/onesignal@4.12.2 requires a peer of @ionic-native/core@^4.11.0 but none is installed. You must install peer dependencies yourself.

npm WARN @ionic-native/onesignal@4.12.2 requires a peer of rxjs@^5.5.11 but none is installed. You must install peer dependencies yourself.

**Comment by pj-gomez** [comment]
Hi @sadiqmmm , I just had the similar problem with the `appversion` plugin, with the exact same missing dependency warnings and some more. 
Manually removing the `node_modules`, `www` and `plugins` folders and running `npm install` from scratch solved the issue.

Hope that helps

**Comment by JavChz** [comment]
Same problem. Can use with Ionic 4

ERROR in node_modules/@ionic-native/onesignal/index.d.ts(2,10): error TS2305: Module '"/home/javier/Dev/RaiseTech/Cuponera/app/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

**Comment by BadiuAlexandru** [comment]
@JavChz  to solve your error, I instaled rxjs-compat 

But now I have a new problem : 

`Uncaught TypeError: Object(...) is not a function
    at index.js:739
    at Object../node_modules/@ionic-native/onesignal/index.js (index.js:1021)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ts (app.component.ts:15)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (environment.ts:17)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)`

**Comment by Klerith** [comment]
> @JavChz to solve your error, I instaled rxjs-compat
> 
> But now I have a new problem :
> 
> `Uncaught TypeError: Object(...) is not a function at index.js:739 at Object../node_modules/@ionic-native/onesignal/index.js (index.js:1021) at __webpack_require__ (bootstrap:81) at Object../src/app/app.module.ts (app.component.ts:15) at __webpack_require__ (bootstrap:81) at Object../src/main.ts (environment.ts:17) at __webpack_require__ (bootstrap:81) at Object.0 (main.ts:12) at __webpack_require__ (bootstrap:81) at checkDeferredModules (bootstrap:43)`

Same here...

**Comment by jkasten2** [comment]
It seems `@ionic-native/onesignal@4.12.2` is using an older version of `rxjs` but adding `rxjs-compat` should be all you need.

I am not sure why your running into this 2nd error after adding `rxjs-compat`. Can you open an issue in the repo below with the error you are seeing now with all the original details?
https://github.com/ionic-team/ionic-native/issues

**Comment by jkasten2** [comment]
Closing this issue as this issue is related to Ionic / rxjs and not this plugin.
