### ISSUE TITLE
overwrite Sendtag data

### ISSUE THREAD

**Issue by AbbasTallaq** [OneSignal/OneSignal-Cordova-SDK#421]
Hi,
I have question, 
Am running a for loop for sendTag function for am tagging the  a player to multiple segments that I have created. 
however if the length of the loop is 2 array {1,2} , it should send two request for the tag for 2 segments, the player will be tagged to segment 1 and 2, but what happened is the player tagged only to 2 , 1 got overwrite by 2
sendtag is working always for the last one, 

how  can I resolve it, I have also set a timeout in loop still it overwrite the data.

**Comment by Nightsd01** [comment]
Requests to `sendTags` get batched over a few seconds. Also, it’s basically a hash map. If you set values for the same key, it’s going to overwrite the previous value.

**Comment by AbbasTallaq** [comment]
Hi,
you're absolutely right, I have change the id of each segment,and it got works,
