### ISSUE TITLE
ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#422]
**Description:**
Hi, we've just refactored our code to handle GDPR consent and are getting this error now. Until now we have had OneSignal working well in test systems. We're trying to move from another Push provider.

As part of the refactoring of code, we've moved anything to do with OneSignal to after we get consent from the user to store their data, if we never get any consent we never call the OneSignal registration code at all.

**Environment**
1. onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"

2. com.jcesarmobile.IDFVPlugin 1.0.0 "Identifier For Vendor Plugin"
com.rwillett.cordova.plugin.keychainutil 2.0.1 "KeyChain Plugin for Cordova iOS (No iCloud Sync)"
cordova-background-geolocation 2.10.1 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.2.1 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email 1.2.6 "EmailComposer"
cordova-plugin-insomnia 4.2.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-network-information 1.1.0 "Network Information"
cordova-plugin-splashscreen 5.0.1 "Splashscreen"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
london.jambuster.cordova.xcodedetector 0.1.2 "Xcode Detector"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notification

**Steps to Reproduce Issue:**
  1. Added onesignal-cordova-plugin 2.4.3 to project. 
  2. We have NOT initialized the plugin as we are awaiting consent from the user. 
  3. Wait for a few seconds (circa 10-15) and we get the error.
  4. We have set the OneSignal debug level to 6 and nothing appears from OnSignal until this error pops up. Which is what we would expect as we have NOT called the registration code at this stage.

```
2018-09-05 07:50:22.983 Jambuster[30132:224937] ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter
2018-09-05 07:50:22.984 Jambuster[30132:224069] ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
2018-09-05 07:50:22.984 Jambuster[30132:224069] ERROR: Encountered error during email registration with OneSignal: (null)
```

We can see that there is a similiar issue at

https://github.com/OneSignal/OneSignal-Unity-SDK/issues/77 

where we are requested to reopen the issue. Since this is Cordova rather than Unity we have opened it here.

**Comment by rwillett** [comment]
This doesn't seem to affect the working of OneSignal but is a worrying error message.

**Comment by Nightsd01** [comment]
@rwillett You should still be initializing our SDK. Just set user consent required to `true` and our SDK wont do anything. 

The problem is that our SDK automatically hooks in to some notification methods in iOS to make things easy for developers, so if you don’t initialize and don’t set user consent required to `true`, our SDK will print those errors because it assumes you’ve made a mistake.

**Comment by rwillett** [comment]
OK, thanks, I'll unpick todays work :(

**Comment by rwillett** [comment]
OK, We've unpicked the refactoring, refactored again (but properly), updated the use of kOSSettingsKeyAutoPrompt so we don't get alerts on top of alerts and it works :)

Perhaps we should have done the job right in the first place .... :)

Rob

**Comment by caipivara** [comment]
Im getting hte same error, how @rwillett did you solve it?

Um using:

```
            var iosSettings = {};
            iosSettings["kOSSettingsKeyAutoPrompt"] = true;
            iosSettings["kOSSettingsKeyInAppLaunchURL"] = false;
            
            var notificationOpenedCallback = function(jsonData) {
                console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
            };
            
            window.plugins.OneSignal.startInit("my-app-id")
            .handleNotificationOpened(notificationOpenedCallback)
            .iOSSettings(iosSettings)
            .inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.Notification)
            .setSubscription(true)
            .allowNotification(true)
            .setLogLevel({logLevel: 6, visualLevel: 6})
            .endInit();
```

**Comment by caipivara** [comment]
It looks like I had multiple errors...

1. I was runing that in 

```$(document).ready(function() {```

instead of 

```document.addEventListener('deviceready'``` 

2. I have 

```
.setSubscription(true)
.allowNotification(true)
.setLogLevel({logLevel: 6, visualLevel: 6})
```

in the Init of the plugin and it looks like it tries something before the `endinit()` is called and then I got that error...

Hope this helps somebody else.

**Comment by Athuli7** [comment]
Still facing this issue. Any ideas ?

**Comment by alexandermainz** [comment]
I had a similar issue (black screen and the same messages in the console).
I did the following to solve it:
- removed the TypeScript wrapper and all references in code: `npm uninstall @ionic-native/onesignal`
- placed the init code right at the beginning of the `platform.ready()` - method in app.component.ts, like in the SDK docs here [https://documentation.onesignal.com/docs/ionic-sdk-setup](https://documentation.onesignal.com/docs/ionic-sdk-setup) 
- removed the iOS plattform completely: `ionic cordova platform rm ios` /  `rm -rf platforms/ios`
- re-added iOS platform with newest release: `ionic cordova platform add ios@5.0.0`
- opened the XCode project and set the development team for signing
- `ionic cordova build ios`

**Comment by mluis** [comment]
I'm facing the same issue.

@caipivara how did you solved it?

**Comment by rwillett** [comment]
We resolved the issue by initiating the right place, e.g. early in the process. Thats all. We only refactored the code as we had GPRD consent to get and that was our issue to resolve.

We did not do remove typescript, remove any plugins, any platforms at all. Our error was cuased by us not initialising early enough in the process. Thats it.

**Comment by mluis** [comment]
I'm using the plugin on an Ionic V1 project, in the right place by the OneSignal's documentation but still getting the error.

**Comment by rwillett** [comment]
We're using Ionic V1 as well. 

Without seeing the code or more information, it's impossible to comment.

**Comment by NALAWALAMURTUZA** [comment]
bhaiya solution do.........

**Comment by LucasOAlves** [comment]
Little late but if someone is still have this erro. 

I faced this same error using ionic 4, to resolve i had to call the initialization process in app.component.ts just after the first platform.ready

**Comment by cgs** [comment]
Just ran into this in an old Ionic v1 app. The solution was to move the OneSignal init code to the very top of the init:

    $ionicPlatform.ready(function() {
        //OneSignal init stuff here

**Comment by gamanox** [comment]
This work for me ... Solution [here](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/495#issuecomment-501039729)
