### ISSUE TITLE
OneSignalPush.init blocked the main thread for 64ms. Plugin should use CordovaInterface.getThreadPool().

### ISSUE THREAD

**Issue by matthewborgcarr** [OneSignal/OneSignal-Cordova-SDK#423]
**Description:**

So I have a cordova Android and iOS app.

The app freezes and crashes after certain clicks only on Android, (iOS works perfectly fine).

refer to Logcat below

**Environment** -> config.xml

<content src="index.html" />
    <preference name="android-minSdkVersion" value="20" />
    <preference name="android-targetSdkVersion" value="23" />
    <preference name="android-installLocation" value="auto" />
    <preference name="orientation" value="portrait" />
    <preference name="permissions" value="none" />
    <preference name="phonegap-version" value="cli-8.0.0" />
    <preference name="fullscreen" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="webviewbounce" value="false" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="deployment-target" value="10.2.1" />
    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="StatusBarBackgroundColor" value="#122e4d" />
    <preference name="TopActivityIndicator" value="white" />
    
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>

    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <preference name="AllowBackForwardNavigationGestures" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <access origin="*" />
    <allow-intent href="market:*" />
    <allow-intent href="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-intent href="maps:*" />
    <allow-navigation href="*" />
    <config-file overwrite="true" parent="NSLocationAlwaysUsageDescription" platform="ios" target="*-Info.plist">
        <string>This app makes use of your location to show you businesses nearby.</string>
    </config-file>
    <config-file overwrite="true" parent="NSLocationWhenInUseUsageDescription" platform="ios" target="*-Info.plist">
        <string>This app makes use of your location to show you businesses nearby.</string>
    </config-file>
    <config-file overwrite="true" parent="NSCameraUsageDescription" platform="ios" target="*-Info.plist">
        <string>This app makes use of your camera to allow you to capture images.</string>
    </config-file>
    <config-file overwrite="true" parent="NSPhotoLibraryUsageDescription" platform="ios" target="*-Info.plist">
        <string>This app makes use of your photo library to allow you to upload images.</string>
    </config-file>
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-appversion" spec="^1.0.0" />
    <plugin name="cordova-plugin-file" spec="^4.3.3" />
    <plugin name="cordova-plugin-dialogs" spec="^1.3.4" />
    <plugin name="cordova-plugin-geolocation" spec="^4.0.1" />
    <plugin name="cordova-plugin-media" spec="^2.4.1">
        <variable name="MICROPHONE_USAGE_DESCRIPTION" value=" " />
    </plugin>
    <plugin name="cordova-plugin-network-information" spec="^1.3.4" />
    <plugin name="cordova-plugin-splashscreen" spec="^3.2.2" />
    <plugin name="cordova-plugin-console" spec="^1.1.0" />
    <plugin name="cordova-plugin-device" spec="^1.1.7" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.1" />
    <plugin name="cordova-plugin-screen-orientation" spec="^2.0.2" />
    <plugin name="info.protonet.imageresizer" />
    <plugin name="com.paypal.cordova.mobilesdk" spec="^3.5.0" />
    <plugin name="onesignal-cordova-plugin" spec="^2.4.3" />
    <plugin name="cordova-plugin-wkwebview-engine" spec="^1.1.4" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
    <plugin name="cordova-plugin-badge" spec="^0.8.7" />
    <plugin name="cordova-plugin-camera" spec="4.0.3" />
    <plugin name="cordova-plugin-google-analytics" spec="^1.8.6">
        <variable name="GMS_VERSION" value="11.0.+" />
    </plugin>
    <engine name="browser" spec="^5.0.3" />
    <engine name="ios" spec="^4.5.5" />
    <engine name="android" spec="^7.0.0" />

**Steps to Reproduce Issue:**

1. Launch the app
2. Navigate
3. After a couple of clicks, app crashes with the following error message from debug.

**Logcat output:**

2018-09-09 22:13:54.640 22133-22152/com.myhurryapp.mbc W/cr_CrashFileManager: /data/user/0/com.myhurryapp.mbc/cache/WebView/Crash Reports does not exist or is not a directory
2018-09-09 22:13:56.519 22133-22233/com.myhurryapp.mbc W/PluginManager: THREAD WARNING: exec() call to UniversalAnalytics.startTrackerWithId blocked the main thread for 34ms. Plugin should use CordovaInterface.getThreadPool().
2018-09-09 22:13:56.522 22133-22233/com.myhurryapp.mbc W/CordovaPlugin: Attempted to send a second callback for ID: UniversalAnalytics1797857167
    Result was: "Invalid action"
2018-09-09 22:13:56.595 22133-22233/com.myhurryapp.mbc W/PluginManager: THREAD WARNING: exec() call to OneSignalPush.init blocked the main thread for 64ms. Plugin should use CordovaInterface.getThreadPool().
2018-09-09 22:13:59.354 22133-22200/com.myhurryapp.mbc W/libEGL: EGLNativeWindowType 0x71c7a38010 disconnect failed
2018-09-09 22:14:02.350 22133-22200/com.myhurryapp.mbc W/libEGL: EGLNativeWindowType 0x71c7a37010 disconnect failed

**Comment by Nightsd01** [comment]
@matthewborgcarr That is just a warning, it would not be causing your crash. Startup time is something we have been actively working on optimizing, but it would not be causing your crash.

 When you say the "app freezes and crashes after certain clicks", I am not sure what that means? What does "certain clicks" mean?

When an app crashes you would be given a stack trace. Can you please post it...? Otherwise it's difficult to try and help you if we don't know what's actually causing the crash.

I'll be closing this issue due to lack of details, but when you can post a stack trace I'll be happy to reopen and help you investigate.
