### ISSUE TITLE
NotificationExtenderService only shows notification when app is open + other issues

### ISSUE THREAD

**Issue by sido420** [OneSignal/OneSignal-Cordova-SDK#424]
**Description:**

I managed to somehow make NotificationExtenderService work for me but the issue now is that the notifications only come in if the app is running. Also, its not respecting                 .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None) in my JS code anymore.

I dont see any notification (no logging even in NotificationExtenderService class).

**Environment**
Onesignal 2.4.3
Android 7.1.1

**Steps to Reproduce Issue:**

Nothing special, just added the background notification support code at https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding and it only seems to work when app is running. Nothing happens when app is not running.

**Anything else:**
Here is my use case. I have a messaging app that would send notifications when app is in the background only (.inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None was used for that). Onesignal was running fine with unmodified repo code for this.

However, there are cases where I want to send hidden messages to app when its not running at all. In order to do that I decided to use hidden notifications and extended NotificationExtenderService.

**Comment by sido420** [comment]
Plz hold off on this. I am making some changes and will update (if needed).

**Comment by sido420** [comment]
Can you at least answer the questions plz?

The reason for the first question is that by default the app is showing notifications even when its in focus. So, I need to make changes to code so that it does not do that when app is in focus.

The second is important because app is not automatically starting to process the background notification making them completely useless (at least for my use case).

**Comment by kanhachinu** [comment]
@sido420 I am using Onesignal Cordova to push notifications in my app. I am facing a similar problem where notifications are getting delivered only when the app is minimised.

Were you able to solve it somehow?

**Comment by sido420** [comment]
I somehow managed to resolve part of it but not sure what worked for me. 

I'm still having trouble getting the Activity object, so haven't managed to make much progress.

**Comment by jkasten2** [comment]
@sido420 There are a few ways to get the Android Activity. One way in Cordova is to call `this.cordova.getActivity()` from your class that extends from the `CordovaPlugin`. If you forking this plugin you can see an example in the line below.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/2.4.4/src/android/com/plugin/gcm/OneSignalPush.java#L170
Let us know if you still stuck on anything else.

@kanhachinu If you are not seeing a notification when the app is closed please follow this troubleshooting guide.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown
