### ISSUE TITLE
Modify URL for action buttons

### ISSUE THREAD

**Issue by loganthomison** [OneSignal/OneSignal-Cordova-SDK#425]
**Description:**
Is it possible to modify the URL that opens when selecting an action button within the InAppAlert? The LAUNCH URL value is empty and I'm able to pass in the desired URL via ADDITIONAL DATA. However, the default OK alert button also opens the desired URL. I would like to be able to have the OK button behave as normal when the LAUNCH URL is not specified and just dismiss the window. Alternatively, I would like to just disable the OK button or change the button text from OK to the desired button text and user the LAUNCH URL and forgo the entire ADDITIONAL DATA/Action Button step. Here is how it currently looks. 

[https://drive.google.com/file/d/13vcGEVgPaOHKNmDZitXjFFUlIsjLA6a6/view?usp=sharing](url)

The app I'm working with is in kiosk mode so I want to maintain the InAppAlert display

**Environment**
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"

cordova-plugin-admobpro 2.29.24 "AdMob Plugin Pro"
cordova-plugin-autostart 2.3.0 "Autostart"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-google-analytics 1.8.2 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
org.hygieiasoft.cordova.uid 1.1.0 "UID"

**Comment by Nightsd01** [comment]
@loganthomison Unfortunately this is not possible currently with our SDK. You would need to implement this in additional data with a custom URL opener.
