### ISSUE TITLE
Rich Notification Not Showing In IOS but Working fine in Android. 

### ISSUE THREAD

**Issue by Piashsarker** [OneSignal/OneSignal-Cordova-SDK#426]
I am working on an **Ionic Project** and did implement the notification service of one signal. Did receiving **Android & IOS** notifications.

Everything is working fine in android but  **Rich attachment** is not working in **IOS**. Did receive the Text & Title but image not showing.
 
I did same as the documentation says. 
https://documentation.onesignal.com/docs/ionic-sdk-setup

I did Add **Notification Service Extension** correctly but seems like it didn't work. 

**Below is my Notification Details.**

![image](https://user-images.githubusercontent.com/8473499/45596928-d0692080-b9e5-11e8-9477-c5ca2a1da9c2.png)

Any help would be appreciated. Thanks 

**Source:** 

      private prepareOneSignalNotification() {
        this.oneSignal.startInit('6ceb23d5-1d9f-4852-b0f6-XXXXX', '3139XXXXXXX');
    
        this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.InAppAlert);
    
        this.oneSignal.handleNotificationReceived().subscribe((data) => {
          // do something when notification is received
          console.log(data);
        });
    
        this.oneSignal.handleNotificationOpened().subscribe(() => {
          // do something when a notification is opened
        });
    
        this.oneSignal.endInit();
      }

**Ionic Documentation:** https://ionicframework.com/docs/native/onesignal/

**Comment by Nightsd01** [comment]
@Piashsarker There are several potential causes of this issue. 

1. Do push notifications with a badge count work?

2. Can you share your `NotificationService.m`? 

3. Is your extension service included in your main app's build settings as an embedded binary?

<img width="878" alt="screen shot 2018-09-19 at 6 27 14 pm" src="https://user-images.githubusercontent.com/8186991/45790442-b6278080-bc39-11e8-8cfc-e2b2bea3fa49.png">

**Comment by Nightsd01** [comment]
Please also make sure you have followed these troubleshooting steps as well:

https://documentation.onesignal.com/docs/notification-images-not-showing

**Comment by Nightsd01** [comment]
Actually, it looks like it's an issue with the Imgur link. Try using a link from a different website, it needs to be a _direct_ link to the file (I believe Imgur actually uses redirects and such)
