### ISSUE TITLE
callback is not a function. (In 'callback(state)', 'callback' is undefined)

### ISSUE THREAD

**Issue by ruchi-goyal** [OneSignal/OneSignal-Cordova-SDK#429]
**Description:**
I am using one signal plugin version-2.2.2, cordova version is 6.5.0 and secure-storage version is 2.6.3.
When building app, I am getting error "**callback is not a function, (In 'callback(state)', 'callback' is undefined)**"  **in internalCallBackProcessor in OneSIgnal.js**. 
Another error coming along with this is: **undefined is not an object (evaluating 'permissionSubscriptionState.permissionStatus')**
Push is working fine even after this. 
This is coming from the past one week. No new plugin add/update has been done.

**Anything else:**
**Stack trace (callback is not a function. (In 'callback(state)', 'callback' is undefined)):**
/var/containers/Bundle/Application/98C7659D-5801-4348-AE69-36715775814F/demo.app/www/plugins/onesignal-cordova-plugin/www/OneSignal.js in internalCallBackProcessor at line 138:13
/var/containers/Bundle/Application/98C7659D-5801-4348-AE69-36715775814F/demo.app/www/cordova.js in callbackFromNative at line 291:63
/var/containers/Bundle/Application/98C7659D-5801-4348-AE69-36715775814F/demo.app/www/cordova.js in nc2 at line 1041:39

**Stack trace (undefined is not an object (evaluating 'permissionSubscriptionState.permissionStatus')):**
/var/containers/Bundle/Application/98C7659D-5801-4348-AE69-36715775814F/b.well%20-%20Staging.app/www/cordova.js in callbackFromNative at line 291:63
/var/containers/Bundle/Application/98C7659D-5801-4348-AE69-36715775814F/b.well%20-%20Staging.app/www/cordova.js in nc2 at line 1041:39

Screenshot of console:
![screen shot 2018-09-20 at 6 51 40 pm](https://user-images.githubusercontent.com/22169708/45821809-b4c48980-bd07-11e8-93bc-1dea894ad319.png)

**Comment by Nightsd01** [comment]
@ruchi-goyal We have fixed multiple issues with `permissionSubscriptionState` - updating to 2.4.3 should fix your issue.
