### ISSUE TITLE
Can't install plugin on iOS - works on Android.

### ISSUE THREAD

**Issue by spinninghamster** [OneSignal/OneSignal-Cordova-SDK#430]
**Description:**
I am adding the plugin with on iOS and it doesn't work. Adding Android works without errors.

**Environment**
Using Cordova. (Android 7.1.0 and iOS 4.5.5).

**Steps to Reproduce Issue:**
`cordova platform ios`

**Anything else:**

Here is the command line error:

```
Installing "onesignal-cordova-plugin" for android
Android Studio project detected
Subproject Path: CordovaLib
Subproject Path: app
Installing "onesignal-cordova-plugin" for ios
apple-ios version check failed ("/Users/spinninghamster/Code/Live/Apps/app/platforms/ios/cordova/apple_ios_version"), continuing anyways.
apple-xcode version check failed ("/Users/spinninghamster/Code/Live/Apps/app/platforms/ios/cordova/apple_xcode_version"), continuing anyways.
Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/spinninghamster/Code/Live/Apps/app/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:87313) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: pod: Command failed with exit code 31
(node:87313) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Installed plugins:

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-open-native-settings 1.5.1 "Native settings"
cordova-plugin-buildinfo 2.0.2 "BuildInfo"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.4.4 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.7.0 "Toast"
cordova.plugins.diagnostic 4.0.5 "Diagnostic"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
```

**Comment by Nightsd01** [comment]
@spinninghamster looks like a pod issue. Can you try running `pod install` directly?

**Comment by spinninghamster** [comment]
Confirmed. Fixed it by updating cocoapods :)

**Comment by whiterook6** [comment]
I'm getting the same error. I'm using xcode 9.4, cordova 7.1.0, cordova-ios 4.5.1, and the following plugins:

- cordova-plugin-camera 2.4.1 "Camera"
- cordova-plugin-compat 1.2.0 "Compat"
- cordova-plugin-contacts 2.3.1 "Contacts"
- cordova-plugin-crop 0.1.0 "CropPlugin"
- cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
- cordova-plugin-device 1.1.5 "Device"
- cordova-plugin-facebook4 1.7.4 "Facebook Connect"
- cordova-plugin-file 4.3.3 "File"
- cordova-plugin-file-transfer 1.6.3 "File Transfer"
- cordova-plugin-geolocation 2.4.3 "Geolocation"
- cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
- cordova-plugin-googleplus 5.1.1 "Google SignIn"
- cordova-plugin-inappbrowser 1.3.0 "InAppBrowser"
- cordova-plugin-ios-microphone-permissions 1.0.0 "iOS Permissions"
- cordova-plugin-splashscreen 3.2.2 "Splashscreen"
- cordova-plugin-whitelist 1.3.3 "Whitelist"
- onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
- phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"

When I run `cordova platform add ios`, I get this message:

    Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 31
      at ChildProcess.whenDone (./platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:885:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
    Error: pod: Command failed with exit code 31

I've run `sudo gem install cocoapods` so I think it's up to date. Any thoughts?
