### ISSUE TITLE
DO NOT DISTURB is enabled for the app?

### ISSUE THREAD

**Issue by sido420** [OneSignal/OneSignal-Cordova-SDK#431]
**Description:**

Is there any way to figure out if DO NOT DISTURB is enabled for the app? Also, if the app has been disabled in power management programs such as Autostart Manager in ASUS devices? 

This is a very important feature for hidden notifications so as to be able to display alerts in apps.

**Environment**
1. What version of the Cordova SDK are you using? OneSignal-Cordova-SDK-2.4.3

**Steps to Reproduce Issue:**
A question

**Comment by sido420** [comment]
I found the following links:
https://developer.android.com/reference/android/Manifest.permission#ACCESS_NOTIFICATION_POLICY 
https://stackoverflow.com/questions/31862753/android-how-to-turn-on-do-not-disturb-dnd-programmatically
https://stackoverflow.com/questions/31387137/android-detect-do-not-disturb-status

**Comment by Nightsd01** [comment]
Currently our SDK does not support this. If you implement it, you'd have to do it natively for both platforms, but it looks possible.
