### ISSUE TITLE
OneSignal OSX platform support?

### ISSUE THREAD

**Issue by theparmis** [OneSignal/OneSignal-Cordova-SDK#433]
Hello everyone,
I just looking for OneSignal cordova osx platform?
Is there any way to use OneSignal on mac apps?

Thanks!

**Comment by jkasten2** [comment]
@theparmis OneSignal does not currently have a macOS native SDK either so support would only come to Cordova after this.

OneSignal's dashboard and backend does support macOS push notifications so if you can register the token with another plugin or your own native code then tokens can be added by following this guide.
https://documentation.onesignal.com/docs/macos-app-sdk-setup
