### ISSUE TITLE
window.plugins.OneSignal.getIds doesn't seem to work with provideUserConsent() on Android

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#434]
**Description:**
We are trying to get our Android application working with setting the GDPR consent. We have the same code working successfully with IOS.

The logic of the code is that we initialise the OneSignal SDK at the very first run of the application BUT we pass true to setRequiresUserPrivacyConsent. Since this is the very first run of the application the user cannot have have provided consent. 

```            
window.plugins.OneSignal.setRequiresUserPrivacyConsent(true); 
```

We then pop up a window asking for the user to provide consent, for testing we allow consent and then call

```
        window.plugins.OneSignal.provideUserConsent(value); 
```

value is set to true and we confirm this in our debug logging. 

We then carry on starting the application up, we generate some unique UUID's for our own use and finally we call 
```
window.plugins.OneSignal.getIds ( function...) 
```
to get the OneSignal ID that we store in our database and use to generate notifications.

The problem is that the getIDs function never returns on Android on the first run. The getIDs function appears to work well on IOS.

If we inspect the debug output 
```
21:22:05.401 utilities.js:82 Notifications.IntialiseOneSignal Started
21:22:05.465 utilities.js:82 We do NOT have GDPR consent
21:22:05.469 utilities.js:82 Notifications.IntialiseOneSignal finished
21:22:05.470 utilities.js:82 DoUserSetup: checkIfShowGDPRForm = true
21:22:05.470 utilities.js:82 ShowGDPRConsentForm called
21:22:05.477 utilities.js:82 ShowGDPRConsentForm providedConsent = false
21:22:27.581 utilities.js:82 SetGDPRConsent: value = 'true'
21:22:27.583 utilities.js:82 CloseWhatsNewModal called
21:22:27.587 utilities.js:82 ProvideGDPROneSignalUserConsent: value = true
21:22:27.594 utilities.js:82 ContinueApplicationLoad called: GDPRConsent = true
21:22:27.595 utilities.js:82 CompleteNotificationRegistration service called
21:22:27.596 utilities.js:82 CompleteNotificationRegistration started: GDPRConsent = true
21:22:27.612 utilities.js:82 ContinueApplicationLoad ended
21:22:27.630 utilities.js:82 RegisterAndGetUUIDSuccess: Called uuid = 2816c3ce-b1a4-5686-3599-060706714618/JFL1-0/android_app
21:22:27.643 utilities.js:82 SetUpNotificationIncrementSuccess called: value = {
  "uuid": "2816c3ce-b1a4-5686-3599-060706714618/JFL1-0/android_app",
  "notificationId": 1
}
21:22:27.645 utilities.js:82 RegisterAndGetNotificationIDS called with UUID='2816c3ce-b1a4-5686-3599-060706714618/JFL1-0/android_app'
21:22:27.646 utilities.js:82 RegisterAndGetOneSignalNotificationIDS called. UUID=2816c3ce-b1a4-5686-3599-060706714618/JFL1-0/android_app
21:22:27.648 utilities.js:82 RegisterAndGetOneSignalNotificationIDS: GDPRConsent = true
21:22:27.649 utilities.js:82 RegisterAndGetOneSignalNotificationIDS: Calling window.plugins.OneSignal.getIds
21:22:27.651 utilities.js:82 Returning from RegisterAndGetOneSignalNotificationIDS with deferred promise
```
We can see that at 21:22:27.587 we call ```   window.plugins.OneSignal.provideUserConsent(true);``` 

but at the 21:22:27.649 when we call ```window.plugins.OneSignal.getIds()``` it never returns. 

When we inspect the code for this
```
            var GDPRConsent = LocalStorage.Get("GDPRConsent");

	    if (debugRegisterAndGetOneSignalNotificationIDS)
                ConsoleLog("RegisterAndGetOneSignalNotificationIDS: GDPRConsent = " + GDPRConsent);

            if (GDPRConsent === true)
            {
                if (debugRegisterAndGetOneSignalNotificationIDS)
                    ConsoleLog("RegisterAndGetOneSignalNotificationIDS: Calling window.plugins.OneSignal.getIds");

                window.plugins.OneSignal.getIds(function(ids) {
                    if (debugRegisterAndGetOneSignalNotificationIDS)
                        ConsoleLog('RegisterAndGetOneSignalNotificationIDS: window.plugins.OneSignal.getIds: getIds: ' + JSON.stringify(ids));

                    notificationIDS = { userId: ids.userId , pushToken: ids.pushToken };

                    if (debugRegisterAndGetOneSignalNotificationIDS)
                        ConsoleLog("RegisterAndGetOneSignalNotificationIDS: notificationIDS = " + JSON.stringify(notificationIDS));

                    deferred.resolve({ uuid: UUID , ids: notificationIDS} );
                } , function () {
                    ConsoleLog("window.plugins.OneSignal.getIds appears to have failed");
                });
            } else
            {
                notificationIDS = { userId: UUID , pushToken: "" };
                deferred.resolve({ uuid: UUID , ids: notificationIDS} );
            }
```

it looks OK, but it never returns the very first time we run the application. If we kill the application and start it again, the function getIds returns the right values.
```
RegisterAndGetOneSignalNotificationIDS: Calling window.plugins.OneSignal.getIds
21:39:47.160 utilities.js:82 Returning from RegisterAndGetOneSignalNotificationIDS with deferred promise
21:39:47.166 utilities.js:82 RegisterAndGetOneSignalNotificationIDS: window.plugins.OneSignal.getIds: getIds: {"userId":"dd4d34fb-f3bf-4d8f-a2a7-523ac1d0368e","pushToken":"fiwGPuAlU-4:APA91bE0iBuPnlWl_mvFDc5qT4N1vQkpBDOF_0gbGkNmDOlhY1vYRqZduYwgFxAR7fG5hFl2MQU0vwf-tH5ivf_3nTIPow8HQ21puXxaMJWuV4ULwlJ-e71HHTjxol7WWwLdJmTpc2aC"}
21:39:47.167 utilities.js:82 RegisterAndGetOneSignalNotificationIDS: notificationIDS = {"userId":"dd4d34fb-f3bf-4d8f-a2a7-523ac1d0368e","pushToken":"fiwGPuAlU-4:APA91bE0iBuPnlWl_mvFDc5qT4N1vQkpBDOF_0gbGkNmDOlhY1vYRqZduYwgFxAR7fG5hFl2MQU0vwf-tH5ivf_3nTIPow8HQ21puXxaMJWuV4ULwlJ-e71HHTjxol7WWwLdJmTpc2aC"}
```

Our best guess is that the provideUserConsent(true) is working but the call to window.plugins.OneSignal.getIds() is coming so quick afterwards that its in a race condition. However that could be complete rubbish.

It would be nice if provideUserConsent was a promise that completed on success to validate this. 

We are using OneSignal 2.4.3 as we couldn't seem to get 2.4.4 to download at all. However after reading the release notes 2.4.4 seems all about IOS.

We also noted #228 but we know we are calling endinit () correctly.
Also #141 seems similar to our issue. 

We are using Android 8 on a Pixel XL phone. It's not rooted and is as standard as we can make it.
Node version: v9.2.0
Cordova version: 8.0.0
Installed platforms:
  android 6.4.0
  ios 4.5.4

**Comment by rwillett** [comment]
Futher update

We have put the call to ```window.plugins.OneSignal.getIds()``` in a timeout to 'push' it back and see if that avoids a race condition. It made no difference.

We've also tested this again on our IOS platform and we are getting very, very slow responses from ```window.plugins.OneSignal.getIds()```. In the region of 20-25 seconds to come back. 

On Android 8, ```window.plugins.OneSignal.getIds()``` doesn't come back at all.

**Comment by rwillett** [comment]
We are now getting ```window.plugins.OneSignal.getIds()``` returning on Android but it still takes a long time. We're expermenting with the GDPR consent to see if that has anything to do with this.

**Comment by jkasten2** [comment]
@rwillett I reviewed the source of our native Android SDK and this Cordova wrapper and wasn't able to find a cause where the callback to `getIds` won't fire as long as you are calling it after `window.plugins.OneSignal.provideUserConsent(true);`.

OneSignal has new functions, [`getPermissionSubscriptionState`](https://documentation.onesignal.com/docs#section--getpermissionsubscriptionstate-) and [`addSubscriptionObserver`](https://documentation.onesignal.com/docs#section--addsubscriptionobserver-) which we recommend migrating to.

You can call `window.plugins.OneSignal.setLogLevel({logLevel: 6, visualLevel: 0});` to enable verbose logging for OneSignal to see if you have any hanging network connections that could cause the issue.
https://documentation.onesignal.com/docs#section--setloglevel-

**Comment by rwillett** [comment]
Josh

Thanks for the update. We can see the getIds now returning but they are still taking a long time to return from the call to ```window.plugins.OneSignal.getIds()```. We are focussing on IOS for the moment.

We've already set the log level to the values you suggest and can't see anything untoward.

We've just tested this again and we called getIds at 2018-10-03 07:25:56
```
2018-10-03 07:25:56.631179+0100 Jambuster[34354:6349354] RegisterAndGetOneSignalNotificationIDS: Calling window.plugins.OneSignal.getIds
```

We get the response back at
```
2018-10-03 07:26:17.389668+0100 Jambuster[34354:6349508] DEBUG: mobileProvision: {
```

Thats a 21 sec wait, which seems wrong.

This only happens on the very first time we register the device with OneSignal. Subsequent calls return instantly. We're still investigating that.

We will also look at getPermissionSubscriptionState and addSubscriptionObserver to see if that helps.

**Comment by rwillett** [comment]
@jkasten2 

We can see the use of ```getPermissionSubscriptionState``` and ```addSubscriptionObserver```, but these are watching functions. I am assuming we still need to call ```window.plugins.OneSignal.setRequiresUserPrivacyConsent()``` and ``` window.plugins.OneSignal.provideUserConsent()``` to actually set permissions or is there a different way of doing this.

**Comment by jkasten2** [comment]
@rwillett `setRequiresUserPrivacyConsent` isn't required to use OneSignal at a technical level. However it might be required based on your privacy policy other legal factors to prompt users to accept.

`getPermissionSubscriptionState` will return the current state.
`addSubscriptionObserver` is a watch method so the callback will only fire if something changed.

@Nightsd01 Any ideas on the 21 sec delay @rwillett noted above on iOS before they see the `DEBUG: mobileProvision: {` entry?

**Comment by rwillett** [comment]
@jkasten2 

We need to use ```setRequiresUserPrivacyConsent``` as we have to get permission under GDPR.

Our logic is as follow. We have condensed different functions together and missed out loads of our code that we do to make this simple to follow.
```
	window.plugins.OneSignal
            .startInit(OneSignalId)
            .iOSSettings(iosSettings)
            .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
            .handleNotificationOpened(notificationOpenedHandler)
            .handleNotificationReceived(notificationReceivedHandler)
	    .endInit();

        // Test to see if user has already granted consent
       // If user hasn't granted consent then
       window.plugins.OneSignal.setRequiresUserPrivacyConsent(true);

      // Display a modal window asking for GDPR consent
      // Capture the consent (or not) and update OneSignal
     window.plugins.OneSignal.provideUserConsent(true);

     // Now we have consent, lets get the OneSignal pushtoken and other information
      window.plugins.OneSignal.getIds(function(ids) {
                    if (debugRegisterAndGetOneSignalNotificationIDS)
                        ConsoleLog('RegisterAndGetOneSignalNotificationIDS: window.plugins.OneSignal.getIds: getIds: ' + JSON.stringify(ids));

                    notificationIDS = { userId: ids.userId , pushToken: ids.pushToken };

                    if (debugRegisterAndGetOneSignalNotificationIDS)
                        ConsoleLog("RegisterAndGetOneSignalNotificationIDS: notificationIDS = " + JSON.stringify(notificationIDS));
                } , function () {
                    ConsoleLog("window.plugins.OneSignal.getIds appears to have failed");
                }); 
```

Our issue seems to be that the function in ```window.plugins.OneSignal.getIds``` takes so long to return. We have also looked at ```window.plugins.OneSignal.getPermissionSubscriptionState()``` but haven't got that working.

This very long delay seems to happen the very first time we call this from out app. We delete the app from the phone, we install it and ask for GDPR consent to simulate the user downloading it.

We have been using OneSignal for a few months until now and the call to ```window.plugins.OneSignal.getIds()``` has been pretty much instantaneous so we figured there was something to do with the very first time we provide consent. 

Previously all this code was one function as we had no need to separate it out. We have two (at least) options.

1. We can stop the initialisation of the OneSignal to the very end of the chain until after we have GDPR consent.

2. We can break the logic of our code and accept that the ```window.plugins.OneSignal.getIds()``` takes a long time and add more promises in (sigh).

We'll try option one, this means that can drop the ``` window.plugins.OneSignal.setRequiresUserPrivacyConsent(true)```  and ```window.plugins.OneSignal.provideUserConsent()```. This is probably the quickest to test.

**Comment by rwillett** [comment]
As previously reported, the very first time we run this, it takes around 20 secs for the OneSignal userId to be returned. 

We've looked at our code from some time ago and are wondering if this is actually how OneSignal has always worked with the OneSignal userId. Our production version of the code has a short video introduction to how our app works which takes longer than 20 seconds. This short introduction is only run the first two times the app is started after being downloaded. If this was the case, we would never have noticed the 20+ sec delay in getting the tokens.

As we are doing development, we don't display the video and so we notice this 21+ sec delay.

We have also tested our app for the second and third runs. We stop the app and restart it and OneSignal returns the userId immediately.

We think that the first time the userId is generated it takes some time to come back from OneSignal. Is this a reasonable hypothesis?

Rob

**Comment by rwillett** [comment]
@rwillett  @Nightsd01 

We have spent most of the day looking at this and we now think there is an issue with ```setRequiresUserPrivacyConsent()``` combined with ```provideUserConsent()``` for the first time you run the application. 

If we call ```setRequiresUserPrivacyConsent(true)``` and then call ```provideUserConsent(true)``` for the very first time after you install the application, we can see that sometimes the userId is never returned or sometimes the pushtoken is never returned though any of the watchers or ```getids```.

If we do not call ```setRequiresUserPrivacyConsent(true)``` and therefore not call ```setRequiresUserPrivacyConsent(true)``` we reliably get the right information. We can also see the OneSignal debugging returning the Apple pushtoken very early on.

We've commented out the ```setRequiresUserPrivacyConsent``` and ```provideUserConsent``` code and it work, add them back in and we can see issues.

We can post the (large) debug output to show this working and not working.

Rob

**Comment by rwillett** [comment]
The search for a solution continues...

We have checked the IOS version of the OneSignal SDK to see if there is any more information in there. https://documentation.onesignal.com/docs/ios-native-sdk#section--setrequiresuserprivacyconsent-

The IOS  SDK description for ```setRequiresUserPrivacyConsent()```is slightly different to the Cordova SDK description.

> For GDPR users, your application should call this method **before** initialization of the SDK. If you pass in true, your application will need to call provideConsent(true) before the OneSignal SDK gets fully initialized. Until this happens, you can continue to call methods (such as sendTags()), but nothing will happen.

It talks about calling ```setRequiresUserPrivacyConsent()``` BEFORE initialisation of OneSignal. We have ```setRequiresUserPrivacyConsent()``` after 

```
        window.plugins.OneSignal
            .startInit(OneSignalId)
            .iOSSettings(iosSettings)
            .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
            .handleNotificationOpened(notificationOpenedHandler)
            .handleNotificationReceived(notificationReceivedHandler)
            .endInit();

        window.plugins.OneSignal.setRequiresUserPrivacyConsent(true);                              
```

The docs in the OneSignal Cordova SDK do not mention this

> Allows you to delay the initialization of the SDK until the user provides privacy consent. The SDK will not be fully initialized until the provideUserConsent(true) method is called.

> If you set this to be true, the SDK will not fully initialize until consent is provided. You can still call OneSignal methods, but nothing will happen, and the user will not be registered for push notifications.

We've put ```setRequiresUserPrivacyConsent()``` before the initialisation ancd tested it.

It could be coincidence but we are getting a better response. 

When we have ```setRequiresUserPrivacyConsent()``` after the initialisation, we would often not get the userId or pushtoken returned. So far they have both been returned, BUT we only get userId 20+ seconds later.

To test this, we have deleted the app, run it from Xcode to install it and requested GDPR consent around 10 times. Each time it has worked, though there is still a 20+ second delay to get the OneSignal userId. 

We then put ```setRequiresUserPrivacyConsent()``` after the OneSignal init code and it failed to return the OneSignalUserId. we get the OneSignal pushtoken but not the userId.

Reverting back to ```setRequiresUserPrivacyConsent()``` before the init code then works.

It appears that ```setRequiresUserPrivacyConsent()``` needs to be called before anything. Does this make sense?

Rob

**Comment by Nightsd01** [comment]
Hi Rob, sorry if our docs are not clear on this but yes it needs to be called before init. 

Also, the SDK will only register and get a user ID under 2 conditions:

1. The user just accepts push permission
2. 30 seconds pass. 

We do this to avoid unnecessary API calls. 

How/when are you prompting for permission?

**Comment by rwillett** [comment]
@Nightsd01 

Blast, that's take five days to resolve. Oh well, we now know the issue. We thought we were going mad as we kept getting inconsistent results.

As we are in the UK, we have to ask for explicit permission to store personal data. We pop up a window asking the user for consent. If they grant it, we then call ```window.plugins.OneSignal.provideUserConsent(true);```

This could take minutes as the user ignores the window or it might be quick. 

It would be illegal for us to do this in any other way. 

We will refactor the code to take this 20+ second delay into account.

**Comment by epetre** [comment]
> As previously reported, the very first time we run this, it takes around 20 secs for the OneSignal userId to be returned.
> 
> We've looked at our code from some time ago and are wondering if this is actually how OneSignal has always worked with the OneSignal userId. Our production version of the code has a short video introduction to how our app works which takes longer than 20 seconds. This short introduction is only run the first two times the app is started after being downloaded. If this was the case, we would never have noticed the 20+ sec delay in getting the tokens.
> 
> As we are doing development, we don't display the video and so we notice this 21+ sec delay.
> 
> We have also tested our app for the second and third runs. We stop the app and restart it and OneSignal returns the userId immediately.
> 
> We think that the first time the userId is generated it takes some time to come back from OneSignal. Is this a reasonable hypothesis?
> 
> Rob

We have the same issue.

**Comment by rwillett** [comment]
This is the behaviour and is not a bug according to OneSignal.
We got around the issue by running it in the background.

**Comment by rr-philips** [comment]
how did you end up running this in the background?

I'm working on getting the userId during an app update and i can't get it to fire unless the app is opened, and then it takes the 20+ seconds, like you've experienced. 

thanks!

**Comment by rwillett** [comment]
we just ran it as an asynchronous call and carried on doing other stuff until it came back. I've just looked at our code again and there's nothing very clever.

```
        window.plugins.OneSignal
            .startInit(OneSignalId)
	    .iOSSettings(iosSettings)
            .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
	    .handleNotificationOpened(notificationOpenedHandler)
            .handleNotificationReceived(notificationReceivedHandler)
            .endInit();

        window.plugins.OneSignal.addSubscriptionObserver(function (state) {
            if (debugIntialiseOneSignal)
            {
                ConsoleLog("*********************");
                ConsoleLog("IntialiseOneSignal: Push Subscription state changed: " + JSON.stringify(state , null , 2));
		ConsoleLog("*********************");
	    }

            var GDPRConsent = LocalStorage.Get("GDPRConsent") === true ? true : false;

            CompleteNotificationRegistration(GDPRConsent).then(function(value) {
                if (debugIntialiseOneSignal)
                    ConsoleLog("IntialiseOneSignal: Notifications.CompleteNotificationRegistration succeeded " + JSON.stringify(value , null , 2));
            } , function () {
                ConsoleLog("IntialiseOneSignal: Notifications.CompleteNotificationRegistration failed");
            });
        });
```

and
```
    function CompleteNotificationRegistration
        var debugCompleteNotificationRegistration = debugFalse || DEBUG_NOTIFICATIONS;
        var deferred = $q.defer();

        if (debugCompleteNotificationRegistration)
            ConsoleLog("CompleteNotificationRegistration started: GDPRConsent = " + GDPRConsent);

        function LogRegistrationDataToServerSuccess (value)
        {
            var debugLogRegistrationDataToServerSuccess = debugFalse || DEBUG_NOTIFICATIONS;
            var GDPRConsent = LocalStorage.Get("GDPRConsent");
            var whatAmI = WhatAmI("LogRegistrationDataToServerSuccess");
            var uuid = value.uuid;
            var ids = value.ids;

            if (debugLogRegistrationDataToServerSuccess)
                ConsoleLog("LogRegistrationDataToServerSuccess: All registered " + JSON.stringify(value , null , 2));

            if (debugLogRegistrationDataToServerSuccess)
            {
                ConsoleLog("LogRegistrationDataToServerSuccess: uuid = " + JSON.stringify(uuid));
                ConsoleLog("LogRegistrationDataToServerSuccess: IDS = " + JSON.stringify(ids));
            }

            RegisterWithServer(GDPRConsent , value);

            $rootScope.$broadcast('AddGDPRConsentEvent');

            if (debugLogRegistrationDataToServerSuccess)
                ConsoleLog("LogRegistrationDataToServerSuccess: Finishing");

            deferred.resolve(1);
        }

        function LogRegistrationDataToServerFailure () {
            ConsoleLog("LogRegistrationDataToServerFailure: called");
            deferred.resolve(0);
        }

     function RegisterAndGetUUIDSuccess(uuid) {
            var debugRegisterAndGetUUIDSuccess = debugFalse;

            if (debugRegisterAndGetUUIDSuccess)
                ConsoleLog("RegisterAndGetUUIDSuccess: Called uuid = " + uuid);

            // We need the UUID to do this.
            if (USE_WEB_SOCKETS)
            {
                WebSocket.Initialise(uuid);
            }

            RegisterAndGetNotificationIDS(uuid).then(LogRegistrationDataToServerSuccess ,
                                                     LogRegistrationDataToServerFailure);
        }

        function RegisterAndGetUUIDFailure() {
            ConsoleLog("UUID.RegisterAndGetUUID failed");
            deferred.resolve(0);
        }
        return deferred.promise;
    }
}

    function RegisterAndGetNotificationIDS (UUID) {
        var debugRegisterAndGetNotificationIDS = debugFalse;

        if (debugRegisterAndGetNotificationIDS)
            ConsoleLog("RegisterAndGetNotificationIDS called with UUID='" + UUID + "'");

        switch (NOTIFICATION_PROVIDER)
        {
            case "OneSignal": return RegisterAndGetOneSignalNotificationIDS(UUID);
        }
    }

    function RegisterAndGetOneSignalNotificationIDS(UUID) {
        var debugRegisterAndGetOneSignalNotificationIDS = debugFalse || DEBUG_NOTIFICATIONS;
        var GDPRConsent = LocalStorage.Get("GDPRConsent");
        var deferred;
        var whatAmI = WhatAmI("RegisterAndGetOneSignalNotificationIDS.RegisterAndGetOneSignalNotificationIDS");

        if (debugRegisterAndGetOneSignalNotificationIDS)
            ConsoleLog("RegisterAndGetOneSignalNotificationIDS called. UUID=" + UUID + " notificationProviderId = '" + notificationProviderId + "' notificationProviderPushToken = '" + notificationProviderPushToken + "'");

        deferred = $q.defer();

        // We have to call window.plugins.OneSignal.getPermissionSubscriptionState() first and continue in the callback.
        // This is because addSubscriptionObserver() only fires when we change a permission. If we start and stop the app
        // we haven't changed permission, therefore it never gets called. So we call getPermissionSubscriptionState, see if we have the right data
        // from this call
        window.plugins.OneSignal.getPermissionSubscriptionState(function(status) {
            if (debugRegisterAndGetOneSignalNotificationIDS)
            {
             	ConsoleLog("*******************");
                ConsoleLog("*******************");
                ConsoleLog("-");
                ConsoleLog("RegisterAndGetOneSignalNotificationIDS: getPermissionSubscriptionState = " + JSON.stringify(status , null , 2));
                ConsoleLog("-");
                ConsoleLog("*******************");
                ConsoleLog("*******************");
            }

            if (typeof status !== "undefined" && status && status.subscriptionStatus && status.subscriptionStatus.userId && status.subscriptionStatus.pushToken)
            {
                if (GDPRConsent)
                {
                    notificationIDS = { userId: status.subscriptionStatus.userId , pushToken: status.subscriptionStatus.pushToken};
                } else
                {
                    notificationIDS = { userId: "N/A" , pushToken: "N/A" };
                }

                if (debugRegisterAndGetOneSignalNotificationIDS)
                    ConsoleLog("notificationIDS = " + JSON.stringify(notificationIDS));

                deferred.resolve({ uuid: UUID , ids: notificationIDS});
            } else
            {
                notificationIDS = { userId: "N/A" , pushToken: "N/A" }

                if (debugRegisterAndGetOneSignalNotificationIDS)
                    ConsoleLog("notificationIDS = " + JSON.stringify(notificationIDS));

                deferred.resolve({ uuid: UUID , ids: notificationIDS});
            }
        });

        if (debugRegisterAndGetOneSignalNotificationIDS)
            ConsoleLog("Returning from RegisterAndGetOneSignalNotificationIDS with deferred promise");

        return deferred.promise;
    }
```

This is production code.

Rob

**Comment by rr-phillips** [comment]
@rwillett thank you! I wasn't sure if you meant "background" like while the app is closed or just an async call. Thanks for the reply and code!
