### ISSUE TITLE
Google Play Services Library Error

### ISSUE THREAD

**Issue by lonwi** [OneSignal/OneSignal-Cordova-SDK#436]
**Description:**

After updating the Google Play services to 13.2.80 on some of the devices (noticed that on few Android 5.1, 6.0, 7.0) I get

Google Play Services Library Error 

Could not register with FCM due to an issue with your AndroidManifest.xml or with 'Google Play services'.

**Environment**

Ionic:

   ionic (Ionic CLI)  : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.1 (cordova-lib@8.1.0)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 13 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.1.2
   NodeJS     : v6.11.4 (/usr/local/bin/node)
   npm        : 6.1.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4 Build version 9F1027a

ordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fingerprint-aio 1.3.8 "FingerprintAllInOne"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.4.0 "Cordova sqlite storage plugin"
onesignal-cordova-plugin 2.4.4 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1. Setup onesignal-cordova-plugin
2. Run in on a device android 6.0 with  Google Play services 13.2.80 (latest)

**Anything else:**

No crash, just notifications are not working anymore. Before the Google Play services update there was not problem

**Comment by lonwi** [comment]
The same version of the app (tired few versions of onesignal plugins) and without cordova-plugin-google-analytics works fine with an older version of Google Play services installed on this phone. When I factory reset it, so the Google Play services app is back to the older version it works without problems. Once I update it to the latest I get this is the error:

!!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)

Could not register with FCM due to an issue with your AndroidManifest.xml or with 'Google Play services'.
java.lang.RuntimeException: Package manager has died
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:139)
	at com.onesignal.GooglePlayServicesUpgradePrompt.isGMSInstalledAndEnabled(GooglePlayServicesUpgradePrompt.java:20)
	at com.onesignal.PushRegistratorAbstractGoogle.internalRegisterForPush(PushRegistratorAbstractGoogle.java:56)
	at com.onesignal.PushRegistratorAbstractGoogle.registerForPush(PushRegistratorAbstractGoogle.java:51)
	at com.onesignal.OneSignal.registerForPushToken(OneSignal.java:789)
	at com.onesignal.OneSignal.access$2000(OneSignal.java:80)
	at com.onesignal.OneSignal$4.onSuccess(OneSignal.java:871)
	at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:208)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:511)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:2183)
	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:134)
	... 8 more

I had a few reports from users with an older Android version that they are not receiving notifications. 
I have checked in onesignal admin panel and these devices have the same error "Google Play Services Library Error". On the other phone phones that I tested, there is no issue.

**Comment by jkasten2** [comment]
@lonwi Thanks for the details, it looks like `android.app.ApplicationPackageManager.getPackageInfo` is throwing due to the package manager being killed on the device. Most likely before OneSignal called this.

Can you look for "Package manager" or ApplicationPackageManager in your logcat before this message? You will need to make sure you don't have any filters for your package name etc. If you can provide a full logcat this will be helpful so we can check for any other events. If you don't want the full logcat public feel free to send it to OneSignal support and a link to this ticket.

**Comment by Nightsd01** [comment]
Closing due to no response - please respond to @jkasten2's message if you are still having this issue and we'll be happy to reopen and help investigate.
