### ISSUE TITLE
Multiple dex files define Lcom/google/android/gms/common/internal/zzb

### ISSUE THREAD

**Issue by artuska** [OneSignal/OneSignal-Cordova-SDK#437]
OneSignal plugin produces this error in Android Studio and stops building process:

```
Multiple dex files define Lcom/google/android/gms/common/internal/zzb
```

Tested with 2.4.3 and 2.4.4 versions of OneSignal plugin.

There was no such error until yesterday.

Cordova 7.1.0 and 8.1.1
Cordova Android 7.1.0 and 6.3.0
Android SDK Platform-Tools 28.0.3
Gradle 4.10.2
com.android.tools.build:gradle:3.2.0

Plugins:
cordova-plugin-console,
cordova-plugin-deeplinks,
cordova-plugin-device,
cordova-plugin-geolocation,
cordova-plugin-inappbrowser,
cordova-plugin-inapppurchase,
cordova-plugin-market,
cordova-plugin-network-information,
cordova-plugin-splashscreen,
cordova-plugin-statusbar,
cordova-plugin-vibration,
cordova-plugin-websocket,
cordova-plugin-whitelist,
cordova-plugin-facebook4,
cordova-social-ok,
cordova-social-vk,
cordova-hot-code-push-plugin,
onesignal-cordova-plugin,
yandex-appmetrica-plugin-cordova

**Comment by jkasten2** [comment]
@artuska Can you make sure you are using Cordova CLI 8.0.0 as well as cordova-android@7.0.0 or newer.

You can run `cordova info` to check this.

If you are up to date already then please run `cordova plugin list` so we can try reproducing the issue.

**Comment by artuska** [comment]
@jkasten2 updated my question with version info

**Comment by jkasten2** [comment]
@artuska The `WARNING: The onesignal-gradle-plugin MUST be before com.android.application!` warning should only be printing if you are using an Android Gradle Plugin (`com.android.tools.build:gradle`) older than 3.0.0. This is where this warning is thrown from
https://github.com/OneSignal/OneSignal-Gradle-Plugin/blob/0.11.2/src/main/groovy/com/onesignal/androidsdk/GradleProjectPlugin.groovy#L229-L230

Would it be possible to reproduce the problem in a new project and share the repo?

**Comment by artuska** [comment]
This error was caused by `cordova-social-ok` plugin. I think i fixed it by excluding GMS group:

```
implementation(project(path: ":cordova-social-ok:odnoklassniki-android-sdk")) {
    exclude group: "com.google.android.gms"
}
```
