### ISSUE TITLE
Can we call window.plugins.OneSignal.provideUserConsent() multiple times?

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#439]
**Description:**
We are trying to give our users the ability to change their minds with GDPR consent. 

This would allow them to refuse GDPR consent, so we then don't store any personal information. This is so often the way now in the UK. Hopefully the users will then change their minds as they see how good our application is and then grant us consent.

We now have our application working correctly with the GDPR methods, ```setRequiresUserPrivacyConsent()``` and ```provideUserConsent()```.

We also have ```window.plugins.OneSignal.addSubscriptionObserver()``` working and we can see the state changing.

We would expect to use ```window.plugins.OneSignal.provideUserConsent(true|false)``` to change GDPR consent. We would then expect to see the state change in ```window.plugins.OneSignal.addSubscriptionObserver()```.

We are calling ```window.plugins.OneSignal.provideUserConsent(true OR false)``` but we never see ```window.plugins.OneSignal.addSubscriptionObserver()``` OR  ```window.plugins.OneSignal.addPermissionObserver()``` come back with anything at all.

We have tried with resetting ```window.plugins.OneSignal.addSubscriptionObserver()``` after changing the user consent and NOT resetting ```window.plugins.OneSignal.addSubscriptionObserver()```, but to no avail. We have waited 30 seconds just in case that was the issue :)

Is the setting of the OneSignal privacy consent a single use item or can it be changed back and forth in a session? Do we need to reinitialise everything? Is this even possible?

Thanks

Rob

**Environment**

1. Cordova 8.0.01. 

2. Plugins

    com.jcesarmobile.IDFVPlugin 1.0.0 "Identifier For Vendor Plugin"
com.rwillett.cordova.plugin.keychainutil 2.0.1 "KeyChain Plugin for Cordova iOS (No iCloud Sync)"
cordova-background-geolocation 2.10.1 "BackgroundGeolocation"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.2.1 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email 1.2.6 "EmailComposer"
cordova-plugin-insomnia 4.2.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-network-information 1.1.0 "Network Information"
cordova-plugin-splashscreen 5.0.1 "Splashscreen"
cordova-plugin-sqlite-2 1.0.4 "SQLitePlugin"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"
london.jambuster.cordova.xcodedetector 0.1.2 "Xcode Detector"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"

3. There appears to be very little about on people using the privacy options in OneSignal. We have also read the IOS SDK documentation just in case :)

**Comment by Nightsd01** [comment]
@rwillett You can definitely retract user consent using `provideUserConsent(false)` later on. This will immediately stop the SDK from doing anything. The subscription/permission observers won't fire in response to this action either way.

The only reason the subscription observer will fire after calling `provideUserConsent(true)` initially is that the subscription _does_ change, since the user will get registered the first time you call this. 

You can always check `OneSignal.userProvidedPrivacyConsent(callback)` to see if the SDK is initialized with the user's consent or not

**Comment by rwillett** [comment]
@Nightsd01 

Thanks for the update. 

We've been testing the app and the only way we could get to get the privacy changes to change either ways and stick appears to be to restart the app. Not as neat as we would like, but hopefully the user won't keep changing their minds. At least it's better than asking them to reinstall the app.

I can't see any way to reinitialise the OneSignal plugin (apart from restarting the app) so I'm assuming thats not possible. 

Rob

**Comment by rwillett** [comment]
@jkasten2  @Nightsd01 

We are still struggling with user privacy. 

The only way we can see around the user changing their mind on GDPR consent is for us to put up a message saying to restart the application, not ideal but thats the best way at the moment. 

So we ask the user to restart the application. We setup the parameters as follows:
```
            window.plugins.OneSignal.setRequiresUserPrivacyConsent(true);
            window.plugins.OneSignal
            .startInit(OneSignalId)
            .iOSSettings(iosSettings)
            .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
            .handleNotificationOpened(notificationOpenedHandler)
            .handleNotificationReceived(notificationReceivedHandler)
            .endInit();

           // Lots of code removed

           window.plugins.OneSignal.provideUserConsent(GDPRConsent);

          // Lots of code removed

         
	   window.plugins.OneSignal.addPermissionObserver(function(state) {
            	    ConsoleLog("*** Notification permission state changed: " + state.hasPrompted);
	            ConsoleLog("*** Notification permission status: " + state.status);
           });

           window.plugins.OneSignal.addSubscriptionObserver(function (state) {
                if (debugRegisterAndGetOneSignalNotificationIDS)
                        ConsoleLog("*** Push Subscription state changed: " + JSON.stringify(state , null , 2));

               if (typeof state.to.userId !== "undefined" && typeof state.to.pushToken !== "undefined" && state.to.userId && state.to.pushToken)
               {
                                  // We have the userId and the pushToken, register.
               } 
         });        
```

When we run this code after an install it works, if we then change the OneSignal permissions by calling ```window.plugins.OneSignal.provideUserConsent(false);``` and then rerun the same code (no reinstall), we do not get any registrations back from OneSignal which is the expected behaviour. If we then run the code again (no re install) but now with ```window.plugins.OneSignal.provideUserConsent(true);``` we get a lot of debug messages being printed, e.g.

```
2018-10-10 22:21:23.446476+0100 Jambuster[6212:1166993] VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
2018-10-10 22:21:23.485641+0100 Jambuster[6212:1166993] DEBUG: mobileProvision: {
    AppIDName = XXXXXXX;
    ApplicationIdentifierPrefix =     (
       
    );
    CreationDate = "2018-09-27 18:59:07 +0000";
    DeveloperCertificates =     (
REMOVED
    );
    Entitlements =     {
        "application-identifier" = "XXXXXXXX";
        "aps-environment" = development;
        "com.apple.developer.team-identifier" = XXXXXXXX;
        "get-task-allow" = 1;
        "keychain-access-groups" =         (
            "XXXXXXXX*"
        );
    };
    ExpirationDate = "2019-09-27 18:59:07 +0000";
    IsXcodeManaged = 1;
    Name = "iOS Team Provisioning Profile: lXXXXXXXXXXX;
    Platform =     (
        iOS
    );
    ProvisionedDevices =     (
    );
    TeamIdentifier =     (
       
    );
    TeamName = "XXXXXX";
    TimeToLive = 365;
    UUID = "6248b04e-1455-4ed3-8eea-c2e60c188186";
    Version = 1;
}
2018-10-10 22:21:23.503978+0100 Jambuster[6212:1166993] VERBOSE: Calling OneSignal create/on_session
2018-10-10 22:21:23.510150+0100 Jambuster[6212:1166994] VERBOSE: HTTP Request (OSRequestRegisterUser) with URL: https://onesignal.com/api/v1/players/ce9061e9-6ae8-4917-bdb5-7c031121c80c/on_session, with parameters: {
  "app_id" : "XXXXXXXXX",
  "net_type" : 0,
  "test_type" : 1,
  "loc_acc_vert" : 3,
  "loc_acc" : 10,
  "long" : -0.1014326792211285,
  "device_type" : 0,
  "sdk" : "020807",
  "lat" : 51.28141127065874,
  "identifier" : "1d33b0fe84b8f1ef24ced6d1bd52ad3ed813f96ea370e8a40991413f43fd4342",
  "language" : "en-GB",
  "device_os" : "10.3.3",
  "game_version" : "2.4.10",
  "timezone" : 3600,
  "ad_id" : "XXXXXX",
  "notification_types" : -18,
  "carrier" : "giffgaff",
  "device_model" : "iPhone7,2"
}
2018-10-10 22:21:23.657591+0100 Jambuster[6212:1166993] VERBOSE: network response (OSRequestRegisterUser): {
    id = "ce9061e9-6ae8-4917-bdb5-7c031121c80c";
    success = 1;
}
2018-10-10 22:21:23.662139+0100 Jambuster[6212:1166950] VERBOSE: updateDeviceToken:onSuccess:onFailure:
2018-10-10 22:21:23.662415+0100 Jambuster[6212:1166950] VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
2018-10-10 22:21:23.668723+0100 Jambuster[6212:1166950] VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
2018-10-10 22:21:23.676141+0100 Jambuster[6212:1166950] VERBOSE: getNotificationTypes:mSubscriptionStatus: -1
```

We would expect to see the 
```window.plugins.OneSignal.addSubscriptionObserver(...)```
called with the change in subscription so we can do something with the userId and pushToken. We get lots of debugging but we never get the push subscription state called. It only appears to be called after an initial install, if we change ```window.plugins.OneSignal.provideUserConsent()``` to true and restart we never get state change called. 

If we uninstall the application and then run the same code it works well with the state change.

It does appear that once you have set the OneSignal privacy, it's difficult (impossible?) to change it without an uninstall. 

Is this is the case? Is there code buried in the app that stops us doing what we want to do?

Thanks

Rob

**Comment by Nightsd01** [comment]
I'm still not entirely sure I understand what exactly the problem is that you are facing? If the user sets consent to `true`, then you should be able to get a OneSignal `userId`. Calling the GDPR/consent methods **will not** cause the subscription or permission observers to fire. 

If the user _already_ had a OneSignal userId **before** you call `OneSignal.provideUserConsent(false)`, our SDK gets disabled but the user ID **does not change**. It remains the same. So if the user changes their mind and decides to give consent later on, when you call `OneSignal.provideUserConsent(true)`, it will re-enable the SDK, but since the user ID has not changed, the observer will not fire.

Keep in mind - the subscription observer **only** fires if the subscription state changes. All GDPR privacy consent does is disable the SDK. If the user has a valid subscription, the GDPR method doesn't change that either way beyond disabling initialization of the SDK.

**Comment by rwillett** [comment]
@Nightsd01 @jkasten2 

OK, we finally understand how this works. We thought  that ```addSubscriptionObserver()``` would always be fired when we change the permissions. It is only fired once when the user subscribes, subsequent changes do NOT fire it. 

We now understand that and it's an easy fix to get it all working the way it should do. 

Thanks and sorry for the confusion.

Rob
