### ISSUE TITLE
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!

### ISSUE THREAD

**Issue by artuska** [OneSignal/OneSignal-Cordova-SDK#440]
I have latest Gradle and Android Gradle Plugin and still getting this message, please fix.

Gradle — 4.10.2
Plugin — 3.2.0

**Comment by jkasten2** [comment]
@artuska Can you share a project repo reproducing the issue? I was not able to reproduce the issue by adding the same plugins as you had in issue #437

**Comment by Nightsd01** [comment]
Closing due to no response. Please reply if you’re still having this issue and we’ll reopen and help investigate.

**Comment by nurayttumer** [comment]
Same problem. reopen pls

**Comment by nurayttumer** [comment]
but ı cant share codes , 

`   PendingIntent resultPendingIntent =
                PendingIntent.getActivity(
                        context,
                        0,
                        pendingIntent,
                        PendingIntent.FLAG_ACTIVITY_NEW_TASK
                );

        Uri defaultSoundUri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(context)
                .setSmallIcon(notificationIcon)
                .setContentTitle(notificationTitle)
                .setStyle(new NotificationCompat.BigTextStyle().bigText(notificationText))
                .setContentText(notificationText)
                .setAutoCancel(true)
                .setSound(defaultSoundUri)
                .setPriority(Notification.PRIORITY_HIGH)
                .setVibrate(new long[0])
                .setContentIntent(resultPendingIntent);                                  
            //.setContentIntent(pendingIntent);`

**Comment by nurayttumer** [comment]
this is my helpşer

**Comment by jkasten2** [comment]
@nurayttumer Any Java code would be unrelated to the onesignal-gradle-plugin warning.

@nurayttumer @artuska Please provide a project reproducing the issue or exact step by step guide to reproduce the warning on a new project and we can reopen this and take a look.

Thanks.

**Comment by nurayttumer** [comment]
I've handle it. it is not giving any error or warning. thnk you

**Comment by jkasten2** [comment]
@nurayttumer What solved the issue for you? This might help others. Thanks.

**Comment by nurayttumer** [comment]
![ss](https://user-images.githubusercontent.com/29413193/47253455-9dd69b80-d45b-11e8-8a52-b670ce542bc2.PNG)

The problem was solved when I wrote the line with sdk top on the android line . just like in the screenshot. like this.

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'

**Comment by himaavar-mt** [comment]
I have fixed it...
Just go to "app/build.gradle"
Replace

"apply plugin: 'com.android.application' 
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin' "

with 

"apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin' "
apply plugin: 'com.android.application' "

**Comment by tharangachaminda** [comment]
Read [Setup](https://github.com/OneSignal/OneSignal-Gradle-Plugin#setup) section of OneSignal [documentation](https://github.com/OneSignal/OneSignal-Gradle-Plugin). It says,

2. Add the following to the top of your app/build.gradle
```
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```
It fixes the warning.

**Comment by Koshemi** [comment]
> I have fixed it...
> Just go to "app/build.gradle"
> Replace
> 
> "apply plugin: 'com.android.application'
> apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin' "
> 
> with
> 
> "apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin' "
> apply plugin: 'com.android.application' "

It helpas for me. Thx.

**Comment by askanhan** [comment]
There is absolutely no need to edit something in gradle or so...
Just bring the definition of one-signal plugin to the top and voila. It is solved.
