### ISSUE TITLE
Can't upgrade to 2.4.4

### ISSUE THREAD

**Issue by geshub** [OneSignal/OneSignal-Cordova-SDK#441]
**Description:**

I follow the normal procedure to upgrade from 2.4.3 to 2.4.4, but i'm always stucked at 2.3.3, do i have to wait to update ?

**Environment**

Using Ionic SDK

**Steps to Reproduce Issue:**

1. ionic cordova plugin remove onesignal-cordova-plugin
2. pod repo update
3. ionic cordova plugin add onesignal-cordova-plugin

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by Nightsd01** [comment]
@geshub "but i'm always stucked at 2.3.3" what does that mean? Are you running into some kind of error or something? If so, can you please post the error?

**Comment by geshub** [comment]
@Nightsd01 I just mean it installs 2.4.3 each time not 2.4.4, no error at all

**Comment by geshub** [comment]
@jkasten2 ,
Got it, I think the confusion came from the fact that this version still indicates 2.4.3 in  [plugin.xml](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/plugin.xml)
 and i'm using an automated tool to check for updates,
Sorry for that and thanks again for your help !
