### ISSUE TITLE
ionic ios title with [modified] message 

### ISSUE THREAD

**Issue by mamonraab** [OneSignal/OneSignal-Cordova-SDK#442]
hello
I am using ionic 3, onesginal  2.4.4  Xcode beta 9.2
my test device iPhone 6  os 9.x
when I send a message from the dashboard to ios I receive with the title [modified]   and I can't find any  solution for that unwanted  behavior

**Comment by Nightsd01** [comment]
@mamonraab please carefully follow step 1.6 of [Setting Up the Notification Service Extension](https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension-recommend-)
