### ISSUE TITLE
Onesignal plugin problem app can't build

### ISSUE THREAD

**Issue by Gercekefsane** [OneSignal/OneSignal-Cordova-SDK#443]
cordova plugin add onesignal-cordova-plugin --save

Api version 19(Android 7.1.1) 
Please fix it this problem 

https://i.hizliresim.com/6NAMNv.png

**Comment by jkasten2** [comment]
@Gercekefsane We haven't seen this error before but it seems it might be related to some old files being left in your build process.

`transformclasseswithdexbuilderfordebug "Dex archives: settings .DEX extenions only for .CLASS files`
https://stackoverflow.com/a/48232296/1244574

For cordova you should be able to run this with the following;
```
cd platforms/android/
./gradlew clean
```

You can also try removing and re-adding the android platform.
```
cordova platform rm android
cordova platform add android
```

**Comment by jkasten2** [comment]
@Gercekefsane Can you try reproducing the issue in a new project? If so please link this repo here and we can take a look.

**Comment by jkasten2** [comment]
@Gercekefsane The error isn't related to OneSignal but an issue with Cordova so closing this issue. I recommend going though their support channels to get help on your build error. Thanks.
