### ISSUE TITLE
After adding onesignal plugin cordova build makes error 

### ISSUE THREAD

**Issue by muthukumarperiyasamy** [OneSignal/OneSignal-Cordova-SDK#446]
**Description:**

I simply created the new project and
I build the app using
ionic Cordova build android --prod,
it builds fine without any issue.
but when I add the one signal plugin in my project using

ionic cordova plugin add onesignal-cordova-plugin

npm install --save @ionic-native/onesignal

when again build the application using

ionic Cordova build android --prod

it creates the following error

when remove the plugin it builds fine..........

**Environment**
cli packages: (C:\Users\master\AppData\Roaming\npm\node_modules)

@ionic/cli-utils  : 1.19.2
ionic (Ionic CLI) : 3.20.0
global packages:

cordova (Cordova CLI) : 8.0.0
local packages:

@ionic/app-scripts : 3.2.0
Cordova Platforms  : android 7.0.0
Ionic Framework    : ionic-angular 3.9.2
System:

Android SDK Tools : 26.1.1
Node              : v6.11.1
npm               :  6.4.1
OS                : Windows 10
Environment Variables:

ANDROID_HOME : C:\Sdk
Misc:

backend: pro

2.cordova plugin list
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
 -->

**Anything else:**
i getting the following error....................

>app:preDebugBuild
FAILED
14 actionable tasks: 1 executed, 13 up-to-date
FAILURE: Build failed with an exception.
*What went wrong:
Could not resolve all files for configuration ‘:app:debugCompileClasspath’.
 Could not find support-v4.aar (com.android.support:support-v4:27.1.1).
Searched in the following locations:
https://jcenter.bintray.com/com/android/support/support-v4/27.1.1/support-v4-27.1.1.aar
*Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log out
put.
*Get more help at https://help.gradle.org
BUILD FAILED in 26s
(node:9756) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
*What went wrong:
Could not resolve all files for configuration ‘:app:debugCompileClasspath’.
> Could not find support-v4.aar (com.android.support:support-v4:27.1.1).
Searched in the following locations:
https://jcenter.bintray.com/com/android/support/support-v4/27.1.1/support-v4-27.1.1.aar
*Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log out
put.
*Get more help at https://help.gradle.org
BUILD FAILED in 26s

**Comment by iranicus** [comment]
Could potentially be the issue where the dependency com.android.support:support-v4:27.1.1 is found at mavenCentral() and not jcenter() which for versions of android prior to 7.1.0 and newer versions of ionic there exists a bug where the build.gradle file for android only pulls in dependencies from jcenter() first before pulling any in from maven. However when looking at the dependency it seems to be for android support library which might be covered by the support repositories that should be installed via Android SDK tools (accessible from Android Studio) mentioned on https://documentation.onesignal.com/docs/ionic-sdk-setup#section-3-android

**Comment by ramanathancse2007** [comment]
Hi Iranicus,

I also get the same error.

Is the bug will get fixed  as mentioned the link ? 
 https://documentation.onesignal.com/docs/ionic-sdk-setup#section-3-android

Thanks

**Comment by ramanathancse2007** [comment]
Ok but i am using ionic 3 version.

**Comment by iranicus** [comment]
Should not matter the issue is down to the version of the android engine you use, I've found it to be an issue on version 6.x.x, you will find the version you are using in your config.xml. But also check with running: 
ionic cordova platform

**Comment by ramanathancse2007** [comment]
Ok. Thanks iranicus ! If i couldnt solve i will ping back in 24 hrs.

**Comment by ramanathancse2007** [comment]
Hi Iranicus, I am able to build without any bug. But now i am not receive notifications from one signal.

**Comment by iranicus** [comment]
Yeah that in itself is another issue you should probably make a new issue for, providing the logcat of the phone when the app is running which helps out and the payload you are sending from your backend server. I recently found on a Samsung Android 7 phone that I had to disable Notification Access to a system app called Zone which was dismissing the notifications as they were being received, once disabled they were received fine.

**Comment by ramanathancse2007** [comment]
Any alternative for one signal.

I can't ask everyuser to change in their phone to receive notification.

**Comment by jkasten2** [comment]
@muthukumarperiyasamy @ramanathancse2007 The build error is related to an issue with Cordova and Gradle only some users are running into. See https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/449#issuecomment-435203945 if you are still seeing this issue.

@ramanathancse2007 If you have fully uninstalled the app on your device then reinstalled it make sure that you are using the new OneSignal player id when testing. If you have confirmed you are still testing with the correct id see following troubleshooting guide.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

@iranicus I think the Zone app @iranicus is talking about would be very rare. I haven't seen this app before so I can't say what it does. @iranicus Do you have a link to this app?

@ramanathancse2007 Since this issue is unrelated to the build issue I recommend opening a new issue here with your logcat if the above trouble shooting does not help.

Thanks.

**Comment by rgomezp** [comment]
Closing due to no response
