### ISSUE TITLE
Could not find support-vector-drawable.aar (com.android.support:support-vector-drawable:27.1.1).

### ISSUE THREAD

**Issue by elysiopires** [OneSignal/OneSignal-Cordova-SDK#449]
**Description:**
Added the lastest version of the plugin and getting:
Could not find support-vector-drawable.aar (com.android.support:support-vector-drawable:27.1.1).
Searched in the following locations:
    https://jcenter.bintray.com/com/android/support/support-vector-drawable/27.1.1/support-vector-drawable-27.1.1.aar

Please install the Android Support Repository from the Android SDK Manager.
Open Android SDK Manager

**Environment**

com-sarriaroman-photoviewer 1.1.18 "PhotoViewer"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-document-viewer 0.9.10 "SitewaertsDocumentViewer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.0.1 "File Chooser"
cordova-plugin-filepath 1.4.2 "cordova-plugin-filepath"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

**Comment by jkasten2** [comment]
Hello sorry for the delay. This is a know issue with Gradle and Cordova with Google dependencies trying to be pulled from jcenter instead of maven.google. This issue seems to only happen to some users. There is a work around noted below;
https://github.com/phonegap/phonegap-plugin-push/issues/2412#issuecomment-396048488

Cordova has already fixed the issue bug but it isn't in a release yet, it will be part of their andoid@7.1.2 release.
https://github.com/apache/cordova-android/pull/523

Thanks.

**Comment by elysiopires** [comment]
To fix that just change the com.android.support:support-v4:27+ to
com.android.support:support-v4:27.1.0
on your build.gradle (Module:app) and have fun!

dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    compile "com.android.support:support-v4:24.1.1+"
---->    compile "com.android.support:support-v4:27.1.0"
