### ISSUE TITLE
OneSignal error on IOS block on a white screen

### ISSUE THREAD

**Issue by jorisnicolas** [OneSignal/OneSignal-Cordova-SDK#450]
**Description**
Hi, while the build is successful when the app is launched, right after the splashscreen, I have a white page with the following error (it's the only error) : 

ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter
ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
ERROR: Encountered error during email registration with OneSignal: (null)

I initialize the plugin like this:

    this.oneSignal.startInit("apeid", "firebaseid");
    this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.Notification);
    this.oneSignal.setSubscription(true);
    this.ones.allowNotification(true);
    this.oneSignal.endInit();

I saw [this issue](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/422) but in this case they were not initializing there SDK, I think I do or I don't understand.

**Environment**
Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 17 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v6.11.3 (/usr/local/bin/node)
   npm        : 6.4.1
   OS         : macOS High Sierra
   Xcode      : Xcode 10.0 Build version 10A255

cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"

**Comment by rammere** [comment]
I have the same issue any luck  ?

**Comment by rammere** [comment]
Hi,
Anyone stuck here just close the xcode . open the file called yourappname.xcworkspace NOT yourappname.xcodeproj! there will be no error.
And please put a delay ( like setTimeout ) before init the one signal plugin since it may need time to platform be ready.

**Comment by Nightsd01** [comment]
@jorisnicolas Was that your issue? Did you open the `.xcodeproj` instead of the `.xcworkspace`..?

**Comment by jorisnicolas** [comment]
Hi, I steal have the same issue, no change. I don't think I need the timeout since I'm initing onesignal once the platform is ready. I tried anyway and it didn't change anything.

**Comment by rammere** [comment]
No to solve the block on the screen you need to open the .xcworkspace and compile below is mycode 
(after platform is ready ) 
  initOneSignal() {

    this.oneSignal.startInit(
      'your-app-id',
      'AndroidID'
    );

    this.oneSignal.inFocusDisplaying(
      this.oneSignal.OSInFocusDisplayOption.InAppAlert
    );

    this.oneSignal.handleNotificationReceived().subscribe((data) => {
      // do something when notification is received
     
      console.log(JSON.stringify(data))
    },err=>{

      console.log("handle receive"+JSON.stringify(err))
    });

    this.oneSignal.handleNotificationOpened().subscribe((data) => {
      // do something when a notification is opened
      // go to communication 
      // add the message 
      console.log(JSON.stringify(data))
    },err=>{
      console.log("ok this is for suscribe"+JSON.stringify(err))
    });
    this.oneSignal.endInit();
    console.log("one signal initaited");
  }

**Comment by jorisnicolas** [comment]
Yes, I tried compiling by opening the .xcworkspace and I had the same error. About the code in it self, I don't see a big difference between the way you initialize and the way I do. I just don't handle notifications when they are received but I don't see how it could cause a problem .

    this.platform.ready().then(() => {
     this.statusBar.styleLightContent();
     this.statusBar.backgroundColorByHexString('#2A79A9');
     this.splashScreen.hide();
     ... stuff for the app

     if(this.platform.is('cordova')) { 
      this.oneSignal.startInit("", "");
      this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.Notification);
      this.oneSignalInit();
     }
    }

    oneSignalInit() {
     this.ones.getNotificationPermission().then(permission => { 
       this.oneSignal.setSubscription(permission);
       this.ones.allowNotification(permission);
     });
     this.oneSignal.endInit();   
    }

On the first launch permission is always equal to true.

**Comment by rammere** [comment]
In the code I sent to you can you tell what the message in the console ( or just add alert as in 

this.oneSignal.handleNotificationOpened().subscribe((data) => {
  // do something when a notification is opened
  // go to communication 
  // add the message 
  console.log(JSON.stringify(data))
},err=>{
  console.log("ok this is for suscribe"+JSON.stringify(err))
});

)
.
Plus did you follow this : https://documentation.onesignal.com/docs/ionic-sdk-setup
and installed the below  ? 
sudo gem install cocoapods
pod repo update

**Comment by jorisnicolas** [comment]
I did follow the doc on OneSignal and on Ionic to install and setup the plugin.

**Comment by smprodev** [comment]
I have the same issue.  Attached are my config.xml, package.json, and home.ts files.

[config.xml.txt](https://github.com/OneSignal/OneSignal-Cordova-SDK/files/2532356/config.xml.txt)
[package.json.txt](https://github.com/OneSignal/OneSignal-Cordova-SDK/files/2532357/package.json.txt)
[home.ts.txt](https://github.com/OneSignal/OneSignal-Cordova-SDK/files/2532358/home.ts.txt)

**Comment by jorisnicolas** [comment]
So, I've removed everything OneSignal related and I still have the white screen so OneSignal has nothing to do with the problem. I just have a withe screen with no error. Great.

**Comment by sdelrue** [comment]
you need to place the onesignal init-code as soon as possible in your app, otherwise the app_id will not be set and will cause the error

**Comment by alexandermainz** [comment]
sdelrue thanks so much, this solved it for me!
I had my OneSignal init code in the first tab of a tabbed app and got a "black screen" after app started.
Now I placed the code into the app.components.ts and the init worked.
Fingers crossed if the first push works now.

**Comment by AcidTr** [comment]
I have the same problem for a new application that uses the same config of another application that has no error at all. I'm using ionic v1 and the first list of platform.ready is the init code of one signal plugin. Can someone help ?
