### ISSUE TITLE
Unknown error getting FCM token

### ISSUE THREAD

**Issue by ahrherrera** [OneSignal/OneSignal-Cordova-SDK#451]
**Description:**

Yesterday I was receiving the notifications on android, but today I ran my Ionic project, then, I noticed that the plugin was not registering my device properly.
(your description here)

**Environment**

Using Ionic Cordova. The latest version available. 

**Steps to Reproduce Issue:**

1. Add android platform (android@6.3.0)
2. Add Onesignal Plugin, configure and add keys
3. Run project and verify the registered devices on the Onesignal dashboard.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by ahrherrera** [comment]
I did not upgraded to android@7.1.1. I stay in 6.3.0 and downgraded plugin version. That fixed it.

**Comment by jkasten2** [comment]
@ahrherrera Thanks for confirming, I'll mark this ticket as resolved then.

Feel free to reopen this ticket if you run into an issue upgrading though
