### ISSUE TITLE
PhoneGap-built app crashes on older iOS versions

### ISSUE THREAD

**Issue by alexmalykh** [OneSignal/OneSignal-Cordova-SDK#453]
**Description:**

I have an application built using PhoneGap Build cloud infrastructure. Testing it on six different iOS devices I've found it crashing on iOS 11.2.6 and 11.1.2. The app shows initial splashscreen, asks for permission to receive push notification and then dies (though permission request modal dialog remains). Reinstalling the application doesn't help. On other test devices I have iOS 11.4.x and iOS 12.x installed, and the app runs on them without any problems.

**Environment**

Cordova SDK is 2.4.5. Cordova plugins used are:

- cordova-plugin-dialogs 2.0.1 "Notification"
- cordova-plugin-geolocation 4.0.1 "Geolocation"
- cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
- cordova-plugin-native-spinner 1.1.3 "Native Spinner"
- cordova-plugin-splashscreen 5.0.2 "Splashscreen"
- cordova-plugin-statusbar 2.4.2 "StatusBar"
- cordova-plugin-vibration 3.1.0 "Vibration"
- cordova-plugin-whitelist 1.3.3 "Whitelist"
- cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
- es6-promise-plugin 4.2.2 "Promise"
- onesignal-cordova-plugin 2.4.5 "OneSignal Push Notifications"

Build environment settings:

- phonegap-version: cli-8.0.0
- cordova-ios platform version: 4.5.4

**Crash dump exerpt:**

```
Incident Identifier: 2AEA30CE-24A1-4771-8DBC-9ABC7C6EC731
Beta Identifier:     A6F4656E-2859-4B58-8F83-A3818BFBD078
Hardware Model:      iPad4,4
Process:             MYAPP TEST [330]
Path:                /private/var/containers/Bundle/Application/9C520482-969F-489F-A60D-B7B647E1615B/MYAPP TEST.app/MYAPP TEST
Identifier:          org.mycompany.myapp
Version:             101.1.20 (101.1.20)
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           org.mycompany.myapp [480]


Date/Time:           2018-11-09 17:39:27.5648 +0600
Launch Time:         2018-11-09 17:39:20.5074 +0600
OS Version:          iPhone OS 11.1.2 (15B202)
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000dede0beb8
VM Region Info: 0xdede0beb8 is not in any region.  Bytes after previous region: 51772440249  
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO (reserved) 00000001d8000000-00000001e0000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)
--->  
      UNUSED SPACE AT END

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  2


...


Thread 2 name:  Dispatch queue: com.apple.StoreServices.SSRequest.0x1c00d3940
Thread 2 Crashed:
0   libobjc.A.dylib                     0x0000000183070430 0x183054000 + 115760
1   StoreServices                       0x000000018eb5d7ec 0x18eb35000 + 165868
2   libdispatch.dylib                   0x0000000183791088 0x183790000 + 4232
3   libdispatch.dylib                   0x0000000183791048 0x183790000 + 4168
4   libdispatch.dylib                   0x000000018379ae48 0x183790000 + 44616
5   libdispatch.dylib                   0x000000018379b7d8 0x183790000 + 47064
6   libdispatch.dylib                   0x000000018379c200 0x183790000 + 49664
7   libdispatch.dylib                   0x00000001837a44a0 0x183790000 + 83104
8   libsystem_pthread.dylib             0x0000000183a36fd0 0x183a36000 + 4048
9   libsystem_pthread.dylib             0x0000000183a36c20 0x183a36000 + 3104
```

**Comment by rgomezp** [comment]
Did you set the deployment target for the notification extension service to iOS 10? Please see our iOS SDK setup [instructions](https://documentation.onesignal.com/docs/cordova-sdk-setup#section-ios-service-extensions) for more info (section 5.11)

**Comment by rgomezp** [comment]
Closing due to no response
