### ISSUE TITLE
Cordova and Android Oreo

### ISSUE THREAD

**Issue by rajeshpal** [OneSignal/OneSignal-Cordova-SDK#458]
**Description:**

OneSignal still reports as Unsupported Android Library
(your description here)

**Environment**

1. What version of the Cordova SDK are you using?
8.1.2 (cordova-lib@8.1.1)
2. Provide a list of your project dependencies (using `cordova plugin list` or copy-pasting your config.xml)

cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.5 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1. followed all instruction
2. browsed issues and attempted the recommendation
3. created category in oneSignal to able sending to Oreo

**Anything else:**

(crash stacktraces, as well as any other information here)
App compiled. Tried to send messages but error Outdated Android Library for Oreo & Pie

**Comment by Nightsd01** [comment]
@jkasten2 Could you take a look at this one?

**Comment by jkasten2** [comment]
@rajeshpal Can you make sure you have cordova platform version 7.0.0 or higher in your `config.xml`?
To update you can run the following.
```
cordova platform rm android
cordova platform add android@7.1.4
```

**Comment by rgomezp** [comment]
Closing due to no response. Feel free to reply with an @ if you would like further guidance
