### ISSUE TITLE
cancel single notification by id on android

### ISSUE THREAD

**Issue by RaiseRaise** [OneSignal/OneSignal-Cordova-SDK#459]
Good day, I'd like to request an ability to cancel a single notification by id.
I understand it will work only on Android, for this you can use method cancel of NotificationManager
https://developer.android.com/reference/android/app/NotificationManager.html#cancel(int)

I think it should work similar way as clearOneSignalNotifications

Thanks!

**Comment by Nightsd01** [comment]
@RaiseRaise Our API has an endpoint that lets you cancel a notification, but it cannot be done from a client. You should REALLY be doing this sort of thing from a backend server and only for authenticated clients.

https://documentation.onesignal.com/reference#cancel-notification
