### ISSUE TITLE
runtime error cannot read property featured_src

### ISSUE THREAD

**Issue by abdulkader-sand** [OneSignal/OneSignal-Cordova-SDK#463]
i have this error in my ionic app i use wampserver and word press as my back end, and i use cross origin sharing  extension in chrome to get the data from the database, it used to work but know i keep getting the error i even drop the whole database
![capture](https://user-images.githubusercontent.com/45739416/49701065-338add80-fbf8-11e8-8f03-65db329f4a7a.PNG)
 and re do it again still the error keep coming.

**Comment by rgomezp** [comment]
Hello, please follow our [issue template](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/issue_template.md) so we can better work with you solving your problem. Feel free to create a new issue with more information. Thank you
