### ISSUE TITLE
Feature request: Support for Voip registration in the SDK

### ISSUE THREAD

**Issue by bgpedersen** [OneSignal/OneSignal-Cordova-SDK#465]
**Description:**
According to OneSignal documentation, the SDK does not yet support VoIP registration. According to this [https://github.com/OneSignal/OneSignal-iOS-SDK/issues/415](thread) from september 2018, it sounds like this feature might be implemented around new year 2018. 

As we currently (and very happily) use OneSignal for all our notification handling and now need to implement VoIP notifications/registration, it seems natural to use OneSignal for this.

So my question is if there exist an estimate for (or if) the SDK will be extended to support VoIP registration?

**Environment**
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
