### ISSUE TITLE
Cannot get Action Buttons to work on IOS

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#474]
**Description:**
I cannot get the Action Buttons to work on IOS with 
Ionic 1, 
Cordova 8.1.2, 
onesignal-cordova-plugin 2.4.5 "OneSignal Push Notifications"
IOS 12.1 
iPhone 6s

Our app has been working well with OneSignal and we wanted to add in Action Buttons. We have had four attempts so far to try and get Action Buttons to work. We have followed the guides in

https://documentation.onesignal.com/docs/cordova-sdk-setup
and 
https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension-recommend-

only doing steps 1.1 to steps 1.6. We can see the newly created extension and have added in the correct framesworks, though the steps in 5.9 on where to find the OneSignal.framework is slightly different to the example in the docs.

<img width="811" alt="screenshot 2019-01-08 at 18 52 43" src="https://user-images.githubusercontent.com/668923/50852177-be393680-1376-11e9-8d92-acb4c7035cb2.png">

However we do seem to get to the right framework (I hope).

<img width="1307" alt="screenshot 2019-01-08 at 18 55 31" src="https://user-images.githubusercontent.com/668923/50852274-fe001e00-1376-11e9-8261-cfd1a558e406.png">

Xcode builds the application without any issues (or at least without the normal issues for a Cordova app).

We run the application and it loads correctly, we can see Xcode displaying the correct debugging from our app.

We then send a test message from the OneSignal website to the application. We add in an action or two (without icons) and send the notification. The notification appears in our app but we do not get any buttons whatsoever.

After writing this, the only thing that we can see (after the fourth attempt) is that we do NOT add in the App Groups 

```
iOS - Add App Groups (Optional but Recommended)
In order for your application to be able to let push notifications increment/decrement the badge count, you need to set up an App Group for your application.

Please follow this guide to set up a OneSignal app group in your app.
```

The documentation doesn't say these are needed for Action Buttons. Are they? We don't need to set badges so didn;t do this.

Apart from that, we're pretty certain we've done exactly what the docs say so we've run out of ideas. Is there any more debugging we can do to verify we have installed correctly?

**Comment by Nightsd01** [comment]
@rwillett Can you send me an iOS screenshot of one of these notifications that is missing the action buttons?

**Comment by rwillett** [comment]
Brad,

Sure. Here's the notification on the screen

![image](https://user-images.githubusercontent.com/668923/50852933-d4e08d00-1378-11e9-84ad-add7cbc34bb1.png)

and if I click on the notification to expand it.

![image](https://user-images.githubusercontent.com/668923/50852963-ee81d480-1378-11e9-854a-a7105eedb16f.png)

If I click on the notification 'normally' it does what it is supposed to and opens our application up.

**Comment by Nightsd01** [comment]
@rwillett thanks for the screenshot.

Can you try sending a push notification with an image, and let me know if the image shows up?

**Comment by rwillett** [comment]
And here's how we created the Action Buttons element of the message 

![image](https://user-images.githubusercontent.com/668923/50853065-20933680-1379-11e9-8ccb-82cebaf0149e.png)

**Comment by rwillett** [comment]
OK. Let me look at how to do that...

**Comment by rwillett** [comment]
Ok. that was embarrassingly easy...

Here's the image I uploaded to the OneSignal console

![image](https://user-images.githubusercontent.com/668923/50853382-f3935380-1379-11e9-8347-9bacb8085144.png)

and here's the notification received

![image](https://user-images.githubusercontent.com/668923/50853342-d2cafe00-1379-11e9-8eaf-82bbb90fe443.png)

The image is actually a cut of the BBS website

**Comment by rwillett** [comment]
If I click on the notification I get this 

<img width="537" alt="screenshot 2019-01-08 at 19 21 18" src="https://user-images.githubusercontent.com/668923/50853623-a499ee00-137a-11e9-848a-a33dc2b73543.png">

which is rather nice as we've not done rich media before. We now will :)

**Comment by rwillett** [comment]
Brad,

<img width="722" alt="screenshot 2019-01-08 at 19 33 52" src="https://user-images.githubusercontent.com/668923/50854214-643b6f80-137c-11e9-8243-e722b6f37e40.png">

Already checked that :)

Where do I get the notification ID from please?

**Comment by rwillett** [comment]
Do you mean the Apple Push notification Id as per your docs?

<img width="1217" alt="screenshot 2019-01-08 at 19 51 51" src="https://user-images.githubusercontent.com/668923/50855122-e167e400-137e-11e9-99e5-58ffa42ecebc.png">

**Comment by rwillett** [comment]
Can't find a notification ID from the web console as thats where are testing from.

**Comment by Nightsd01** [comment]
@rwillett If you send a push notification, and you view the notification delivery report on our dashboard, you should be able to see the notification ID in the actual URL

**Comment by rwillett** [comment]
Ah! OK.

I've just sent a new test message with Action Buttons set. It appears correctly (without Action Buttons) on my phone.

The notification ID from the URL is

d6ed5798-b5e2-4005-bb5b-96b51581a6d4

Hope this helps,

Rob

**Comment by Nightsd01** [comment]
@rwillett Interesting. I am starting to suspect you may be witnessing a relatively rare iOS 12 bug we discovered a few months ago.

https://github.com/OneSignal/OneSignal-iOS-SDK/issues/430

With this bug, it can sometimes take many attempts and app closes/reopens before action buttons start to appear. Even worse, sometimes when they _do_ eventually appear, you will start seeing the wrong action buttons from previous notifications. 

Fortunately we've only ever heard of this bug happening on _development_ installs, we've never seen this on a production app downloaded from the App Store.

Are you completely uninstalling your app frequently? If so, please stop doing that for a while and try this. Try installing the app, sending a push notification with action buttons. If they do not appear, try sending a push notification with an image (like you did previously). Do NOT uninstall the app. Relaunch the app from Xcode and try sending a push notification with buttons again.

Lastly, try also sending a push notification with BOTH image and buttons.

Let me know if the action button appears.

**Comment by rwillett** [comment]
Brad,

Thanks for the update. 

We've read #430 and found the bug report from October. The fact it's marked as a duplicate is good as it means it's real and Apple acknowledge it, however the fact we can't see the original big reprot is frustrating and one of the reasons why Apple annoys the hell of us. I recognise this is not your problem though :)

It depends on the changes we make as to whether we remove the app when debugging. As the changes here didn't appear to need removal we didn't remove the app.  The fact that it appears to related to development releases is good but makes a release difficult, we may try and do a beta release to see if that works. Thats a PITA though. 

What we will do is:

1. Try the various permutations to see what that does.
2. We'll do a beta release through the App store for kicks to see if that helps.
3. We'll reverse our schedule for the next release which was Action Buttons followed by Rich Media to get the Rich Media out first and then add Action Buttons. That's not a problem. 
4. We'll use Android for some of the development to see if that helps. We normally do iOS first with Android second. Again it's no big deal to put Android ahead of iOS.

Is there anyway to find out when this Apple bug is fixed? We appreciate your updates and the time you've taken to help us.

Rob

**Comment by rwillett** [comment]
@Nightsd01 

A positive update. 

We have just sent a notification with rich media AND action buttons. It works. We see three buttons and an image. This does appear to validate your theory, though one success doesn't wholly validate it :)

We will still do the other actions, but we do appear to have a path through this, we need to do Action Buttons and send an image. Thats the work for this weekend sorted :)

Rob

**Comment by rwillett** [comment]
I'll update this thread over the next few days as we investigate further, so suggest we keep it open.

**Comment by rwillett** [comment]
@Nightsd01 

We've got it working with Android using the OneSignal console as well. That just worked, it's only IOS now. 

Appreciate that you're at Apple's mercy. Apple is rubbish at keeping people informed about stuff like this. 

I'm actually sitting on the train now working with phantomjs to generate the rich text images needed for both iOS and Android notifications. We have to generate multiple images for each notification pass, these are generated from a website and it's 'tricky',

**Comment by Nightsd01** [comment]
@rwillett Thanks for providing so many details on this issue. Thanks to the details you've provided, we've been able to ascertain that you are definitely experiencing the same iOS bug I discussed early.

Because we already have an [issue](
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/430) open to track this issue on our native iOS SDK repo I will be closing this issue as a duplicate. 

Please feel free to reply to that issue moving forward if you have anything new to add, and I apologize that you've seen this issue - I wish there was more we could do.
