### ISSUE TITLE
Feature: Read all OneSignalNotifications that have not been clicked by user

### ISSUE THREAD

**Issue by billy124** [OneSignal/OneSignal-Cordova-SDK#475]
Hi Guys,

I just wanted to know if there is a way to loop through all the notifications that have not been clicked on or swiped away by the user.

Example:
Let's say the user has received 4 push notifications while the application has been closed, they click on the app icon from home screen to open the app, I need to loop through the 4 notifications to access the data.

I am using Ionic 3.

Plugin list 
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-youtube-video-player 1.0.6 "CordovaYoutubeVideoPlayer"
onesignal-cordova-plugin 2.4.5 "OneSignal Push Notifications"

**Comment by Nightsd01** [comment]
@billy124 This is a good question. It is not currently possible to do this since our iOS SDK doesn't currently save references to push notifications that were received. 

There may be a way to do it natively in ObjC/Java or Swift/Kotlin in both android and iOS, but currently we don't support it.
