### ISSUE TITLE
Notification opened callback when app is closed does not work on IOS

### ISSUE THREAD

**Issue by noveweb** [OneSignal/OneSignal-Cordova-SDK#479]
I'm using the version 2.4.5 on IOS cordova app and when notification comes and the app is completly closed, i tap on the notification, the app opens, but NotificationOpened Callback don't fires.

When the app is opened or minimized works fine. I tap on the notification and the app maximize and go to the specific page.

what i'm doing wrong?

Thanks in advance!

**Comment by Nightsd01** [comment]
@noveweb please post more details, a code sample and your `package.json` especially.

**Comment by Nightsd01** [comment]
Also, you are certain that you’re talking about the `onOpened` callback and not the `onReceived` callback right?

**Comment by noveweb** [comment]
Yes, on opened.
What i want: With the app completly closed, the user receive the notification, tap on the notification, then the app opens and go to notification page and show the notification.

With the app opened or minimized works fine, but with the app closed not.

I’m using phonegap build cli-8.0.0

**Comment by Nightsd01** [comment]
Can you please post your code for the callback and your `package.json`?

Also....are you sure the callback isn’t getting called? You might try using logging and the Console app to make sure.

**Comment by noveweb** [comment]
im using phonegap build, how i can find this file? 

**My Code**

_**///Opened Callback (Works fine when app is opened in focus or minimized)///**_

var notificationOpenedCallback = function(jsonData) {

  var titulo = jsonData.notification.payload.title;
  var texto = jsonData.notification.payload.body;
  var id = jsonData.notification.payload.additionalData.id;
  var data_hora = jsonData.notification.payload.additionalData.data_hora;
  var situacao = jsonData.notification.payload.additionalData.situacao;

  fw7.router.navigate('/ver-notificacao/?id='+id+'&titulo='+titulo+'&texto='+texto+'&data_hora='+data_hora+'&situacao='+situacao);

};

_**///Opened Callback (Works fine when app is opened in focus or minimized)///**_

var notificationReceivedCallback = function(jsonData) {

  $(".icone_notificacoes").addClass("tem");
  $(".icone_notificacoes i").html("notifications");
  cordova.plugins.notification.badge.increase(1);

  var titulo = jsonData.payload.title;
  var texto = jsonData.payload.body;
  var id = jsonData.payload.additionalData.id;
  var data_hora = jsonData.payload.additionalData.data_hora;
  var situacao = jsonData.payload.additionalData.situacao;

fw7.notification.create({
  icon: '<i class="icon material-icons">notifications_active</i>>',
  title: 'Nova notificação',
  titleRightText: 'Agora',
  subtitle: titulo,
  text: 'Toque para ler',
  closeOnClick: true,
  closeTimeout: 5000,
  on: {
    notificationClick: function () {
      fw7.router.navigate('/ver-notificacao/?id='+id+'&titulo='+titulo+'&texto='+texto+'&data_hora='+data_hora+'&situacao='+situacao);
    },
  },
}).open();


};

_**///Plugin initialization///**_

window.plugins.OneSignal.startInit("XXXXXXX").inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None).handleNotificationReceived(notificationReceivedCallback).handleNotificationOpened(notificationOpenedCallback).endInit();

**Comment by noveweb** [comment]
I will test now and look the console log of device.

**Comment by noveweb** [comment]
@Nightsd01 i'm a web developer since 2001, i know what is console, all my day today was looking for some problem on device console of xcode! The "situation" is a aditional data sent by our rest api and is impossible its coming null. I'll repeat... with the app maximized works fine, the console.log shows "ok", but when the app is closed and opens after the user tap the notification console.log dont show "ok".

**Comment by Nightsd01** [comment]
@noveweb you’re saying that you aren’t seeing `ok` getting logged to console when you open the notification when the app was closed?

You can also try using an alert to make certain, add the alert to the top of the callback. This is even easier than using console.

**Comment by Nightsd01** [comment]
And as an aside, if there’s ever a bug in your backend, an “impossible” situation can suddenly become a bad crash hurting users, so I would definitely recommend checking to make sure fields like `additionalData.situacao` actually exist before attempting to use it.
