### ISSUE TITLE
know if notifications are enabled

### ISSUE THREAD

**Issue by BugsBunnyBR** [OneSignal/OneSignal-Cordova-SDK#48]
Is there a way to know if `setSubscription` has it's current value as true or false?

**Comment by jkasten2** [comment]
There currently isn't a way to get the state of this. I recommend you wrap this function with your own code to handle saving of the current state. We will consider adding this as an enhancement to our SDK.

**Comment by tavosansal** [comment]
I think this is very valuable for this plugin. Sounds like it is doable since this plugin does do it: https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationhaspermissionsuccesshandler---android--ios-only

**Comment by mtshare** [comment]
This would be awesome! Hope to see this function in the next updates.

**Comment by gianpaj** [comment]
Just 60 lines of code:
https://github.com/phonegap/phonegap-plugin-push/blob/945aa2ad6d266e82683e0bee86f53d258f2b31b6/src/android/com/adobe/phonegap/push/PermissionUtils.java

**Comment by AdrienDC** [comment]
+1 this is really needed

**Comment by jkasten2** [comment]
@BugsBunnyBR @tavosansal @mtshare @gianpaj @AdrienDC  You can now call [`getPermissionSubscriptionState`](https://documentation.onesignal.com/docs/cordova-sdk#section--getpermissionsubscriptionstate-) to get the current notification permission and subscription state for the device. There is also now a [`addPermissionObserver`](https://documentation.onesignal.com/docs/cordova-sdk#section--addpermissionobserver-) and [`addSubscriptionObserver`](https://documentation.onesignal.com/docs/cordova-sdk#section--addsubscriptionobserver-) so you can pass in a function to response to these events as well.

These were added in the Cordova 2.1.0 SDK release.

**Comment by AdrienDC** [comment]
Great work team ! I'm implementing it straight way
