### ISSUE TITLE
handleNotificationOpened and handleNotificationReceived handlers not called on iOS after app closed

### ISSUE THREAD

**Issue by misog** [OneSignal/OneSignal-Cordova-SDK#480]
**Description:**

```
document.addEventListener("deviceready", function() {
  var iosSettings = {};
  iosSettings["kOSSettingsKeyAutoPrompt"] = true;
  iosSettings["kOSSettingsKeyInAppLaunchURL"] = true;
  window.plugins.OneSignal
    .startInit("XXXXXXXXXXXXXXXXXXXX")
    .iOSSettings(iosSettings)
    .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
    .handleNotificationOpened(function(jsonData) {
      var url = jsonData.payload.additionalData.url;
      app.dialog.alert('DEBUG/O: ' + url);
      mainView.router.navigate(url);
    })
    .handleNotificationReceived(function(jsonData) {
      var url = jsonData.payload.additionalData.url;
      app.dialog.alert('DEBUG/R: ' + url);
      mainView.router.navigate(url);
    })
    .endInit();
}, false);
```
**Environment**
Cordova iOS 4.5.5
Onesignal 2.4.6
Plugins:
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-transport-security 0.1.2 "App Transport Security"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**
1. Run my app in iOS 12 and hide it in the background
2. Send notification (via API)
3. Click on the notification in iOS Notification center
4. The app is open and only handleNotificationReceived handler is called
5. Kill the app in iOS
6. Send notification again (via API)
7. Click on the notification in iOS Notification center
8. The app is open but handleNotificationReceived nor handleNotificationOpened handler are called

**Comment by rgomezp** [comment]
Hello,
Sorry for the delay. Are you still seeing the issue?

**Comment by rgomezp** [comment]
Closing due to no response.

**Comment by misog** [comment]
Yes, this is still an issue.

**Comment by kaiquecruz** [comment]
Hi @misog 
Did you solve this navigation problem?
I couldn't :/

**Comment by misog** [comment]
No, it is not working on iOS. My workaround is to save notifications to DB and check newest notification on my server when the app is initialized and then open url in my app.

**Comment by kaiquecruz** [comment]
> No, it is not working on iOS. My workaround is to save notifications to DB and check newest notification on my server when the app is initialized and then open url in my app.

Thaks!!!

**Comment by misog** [comment]
@rgomezp it is not working for many people, does it work for you?

**Comment by rgomezp** [comment]
I will have to reproduce @misog,
Thank you for your patience

**Comment by rgomezp** [comment]
Hello @misog , @kaiquecruz ,
I looked into the issue and realized there was a mistake in the documentation (which has been [fixed](https://documentation.onesignal.com/docs/cordova-sdk#section--handlenotificationreceived-)). In fact, the received handler should only fire in the foreground. This is the correct expected behavior. 

The `opened` handler perhaps appears to not fire because the debugger doesn't know how to re-attach to a killed app process. To prove this, open XCode and go to:
Window > Devices & Simulators > [YOUR DEVICE] > Open Console

This console will log EVERYTHING so you need to make sure to have a unique string you can search for.

The expected behavior here (after killing an app) is that the `handleNotificationOpened` should be the only one to fire. You should see any logs from this handler appear in this console.

Thanks for bringing this up!

**Comment by misog** [comment]
@rgomezp Hi, the issue is still present and it is worse. When I use just handleNotificationOpened and do not use handleNotificationReceived then the bug is present on Android too - it does not call the callback. The notification is received and when it is clicked then it just opens the app but callback is not called.

**Comment by misog** [comment]
@rgomezp so the handleNotificationOpened is useless. Callback in handleNotificationReceived is called after user clicks on notification - this is not expected behaviour:
```
handleNotificationReceived
Sets a notification received handler. Only called if the app is running in the foreground at the time the notification was received.
```

**Comment by misog** [comment]
In 2.4.7 it works on iOS. I would like to mention that the jsonData object passed by handleNotificationOpened has different object structure than the jsonData object passed by handleNotificationReceived 
![obrázok](https://user-images.githubusercontent.com/6667651/60259299-41275c80-98d7-11e9-9094-f1b9c861f68a.png)

**Comment by Ademking** [comment]
@misog thank you so much.. this problem made me crazy for hours...

**Comment by aishwaryarh** [comment]
Hi i have the same issue after updating to one signal plugin version 3 
handleNotificationReceived is not working. please provide me with the solution
