### ISSUE TITLE
Ability to remove push notification from notifications center on android device

### ISSUE THREAD

**Issue by RaiseRaise** [OneSignal/OneSignal-Cordova-SDK#481]
Good Day, please add ability to remove push notification from notifications center on android device.
Maybe It is a copy of #344, but I try to explain in details what is it for.
When user receives push notification (about private message for example) it is displayed in the notifications center(status bar) of android device. But user can manually read this message, without clicking on notification. In that case we should programmatically remove this notification from notifications center, because it is already irrelevant.
For this, the method **cancel** of NotificationManager is used in android native apps.
https://developer.android.com/reference/android/app/NotificationManager.html#cancel(int)

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
