### ISSUE TITLE
One Signal Rich notifications are not working after uploading over testflight 

### ISSUE THREAD

**Issue by jamtechdev** [OneSignal/OneSignal-Cordova-SDK#482]
Hey there! 

I am experiencing one issue with my ionic (Ionic 3) project. I was trying to integrate Rich push notifications with my app and I got success in that too. But the issue is that when I am uploading my app to the test flight (https://developer.apple.com/testflight/). 

I am getting push notification without media content what can be issue? 

I will really appreciate your kind help.

**Comment by rgomezp** [comment]
Hello,
Did you set up the Notification Service Extension? Also, if you ever did a clean-build, you have to redo this step.

**Comment by rgomezp** [comment]
Closing due to no response
