### ISSUE TITLE
In latest cordova ios(cordova-ios@5.0.0), failed to install Onesignal plugin

### ISSUE THREAD

**Issue by kkjhamb01** [OneSignal/OneSignal-Cordova-SDK#484]
After adding cordova-ios@5.0.0, can't add onesingal plugin.

It shows this issue:

> cordova plugin add onesignal-cordova-plugin --save
> Installing "onesignal-cordova-plugin" for ios
> "framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
> Failed to install 'onesignal-cordova-plugin': undefined
> CordovaError: Promise rejected with non-error: '/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!\': \u001b[31m[!] You cannot run CocoaPods as root.\u001b[39m (CLAide::Help)\n\n\u001b[4mUsage:\u001b[24m\n\n    $ \u001b[32mpod\u001b[39m \u001b[32mCOMMAND\u001b[39m\n\n      CocoaPods, the Cocoa library package manager.\n\n\u001b[4mCommands:\u001b[24m\n\n    \u001b[32m+ cache\u001b[39m      Manipulate the CocoaPods cache\n    \u001b[32m+ env\u001b[39m        Display pod environment\n    \u001b[32m+ init\u001b[39m       Generate a Podfile for the current directory\n    \u001b[32m+ install\u001b[39m    Install project dependencies according to versions from a\n                 Podfile.lock\n    \u001b[32m+ ipc\u001b[39m        Inter-process communication\n    \u001b[32m+ lib\u001b[39m        Develop pods\n    \u001b[32m+ list\u001b[39m       List pods\n    \u001b[32m+ outdated\u001b[39m   Show outdated project dependencies\n    \u001b[32m+ repo\u001b[39m       Manage spec-repositories\n    \u001b[32m+ setup\u001b[39m      Setup the CocoaPods environment\n    \u001b[32m+ spec\u001b[39m       Manage pod specs\n    \u001b[32m+ update\u001b[39m     Update outdated project dependencies and create new Podfile.lock\n\n\u001b[4mOptions:\u001b[24m\n\n    \u001b[34m--silent\u001b[39m     Show nothing\n    \u001b[34m--version\u001b[39m    Show the version of the tool\n    \u001b[34m--verbose\u001b[39m    Show more debugging information\n    \u001b[34m--no-ansi\u001b[39m    Show output without ANSI codes\n    \u001b[34m--help\u001b[39m       Show help banner of specified command\n\tfrom /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:47:in `run'\n\tfrom /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>\'\n\tfrom /usr/local/bin/pod:22:in `load'\n\tfrom /usr/local/bin/pod:22:in `'\n'
> at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> [ERROR] An error occurred while running subprocess cordova.

cordova plugin add onesignal-cordova-plugin --save exited with exit code 1.
Re-running this command with the --verbose flag may provide more information.

**Comment by vptcnt** [comment]
+ 1

**Comment by dimitriteixeira** [comment]
Please, how did you solve this problem? Here is exactly the same thing happening.

**Comment by ciekawy** [comment]
for now I am still on `cordova-ios` < 5.0. 
5.0 introduced breaking changes aa for `CocoaPod`s integration so it will take time to make it working.

**Comment by jkasten2** [comment]
@kkjhamb01 It looks like you got things working? Noticed your reply here https://github.com/apache/cordova-ios/issues/521. Was the permission I noted below that fixed it for you?

@vptcnt @dimitriteixeira @ciekawy Is your error the same as @kkjhamb01's above?
`You cannot run CocoaPods as root`

## Ensure Cocoapods version and permission are correct
I recommend running the following to make sure the correct permissions are set for Cocoapods on your system.
```
sudo chown -R $USER ~/Library/Caches/CocoaPods
sudo chown -R $USER ~/.cocoapods
```
Newer versions of Cocoapods should be preventing you from running options as root so you shouldn't see this issue in the future.
I would recommend making sure you have the latest version of cocoapods. Your can run the following to update.
`sudo gem install cocoapods`
*(using sudo to install or update cocoapods is the only exception to running as root for cocoapods)*

## Steps of attempting to reproduce
1. Updated to latest npm and cordova
```
npm install -g npm
npm install -g cordova
```
2. Created new project
```
cordova create test_onesignal_with_ios5platform
cd test_onesignal_with_ios5platform
```

3. Add cordova iOS 5.0.0 platform
`cordova platform add ios@5.0.0`

4. Add latest OneSignal version
`cordova plugin add onesignal-cordova-plugin@^2.4.6`

5. Build iOS
`cordova build ios`

@vptcnt @dimitriteixeira @ciekawy Can you produce the issue in a new project after following the above?

**Comment by rgomezp** [comment]
Closing due to no response.
