### ISSUE TITLE
setExternalUserId non available from TypeScript

### ISSUE THREAD

**Issue by dafi** [OneSignal/OneSignal-Cordova-SDK#485]
**Description:**

I use OneSignal from Ionic v4 app, everything works fine but the methods `setExternalUserId` and `removeExternalUserId` are not available from TypeScript wrapper.

I tried to mix TypeScript with Javascript code calling `window['plugins'].OneSignal` and this works but should be great if the API calls could be available from TypeScript, too.

**Environment**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0, ios 4.5.5
   Cordova Plugins       : onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"


System:

   ios-deploy : 1.9.4
   NodeJS     : v10.9.0 (/usr/local/Cellar/node/10.9.0/bin/node)
   npm        : 6.7.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.1 Build version 10B61

```

**Steps to Reproduce Issue:**

  1. Add the onesignal-cordova-plugin to your project
  2. Initialize the plugin with your app ID
  3. From code call the plugin using Javascript

```javascript
window['plugins'].OneSignal.setExternalUserId('my_unique_name');
``` 

Copied from the [Cordova example](https://github.com/OneSignal/OneSignal-Cordova-Example) (no typescript obviously)

**Anything else:**

none

**Comment by rgomezp** [comment]
Thank you for your request. I will be closing this issue though we will still be tracking the feature request internally
