### ISSUE TITLE
this.oneSignal.OSInFocusDisplayOption.None DOES NOT WORK

### ISSUE THREAD

**Issue by zigou13** [OneSignal/OneSignal-Cordova-SDK#489]
Hello, I do not want to display the notification window when the application is open, so I put like this .inFocusDisplaying (this.oneSignal.OSInFocusDisplayOption.None); but this function is not taken into account, I always have the notification while the application is open, I do not have twice in my application startInit ()!
Version sdk: 2.4.6
Device : Android And IOS

`Ionic:

   ionic (Ionic CLI)  : 4.11.0
   Ionic Framework    : ionic-angular 3.9.4
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 18 other plugins)

System:

   Android SDK Tools : 26.1.1 (D:\Android-SDK)
   NodeJS            : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10`

**Comment by rgomezp** [comment]
Hello,
Please see our [documentation](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) for info on how to send silent notifications.

**Comment by rgomezp** [comment]
Closing due to no response
