### ISSUE TITLE
support background/silent notifications on Android

### ISSUE THREAD

**Issue by ciekawy** [OneSignal/OneSignal-Cordova-SDK#491]
**Description:**

Integrate `NotificationExtenderService` to allow background/silent notifications on Android as it is now available on iOS.
As thats a known limitation and mentioned in documentation I believe it is worth to be added to Android, especially this is already working in iOS.

**Environment**

Android

**Steps to Reproduce Issue:**

A use case which I believe is pretty common is in app messaging.

App is in background (or fully off): new message send to a user should trigger push notification to be shown on mobile device.

App is in foreground: no notification is shown but app-specific logic is involved to provide desired UX  - to achieve this ideally `CordovaNotificationReceivedHandler` should be called and same flags to be used to be in sync how it works now for iOS

**Comment by ciekawy** [comment]
this topic was raised also over a year ago yet no solution or working implementation example has been provided https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/64

**Comment by rgomezp** [comment]
Hello,
Perhaps you're looking for `inFocusDisplaying` https://documentation.onesignal.com/docs/cordova-sdk#section--infocusdisplaying-.

If you set this to `None` then the notification won't show when the app is in focus. Then, use `handleNotificationReceived` to perform the logic you want. https://documentation.onesignal.com/docs/cordova-sdk#section--handlenotificationreceived-

**Comment by rgomezp** [comment]
Closing due to no response
