### ISSUE TITLE
Automate "Notification Service Extension" step

### ISSUE THREAD

**Issue by rricamar** [OneSignal/OneSignal-Cordova-SDK#493]
**Description:**

Hi ✋ ,

I'm working with an Ionic / Cordova based App, and I would like to automate the Notification Service Extension step ( for example, in Jenkins pipeline)  , since I saw that after doing it, remove platform, and add it again, the associated target is removed 😭 

I've been searching through the docs and another issues and I haven't seen anything, is this possible (custom hook / post build script ) ?

Thanks a lot in advance!

**Comment by manudefrutosvila** [comment]
would be interesting to have this... it's a pain every build to have all the steps because it is lost when platform is removed

**Comment by rgomezp** [comment]
Thanks for this request. We will consider this internally moving forward and will close this issue for now.

**Comment by kamekazemaster** [comment]
Is there any decision made yet? I am facing the exact same problem as @manudefrutosvila and I am sure as many others. To do things manually prevents us to deploy our app over our CI pipeline automatically.

**Comment by ludufre** [comment]
If this https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/537#issuecomment-770368704 works. I'll create a pull request.
