### ISSUE TITLE
Ionic onesignal startinit whitescreen

### ISSUE THREAD

**Issue by Samuel-Obosu** [OneSignal/OneSignal-Cordova-SDK#494]
**Description:**

I'm testing my ionic app on ios, the screen goes blank after the splash. I see these error in xcode:
1. ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter
2. ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}

Here is that bit of my code:
platform.ready().then(() => {

        console.log("Platform is ready.....Initializing one signal--------------");
        this.oneSignal.startInit(this.appId);

        this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.InAppAlert);

        this.oneSignal.handleNotificationReceived().subscribe(() => {
        // do something when notification is received
        });

        this.oneSignal.handleNotificationOpened().subscribe(() => {
          // do something when a notification is opened
        });

        this.oneSignal.endInit();

        this.oneSignal.getIds().then((id) => {
          console.log(id);
        });

(your description here)

**Environment**

com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-plugin-background-mode 0.7.2 "BackgroundMode"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.7.2 "Toast"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1. Add the onesignal-cordova-plugin to your project
2.  Initialize the plugin with your app ID in the platform.ready()

**Anything else:**

(crash stacktraces, as well as any other information here)
xxxx = App name

ERROR: HTTP Request (OSRequestRegisterUser) must contain app_id parameter
2019-03-27 12:37:52.050329+0000 xxxx[37661:553686] ERROR: Encountered error during push registration with OneSignal: Error Domain=OneSignalError Code=-1 "(null)" UserInfo={error=HTTP Request (OSRequestRegisterUser) must contain app_id parameter}
2019-03-27 12:37:52.050428+0000 xxxx[37661:553686] ERROR: Encountered error during email registration with OneSignal: (null)

**Comment by venomberry** [comment]
same issue here

**Comment by Samuel-Obosu** [comment]
So I added this snippet from https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension-recommend- to my AppDelegate.m in xcode.

// Replace 'YOUR_APP_ID' with your OneSignal App ID.
   OneSignal.initWithLaunchOptions(launchOptions,
       appId: "YOUR_ONESIGNAL_APP_ID",
       handleNotificationAction: nil,
       settings: onesignalInitSettings)
   
   OneSignal.inFocusDisplayType = OSNotificationDisplayType.notification;
   
   // Recommend moving the below line to prompt for push after informing the user about
   //   how your app will use them.
   OneSignal.promptForPushNotifications(userResponse: { accepted in
      print("User accepted notifications: \(accepted)")
   })


Now the application asks the user for permission to send notifications. But the screen is black, nothing shows, not even the splash.

**Comment by venomberry** [comment]
which snippet have you added; there is a lot of snippets in the document you sent.

**Comment by Samuel-Obosu** [comment]
```
#import <OneSignal/OneSignal.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
   [OneSignal initWithLaunchOptions:launchOptions
                              appId:@"YOUR_ONESIGNAL_APP_ID"
   				 handleNotificationAction:nil
                            settings:@{kOSSettingsKeyAutoPrompt: @false}];
   OneSignal.inFocusDisplayType = OSNotificationDisplayTypeNotification;
   
   // Recommend moving the below line to prompt for push after informing the user about
   //   how your app will use them.
   [OneSignal promptForPushNotificationsWithUserResponse:^(BOOL accepted) {
        NSLog(@"User accepted notifications: %d", accepted);
   }];
    
   return YES;
}
```
Adding this bit solved the black screen issue:
Note: Add this just before return YES
```
self.viewController = [[MainViewController alloc] init];
   return [super application:application didFinishLaunchingWithOptions:launchOptions];
```

**Comment by rgomezp** [comment]
@Samuel-Obosu @venomberry ,
Gonna go ahead and close this. If you wish to reopen just let us know with an @

**Comment by jcagme** [comment]
@Samuel-Obosu I'm facing the same issue. I added the snippet as you suggested to AppDelegate.m but I still get a white screen and the app gets stuck there. Do you know what I'm missing?

**Comment by rgomezp** [comment]
Howdy,
This seems to be a recurring problem in Cordova related to initializing OneSignal too late. Simply initialize it earlier in the app lifecycle.

Take a look at the following old issues:
* https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/422
* https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/450

**Comment by jcagme** [comment]
Thanks @rgomezp! Turned out I had a huge mess with my cordova and Pod versions (and maybe even the ionic CLI). After restoring correctly and degrading the CLI I was able to make this work.

**Comment by rgomezp** [comment]
Great to hear @jcagme .

Enjoy!
