### ISSUE TITLE
Unable to Upload to App Store 'The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription'

### ISSUE THREAD

**Issue by wi3land** [OneSignal/OneSignal-Cordova-SDK#496]
**Description:**
I am unable to upload to the App Store due to the app being rejected please see the reply below.

Dear Developer,   We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload   again.    "Missing Purpose String in Info.plist File. Your app's code   references one or more APIs that access sensitive user data. The app's   Info.plist file should contain a NSLocationAlwaysUsageDescription key with a   user-facing purpose string explaining clearly and completely why your app   needs the data. Starting spring 2019, all apps submitted to the App Store   that access user data will be required to include a purpose string.If you're   using external libraries or SDKs, they may reference APIs that require a   purpose string. While your app might not use these APIs, a purpose string is   still required. You can contact the developer of the library or SDK and   request they release a version of their code that doesn't contain the APIs.   Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."      "Missing Purpose String in Info.plist File. Your app's code   references one or more APIs that access sensitive user data. The app's   Info.plist file should contain a NSLocationWhenInUseUsageDescription key with   a user-facing purpose string explaining clearly and completely why your app   needs the data. Starting spring 2019, all apps submitted to the App Store   that access user data will be required to include a purpose string.If you're   using external libraries or SDKs, they may reference APIs that require a   purpose string. While your app might not use these APIs, a purpose string is   still required. You can contact the developer of the library or SDK and   request they release a version of their code that doesn't contain the APIs.   Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."      Best regards,   The App Store Team
--

**Environment**
1. What version of the Cordova SDK are you using? iOS 5.0.0
2. Provide a list of your project dependencies (using `cordova plugin list` or copy-pasting your config.xml)
cordova-plugin-advanced-http 2.0.6 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.2.0 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.1 "cordova-plugin-filepath"
cordova-plugin-filepicker 1.1.5 "File Picker"
cordova-plugin-fingerprint-aio 1.6.0 "FingerprintAllInOne"
cordova-plugin-inappbrowser 1.7.1-dev "InAppBrowser"
cordova-plugin-ionic 5.3.0 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-iroot 0.8.0 "iRoot"
cordova-plugin-native-spinner 1.1.3 "Native Spinner"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-pin-dialog 0.1.3 "PinDialog"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.1 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"

**Comment by jkasten2** [comment]
@MatrixMatt249 If you don't use location based notifications in your app I recommend removing the `CoreLocation.framework` from your app. OneSignal doesn't add the `CoreLocation.framework` automatically so one of the other plugins may have add it.

To remove the framework manually within code follow these steps.
1. Select your project on left.
2. Select your app target.
3. Open the "Build Phases" tab.
4. Expand the "Link Binary With Libraries"
5. Select `CoreLocation.framework` and press delete.
![image](https://user-images.githubusercontent.com/645861/55254340-d2bdfa00-5214-11e9-8614-e0a30094daa6.png)

Let us know if this solves your issue.

**Comment by MatrixMatt249** [comment]
Hi I am not using the CoreLocation.framework please see below.
![Screenshot 2019-04-01 at 09 04 38](https://user-images.githubusercontent.com/40289227/55312450-7d285e00-545d-11e9-870b-7b040b013bdc.png)

**Comment by MatrixMatt249** [comment]
I didn't find out why it randomly started requesting this string, I noticed the iOS sdk also has a similar issue outstanding. 

I just added the two lines below to my config.xml to fix the issue for now as I have a release i need to send out.

        <config-file parent="NSLocationAlwaysUsageDescription" platform="ios" target="*-Info.plist">
            <string>One Signal Notifications</string>
        </config-file>
        <config-file parent="NSLocationWhenInUseUsageDescription" platform="ios" target="*-Info.plist">
            <string>One Signal Notifications</string>
        </config-file>

**Comment by kennethwwu** [comment]
I still can submit my app for review even has this issue
