### ISSUE TITLE
 window.plugins.OneSignal.setEmail  is not setting the user's email

### ISSUE THREAD

**Issue by ebellumat** [OneSignal/OneSignal-Cordova-SDK#497]
**Description:**

The method  ``` window.plugins.OneSignal.setEmail  ```  does not save the e-mail of the users. In users list on OneSignal, the e-mail column was not setted. The only information appears on users list is the "-" on e-mail field. The callback function returns success.

**Environment:**

branch-cordova-sdk 2.6.24 "branch-cordova-sdk"
card.io.cordova.mobilesdk 2.1.0 "CardIO"
cordova-android-firebase-gradle-release 1.0.5 "cordova-android-firebase-gradle-release"
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-3dtouch 1.3.6 "3D Touch"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-firebase-analytics 1.1.1 "FirebaseAnalyticsPlugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.5.3 "cordova-plugin-googlemaps"
cordova-plugin-intercom 6.2.0 "Intercom"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.4.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.3.1 "cordova-support-google-services"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"

**Steps to Reproduce Issue:**

1. Call the function ```window.plugins.OneSignal.setEmail("test@gmail.com") ```
2. Wait the success callback function
3. Check the e-mail on list on OneSignal Dashboard.

**Comment by rgomezp** [comment]
Hello,
Sorry for the delay, just wanted to follow up regarding this issue. Could you please include the entire code snippet?

**Comment by ebellumat** [comment]
I already fixed the problem turning off one config about signature. Thanks!

**Comment by juanico18** [comment]
> I already fixed the problem turning off one config about signature. Thanks!

Hello @ebellumat What exactly do you turn off?
My problem is that we are setting email but email is set in a different player id instead of the one used in the device.
