### ISSUE TITLE
Latest version of the plugin is obsolete w.r.t. the Android SDK (3.10.7)

### ISSUE THREAD

**Issue by andreacimino** [OneSignal/OneSignal-Cordova-SDK#498]
The current version of the plugin is pointing to to an obsolete version of the OneSignal SDK com.onesignal:OneSignal:3.10.5 .
Is there something preventing to upgrade to  com.onesignal:OneSignal:3.10.7 ?

Thanks.

**Comment by rgomezp** [comment]
We will be releasing a new version shortly with the changes reflected. Thanks
