### ISSUE TITLE
Clear single push notification based on data/additionalData in push

### ISSUE THREAD

**Issue by entom** [OneSignal/OneSignal-Cordova-SDK#499]
**Description:**

I can clear all notifications with method provided in cordova onesignal plugin: clearOneSignalNotifications. But I need to clear single push notification based on some custom data provided in push.

**Environment**

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 8.0.0, browser 5.0.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.1, (and 39 other plugins)

System:

   NodeJS : v11.12.0 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
   Xcode  : Xcode 10.1 Build version 10B61

**Steps to Reproduce Issue:**

None

**Anything else:**

None

**Comment by rgomezp** [comment]
Could you please elaborate on the behavior you are looking for? Perhaps provide an example

**Comment by rgomezp** [comment]
Closing due to no response
