### ISSUE TITLE
Auto execute push notification?

### ISSUE THREAD

**Issue by jeancloude** [OneSignal/OneSignal-Cordova-SDK#500]
Hi,
with your plugin is possible to execute push automatically without click on badge?
I would like to launch automatically in silent mode all notified received also if my app is closed.

thanks!

**Comment by rgomezp** [comment]
I'm assuming you're asking about Android. You have to handle silent notifications through the Notification Extender Service: https://documentation.onesignal.com/docs/silent-notifications. If your app is in the background, you should still receive notifications unless you force-kill the app.

**Comment by jeancloude** [comment]
Yes for Android. Sorry not understand, with this plugin is not possible to click automatically push without action from user?

**Comment by rgomezp** [comment]
Hello @jeancloude ,
Take a look at our `[provideUserConsent](https://documentation.onesignal.com/docs/cordova-sdk#section--provideuserconsent-)` method in our docs.

**Comment by rgomezp** [comment]
Closing due to no response
