### ISSUE TITLE
Unity SDK - OneSignal.SetLocationShared(false) crashes the app if called before OneSignal.StartInit()

### ISSUE THREAD

**Issue by GabrielCoriiu** [OneSignal/OneSignal-Cordova-SDK#501]
**Description:**

Calling `OneSignal.SetLocationShared(false)` in Unity before calling `OneSignal.StartInit()` crahses the app

**Environment**
Latest Unity SDK and Unity 2018.3.11f1

**Steps to Reproduce Issue:**
Every time `OneSignal.SetLocationShared(false)` is called before `OneSignal.StartInit()` in the Start() method

**Comment by rgomezp** [comment]
Hello,
You must initialize OneSignal before doing anything else. Hope this helps.
