### ISSUE TITLE
NotificationExtenderService - app crash

### ISSUE THREAD

**Issue by jeancloude** [OneSignal/OneSignal-Cordova-SDK#502]
Hi, 
I need to update content through push notification without manual click by user.
I'm trying to implement NotificationExtenderService on my app.

added NotifcationService.java here: > platforms/android/app/src/main/java/com/example/hello

```
package com.hello.app;

import com.onesignal.OSNotificationPayload;
import com.onesignal.NotificationExtenderService;
import com.onesignal.OSNotificationReceivedResult;

public class NotificationService extends NotificationExtenderService {
    @Override
    protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
        return false;
    }
}
```
then added in AndroidManifest.xml

` </receiver>
        <service android:exported="false" android:name=".NotificationService" android:permission="android.permission.BIND_JOB_SERVICE">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
        </service>
    </application>`

When I send push, my app go in crash.

thanks

**Comment by jeancloude** [comment]
It was an my error (I'm new in Java) my correct package is  com.hello.app;

Now doesn't crash, but push will show same.

this is my PHP API

				$fields = array(
					'app_id' => $appId,
					'android_sound' => "",
					'headings' => "title",
					'contents' => "desc",
					'android_background_data' => true,
					'content_available' => true,
					'include_player_ids' => array("xxx"),
					'priority' => 10	
				  );
							
 this is my cordova code after on ready event

	   var notificationOpenedCallback = function(jsonData) {
		 console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
	    };

	   window.plugins.OneSignal
		.startInit("xxxx")
		.handleNotificationOpened(notificationOpenedCallback).endInit();

**Comment by rgomezp** [comment]
Hello @jeancloude ,
We have [documentation](https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) regarding exactly this. I didn't quite follow the second post. Were you able to resolve? Is this still a problem?

**Comment by rgomezp** [comment]
Closing due to no response
