### ISSUE TITLE
Huawei Devices: onNotificationReceived not firing when app is closed

### ISSUE THREAD

**Issue by justAguyTryingToLearn** [OneSignal/OneSignal-Cordova-SDK#505]
**Description:**

Okay so i have an ionic 4 app that receives notifications from one signal and i am saving those notifications in the local storage. When the app is running or is in background the notificationReceive handler is triggered and the data is saved to the local storage. However when the app is in closed the notificationReceive handler is not triggered and i am not able to save my notification data.
(your description here)

**Environment**

onesignal-cordova-plugin version - 2.4.6

 Cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
 Cordova Platforms     : android 8.0.0
 Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 9 other plugins) 

 ionic (Ionic CLI)             : 4.12.0 (/home/saurabh/node_modules/ionic)
 Ionic Framework               : @ionic/angular 4.1.2
 @angular-devkit/build-angular : 0.13.8
 @angular-devkit/schematics    : 7.2.4
 @angular/cli                  : 7.3.7
 @ionic/angular-toolkit        : 1.4.1

**Steps to Reproduce Issue:**

1. Open the app and register for one signal notifications.
2. Keep app in background ( onNotificationReceive is triggered on receiving notification ).
3.Close the app. ( onNotificationReceive is NOT triggered on receiving notification )

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Hello,
Can you provide some further info regarding your environment? What version of Android or iOS are you running? 

We also provide info on notification behavior in our [docs](https://documentation.onesignal.com/docs/how-notifications-work). Perhaps you can find some interesting insights there.

**Comment by zamora95** [comment]
Hello, 
I'm facing same issue in Ionic 3

my dependencies
"@ionic-native/onesignal": "^4.5.3",
"cordova-android": "6.4.0",
"cordova-ios": "^4.5.5",
"onesignal-cordova-plugin": "^2.4.6",

I'm testing in Huawei Android 8.0 and iOS 12.2, neither runs the code inside **handleNotificationReceived()** method when app is closed

**Comment by snt1017** [comment]
A lot of Huawei and Android >= 8 phones, close your app automatically to reduce battery use, you could use NotificationExtender (https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding) to handle the notification always, the "problem" is that you have to know Android native coding

**Comment by rgomezp** [comment]
Thanks for that answer. This is true about Huawei devices, though you should really be handling this in the notification extender service anyway no matter what the device.

**Comment by rgomezp** [comment]
Closing due to no response from op

**Comment by rcr47** [comment]
@rgomezp 
I want to save some data in storage when notification received. But handleNotificationReceived function is not working when my app is in killed/ swiped away.

Is that any way to handle this if my app is in kill (not forced kill)?

**Comment by snt1017** [comment]
You have to handle it native using NotificationExtender (https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding), maybe you can integrate it with another native plugin to storage it if you want to show it in the web view
