### ISSUE TITLE
Debug Native portion of OneSignal plugin

### ISSUE THREAD

**Issue by veso266** [OneSignal/OneSignal-Cordova-SDK#509]
**Description:**

I was wondering how can I tell OneSignal NativeSDK to print anything to Logcat from Cordova like you describe here: https://documentation.onesignal.com/docs/troubleshooting-android#section-no-users-showing-on-the-onesignal-dashboard

but here is if you are using OneSignal-Android-SDK while I am using Cordova Plugin

**Environment**

1. cordova --version
9.0.0 (cordova-lib@9.0.1)

ionic cordova --version
4.12.0

2. My plugin list
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.7 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1. standard OneSignal HelloWorld example
```
 // Enable to debug issues:
    this.oneSignal.setLogLevel({logLevel: 4, visualLevel: 4}); //this should be the same as  OneSignal.setLogLevel(OneSignal.LOG_LEVEL.VERBOSE, OneSignal.LOG_LEVEL.NONE); right?

    this.oneSignal.startInit('9a52db4a-07eb-42bf-8761-4c3b1e93bff8', '829060160759');

    this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.InAppAlert);

    this.oneSignal.handleNotificationReceived().subscribe(() => {
      // do something when notification is received
    });

    this.oneSignal.handleNotificationOpened().subscribe(() => {
      // do something when a notification is opened
    });

    this.oneSignal.endInit();
```

**Anything else:**

I would just like to debug One-Signal Native plugin (catching Log errors maybe redirecting them to console.log so I see them from console instead of Logcat)

Thanks for Anwsering and Best Regards

**Comment by rgomezp** [comment]
@veso266 ,
It sounds like you're looking for [this](https://documentation.onesignal.com/docs/cordova-sdk#section--setloglevel-)

**Comment by rgomezp** [comment]
Closing due to no response
