### ISSUE TITLE
iOS Home Screen Badge Count numbers are not incrementing past a count of 1 using PhoneGap Build app build process

### ISSUE THREAD

**Issue by jlomelino** [OneSignal/OneSignal-Cordova-SDK#511]
Issue Title: 
iOS Home Screen Badge Count numbers are not incrementing past a count of 1 using PhoneGap Build app build process

Environment:
Note that the config.xml below is our full config.xml. We have tried stripping everything down except for OneSignal and we have tried every version of CLI and OneSignal plugin version number we could try. 

<?xml version='1.0' encoding='utf-8'?>
	<widget id="com.ourappidhere.app" version="0.1.6" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:gap="http://phonegap.com/ns/1.0">
	    <name>Our Name Here</name>
	    <description>
	        Our Name Here
	    </description>
	    <author email="support@oursite.com" href="https://oursite.com">
	        Our Team
	    </author>
	    <content src="index.html" />
	

	    <preference name="phonegap-version" value="cli-7.0.1" />
	

	    
	    <platform name="android">
	        <allow-intent href="market:*" />
	    </platform>
	    <preference name="android-build-tool" value="gradle" />
	    <preference name="android-targetSdkVersion" value="26" />
	    <preference name="android-minSdkVersion" value="17" />
	    <plugin name="cordova-android-support-gradle-release">
	        <variable name="ANDROID_SUPPORT_VERSION" value="26.0.0" />
	    </plugin>
	

	    
	    <platform name="ios">
	        <allow-intent href="itms:*" />
	        <allow-intent href="itms-apps:*" />
	    </platform>
	    <config-file platform="ios" parent="NSPhotoLibraryUsageDescription" mode="replace">
	        <string>For uploading images</string>
	    </config-file>
	

	    
	    <plugin name="cordova-plugin-file" spec="^4.3.3" />
	

	    
	    <plugin name="cordova-plugin-device" spec="^2.0.2" />
	    <plugin name="cordova-plugin-android-permissions" spec="^1.0.0" />
	

	    
	    <gap:plugin name="onesignal-cordova-plugin" source="npm" spec="2.4.0" />
	

	    
	    <plugin name="cordova-plugin-camera" spec="^2.1.1" />
	    <plugin name="cordova-plugin-image-picker" spec="^1.1.3" />
	

	    
	    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
	    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
	    <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
	    <access origin="*" />
	    <allow-intent href="http://*/*" />
	    <allow-intent href="https://*/*" />
	    <allow-intent href="tel:*" />
	    <allow-intent href="sms:*" />
	    <allow-intent href="mailto:*" />
	    <allow-intent href="geo:*" />
	

	    
	    <preference name="DisallowOverscroll" value="true" />
	    <gap:plugin name="cordova-plugin-spinnerdialog" source="npm" />
	    <plugin name="cordova-plugin-dialogs" spec="^2.0.1" />
	    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
	

	    
	    <preference name="SplashMaintainAspectRatio" value="true" />
	    <platform name="android">
	        
	        <icon density="mdpi" src="www/res/icon/android/drawable-mdpi-icon.png" />
	        <icon density="hdpi" src="www/res/icon/android/drawable-hdpi-icon.png" />
	        <icon density="xhdpi" src="www/res/icon/android/drawable-xhdpi-icon.png" />
	        <icon density="xxhdpi" src="www/res/icon/android/drawable-xxhdpi-icon.png" />
	        <icon density="xxxhdpi" src="www/res/icon/android/drawable-xxxhdpi-icon.png" />
	

	        
	        <resource-file src="www/res/icon/android/res/drawable-mdpi/ic_stat_onesignal_default.png" target="res/drawable-mdpi/ic_stat_onesignal_default.png" />
	        <resource-file src="www/res/icon/android/res/drawable-hdpi/ic_stat_onesignal_default.png" target="res/drawable-hdpi/ic_stat_onesignal_default.png" />
	        <resource-file src="www/res/icon/android/res/drawable-xhdpi/ic_stat_onesignal_default.png" target="res/drawable-xhdpi/ic_stat_onesignal_default.png" />
	        <resource-file src="www/res/icon/android/res/drawable-xxhdpi/ic_stat_onesignal_default.png" target="res/drawable-xxhdpi/ic_stat_onesignal_default.png" />
	        <resource-file src="www/res/icon/android/res/drawable-xxxhdpi/ic_stat_onesignal_default.png" target="res/drawable-xxxhdpi/ic_stat_onesignal_default.png" />
	

	

	        
	        <splash density="land-ldpi" src="www/res/screen/android/drawable-land-ldpi-screen.png" />
	        <splash density="land-mdpi" src="www/res/screen/android/drawable-land-mdpi-screen.png" />
	        <splash density="land-hdpi" src="www/res/screen/android/drawable-land-hdpi-screen.png" />
	        <splash density="land-xhdpi" src="www/res/screen/android/drawable-land-xhdpi-screen.png" />
	        <splash density="land-xxhdpi" src="www/res/screen/android/drawable-land-xxhdpi-screen.png" />
	        <splash density="land-xxxhdpi" src="www/res/screen/android/drawable-land-xxxhdpi-screen.png" />
	        <splash density="port-ldpi" src="www/res/screen/android/drawable-port-ldpi-screen.png" />
	        <splash density="port-mdpi" src="www/res/screen/android/drawable-port-mdpi-screen.png" />
	        <splash density="port-hdpi" src="www/res/screen/android/drawable-port-hdpi-screen.png" />
	        <splash density="port-xhdpi" src="www/res/screen/android/drawable-port-xhdpi-screen.png" />
	        <splash density="port-xxhdpi" src="www/res/screen/android/drawable-port-xxhdpi-screen.png" />
	        <splash density="port-xxxhdpi" src="www/res/screen/android/drawable-port-xxxhdpi-screen.png" />
	    </platform>
	    <platform name="ios">
	        <icon height="57" platform="ios" src="www/res/icon/ios/icon.png" width="57" />
	        <icon height="114" platform="ios" src="www/res/icon/ios/icon@2x.png" width="114" />
	        <icon height="40" platform="ios" src="www/res/icon/ios/icon-40.png" width="40" />
	        <icon height="80" platform="ios" src="www/res/icon/ios/icon-40@2x.png" width="80" />
	        <icon height="50" platform="ios" src="www/res/icon/ios/icon-50.png" width="50" />
	        <icon height="100" platform="ios" src="www/res/icon/ios/icon-50@2x.png" width="100" />
	        <icon height="60" platform="ios" src="www/res/icon/ios/icon-60.png" width="60" />
	        <icon height="120" platform="ios" src="www/res/icon/ios/icon-60@2x.png" width="120" />
	        <icon height="180" platform="ios" src="www/res/icon/ios/icon-60@3x.png" width="180" />
	        <icon height="72" platform="ios" src="www/res/icon/ios/icon-72.png" width="72" />
	        <icon height="144" platform="ios" src="www/res/icon/ios/icon-72@2x.png" width="144" />
	        <icon height="76" platform="ios" src="www/res/icon/ios/icon-76.png" width="76" />
	        <icon height="152" platform="ios" src="www/res/icon/ios/icon-76@2x.png" width="152" />
	        <icon height="29" platform="ios" src="www/res/icon/ios/icon-small.png" width="29" />
	        <icon height="58" platform="ios" src="www/res/icon/ios/icon-small@2x.png" width="58" />
	        <icon height="87" platform="ios" src="www/res/icon/ios/icon-small@3x.png" width="87" />
	        <splash height="1136" platform="ios" src="www/res/screen/ios/Default-568h@2x~iphone.png" width="640" />
	        <splash height="1334" platform="ios" src="www/res/screen/ios/Default-667h.png" width="750" />
	        <splash height="2208" platform="ios" src="www/res/screen/ios/Default-736h.png" width="1242" />
	        <splash height="1242" platform="ios" src="www/res/screen/ios/Default-Landscape-736h.png" width="2208" />
	        <splash height="1536" platform="ios" src="www/res/screen/ios/Default-Landscape@2x~ipad.png" width="2048" />
	        <splash height="768" platform="ios" src="www/res/screen/ios/Default-Landscape~ipad.png" width="1024" />
	        <splash height="2048" platform="ios" src="www/res/screen/ios/Default-Portrait@2x~ipad.png" width="1536" />
	        <splash height="1024" platform="ios" src="www/res/screen/ios/Default-Portrait~ipad.png" width="768" />
	        <splash height="960" platform="ios" src="www/res/screen/ios/Default@2x~iphone.png" width="640" />
	        <splash height="480" platform="ios" src="www/res/screen/ios/Default~iphone.png" width="320" />
	    </platform>
	

	</widget>

Steps to Reproduce the Issue

Hello, I am starting a new issue here as this is a unique scenario compared to all the other related issues on this topic. The given solution in other issues is to ensure that App Groups are setup properly so that that the Notification Service Extension can be setup.

Note that these two steps do not seem to be possible with a PhoneGap build process. For our build process we include the required elements in config.xml and off we go. This has worked for two years without issues at all for our development app. However, now we are going to market to the app store and the new oneSignal app we created on a new onesignal app breaks the whole workflow.

Here are some details to help delineate the road block.

Definitions:
Staging: This is the original OneSignal account created a couple years ago and it has the OneSignal app that ties to my original app.

Production: This is the new OneSignal account. It was created a couple months ago and it has the OneSignal app that ties to my production app. The only difference here is the OneSignal app id and the web logic ties to a different server.

1)	The old/original app was created before June 2018. It continues to work without issues. We can build new iOS apps in PhoneGap build all day long without BadgeCount issues. It literally works perfectly. We have absolutely no need to add app groups or the notification service extension. I can spin up a brand new app, and as long as it is pointing to my old/original onesignal account and app that was created prior to June 2018 everything works perfectly.
2)	The new app that was created just a couple months ago is created in a new onesignal account as a new onesignal app. I can take the same iOS app that works perfectly on staging (number one above) and still receive push notifications all day long on all  my iOS devices, but the badge count will not go above 1. 
3)	I can use the OneSignal dashboard and send push notifications to all my devices on the staging app (original one signal account) and badge counts increment by one just fine. If I use the OneSignal dashboard and send push notifications to with the production app installed, tied to the production app, I receive push notifications just fine but the badge count is stuck on 1 and will not increment. On the production app I can push a notification from the OneSignal dashboard and specify a number to set the badge count to and it will set to that specific number. If I increase by a specific number there are difference that happen, they are just not accurate. For example "increase by" doesn't increase, it just sets as hard coded, so increase by 2 just sets the badge to 2, increase by 3 and it just says 3, instead of 5.

Summary Conclusion:
-	We worked to resolve iOS badge count issues with the OneSignal changes; determined that their build process has changed post-June 2018 and that they have created other specific iOS dependencies with notification service extensions that are not possible or accessible for us with PhoneGap Build
-	Something has changed it seems after June 2018 with new apps. Our old/original app is completely unaffected.
-	I need to have my new production OneSignal app perform like my old/original OneSignal app and not have the dependency on app groups and Notification Service Extension. This is not an issue at all on my original OneSignal account.
-	There is not way to add App Groups or the Notification Service Extension using a PhoneGap Build Process that relies on the OneSignal NPM plugin via config.xml.
-	we use phonegap build and as such cannot add service extension or app groups
-	The absolute latest combination of CLI version and onesignal plugin version is CLI 7.0.1 and onesignal npm version 2.4.1
-	We have been pointed back to the documentation for PhoneGap Build but the documentation does not reflect what is possible to do with PhoneGap Build. We are limited to the inclusion of the OneSignal plugin in config.xml and the build process handles everything else from there and it is all working perfectly for any app I build recently for my OneSignal staging account. 

Can you help us implement a way forward here? We really need to launch this into production and this is the last piece that is stopping us. 
Below is original correspondence for support. I have changed server names for client confidentiality.

OneSignal support dialogue is below to show what we have tried, which led to the summary conclusion above. We are stuck and cannot go to production without a build process in our new app that allows to deploy like our old/original app prior to June 2018. To reiterate that point, our old/original app works perfectly without any issues at all. We just need to get this working on the new app because that is the client account that holds the terms/privacy agreement with OneSignal and the client is paying the monthly bill to OneSignal for the paid account. 

===================================

Hello, I hope all is well! I have been working on an app for a customer for the past couple years and we are about ready to go into production. In the process we moved him over to his own paidi OneSignal account. That account is support@productionserver.com. In the process of doing so we setup an app named Productionserver and made a clone of everything from GitHub so there is a line-by-line exact match in the codebase. However, the production app is not incrementing home screen badge counts properly. We get a 1 count on the home screen badge count and every notification after that point doesn't increment the badge counter. I'm not sure where to go from here as everything appears to be an identical match between support@stagingserver.com(staging) and support@productionserver.com(production).

OneSignal: Hello
This is likely due to the Notification Service Extension not setup correctly.
Make sure to run through the setup guide again to make sure it is setup correctly for this new app: https://documentation.onesignal.com/docs/cordova-sdk-setup

Hi Jon,

Thanks for getting back with me.

My concern here is that there are references to xCode. In the two years of development leading up to this point we have exclusively used PhoneGap Build to handle everything with the build process. All of our Apple certificates and everything are managed through PhoneGap Build. The entire build process for us is built around that workflow and pipeline. We have never used XCode.

I looked at the link directly above the link you provided here https://documentation.onesignal.com/docs/phonegap-sdk-setup

This seems to be all par for the course until section 5, which links back to the same article with xcode setup.

Has something major changed with the SDK or build process so that it can't be done through PhoneGap build any more?

What are we supposed to do to move forward here? Our staging app that uses all the same processes we have used builds just fine without issues. We have the NPM plugins listed in our config.xml and everything works 100% perfectly. Can that not be replicated with new apps in phonegap build? Our entire codebase is identical between our OneSignal accounts.

Thanks for your help,

Josh

Hi Jon,

To add to this thread, I wanted to let you know that we reversed the process here and took the exact code on the production sever's build and moved it all over to our staging server. The only difference between the two is the app id / key for onesignal. The staging server works perfectly and the badge count auto-increments as expected. The production server does not. 

This isolation demonstrates a test where the only difference is the app id/key for onesignal. There is something different between the accounts. 

support@productionserver.com(production) does not work as expected (the home screen badge count does not increment past 1 on ios)
support@productionserver.com(staging) this works perfectly and badge counts increment as expected. 

support@productionserver.com will be a paid account at $99/month. It is the account that is not working and need this resolved before upgrading.

Thanks!

Josh

Hi Josh,
Just to make sure I understand.
The Staging and Production apps both can receive push and subscribe users.
The only issue is the Production app is not updating badges correctly.
I see you are sending push notificaitons with the increment by 1 option: https://app.onesignal.com/apps/a99105b9-e9b3-48a7-870e-21bd18746bb7/notifications
Is this on all your devices reproducible? If you uninstall the app (make sure the staging app is also uninstalled) and re-install Production does that fix it?

Would you be able to share the log from the device when you receive the notification so we can see what is going on: https://documentation.onesignal.com/docs/cordova-sdk#section--setloglevel-
PGB is having some issues and we are looking into it: https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/468
Worst case, would you be able to use the staging for production?
Thanks

Hi Jon,

Here are some data points.

The Staging and Production apps both can receive push and subscribe users.
Correct - no issues here

The only issue is the Production app is not updating badges correctly.
That is correct. To clarify, this happens with ios 11 and ios12 so it does not seem to be ios version related.

I see you are sending push notificaitons with the increment by 1 option
That is correct.

Is this on all your devices reproducible? If you uninstall the app (make sure the staging app is also uninstalled) and re-install Production does that fix it?
Yes, this is across all our ios devices. I have tried uninstalling the app and have reinstalled multiple times. This does not resolve the issue. 

Would you be able to share the log from the device when you receive the notification so we can see what is going on: 
I will try to get this but do not have xCode as we do all work with phoneGap build.

PGB is having some issues and we are looking into it: https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/468

I read through each of these comments. It does not seem this aligns with our situation. This scenario happens across iOS 10.3.3, 11 and 12 and is not isolated to iOS 12. 

Also, to clarify we have no issues doing builds in PhoneGap Build. Both the production app and staging app build with no issues and send push notifications just fine.

Worst case, would you be able to use the staging for production?
I wish we could. However, the production app is maintained by the end customer who has entered into the user agreement with OneSignal. The customer will be converting this to a paid account and will manage that billing through his account once this is working. As such we have to use his account for billing. 

We just stripped down both servers and spun them back up again with a fresh install from our Git repo. 

Literally, the only differences between the staging app and the production app are:
•	the package name (this represents staging and production apps)
•	the Apple certificate is different for production - it is a production certificate, not created through provisionator but straight through the certificate process prescribed by OneSignal. The staging server app uses the provisionator-generated apple certificate. The production server users a production certificate that was generated completely outside of provisionator using the processes described in the onesignal help.

To clarify, both production and staging both have working push notifications and there are no delivery issues. Both builds will get push notifications just fine. However, the badge counts are not incremented by one on the production app. 

Can you help us get a path to resolution so we can switch over this customer the paid OneSignal plan and launch this app?

Thanks!

Josh

https://s3.amazonaws.com/tw-desk/i/109746/attachment-inline/67167.20180210042543203.67167.20180210042543203Gg7Qr.jpg
Hi Jon,

Also, we have also tried bypassing the API completely and instead of initiating a push notification from within the app, to the API, we have tried sending straight from the OneSignal dashboard. We get the push notifications for the staging app, and for the production app just fine. However, we do not get badge count increments on the production app, but do on the staging app.

It seems like this behavior indicates that the issue persists even in a simple test like the above scenario. It seems like the OneSignal account for the production app is the issue. It's either that or the differences in the Apple certificate. It would seem though that if it were certificate issue that we would get push notifications at all for the production server?

Josh

https://s3.amazonaws.com/tw-desk/i/109746/attachment-inline/67167.20180210042543203.67167.20180210042543203Gg7Qr.jpg
One last detail here that came to mind. On the production server I received the following error when I first deployed the production app. I was not getting push notifications at all until I resolve this. Then once it was resolved this error stopped appearing. 

I wanted to offer this up if this was a part of the puzzle that would be helpful. 

https://s3.amazonaws.com/tw-desk/i/109746/attachment-inline/67167.20190509214905988.67167.20190509214905988ojByX.png

Josh

https://s3.amazonaws.com/tw-desk/i/109746/attachment-inline/67167.20180210042543203.67167.20180210042543203Gg7Qr.jpg

Hello,
The mismatched bundle id warning shouldn't affect badge behavior. I find it interesting that it works fine in one build but not the other. Are you 100% sure you set up App groups for bothbuilds?
https://documentation.onesignal.com/docs/cordova-sdk-setup#section-ios-add-app-groups-optional-but-recommended-
Best,
Rodrigo from OneSignal

Hi Rodrigo,
We're actually 100% sure that we've NEVER configured app groups at all. We're following the instructions for PhoneGap (link below), not Cordova.
https://documentation.onesignal.com/docs/phonegap-sdk-setup
You'll see that step 5 of those instructions indicate those steps are only needed for the PhoneGap CLI. Our builds are being done through PhoneGap's web platform at build.phonegap.com. There are no options there for setting up App Groups. As you can imagine this makes it very confusing because we can build our staging app and notifications work perfectly. When we change out the package name to match our APNS certificate and the onesignal app id, rebuild and deploy and notifications work fine, but the badge increment fails.
We've built and rebuilt hundreds of versions of the staging app over the last year or so and never had an issue.
Thanks for your help!

I wanted to follow up on this... we are needing to do a release and we still don't have a direction here. I have gone through all the instructions. It is literally not possible to add app groups as has been recommended. Our build process uses PhoneGap Build exclusively. I do not believe there is any way to insert Xcode into that build workflow. Furthermore, in researching different GitHub issue threads, it appears that there is a difference between app created in oneSignal prior to June 2018 compared to after June 2018. This is definitely the case for us. The staging app, which works perfectly is a couple years old from it's inception date, and the new production app (the one that does not increment badge counts correctly) has issues and it was created just in the last month. That is the only difference I can see and my gut says that is the hinge point of this issue. Please help us get untstuck so we can launch this to the customer and get them on a paid onesignal plan. Thanks!
To confirm, and provide a very simple test to show that this seems to be tied to the creation date of the app (pre June 2018 and post June 2018) you can login to onesignal dashboard of staging and app and send a manual push and the badge count increment works fine - but if you login to production dashboard and send a manual push it doesn't increment.

**Comment by rgomezp** [comment]
Closing due to resolved through support
