### ISSUE TITLE
[Android] App crashes on clean start when using firebase analytics

### ISSUE THREAD

**Issue by Maistho** [OneSignal/OneSignal-Cordova-SDK#512]
**Description:**
On Android, our app crashes on start with the following error:

```
FATAL EXCEPTION: main
Process: se.iFiske.fiskekort, PID: 9431
java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/se.iFiske.fiskekort-1/base.apk)
  at java.lang.VMClassLoader.findLoadedClass(Native Method)
  at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at android.app.ActivityThread.handleCreateService(ActivityThread.java:3310)
  at android.app.ActivityThread.-wrap5(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
  at android.os.Handler.dispatchMessage(Handler.java:105)
  at android.os.Looper.loop(Looper.java:156)
  at android.app.ActivityThread.main(ActivityThread.java:6524)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

The crash only appears when the app is started after clearing data/cache.

It seems to be caused by me having both onesignal and firebase-analytics. Maybe the wrong version of something is installed from the [gradle plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin), it seemed to have a bunch of logic for changing the versions of different firebase plugins.

I manually changed the build.gradle file to add firebase-messaging manually, which seems to solve the issue, but we treat the platform folder as build output, and this seems like a bug/regression since the error didn't appear last month.

```
    // Added this inside dependencies in build.gradle, after SUB-PROJECT DEPENDENCIES END
    implementation "com.google.firebase:firebase-messaging:18.0.+"
```

**Environment**

The app is open source, and can be accessed at https://github.com/ifiske/ifiske

**Steps to Reproduce Issue:**

1. Download the repo above
2. `npm install`
3. `npm run android`
4. App crashes

If the app doesn't crash, try clearing the app data and restarting it, then it should crash.

My best guess as to what this is caused by is that the onesignal gradle plugin doesn't take into account the version of firebase that is specified by cordova-plugin-firebase-analytics and installs an incompatible version of firebase-messaging.

Let me know if I can help resolve this quicker in any way.

**Comment by rodrigoreal** [comment]
Hey, i'm having the same exact problem as you, i have both of the plugins and the app crash the first time it is opened.
I was struggling here for hours, your solution worked perfect, the app is not crashing anymore.

**Comment by uguratmaca** [comment]
> Hey, i'm having the same exact problem as you, i have both of the plugins and the app crash the first time it is opened.
> I was struggling here for hours, your solution worked perfect, the app is not crashing anymore.

What is solution? Issue is stiil open and I'm getting this error some specific devices.

**Comment by Maistho** [comment]
@uguratmaca as a workaround, you may be able to add `cordova-plugin-firebase-messaging` to your app, but that might interfere with OneSignal so you'll have to test the notifications thoroughly.

**Comment by rgomezp** [comment]
This is something we have to update in the gradle plugin. Thanks for your patience while we resolve.

In the meantime, adding 18.0 manually should do the trick.

**Comment by Maistho** [comment]
Thanks, this seems to be resolved in version 1.12.2 of onesignal-gradle-plugin https://github.com/OneSignal/OneSignal-Gradle-Plugin/commit/db061ce723cb55ac286440824adbe7c98e01c690

When can we expect an update for onesignal-cordova-plugin?

**Comment by rgomezp** [comment]
@Maistho ,
Yes this should be fixed now. 

It's hard to say. Is there a reason you ask? We very recently updated the plugin (couple weeks ago)

**Comment by jkasten2** [comment]
@Maistho @rgomezp A version range is used for the gradle plugin so it will use the updated version automatically.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/build-extras-onesignal.gradle#L21

However you might need to do a clean build for Cordova to pick-up the new plugin version.

**Comment by Maistho** [comment]
Alright, thanks for the heads up, I'll reopen the issue if it's not resolved.

Thanks for the quick fix!

**Comment by shofiulla-iota** [comment]
Thank you so much

**Comment by arutkayb** [comment]
Followed the guideline :
https://github.com/OneSignal/OneSignal-Gradle-Plugin
instead of 
https://documentation.onesignal.com/docs/flutter-sdk-setup because the gradle levels are wrong

Also added
implementation 'com.google.firebase:firebase-messaging:18.0.0'
implementation 'com.google.firebase:firebase-iid:18.0.0'
into app level gradle and solved

**Comment by rgomezp** [comment]
Howdy,
We've updated the documentation with the updated version range. Cheers

**Comment by raja110199** [comment]
Sir, I am facing the same issue, after implemented  this code "implementation "com.google.firebase:firebase-messaging:18.0.+"".

Please help me to get out of this. it's spoiling the impression of my app.
