### ISSUE TITLE
User not really subscribed when getPermissionSubscriptionState() says it is

### ISSUE THREAD

**Issue by allanpoppe** [OneSignal/OneSignal-Cordova-SDK#513]
**Description:**
Some users are experiencing not receiving my notifications. Investigating the issue, I found out that `getPermissionSubscriptionState().subscriptionStatus.subscribed is returning true` and `getPermissionSubscriptionState().permissionStatus.state is returning 1` (that means subscribed on Android), but when searching for the Player ID on OneSignal console, I found out that the user is not really subscribed. See images below.

EDIT:
I think this has something to do with uninstalling & reinstalling the app.

EDIT 2:
This is not relative to uninstalling & reinstalling. One of my associates just sent one test notification to himself, which he received. Then he sent another, and didn't received. When we checked the console, he was Unsubscribed. He didn't uninstalled the app. He just closed it.

**Environment**
```
"ionic-angular": "3.9.2"

cordova -v
8.1.2 (cordova-lib@8.1.1)

node -v
v8.9.3

cordova plugin list
branch-cordova-sdk 3.1.5 "branch-cordova-sdk"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-android-support-gradle-release 1.4.5 "cordova-android-support-gradle-release"
cordova-clipboard 1.2.1 "Clipboard"
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appcenter-analytics 0.1.8 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.8 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.8 "App Center shared code for Cordova"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-calendar 5.1.2 "Calendar"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-chooser 1.2.5 "Chooser"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.0.3 "CropPluginWithRatio"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-filepicker 1.1.4 "File Picker"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.2 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-qrscanner 2.6.0 "QRScanner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-vibration 3.1.0 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
es6-promise-plugin 4.2.2 "Promise"
me.tonny.cordova.plugins.multidex 0.1.0 "Cordova Multi Dex"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
onesignal-cordova-plugin 2.4.3 "OneSignal Push Notifications"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"
```

```
this.oneSignal.startInit(##OneSignalID###, ##PushSenderID###);
this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.Notification);
this.oneSignal.iOSSettings({ kOSSettingsKeyAutoPrompt: false, kOSSettingsKeyInAppLaunchURL: false });
this.oneSignal.handleNotificationOpened().subscribe((notificationData) => {
	this.openPush(notificationData);
});
this.oneSignal.endInit();

async getPermission() {
	const permission = await this.oneSignal.getPermissionSubscriptionState();
	if (permission.subscriptionStatus.subscribed && (
		(this.platform.is('android') && permission.permissionStatus['state'] === 1) ||
		(this.platform.is('ios') && permission.permissionStatus.status === 2))
	) {
		return { permissionStatus: 'subscribed', subscriptionStatus: permission.subscriptionStatus };
	} else if (permission.permissionStatus.hasPrompted &&
		!permission.subscriptionStatus.subscribed && (
			(this.platform.is('android') && permission.permissionStatus['state'] === 1) ||
			(this.platform.is('ios') && permission.permissionStatus.status === 2))
	) {
		return { permissionStatus: 'undefined', subscriptionStatus: permission.subscriptionStatus };
	} else {
		return { permissionStatus: 'unsubscribed', subscriptionStatus: permission.subscriptionStatus };
	}
}
```
![image](https://user-images.githubusercontent.com/19921033/57810529-5d63a580-773e-11e9-9ba4-f76f01536802.png)

![image](https://user-images.githubusercontent.com/19921033/57809226-699a3380-773b-11e9-8b9a-2985d4aa1c2d.png)

**Comment by rgomezp** [comment]
Hello,
This behavior is very strange. Could you please try to send a notification, check the dashboard (refresh), send a second notification, check the dashboard (refresh) in that order?

**Comment by allanpoppe** [comment]
Right after sending the first notification, the Subscribed field appears as Unsubscribed in the dashboard.

Then, I close the app and reopen it (using Android). The field appears as Subscribed again (intended behavior if user is not subscribed).

Sending a notification will make it go to Unsubscribed again. And so this goes.

I'm not even receiving the notification now.

By any chance this has to be to the fact I'm using Ionic Native's outdated OneSignal plugin?

**Comment by rgomezp** [comment]
I really have no idea what could be happening here. It certainly is possible given that is not a plugin that we maintain. See if you can reproduce it in a blank project. If so, send it to us and we will take a closer look when possible. Thanks!

**Comment by byukihara** [comment]
Hey, we're having the same issue on many users..
I tried update to the last plugin version to solve the problem, but still not working =(

**Comment by rgomezp** [comment]
@byukihara , @allanpoppe 
Could you please reproduce in a blank project and send it to us through our support channel at onesignal.com ? Thanks

**Comment by rgomezp** [comment]
Is this still an issue?

**Comment by rgomezp** [comment]
Closing due to no response
