### ISSUE TITLE
Outdated Ionic Native plugin

### ISSUE THREAD

**Issue by allanpoppe** [OneSignal/OneSignal-Cordova-SDK#514]
**Description:**
@ionic-native/onesignal is outdated, doesn't have setExternalUserId method.

**Comment by rgomezp** [comment]
Hello,
Please make sure you have the right version as this method should be there.

**Comment by allanpoppe** [comment]
https://github.com/ionic-team/ionic-native/blob/master/src/@ionic-native/plugins/onesignal/index.ts

The method is not there.

**Comment by rgomezp** [comment]
You are correct, my apologies. We actually don't own or maintain that 3rd party library. I would encourage you to create an issue in that repository or submit a PR to them. Sorry about that!

**Comment by allanpoppe** [comment]
Thank you, just created an issue.

https://github.com/ionic-team/ionic-native/issues/3032
