### ISSUE TITLE
How to actually show the notification in the notification bar 

### ISSUE THREAD

**Issue by thekingrenz23** [OneSignal/OneSignal-Cordova-SDK#515]
the code that is included as a sample in the documentation only consoles the notification.
how can i put that on notification bar?

**Comment by rgomezp** [comment]
Hello,
You should be seeing the notification in the shade. Could you please provide us with more info regarding the issue you're seeing. We have an issue template you can follow when you create a new issue.

**Comment by rgomezp** [comment]
Closing due to no response
