### ISSUE TITLE
We receive userId but no pushToken.

### ISSUE THREAD

**Issue by zaitsev1393** [OneSignal/OneSignal-Cordova-SDK#516]
**Description:**
So we don't receive pushToken although userId is ok.
Well actually we are using Ionic and after migration from 3 to 4 and updating from 2.3.3 to 2.4.7 i don't have pushToken anymore:
http://joxi.ru/82395R6F94yZEr.jpg

and here you can see we can't subscribe to the onesignal, after pushing notifications request popup although permissionStatus is 2 (you can see it just below the arrow) 
http://joxi.ru/KAxnjWxIZ89WZm.jpg

**Environment**
1. 2.4.7
2.
branch-cordova-sdk 3.1.5 "branch-cordova-sdk"
com-sarriaroman-photoviewer 1.2.1 "PhotoViewer"
cordova-clipboard 1.2.1 "Clipboard"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase-analytics 1.0.1 "FirebaseAnalyticsPlugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googleplus 7.0.1 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.2.3 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
cordova.plugins.diagnostic 4.0.11 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.4.7 "OneSignal Push Notifications"

**Comment by rgomezp** [comment]
Hello,
Can you please provide more details regarding your environment? For example, you can't be running it in a simulator. If you are building online, you may need to re-upload your provisional profile. There are lots of possibilities you aren't actually getting subscribed but we need to understand what your setup is to be able to help you. Thanks

**Comment by absolutsoul** [comment]
I’m having the same problem, do you know if it works with a previous version of the plugin?

**Comment by rgomezp** [comment]
@absolutsoul ,
Please provide your environment details. Take a look at our issue template for reference

**Comment by zaitsev1393** [comment]
Hi, I use xcode and real device (iphone 7+). Also:
![image (6)](https://user-images.githubusercontent.com/20440405/58586497-dfd28600-8263-11e9-8ded-18a5adeb457c.png)

**Comment by epetre** [comment]
Could this be a compatibility issue with another plugin? I don't see another plugin in that list that implements Push Notification.

**Comment by rgomezp** [comment]
It could be, I've attempted to reproduce but it's working for me so I'll have to dig further. If you can share your project or reproduce it would help expedite our support process. Thanks

**Comment by epetre** [comment]
Me and @zaitsev1393  work on the same project. 

Sadly, we can't share the full source code as it is an App on the Appstore and we didn't open source it.

However, I was able to reproduce exactly the same issue in my environment on an iPhone 5S.

I am still looking into the issue right now to figure out what seems to be an incompatibility with another plugin. We uninstalled the plugin and reinstalled without luck. I will keep looking and report here.

Since it's only happening in iOS, I could share the list of our other pods.
![List of our other pods](https://i.imgur.com/OwU6I3s.jpg)

**Comment by epetre** [comment]
It started working again after reverting the version and removing firebase.
I since added firebase and brought back OneSignal with the latest version and it works.
I uninstalled pods too and reinstalled the platform, I don't know for sure what did the trick but it's working now.

Thx.
