### ISSUE TITLE
Repeat notification sound

### ISSUE THREAD

**Issue by Swapniltdatalogy** [OneSignal/OneSignal-Cordova-SDK#519]
**Description:**

How we will repeat the notification sound play ?

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
I'm sorry but I don't understand your question

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by johnsonsy** [comment]
@rgomezp I think @Swapniltdatalogy means he wants the sound play repeat like a ringtone

**Comment by johnsonsy** [comment]
I also wanna know plz

**Comment by Swapniltdatalogy** [comment]
Yes right @johnsonsy , Still didn't find any solution , could you please help me.
Thanks.

**Comment by johnsonsy** [comment]
I also wanna know
