### ISSUE TITLE
Support for TypeScript and/or Ionic Native

### ISSUE THREAD

**Issue by nunoarruda** [OneSignal/OneSignal-Cordova-SDK#52]
Please make type annotations so TypeScript developers can have type checking, autocompletion support and avoid compilation/console errors: 
<img width="235" alt="screen shot 2016-05-08 at 08 47 42" src="https://cloud.githubusercontent.com/assets/1189149/15094489/bd99afbc-14f9-11e6-9a92-2d0d7adf9e96.png">
<img width="575" alt="screen shot 2016-05-08 at 08 48 34" src="https://cloud.githubusercontent.com/assets/1189149/15094491/c7f190d8-14f9-11e6-93af-1d7e584059f3.png">
<img width="1269" alt="screen shot 2016-05-08 at 21 06 19" src="https://cloud.githubusercontent.com/assets/1189149/15096949/db02f696-1560-11e6-8958-841a10b5c0f2.png">

An [Ionic Native](https://github.com/driftyco/ionic-native) wrapper for your cordova plugin would be nice too.

**Comment by jkasten2** [comment]
Thanks for the suggestions, this is a lower priority for us but feel free to fork our repo and make a pull request.

**Comment by jpasillas** [comment]
Hi @nunoarruda
I have the same problem ¿Could you solve this issue?

**Comment by paulocarvalhodesign** [comment]
Surprise that this is low priority, typescript is become ever so big and that could infact be a deal breaker for a new user, like me 😂😉

**Comment by jkasten2** [comment]
Can you try `window["plugins"]` as a work around?

Since we support Cordova CLI, Ionic, PhoneGap Build(PGB), and Intel XDK we have in ensure any change did not break these forks.

Pull requests or any additional information on required code changes are welcome.

**Comment by nunoarruda** [comment]
Ionic 2 now breaks if there is any TypeScript errors. A temporary workaround is to declare window above the decorator:

`declare var window;`

**Comment by dylanvdmerwe** [comment]
Pretty certain this can be closed? http://ionicframework.com/docs/v2/native/onesignal/
