### ISSUE TITLE
How do I handle silent push notification in android? content_available = 1

### ISSUE THREAD

**Issue by btate** [OneSignal/OneSignal-Cordova-SDK#520]
**Description:**

I can't find a way to handle silent notifications in android. I'm aware of the documentation for NotificationExtenderService, but that only helps in the native java world. The scenario I'm trying to solve for is I need to let the app know that a piece of data is no longer relevant, so it can be removed from the screen. So I need access to the push notification payload in the angular application. 

**Environment**

1. What version of the Cordova SDK are you using?
**8.1.1**
2. Provide a list of your project dependencies (using `cordova plugin list` or copy-pasting your config.xml)
branch-cordova-sdk 2.6.24 "branch-cordova-sdk"
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-background-geolocation 2.13.2 "BackgroundGeolocation"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-calendar 5.1.4 "Calendar"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-secure-storage 3.0.1 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.2.2 "Launch Navigator"

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Unfortunately, you will have to write a bit of native code here

**Comment by rwillett** [comment]
You do not need to do any Java programming as Android silent notification just works using content_available=1 and thats it.

That what we do, it's not documented but it does work.

**Comment by rgomezp** [comment]
Howdy @rwillett ,
Thanks for your input. While it's a good thought, you would be losing some events with this implementation. Your idea will work if the app is out of focus (in the background). However, if you swipe it away, the app would not receive those events.

**Comment by rwillett** [comment]
The way we handle that is that the Android device acknowledges the silent push notification once received using a simple REST API. 

If it doesn't acknowledge the silent push, we send a full notification afterwards to the Android device. Pretty simple and takes care of when the application is swiped away.

Rob

**Comment by rgomezp** [comment]
@rwillett ,
Ah okay. That should work then. Thanks for your input! I will go ahead and close since I haven't heard back from OP.
