### ISSUE TITLE
Cannot use SDK in a newly created app.

### ISSUE THREAD

**Issue by mluis** [OneSignal/OneSignal-Cordova-SDK#526]
**Description:**

Creating a new ionic v1 app, installing the plugin, and running through the tutorial, the app shows a white screen after writing the OneSignal javascript code.

**Environment**

1.
 ```
$ ionic info

Ionic:

   Ionic CLI         : 5.2.1 (/Users/miguelluis/.nvm/versions/node/v11.3.0/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.22

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 5 other plugins)

Utility:

   cordova-res : 0.5.1 (update available: 0.6.0)
   native-run  : 0.2.7 

System:

   Android SDK Tools : 26.1.1 (/Users/miguelluis/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.1
   NodeJS            : v11.3.0 (/Users/miguelluis/.nvm/versions/node/v11.3.0/bin/node)
   npm               : 6.10.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61
```
2. 
```
$ ionic cordova plugin list
> cordova plugin ls
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 2.4.7 "OneSignal Push Notifications"
```

**Steps to Reproduce Issue:**

1. ionic start myApp tabs --type ionic1
2. ionic cordova plugin add onesignal-cordova-plugin
3. ionic cordova platform add ios
4. Run the [tutorial](https://documentation.onesignal.com/docs/ionic-sdk-setup).

**Anything else:**

(crash stacktraces, as well as any other information here)
```
...
2019-07-11 17:27:15.822086+0000 MyApp[2956:438045] User accepted notifications: 1
...
```

**Comment by rgomezp** [comment]
Please use our logging [method](https://documentation.onesignal.com/docs/cordova-sdk#section--setloglevel-) to get more info in the logs regarding the initialization of the ONeSignal SDK. Thanks!

**Comment by mluis** [comment]
@rgomezp it is not possible. If you run into the procedures of this issue that line of code will show the white screen.

**Comment by rgomezp** [comment]
Howdy,
Could you please contact us through our support channel at onesignal.com? Please include the project or a blank project reproducing the issue in a zip file so we can take a closer look at what is happening.

Thanks
