### ISSUE TITLE
App crash on some android device with errors (Block-scoped declarations (let, const, function, class) not yet supported outside strict mode polyfills.js:2561, Uncaught Error: Module onesignal-cordova-plugin.OneSignal does not exist. vendor.js:50686 Uncaught TypeError: (intermediate value).fill is not a function)

### ISSUE THREAD

**Issue by markusila** [OneSignal/OneSignal-Cordova-SDK#532]
**Description:**

App stuck on splash screen due to these error on some android devices, API is 23
- errors (Block-scoped declarations (let, const, function, class) not yet supported outside strict mode polyfills.js:2561,
- Uncaught Error: Module onesignal-cordova-plugin.OneSignal does not exist. vendor.js:50686
- Uncaught TypeError: (intermediate value).fill is not a function)

**Environment**

cordova-background-geolocation 3.0.8 "BackgroundGeolocation"
cordova-background-geolocation-firebase 0.0.1 "CDVBackgroundGeolocationFirebase"
cordova-plugin-background-fetch 5.5.0 "CDVBackgroundFetch"
cordova-plugin-battery-status 2.0.2 "Battery"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic 5.4.4 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.2 "ImagePicker"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
onesignal-cordova-plugin 2.5.0 "OneSignal Push Notifications"

**Comment by nyancodeid** [comment]
find file `OneSignal.js` on `plugins/onesignal-cordova-plugin/www`. and find `let obj = {};` replace with `var obj = {};`
next replace same code on `platform/android/src/main/assets/www/onesignal-cordova-plugin/www/OneSignal.js`

**Comment by rgomezp** [comment]
Thanks for pointing this out. The changes are included in #535

**Comment by acedigibits** [comment]
Block-scoped declarations (let, const, function, class) not yet supported in NotificationReceived.js . Please do not use let, const. There are still many older Android devices  that will not receive es6 support but need to be supported.

**Comment by jkasten2** [comment]
@acedigibits Thanks for the feedback, I believe it is Android 4.4 and older do no support ES6, since the WebView is stuck on Chrome 30 something.
What percentage of your users would that effect?

**Comment by acedigibits** [comment]
@jkasten2 , i tested it on android 6.0 . i know percentage of people on these versions would be very low, but its just a question of using var instead of let , which is a very small change to maintain support for these versions. 

https://gs.statcounter.com/os-version-market-share/android , suggests android versions 5, 6 and 7 hold approx 6 - 8% of total market.

**Comment by jkasten2** [comment]
> As new versions of Chromium become available, users can update from Google Play to ensure they get the latest enhancements and bug fixes for WebView, providing the latest web APIs and bug fixes for apps using WebView on Android 5.0 and higher.

https://developer.android.com/about/versions/lollipop#WebView

The Android 5.0+ devices should update the WebView automatically, maybe your test devices (and some of your customers) haven't update for some reason.

Regardless, this SDK should still support Android 4.1 - Android 4.4 for the time being.

@acedigibits Could you open a new issue with your findings? (I see some in [`const` usages in OneSIgnal.js](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/3.0.2/www/OneSignalPlugin.js#L150) as well.)
Also PRs are welcome if you would like to contribute code as well.

**Comment by acedigibits** [comment]
> > As new versions of Chromium become available, users can update from Google Play to ensure they get the latest enhancements and bug fixes for WebView, providing the latest web APIs and bug fixes for apps using WebView on Android 5.0 and higher.
> 
> https://developer.android.com/about/versions/lollipop#WebView
> 
> The Android 5.0+ devices should update the WebView automatically, maybe your test devices (and some of your customers) haven't update for some reason.
> 
> Regardless, this SDK should still support Android 4.1+ for the time being.
> 
> @acedigibits Could you open a new issue with your findings? (I see some in [`const` usages in OneSIgnal.js](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/3.0.2/www/OneSignalPlugin.js#L150) as well.) Also PRs are welcome if you would like to contribute code as well.

i tested it further and realized it was not issue of let, const but of not using "use strict" ; After i added this at the beginning, all worked well.

**Comment by jkasten2** [comment]
@acedigibits Could you let us know where exactly you see this error so we can reproduce it?
