### ISSUE TITLE
Error: Mismatched User Environment (Production)

### ISSUE THREAD

**Issue by Aarbel** [OneSignal/OneSignal-Cordova-SDK#538]
Faced this error in Onesignal Settings while testing notifications under dev, and building many apps.
![image](https://user-images.githubusercontent.com/25119847/63009007-f6ac7000-be83-11e9-901e-56265ce3a2ca.png)

```
Mismatched User Environment (Production)
Apple returned a BadDeviceToken error. Some users are tied to a different environment from your sending environment.
```

Solved with setting the Xcode build environment to Legacy Build System.
![image](https://user-images.githubusercontent.com/25119847/63009167-425f1980-be84-11e9-99a0-0a4fb7868705.png)
![image](https://user-images.githubusercontent.com/25119847/63009183-48ed9100-be84-11e9-9ca5-e7b7687a5020.png)

**Comment by jkasten2** [comment]
@Aarbel The is an issue with `cordova-ios` version 4 and the new Xcode 10 build system.  `cordova-ios` 5.0.0 fixed this issue with XCode 10

**Comment by Aarbel** [comment]
thank you @jkasten2
