### ISSUE TITLE
Error : Method 'setInAppMessageClickHandler:' not defined in Plugin 'OneSignalPush'

### ISSUE THREAD

**Issue by Aarbel** [OneSignal/OneSignal-Cordova-SDK#539]
Error in xcode debug logs :
![image](https://user-images.githubusercontent.com/25119847/63015323-e77fef00-be90-11e9-9033-1d64f772e425.png)

```
ERROR: Method 'setInAppMessageClickHandler:' not defined in Plugin 'OneSignalPush'
FAILED pluginJSON = ["OneSignalPush1426266551","OneSignalPush","setInAppMessageClickHandler",[]]
```

Don't know the impact of this error

**Comment by Aarbel** [comment]
The only insight i have is that the second line `FAILED pluginJSON = ["OneSignalPush1426266551","OneSignalPush","setInAppMessageClickHandler",[]]` disappears when selecting the legacy build system with cordova-ios < 5.0.0

**Comment by rgomezp** [comment]
Are you on the latest version of the SDK?

**Comment by Aarbel** [comment]
Yes `2.5.2` 

I use cordova-cli 8.0, Legacy Build Settings, iOS 10.3.3

**Comment by rgomezp** [comment]
@Aarbel ,
This will be fixed in the next version of the SDK. Thanks for bringing this up!

**Comment by Aarbel** [comment]
Great, thank you for the high maintance of this plugin ;)

**Comment by rgomezp** [comment]
@Aarbel , 
It's our pleasure. Enjoy!

**Comment by byukihara** [comment]
@rgomezp Thank you the good work that you're doing.
 I just updated my app to this new version, but my notifications doesn't works anymore I saw the same problem on XCode console.

ERROR: Method 'setInAppMessageClickHandler:' not defined in Plugin 'OneSignalPush'
2019-08-30 17:43:18.695531-0300 c2s[6399:1506916] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["OneSignalPush1242222751","OneSignalPush","setInAppMessageClickHandler",[]]

Do you have estimate when launch the new release?

Thank you so much

**Comment by AnangKurendi** [comment]
I have some issue also sir @rgomezp
![image](https://user-images.githubusercontent.com/34293888/64163358-4ff83580-ce6b-11e9-8734-70c4de42f239.png)
```
[4688:2847352] ERROR: Method 'setInAppMessageClickHandler:' not defined in Plugin 'OneSignalPush'
[4688:2847352] FATAL: OneSignal AppId format is invalid.
```
thank sir

**Comment by rgomezp** [comment]
We're working hard to make sure the change is released asap. Thanks for your patience

**Comment by JayBizzle** [comment]
We are also seeing this issue, holding out for the new release to fix it.

In the meantime, are we okay releasing new app versions? Ive test our app and everything relating to push notifications is working as expected.

Thanks

**Comment by rgomezp** [comment]
This has been resolved in the latest version of the SDK. Please update
