### ISSUE TITLE
Ionic 4 + One Signal handleNotificationOpened doesn't get fired when app is closed iOS

### ISSUE THREAD

**Issue by bexarkr** [OneSignal/OneSignal-Cordova-SDK#546]
handleNotificationOpened doesn't get fired when the app is closed on iOS, but when app is opened handleNotificationOpened fires perfectly

Im using onesignal-cordova-plugin: 2.5.2

Here is the code:

const iosSettings = {};
            iosSettings['kOSSettingsKeyAutoPrompt'] = false; 
            iosSettings['kOSSettingsKeyInAppLaunchURL'] = false; 
            const notificationOpenedCallback = (jsonData) => {
                console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
                return this.router.navigate([jsonData.notification.payload.additionalData.url]);
            };
            window['plugins'].OneSignal
                .startInit('APP_ID', 'SENDER_ID')
                // .iOSSettings(iosSettings)
                .handleNotificationOpened(notificationOpenedCallback)
                .endInit();

**Comment by rgomezp** [comment]
Please follow our issue template
