### ISSUE TITLE
Get received notifications list/count

### ISSUE THREAD

**Issue by juanjoseadan** [OneSignal/OneSignal-Cordova-SDK#547]
**Description:**
Hello everyone, I would like to make a feature request for this incredible service. I'm currently using OneSignal with Ionic Framework 3/4, and they are working great, the problem I'm having is that I cannot get the notifications received if I open the app directly by clicking the app icon (iOS or Android). If we could get a function or something to get a list of received notifications while the app wasn't active, it would be awesome.

Correct me if I'm wrong, but right now there is not a way to get the notification count with any other plugin or this one.

Thanks!

**Comment by rgomezp** [comment]
Thanks for your request. This does not exist currently. I will close this though we have made a note and will track it internally. Thanks again
