### ISSUE TITLE
Apple starts to rejecting apps with UIWebView

### ISSUE THREAD

**Issue by Nodonisko** [OneSignal/OneSignal-Cordova-SDK#549]
Apple starts to rejecting apps with UIWebView APIs.

> Dear Developer,
>
>We identified one or more issues with a recent delivery for your app, "MALL Pay accept" 1.0 (287). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
>ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
>
>After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
>
>Best regards,
>
>The App Store Team

**Steps to Reproduce Issue:**
  1. Try publish app to App Store

**Comment by Aarbel** [comment]
Normally you can easily use WkWebview instead of UIWebview.

**Comment by Nodonisko** [comment]
@Aarbel Yea, but it's used somewhere inside iOS SDK so I can't change it.

**Comment by Aarbel** [comment]
Don't have the problem my side, i use pure Cordova on my project and plugin `cordova-plugin-wkwebview-engine`

**Comment by Nodonisko** [comment]
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/522

**Comment by Aarbel** [comment]
Ok thank you @Nodonisko, didn't had any error in XCode, just submitted my app and will see if refused.

Otherwise this issue is critical

**Comment by rgomezp** [comment]
This was fixed in the latest iOS Native SDK. We will be releasing a Cordova update shortly, though you should be able to modify the plugin directly to pull 2.11.0

**Comment by rgomezp** [comment]
this has now been shipped. please upgrade the Cordova SDK to get the changes

**Comment by jkasten2** [comment]
This fix was included in [OneSignal-Cordova-SDK 2.10.2](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.6.0) released Sep. 16 2019.
