### ISSUE TITLE
How to set additonal launch url

### ISSUE THREAD

**Issue by subhash8108** [OneSignal/OneSignal-Cordova-SDK#55]
Hello,

I have no idea, how to set additional launch url in cordova with code?

![onesignal 2016-06-01 16-36-22](https://cloud.githubusercontent.com/assets/542535/15707592/1e9c9bb4-2817-11e6-8684-a151312725a6.png)

please help me.

Thanks & Regards
Subhash Patel

**Comment by subhash8108** [comment]
Hello,

Onesignal site through perfect working launch url, but same not set launch url with cordova code.
Is it possible for puch notifcation with launch url?

Please help me

Thanks & Regards
Subhash Patel

**Comment by jkasten2** [comment]
The 'url' field is the same as the dashboard "Launch URL" option. See our [create notification](http://documentation.onesignal.com/v2.0/docs/notifications-create-notification) REST API POST call.
