### ISSUE TITLE
[Documentation] Additional libraries required to link OneSignal iOS SDK 2.11.0

### ISSUE THREAD

**Issue by codinronan** [OneSignal/OneSignal-Cordova-SDK#552]
**Description:**

**This doesn't require action on OneSignal's part AFAIK** except for maybe an edit to the documentation. It is for information for other developers who may come looking for this.

The new OneSignal iOS SDK version 2.11.0 adds the in-app messaging features, and this Cordova plugin 2.6.0 adds the accompanying support.

It is important to note that the OneSignal docs for setting up the OneSignalNotificationServiceExtension are now out of date: The new features in the base iOS library now require two additional libraries to be linked in the setup step. The full list is now:

  SystemConfiguration.framework
  UIKit.framework
  OneSignal.framework
  WebKit.framework **(new)**
  CoreGraphics.framework **(new)**

This despite the fact that the core devs DID add these deps to the Podspec, for some reason Xcode doesn't pick up the transitive dependencies.

**Environment**
Cordova CLI: 9.0
OneSignal-Cordova-SDK: 2.6.0
Xcode: 10.3
macOS: Mojave 10.14.6

**Steps to Reproduce Issue:**

1. Add the NSE as shown in the docs: https://documentation.onesignal.com/docs/ionic-sdk-setup#section-5-ios-part-2-recommend-
2. Product -> Clean then Product -> Build
3. Receive the following errors:

:-1: Undefined symbol: _OBJC_CLASS_$_WKWebViewConfiguration
:-1: Undefined symbol: _OBJC_CLASS_$_WKWebView
:-1: Undefined symbol: _CGAffineTransformIdentity
:-1: Undefined symbol: _CGAffineTransformMakeScale

![image](https://user-images.githubusercontent.com/13020457/64882548-f807be80-d622-11e9-9fb8-81c9f927c5ac.png)

4. Add the two new dependencies above (CoreGraphics & WebKit):

![image](https://user-images.githubusercontent.com/13020457/64882639-2ab1b700-d623-11e9-870f-5d0e756b4cc5.png)

5. Product -> Clean && Product -> Build
6. Successful build 🎉 🎉 🎉

**Comment by rgomezp** [comment]
@codinronan ,
Thanks so much for your feedback. We'll be sure to update the docs to help out folks who may run into this as well

**Comment by rgomezp** [comment]
Added to Troubleshooting section
