### ISSUE TITLE
Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer

### ISSUE THREAD

**Issue by indraraj26** [OneSignal/OneSignal-Cordova-SDK#556]
**Description:**

I am getting this warning when i am building apk.  Same warning for both version 8.1.0 & 8.0.0

**Environment**

"cordova-android": "^8.1.0",

cordova plugin list
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-native-spinner 1.1.3 "Native Spinner"
cordova-plugin-nativegeocoder 3.2.2 "NativeGeocoder"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.0 "SocialSharing"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.6.0 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1.  ionic cordova platform add android@8.1.0
2.  ionic cordova build android
3.

**Anything else:**

(crash stacktraces, as well as any other information here)
![image](https://user-images.githubusercontent.com/23274631/65485765-59038200-dec0-11e9-956f-048788853688.png)
![image](https://user-images.githubusercontent.com/23274631/65485778-60c32680-dec0-11e9-9c41-00b717a2dc3a.png)

**Comment by indraraj26** [comment]
In root, build.gradle
```
buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }

    dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.3, 0.99.99]'
    }
}

```

In app/build.gradle
```
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
apply plugin: 'com.android.application'
```

**Comment by rgomezp** [comment]
Try putting `classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.3, 0.99.99]'`
before `classpath 'com.android.tools.build:gradle:3.3.0'`

**Comment by obidoank15** [comment]
Facing same issue. Same error.
Apk was built, but got error: App not Installed tested on android 6 and 9.

Removing the onesignal plugin, apk installed and working fine.

**Comment by rgomezp** [comment]
@obidoank15 , have you tried my recommendation above?

**Comment by obidoank15** [comment]
@rgomezp  already

**Comment by rgomezp** [comment]
THis is just a warning though, is this causing any blocking issues?

**Comment by pscott-au** [comment]
I was stuck on this and still seeing this in Android Studio when I build but my app runs and triggers notifications on Android and IOS without any issue so it appears that this warning is ignorable .. perhaps the 'MUST' in the warning isn't in the expected context.

**Comment by mriegler** [comment]
I can attest to the same issue. Same new versions of cordova , platform and the plugin.
I'm updating an existing app from older versions (cordova 5). The old app still gets pushes on the same phone.
The updated version, without any manual changes in the platforms/android files builds and runs and even gets a Player ID and Push Token, but actually pushing to the device fails.

After manually changing things in accordance to the OneSignal Gradle Plugin installation guide, things work now. 

Obviously, manual changes aren't ideal, but I was all out of ideas. I can't invest anymore time into this, but my quess would be the newer versions having problems. The example project doesn't throw the error. It has the gradle 3.0.1 in the buildscript, while the newest cordova puts version 3.3.0 in the buildscript.

**Comment by rgomezp** [comment]
I see. Thanks for the replies y'all. We will update the gradle version in the example project

I will close this issue then
