### ISSUE TITLE
E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by pedroayres** [OneSignal/OneSignal-Cordova-SDK#558]
1. Add the onesignal-cordova-plugin to your project
2. Initialize the plugin with your app ID
3. Attempt to receive a push notification

My enviroment 
Cordova version
9.0.0 (cordova-lib@9.0.1)

Ionic version
3.19.1

Real device:
ASUS_T00J ( Android 4.4.2, API 19)

**Error on android studio**
09-26 10:45:15.262 24848-24938/com.contact2sale.c2s E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.onesignal.NotificationChannelManager.createChannel
09-26 10:45:15.262 24848-24938/com.contact2sale.c2s W/dalvikvm: VFY: unable to resolve new-instance 67 (Landroid/app/NotificationChannel;) in Lcom/onesignal/NotificationChannelManager;
09-26 10:45:15.262 24848-24938/com.contact2sale.c2s D/dalvikvm: VFY: replacing opcode 0x22 at 0x005f
09-26 10:45:15.262 24848-24938/com.contact2sale.c2s E/dalvikvm: Could not find class 'android.app.NotificationChannel', referenced from method com.onesignal.NotificationChannelManager.createDefaultChannel
09-26 10:45:15.262 24848-24938/com.contact2sale.c2s W/dalvikvm: VFY: unable to resolve new-instance 67 (Landroid/app/NotificationChannel;) in Lcom/onesignal/NotificationChannelManager;
09-26 10:45:15.262 24848-24938/com.contact2sale.c2s D/dalvikvm: VFY: replacing opcode 0x22 at 0x0000
09-26 10:45:15.262 24848-24938/com.contact2sale.c2s I/dalvikvm: Could not find method android.app.NotificationManager.getNotificationChannel, referenced from method com.onesignal.NotificationChannelManager.createNotificationChannel
09-26 10:45:15.262 24848-24938/com.contact2sale.c2s W/dalvikvm: VFY: unable to resolve virtual method 478: Landroid/app/NotificationManager;.getNotificationChannel (Ljava/lang/String;)Landroid/app/NotificationChannel;

**Cordova list**
com.lampa.startapp 0.1.4 "startApp"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-android-permissions 0.11.0 "Permissions"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-contacts 3.0.2-dev "Contacts"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-intercom 7.1.0 "Intercom"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.6.0 "OneSignal Push Notifications"

**Config.xml**
    <plugin name="cordova-plugin-android-permissions" spec="^0.11.0" />
    <plugin name="cordova-plugin-console" spec="^1.1.0" />
    <plugin name="cordova-plugin-contacts" spec="git+https://github.com/apache/cordova-plugin-contacts.git" />
    <plugin name="cordova-plugin-device" spec="^1.1.7" />
    <plugin name="cordova-plugin-inappbrowser" spec="^1.7.2" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.1.0" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="com.lampa.startapp" spec="^0.1.4" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="cordova-plugin-call-number" spec="^1.0.1" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-open-native-settings" spec="1.5.2" />
    <plugin name="cordova-support-android-plugin" spec="1.0.1" />
    <plugin name="cordova-android-support-gradle-release" spec="^3.0.1" />
    <plugin name="cordova.plugins.diagnostic" spec="^5.0.0" />
    <engine name="android" spec="8.0.0" />
    <engine name="ios" spec="^5.0.0" />

**Comment by rgomezp** [comment]
`Could not find class` errors are expected in the logcat for Android devices before 5.0. It is just letting you know it could not find these classes as your app loads into memory. It does not cause any issues in your app as the calls are guarded with runtime checks so they won't create any issues.
