### ISSUE TITLE
Android devices don't play any sound when receive notification

### ISSUE THREAD

**Issue by sergiol29** [OneSignal/OneSignal-Cordova-SDK#559]
**Description:**
Hi, I've issue with android notifications. When I send a notification from oneSignal with default sound or custom sound the android devices show notification and only vibrate and don't play any sound.

At devices iOS I have not issues and the devices show notification and play sound.

any idea?

Thanks.

**Comment by sergiol29** [comment]
When I generate a notification from oneSignal at options I select "notifications urgent" category (this category  I created previously)
<img width="729" alt="Captura de pantalla 2019-09-30 a las 11 28 19" src="https://user-images.githubusercontent.com/15367305/65866642-75e2fe00-e375-11e9-98ba-271a3d5d0968.png">

I configured the category as you can see in the next picture:
<img width="707" alt="Captura de pantalla 2019-09-30 a las 11 33 15" src="https://user-images.githubusercontent.com/15367305/65867190-408ae000-e376-11e9-958c-83e51e4e90ce.png">

But when I receive the notifications my devices only vibrate and don't play any sound.

**Comment by rgomezp** [comment]
Hello,
Please take a look at these [docs](https://documentation.onesignal.com/docs/customize-notification-sounds#section-android-and-derivatives-like-amazon-) and make sure the file is in the correct spot

**Comment by rgomezp** [comment]
Closing due to no response
