### ISSUE TITLE
handle push notification payload when App is closed

### ISSUE THREAD

**Issue by Meseery** [OneSignal/OneSignal-Cordova-SDK#56]
how should i handle push notification when the App is launched from a notification while it was killed or suspended .. i need to do some action using the notification payload when app is closed and opened from a push notification.

**Comment by jkasten2** [comment]
The `notificationOpenedCallback` function will be called when a notification is opened either when the app is open or closed. See [step 2](https://documentation.onesignal.com/docs/phonegap-sdk-installation#2-add-required-code) in our setup guide.

**Comment by neves** [comment]
@Meseery maybe you mean this: #50

**Comment by reza-khalafi** [comment]
Do it solve ?????

**Comment by NurGuz** [comment]
+1
