### ISSUE TITLE
Auto prompt for devices that interfere with default notification behaviour

### ISSUE THREAD

**Issue by sido420** [OneSignal/OneSignal-Cordova-SDK#570]
**Description:**

For devices mentioned in https://onesignal.com/blog/manufacturers-interfere-with-reliable-notifications/: can we have a feature in Onesignal plugin which when enabled lets the user know upon initialization what needs to be done to disable power optimization for the app for the particular device?

I am still having issues with this on ASUS device. At the least please provide some code to detect such devices where app is not enabled in power optimizer.

**Environment**
Cordova 7.1.0 
Android 6.4.0

**Steps to Reproduce Issue:**
Install app on ASUS Android device

**Comment by rgomezp** [comment]
Thanks for your suggestion. We will make a note and track it internally
