### ISSUE TITLE
Use of => notation causes issues on older Android phones

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#575]
**Description:**
The latest version of the OneSignal plugin 2.6.0 has a number of ES 6 'features' specifically the use of the => notation. This causes problems on some older Android phones, e.g. Android 6 using Genymotion.  e.g.
```
OneSignal.prototype.addTriggers = function(triggers) {
    Object.keys(triggers).forEach((key) => {
        // forces values to be string types
        if (typeof triggers[key] !== "string") {
            triggers[key] = JSON.stringify(triggers[key]);
        }
    });
    cordova.exec(function() {}, function() {}, "OneSignalPush", "addTriggers", [triggers]);
};
```

**Environment**
Cordova Onesignal plugin 2.6.0 and Android 6.

V2.5.2 of the code uses the older ES notation and works fine.

We are slowly going back and testing out different versions of Android and IOS to check what works and what doesn't.

**Suggestion**

Given that Android 6 is still prevalent amongst Android users, our suggestion is that all code is written using the older format. The vast majority of the OneSignal code is written using the older style and there doesn't appear to be a major reason not to use it.

Whilst we can fork the code and rewrite the admittedly small sections of new notation, it would make sense not to have to do this as the new notation provides no advantages that we can see.

Thanks

Rob

**Comment by rgomezp** [comment]
This is a very fair suggestion. We will make sure to fix this in the next release. Thanks for bringing it up

**Comment by rwillett** [comment]
Great, We're still using 2.5.2 as thats 'old school' coding. We may rewrite it, but focus is getting rich media attachments working again. We seem to have killed it somehow :(
