### ISSUE TITLE
Android 8.0 devices not registering and not receiving any notification.

### ISSUE THREAD

**Issue by tamsel12** [OneSignal/OneSignal-Cordova-SDK#577]
This is still reproducing, Android 8.0 devices not registering and not receiving any notification. 
is anybody has solution for this? 
Thanks in advance

_Originally posted by @tamsel12 in https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/492#issuecomment-540921371_

**Comment by khaled-developer** [comment]
any solutions ?

**Comment by rgomezp** [comment]
Duplicate of #492
