### ISSUE TITLE
App Removed from Play Store

### ISSUE THREAD

**Issue by gonbasaldua** [OneSignal/OneSignal-Cordova-SDK#578]
Today we received a notice from Google that they remove our app from the store with this message:

"We have identified that your app is using the OneSignal SDK or library, that facilitates the collection and transmission of users’ install application information without meeting the prominent disclosure guideline".

Anyone else is getting the same email? Any idea on how can we solve this?

**Comment by vash15** [comment]
Really? Are you using the latest version of the SDKs?

**Comment by gonbasaldua** [comment]
The app that got removed has the 2.4.6 version. Upgrading it to the 2.6.0 would do any help with this?

**Comment by gonbasaldua** [comment]
> Really? Are you using the latest version of the SDKs?

The app that got removed has the 2.4.6 version. Upgrading it to the 2.6.0 would do any help with this?

**Comment by vash15** [comment]
I hope so, I still have the old version but I'm preparing an update with the new version. What does OneSignal  say?

**Comment by gonbasaldua** [comment]
They just told me to update to the latest version of the SDK and publish a new version with it. Will try that and update the issue later.

**Comment by rgomezp** [comment]
Howdy,
I can confirm that updating the SDK will resolve the issue. We sincerely apologize for the inconvenience

**Comment by rgomezp** [comment]
Howdy,
I'll go ahead and close out this issue. If you have any other questions, just comment and I will make sure to reopen
