### ISSUE TITLE
Has 2.7.0 been released by accident?

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#580]
**Description:**
Just downloaded the latest (and greatest) one-signal release and it came up flagged as 2.7.0 rather than 2.6.0. Can't see any release note with whats changed.

**Environment**
cordova plugins shows

```
onesignal-cordova-plugin 2.7.0 "OneSignal Push Notifications"
```

**Steps to Reproduce Issue:**
```
cordova plugin rm onesignal-cordova-plugin
Stuff removed as it's boring
cordova plugin add onesignal-cordova-plugin
More stuff removed as thats boring....
cordova plugins
onesignal-cordova-plugin 2.7.0 "OneSignal Push Notifications"
```

Should I really use this one?

**Comment by rwillett** [comment]
I have also had problems compiling it with Xcode 11.2 (11B52). 

As per normal with Apple, they appear to have changed things around and to get 2.7.0 to compile I had to add in WebKit.framework and CoreGraphics.framework to the OneSignal extension to get it to work. I also added it to the main application but not sure whether I needed to or not.

I still can't get Rich Media working with this but that's a different problem <sigh>.

**Comment by rgomezp** [comment]
Howdy,
We just hadn't drafted a release. But it was no accident. Thanks for the reminder. Check out the release notes here: https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.7.0

For the second issue, see https://github.com/OneSignal/OneSignal-iOS-SDK/issues/430
