### ISSUE TITLE
In App Message action : Different data format for iOS and Android

### ISSUE THREAD

**Issue by guillaumegd** [OneSignal/OneSignal-Cordova-SDK#582]
**Description:**

Hi,
After implementing in app message click handling, I noticed `handleInAppMessageClicked` returns inconsistent data depending on the targetted OS.
For Android, here the data format :
```
{  
    "click_name": "somestring",  
    "first_click": true,  
    "closes_message": true  
}
```
And for iOS :
```
{  
    "clickName": "somestring",  
    "firstClick": true,  
    "closesMessage": true,  
    "clickUrl": null  
}
```

According to the [Cordova documentation](https://documentation.onesignal.com/docs/cordova-sdk#section--handleinappmessageclicked-) we expect to get the data formatted as in the first example.
See:
- Android [toJSONObject function](https://github.com/OneSignal/OneSignal-Android-SDK/blob/0508d7e8dc0da62c2ab4f421db69a2fc4028f72d/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSInAppMessageAction.java#L44) called [here](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/3888cfd2746f68efc097d766cf9d2dd019a047cc/src/android/com/plugin/gcm/OneSignalPush.java#L658)
- iOS [data format](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/3888cfd2746f68efc097d766cf9d2dd019a047cc/src/ios/OneSignalPush.m#L377)

It would be great to have the same behavior on Android and iOS and eventually to update the documentation if necessary.

**Environment**

```
Cordova CLI : 9.0.0 (cordova-lib@9.0.1)
onesignal-cordova-plugin 2.7.0 "OneSignal Push Notifications"
```

**Steps to Reproduce Issue:**

1. Add the onesignal-cordova-plugin to your project
2. Initialize the plugin with your app ID
3. Add `.handleInAppMessageClicked(inAppClickedCallback)` to plugin initialization
4. From OneSignal dashboard, create an In App Message with a button (without URL) and a "Click action name" under "Advanced message Settings / Button". You can either send it or preview it on a test device
5. Click the button on Android and see the logged data
6. Click the button on iOS and see the logged data

**Anything else:**

Example of callback for logging data :
```
let inAppClickedCallback = (jsonData) => {
        console.log(jsonData);
};
```

Thank you

**Comment by rgomezp** [comment]
Thanks for surfacing this

**Comment by rgomezp** [comment]
WARNING
---
This is a breaking change. Please make sure you update the values
