### ISSUE TITLE
Mismatched User Environment - Confusion all around :)

### ISSUE THREAD

**Issue by rwillett** [OneSignal/OneSignal-Cordova-SDK#585]
**Description:**
I'm getting mismatch User Environments for both the Production and Sandbox environments. We've had this before (see #483) and seen other people with it #538. Though the latter appears to more to do with the Xcode newbuild vs the legacy build.

<img width="363" alt="Screenshot 2019-11-20 at 08 45 15" src="https://user-images.githubusercontent.com/668923/69222936-5c3e8580-0b72-11ea-921b-72a52620b788.png">

When we check the OneSignal userId's in both the production and sandbox environments in the OneSignal dashboard we cannot find any of the userid's at all. 

We believe this is due to using OneSignal sandbox for testing and then switching to using production OneSignal  without uninstalling our application and then reinstalling a new version. This correlates to #483. 

However as we dig into the OneSignal docs 

https://documentation.onesignal.com/docs/mismatched-user-environment

referred to by the error we can see the following lines which worry us, we don't think this document was there in January of this year (or at least we don't remember it).

 ```
Users cannot "switch" environments. This is set by Apple and is why we recommend the Dual Sandbox and Production certificate in our setup guide step 2.3: https://documentation.onesignal.com/docs/generate-an-ios-push-certificate

Steps to Resolve
Users on the Sandbox or Ad-hoc environment will need to uninstall the app and re-install it to be on the Production Environment. You will not be able to remove a Production Push Certificate once it is set.
```

We hope this is ambiguously phrased and that when it says ```User cannot "switch" environments.``` it actually means that end users of the app cannot switch production environments once it is installed, but that uninstalling the production app and reinstalling a sandboxed version of the app does work. 

The phrase ```You will not be able to remove a Production Push Certificate once it is set.``` seems to imply that once you have set the iPhone device to use a Production certificate it can never be changed, which doesn't seem to be right. Surely uninstalling the application would uninstall any push certificate attached to that app, otherwise once a phone has had a production certificate on, it can never be used for testing?

Summary

1. How do we remove the error message for the player_id's above when they are not in the OneSignal database and not in our database? Is there a timeout from Apple?

2. Is our reading of the documentation correct, i.e. if you wholly remove an app you can then use it in the sandbox or production environment? If not it means we have a number of iPhones we can't test with :(.

Thanks 

Rob

**Comment by rgomezp** [comment]
Howdy,
>You will not be able to remove a Production Push Certificate once it is set.

This is referring to the dashboard. 

1. Please reach out to our support channel at OneSignal.com for further assistance.

2. I'm not sure what you mean here? Like I said, the push certificate question above refers to removing it from the dashboard

**Comment by rwillett** [comment]
Ah! that explains it. We didn't realised it refers to the dashboard. 

Thats fine. We have set the right certificates for the sandbox and production. No intervention is necesary.
