### ISSUE TITLE
Crash on first launch during plugin "endInit" method call. 

### ISSUE THREAD

**Issue by dockinkong** [OneSignal/OneSignal-Cordova-SDK#588]
**Description:**
App crashes on first launch, on plugin init on Android and iOs

**Environment**
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-bluetoothle 4.5.5 "Bluetooth LE"
cordova-plugin-buildinfo 2.0.2 "BuildInfo"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
onesignal-cordova-plugin 2.7.0 "OneSignal Push Notifications"

**Comment by rgomezp** [comment]
Please follow our issue template
