### ISSUE TITLE
How to make the large icon take the shape of the launcher icons?

### ISSUE THREAD

**Issue by spinninghamster** [OneSignal/OneSignal-Cordova-SDK#590]
This is more of a question than an issue. On Android 9, most app notifications show the "Large Icon" in the shape of the launcher icons. In my case, somewhat square-roundish.

I can achieve that for launcher icons with .XML icons but for the "Large Icon" they need to be set as "ic_stat_onesignal_default.png", which means I can't give them a custom shape or make them adaptive ..and they end up showing square.

How to fix that?

**Comment by rgomezp** [comment]
Howdy, 
Thanks for your question. Can you please provide screenshots for context?

**Comment by rgomezp** [comment]
Closing due to no response.
