### ISSUE TITLE
Please remove callback=function() {} to function(name, callback) {

### ISSUE THREAD

**Issue by antivir88** [OneSignal/OneSignal-Cordova-SDK#594]
D/SystemWebChromeClient: file:///android_asset/www/plugins/onesignal-cordova-plugin/www/OneSignal.js: Line 341 : Uncaught SyntaxError: Unexpected token =
I/chromium: [INFO:CONSOLE(341)] "Uncaught SyntaxError: Unexpected token =", source: file:///android_asset/www/plugins/onesignal-cordova-plugin/www/OneSignal.js (341)
D/SystemWebChromeClient: file:///android_asset/www/cordova.js: Line 1352 : Uncaught Error: Module onesignal-cordova-plugin.OneSignal does not exist.
I/chromium: [INFO:CONSOLE(1352)] "Uncaught Error: Module onesignal-cordova-plugin.OneSignal does not exist.", source: file:///android_asset/www/cordova.js (1352)

Android 6 - API 23

**Comment by vikshv** [comment]
+1, test Android 4.4. API 19 - http://prntscr.com/qcm1ew

**Comment by epetre** [comment]
> +1, test Android 4.4. API 19 - http://prntscr.com/qcm1ew

Same issue and it just makes the app load forever.

**Comment by rgomezp** [comment]
This has been resolved in 2.8.1

**Comment by vikshv** [comment]
The current version of the file OneSignal.js still contains "callback=function() {}", example OneSignal.prototype.sendOutcome function

**Comment by epetre** [comment]
Yes, it's definitely still there in 2.8.1:

![image](https://user-images.githubusercontent.com/1010282/71588681-639d6b00-2af0-11ea-8c3f-4e0bd4493877.png)

https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/www/OneSignal.js#L341

**Comment by rgomezp** [comment]
My apologies, I misread the comment. This is a strange issue since it should be supported. Take a look at the following chart that shows the support for Javascript default parameters...
![Screen Shot 2020-01-02 at 12 22 23 PM](https://user-images.githubusercontent.com/11739227/71692972-293a0500-2d60-11ea-8f87-26a769ed323d.png)

Can you please provide the full environment info?

**Comment by jkasten2** [comment]
This was fixed in PR #603, it will be included in the upcoming week.
