### ISSUE TITLE
Onesignal Not working on  iOS Device -   XCode 11.2

### ISSUE THREAD

**Issue by dhavalsoni2001** [OneSignal/OneSignal-Cordova-SDK#596]
**Description:**
I have successfully integrated onesignal with my app one year ago and it was working perfectly fine and currently, I am not getting prompted on iOS though it's working fine on android.

**Environment**

1. What version of the Cordova SDK are you using?
Cordova CLI: 9.0.0 (cordova-lib@9.0.1) 
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.4 
ios-sim version: 8.0.2 
OS: macOS
Node Version: v8.5.0
Xcode version: Xcode 11.2.1 Build version 11B500

2. Provide a list of your project dependencies (using `cordova plugin list` or copy-pasting your config.xml)

com-sarriaroman-photoviewer 1.2.4 "PhotoViewer"
com.eightz.mobile.cordova.plugin.android.referrer 1.0.0 "Android Referrer Plugin"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-downloadmanager 0.0.1 "DownloadManager"
cordova-plugin-facebook4 6.2.0 "Facebook Connect"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-filepicker 1.1.6 "File Picker"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-googleplus 8.2.0 "Google SignIn"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.3 "ImagePicker"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.2 "SocialSharing"
cordova-plugin-x-toast 2.7.2 "Toast"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.8.1 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

  1. Add the onesignal-cordova-plugin to your project
  2. Initialize the plugin with your app ID
  3. Running the application on device from xCode,

Not getting any error though I am also not getting prompt for `Allow` Notifications as well as in device `Settings > Notifications`   I am not able to see my application.

**Anything else:**

-> Ionic Documentation updated latest 8 months so I think I have followed that may cause the error.

**Comment by woondossier** [comment]
I ran into this issue myself, I fixed it by doing this at the end of the init.

` this.oneSignal.getPermissionSubscriptionState().then(state => {
                //because onesignal broke this, check if prompted
                if(prompt && !state.permissionStatus.hasPrompted && this.platform.is('ios'))
                {
                    this.oneSignal.promptForPushNotificationsWithUserResponse().then(() => {
                    });
                }
            });`

**Comment by tamsel12** [comment]
@woondossier  Have you get notification permission popup and device registered in onesignal ?

**Comment by jkasten2** [comment]
@dhavalsoni2001 I recommend checking the Xcode log for any errors. If there are non I recommend enabling extra logging note here
https://documentation.onesignal.com/docs/troubleshooting-cordova-variants#section-6-check-below-for-common-issues-and-if-still-not-sure-send-us-a-log

@tamsel12 Can you share what code you had before that was not working?

**Comment by rgomezp** [comment]
Closing due to no response
