### ISSUE TITLE
OneSignal.OSInFocusDisplayOption.Notification shows in-app alert on iOS - Ionic 4

### ISSUE THREAD

**Issue by maidmehic** [OneSignal/OneSignal-Cordova-SDK#597]
**Description:**

Hello everyone. This is my OneSignal initialization that runs after platform.ready() in ionic 4 project:

`this.oneSignal.startInit('---', '---');

    this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.Notification)

    this.oneSignal.handleNotificationReceived().subscribe(data => {
      console.log(JSON.stringify(data));
      this.presentNoConnectionAlert('Received', 'Received', 'Received');
    });

    this.oneSignal.handleNotificationOpened().subscribe(data => {
      console.log(JSON.stringify(data));
      this.presentNoConnectionAlert('Opened', 'Opened', 'Opened');
    });

    this.oneSignal.endInit();`

The problem occurs on iOS device, even though I set **inFocusDisplaying** to **Notification** or **None**, default in-app alert appears on the screen when a notification is received while my app is open. Does anyone have any idea what could be causing this strange behavior? 

**EDIT**
Everything works as expected only on the first app run from fresh installation. When app is in the foreground, it receives a notification without in-app alert what is great. But if I reopen it, next push notifications are received with in-app alert included. 

**Environment**
    "onesignal-cordova-plugin": "^2.8.0"
    "@ionic-native/onesignal": "^5.18.0"
    "ionic": "~5.4.4"
    "cordova": "~9.0.0"
    "cordova-ios": "5.0.0",

**Steps to reproduce**
Make new Ionic project with `ionic start newProject`
Install required plugins for OneSignal :
`ionic cordova plugin add onesignal-cordova-plugin
npm install @ionic-native/onesignal
`
in app.component.ts -> platform.redy() add code I wrote above

**Comment by maidmehic** [comment]
Hello, the issue is fixed after downgrading to 2.7.0 version of onesignal-cordova-plugin so the bug still persists in 2.8.0 and 2.8.1 versions.

**Comment by ludufre** [comment]
Same issue here

**Comment by sourbell** [comment]
Same issue here

**Comment by rexx-org** [comment]
Also have the same issue. This is a bit concerning that 
a) The bug was introduced in 2.8.0 when it worked fine before
b) Nothing appears to have been done about fixing the issue.

**Comment by rgomezp** [comment]
Appears to be a native issue. Please track this issue in the iOS repository: https://github.com/OneSignal/OneSignal-iOS-SDK/issues/600

**Comment by ludufre** [comment]
For the record: this issue continues in 2.8.2.

**Comment by mikechoch** [comment]
Has anyone confirmed using the `setInFocusDisplay` method instead of `inFocusDisplaying` builder method?

**Comment by ludufre** [comment]
> Has anyone confirmed using the `setInFocusDisplaying` method instead of `inFocusDisplaying` builder method?

```javascript
TypeError: this.push.oneSignal.setInFocusDisplaying is not a function. (In 'this.push.oneSignal.setInFocusDisplaying(_ionic_native_onesignal_ngx__WEBPACK_IMPORTED_MODULE_10__["OSDisplayType"].Notification)', 'this.push.oneSignal.setInFocusDisplaying' is undefin...
  at None (app:///pages-push-push-module.js:208:49)
  at callWithDebugContext (app:///vendor.js:81180:30)
  at dispatchEvent (app:///vendor.js:70730:36)
  at None (app:///vendor.js:98557:48)
  at sentryWrapped (app:///vendor.js:141305:28)
...
```

**Comment by fitmax-project** [comment]
the issue still occur

**Comment by rgomezp** [comment]
Please follow the issue in the iOS repository linked above
