### ISSUE TITLE
MinSDK android issue, onesignal forces 26 while google requires 28

### ISSUE THREAD

**Issue by Valkhan** [OneSignal/OneSignal-Cordova-SDK#598]
**Description:**

MinSdkVersion for android is now 28, i've set it to 28 but this plugin is overwriting it with 26, if I remove this plugin it works as intended, please double check and remove this behavior so we may respond to Google Play requirements faster

**Environment**

<preference name="phonegap-version" value="cli-8.0.0" />
  <preference name="android-minSdkVersion" value="28"/>
  <preference name="android-build-tool" value="gradle" />
  <preference name="DisallowOverscroll" value="true" />
  <preference name="StatusBarStyle" value="blacktranslucent" />
  <engine name="ios" spec="~4.5.1" />
  <plugin name="cordova-plugin-network-information" source="npm" spec="*"/>
  <plugin name="cordova-plugin-file" source="npm" spec="*"/>
  <plugin name="cordova-plugin-statusbar" source="npm" spec="*"/>
  <plugin name="cordova-plugin-whitelist" source="npm" spec="*"/>
  <plugin name="onesignal-cordova-plugin"/>

**Steps to Reproduce Issue:**

1. Add the onesignal-cordova-plugin to your project
  2. Add preference to android-minSdkVersion with value=28
  3. Compile APK
  4. Send to Google Play (it's rejected with minSdkVersion set to 26)

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@Valkhan I believe you meant to set `android-targetSdkVersion` instead of `android-minSdkVersion`.  More details on these values in the links below:
* https://cordova.apache.org/docs/en/latest/config_ref/
* https://developer.android.com/guide/topics/manifest/uses-sdk-element.html
