### ISSUE TITLE
please remove default parameters (ES2015 feature) this break Android 6/5

### ISSUE THREAD

**Issue by victorvhpg** [OneSignal/OneSignal-Cordova-SDK#601]
Please remove default parameters
its ES2015 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/default_parameters

callback=function() {}

https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/www/OneSignal.js#L340

https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/www/OneSignal.js#L353

https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/master/www/OneSignal.js#L366

**Comment by albertopq** [comment]
+1

**Comment by jkasten2** [comment]
@victorvhpg This was fixed in PR #603, it will be included in the next release this upcoming week.

**Comment by victorvhpg** [comment]
@jkasten2  thanks
