### ISSUE TITLE
Onesignal does not register ios device (ios 13) Xcode 11.3 

### ISSUE THREAD

**Issue by tamsel12** [OneSignal/OneSignal-Cordova-SDK#604]
Hai, Onesignal does not register the IOS device which has ios version 13. But it has asked permission of push notification, and notifictation permission is enabled in  device. I am using the latest version of plugin 2.8.1?  Could any one have solution? Thanks in advance

**Comment by jkasten2** [comment]
@tamsel12 Do you have any users / players on the OneSignal dashboard for your app? If not see this guide:
https://documentation.onesignal.com/docs/no-users-on-dashboard-after-installing-sdk

If there is a user / player then it should state the reason why it isn't subscribed. More details in this guide
https://documentation.onesignal.com/docs/all-users-are-shown-as-not-subscribed

**Comment by tamsel12** [comment]
@jkasten2 i am having the same code for both droid and IOS.  Droid devices list shows successfully  and it is subscribed inside oneSignal. IOS Devices are not showed any info that it is subscribed because the devices are not  listed inside the onesignal.

**Comment by rgomezp** [comment]
Consider reaching out to our support channel for assistance. Thank you!
