### ISSUE TITLE
VOIP Notifications not working

### ISSUE THREAD

**Issue by mattkhaw** [OneSignal/OneSignal-Cordova-SDK#605]
**Description:**
I'm trying to integrate VOIP notifications into my Cordova app but to no success. The issue I'm having right now is client app is not receiving the notifications and no event is triggering it. I wish to know which event is supposed to be triggered and also the setup for the Cordova app. I do believe my server setup is registering the users correctly since I can see from the dashboard. Sending is also taken care of since the dashboard states that every push is successful. I have to incorporate normal push notifications as well.

**Environment**
Cordova 9.0.0, iOS 5.1.1

These are the plugins I'm using in my app. Basically I used the VoIPPushNotification plugin to get the VOIP token and register it to OneSignal's REST API via Add Device.

com.nikola-breznjak.voippush 1.0.2 "VoIPPushNotification"
cordova-call 1.1.6 "CordovaCall"
cordova-plugin-bring-to-front 0.0.3 "Bring to Front"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-iosrtc 6.0.5 "iosrtc"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
onesignal-cordova-plugin 2.8.1 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

1. Create a VOIP Services certificate.
2. Setup OneSignal App in the dashboard (I've created 2 separate ones. One for normal push, the other for VOIP)
3. Upload and configure VOIP Services certificate to the 2nd OneSignal app via dashboard
4. Setup app server to use REST API Add A Device in order to register device (using 2nd OneSignal app ID and REST Key)
5. Setup client app to get iOS VOIP Token and send it to app server for registration with POST content (app_id = "2nd OneSignal App ID", device_type = 0, identifier = "iOS VOIP Token", test_type = 1)
6. Once registered, push a notification with apns_push_type_override = "voip"
7. Dashboard always says successful but client doesn't receive anything

**Anything else:**

Of course the only thing I missed out is plugin initialisation for normal push since that's a no brainer to include. I've tested normal push and it works fine. The only issue here is VOIP push. I do think that I'm missing something but no documentation exists on what the hints are or maybe my Google-fu is not up to snuff. I also noticed that there's a feature request to support VOIP push notifications. Don't know whether that is related or not, but it might be the answer as well.

**Comment by rgomezp** [comment]
Hello,
VOIP should now be fixed. Thanks for your patience
