### ISSUE TITLE
Feature --> Allow to open app without user interaction

### ISSUE THREAD

**Issue by videmort** [OneSignal/OneSignal-Cordova-SDK#608]
**Description:**
It will be nice for videocalls/calls  to open the aplication without user interaction.

For example this plugin allow callkit and android calls --> https://github.com/WebsiteBeaver/CordovaCall

But if app is not running  (no background) user need to press the push to receive the event and do what you want.

https://stackoverflow.com/questions/30089963/how-to-automatically-open-the-app-without-user-action-on-receiving-a-push-on-and

**Comment by rgomezp** [comment]
Thanks for the request. We will track this request internally
