### ISSUE TITLE
Google Play Developer Term Violation

### ISSUE THREAD

**Issue by ludooo** [OneSignal/OneSignal-Cordova-SDK#61]
I received this email after the publishing of my app on Google Play. Is there a way to avoid this issue ?

"We detected that the app(s) listed at the end of this email contain a version of OneSignal, a messaging SDK, that collects personally identifiable information (PII) without disclosure. Apps like this may be considered in violation of our User Data policy.

Action required: Your app(s) may be removed from Google Play if the issue is not resolved within 10 days of receiving this message. If the affected version is inactive, future submissions will be rejected if you attempt to publish without first resolving the issue.

You can resolve this issue by:

adding a privacy policy URL to your app listing and within the app, notifying the user that their PII is collected; or
removing any such functionality from your app. You may need to contact your SDK provider for an updated, policy compliant version to include in your app.
After resolving the issue, you’ll need to sign in to your Developer Console and submit the updated version of your app."

**Comment by jkasten2** [comment]
@ludooo Please contact OneSignal support from the red question mark on the bottom right when signed in or email support@onesignal.com.

Thanks.
