### ISSUE TITLE
"Invalid amount spend" error (Ionic 5, Angular 9)

### ISSUE THREAD

**Issue by petrot** [OneSignal/OneSignal-Cordova-SDK#613]
I just upgraded my working project to Ionic 5 / Angular 9

My working code now give the following error and my app stacks on the splashscreen :

```
Request <OSRequestSendPurchases: 0x283a96490> fail result error Error Domain=OneSignalError Code=400 "(null)" UserInfo={returned={
    errors =     (
        "Invalid amount spend"
    );
}}
```

My POD file:

```
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target 'xy' do
	project 'xy.xcodeproj'
	pod 'OneSignal', '2.12.6'
	pod 'FirebaseMessaging', '~> 2.0.0'
end

```

**Comment by rgomezp** [comment]
Howdy,
Sorry for the delay. Are you still seeing the issue? We haven't heard other reports of this. If so, please try updating to the latest plugin version

**Comment by petrot** [comment]
sorry, it's invalid... My problem caused by ivy...

**Comment by rgomezp** [comment]
Ahh. Ok. Hope you can resolve your issue!
