### ISSUE TITLE
iOS Service Extensions 

### ISSUE THREAD

**Issue by videmort** [OneSignal/OneSignal-Cordova-SDK#615]
**Description:**
Hello,  if I want to use iOS Service Extensions I need to do manually every time, so it broke my continous integration. ¿it's possible to automatize that process?

**Comment by rgomezp** [comment]
Howdy,
Unfortunately, there isn't a workaround currently. Support to add iOS App Extensions is something we were hoping Cordova would add. There is an open ticket for a feature request for this but there hasn't been any recent updates.
https://issues.apache.org/jira/browse/CB-10218
If this was added as a feature to Cordova it would then also work on cloud builds like Adobe PhoneGap Build (PGB) where it might not be possible to modify the Xcode project, even programmatically.

**Comment by rgomezp** [comment]
Closing due to no response
