### ISSUE TITLE
Google Play Services Library Error Recibe in Dashboard OneSignal For Android Devices

### ISSUE THREAD

**Issue by jsanchez2803** [OneSignal/OneSignal-Cordova-SDK#617]
**Description:**

Yesterday I installed the latest version of the plugin to include in the project and although it compiles normally when taking the token it generates it in 'null' in the dasboard for that session it indicates to me 'Google Play Services Library Error'

I tried to download the version but I did not succeed
try to solve by attaching the plugin https://github.com/OneSignal/OneSignal-Gradle-Plugin but I did not succeed

Any idea what might be happening?

**Environment**

IONIC  3 Proyect
Android 8.0.0
Cordova 9.0.0 (cordova-lib@9.0.1)

Plugin Installs:
`
<plugin name="cordova-plugin-whitelist" spec="^1.3.4" />

    <plugin name="cordova-plugin-statusbar" spec="^2.4.3" />
    <plugin name="cordova-plugin-device" spec="^2.0.3" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.3" />
    <plugin name="cordova-plugin-ionic-webview" spec="^2.5.3">
        <variable name="ANDROID_SUPPORT_ANNOTATIONS_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.2.0" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.2.0" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.2" />
    <plugin name="cordova.plugins.diagnostic" spec="^4.0.12">
        <variable name="ANDROID_SUPPORT_VERSION" value="28.+" />
    </plugin>
    <plugin name="cordova-plugin-geolocation" spec="^4.0.2">
        <variable name="GEOLOCATION_USAGE_DESCRIPTION" value="To locate you" />
    </plugin>
    <plugin name="cordova-plugin-camera" spec="^4.1.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
        <variable name="CAMERA_USAGE_DESCRIPTION" value="This application requires access to the camera to scan QR codes and register addresses" />
        <variable name="NSPHOTOLIBRARYUSAGEDESCRIPTIONENTRY" value="This application requires access to the camera to scan QR codes and register addresses" />
    </plugin>
    <plugin name="mx.ferreyra.callnumber" spec="0.0.2" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.6.4">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.1+" />
    </plugin>
    <plugin name="cordova-plugin-email-composer" spec="^0.9.2">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-file-transfer" spec="^1.7.1" />
    <plugin name="cordova-plugin-androidx" spec="^1.0.2" />
    <plugin name="cordova-plugin-androidx-adapter" spec="^1.1.0" />
    <plugin name="phonegap-plugin-barcodescanner" spec="^8.1.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
        <variable name="CAMERA_USAGE_DESCRIPTION" value="This application requires access to the camera to scan QR codes and register addresses" />
    </plugin>
    <plugin name="cordova-clipboard" spec="^1.3.0" />
    <plugin name="cordova-plugin-google-analytics" spec="^1.8.6">
        <variable name="GMS_VERSION" value="11.0.1" />
    </plugin>
    <plugin name="call-number" spec="^1.0.1" />
    <engine name="browser" spec="5.0.4" />
    <plugin name="onesignal-cordova-plugin" spec="^2.8.4" />
`

**Comment by rgomezp** [comment]
Howdy,
Sorry for the delay. Are you still seeing this issue or can it be closed out? I encourage you to reach out to support at onesignal.com for these types of issues and quicker responses

**Comment by rgomezp** [comment]
Closing due to no response
