### ISSUE TITLE
push token not set with Meteor 1.3 (cordova ios 4.0.1)

### ISSUE THREAD

**Issue by realyze** [OneSignal/OneSignal-Cordova-SDK#62]
OneSignal SDK with Meteor 1.2 works perfectly. Meteor 1.3 updated to Cordova ios 4.0.1 and now after upgrade, this SDK reports pushToken as empty string.

I'm using phonegap-plugin-push@1.7.3 in the same project and that one reports device id OK.

Looks like `oneSignalDidRegisterForRemoteNotifications` never gets called.

**Comment by jkasten2** [comment]
@realyze Can you try removing the `phonegap-plugin-push` plugin from your project? We seen issues where other push plugins can interfere with OneSignal get a push token.

**Comment by realyze** [comment]
@jkasten2 Yes, that helps. But I actually need the app to handle background notifications...

**Comment by jkasten2** [comment]
@realyze I see, so you need to keep this plugin as you are still need it to handle your background notifications?

**Comment by realyze** [comment]
Yes. We've actually switched to UrbanAirship meanwhile (because of this issue - UA doesn't have problems).

The idea was to use `phonegap-plugin-push` to handle silent pushes on the client (fetching some data in the background) and OneSignal to handle alerts.

**Comment by jkasten2** [comment]
@realyze We have made a number of internal changes to our 2.0 SDK and now adding `phonegap-plugin-push` no longer creates an issue. Please follow our new 2.0 guide below.

https://documentation.onesignal.com/docs/cordova-sdk-setup

You may need to remove and re-add our plugin to get it to update.

Thanks.
