### ISSUE TITLE
java Didn't find class "<appname>.OneSignalNotificationExtender" on path: DexPathList[[zip file]]

### ISSUE THREAD

**Issue by RicTheJamGuy** [OneSignal/OneSignal-Cordova-SDK#620]
**Description:**

I have created the file OneSignalNotificationExtender.java in

node_modules\onesignal-cordova-plugin\src\android\com\plugin\gcm\OneSignalNotificationExtender.java

with the following code:

import com.onesignal.OSNotificationReceivedResult;
import com.onesignal.NotificationExtenderService;

public class OneSignalNotificationExtender extends NotificationExtenderService  {
   @Override
   protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
      return false;
   }

}
This is my AndroidManifest.xml at

platforms\android\app\src\main\AndroidManifest.xml

    <service android:exported="false" android:name=".OneSignalNotificationExtender" android:permission="android.permission.BIND_JOB_SERVICE">
        <intent-filter>
            <action android:name="com.onesignal.NotificationExtender" />
        </intent-filter>
    </service>

**Environment**

**Steps to Reproduce Issue:**

1. This application compiles and installs without issues
2. When I send a push notification to it, the application crashes
3.

**Anything else:**

error message:
java.lang.RuntimeException: Unable to instantiate service io.SMECS.us.OneSignalNotificationExtender: java.lang.ClassNotFoundException: Didn't find class "io.SMECS.us.OneSignalNotificationExtender" on path: DexPathList[[zip file "/data/app/io.SMECS.us-0MNYrvhTOW1AK21u2PKJIA==/base.apk"],nativeLibraryDirectories=[/data/app/io.SMECS.us-0MNYrvhTOW1AK21u2PKJIA==/lib/arm64, /data/app/io.SMECS.us-0MNYrvhTOW1AK21u2PKJIA==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]

**Comment by jkasten2** [comment]
@RicTheJamGuy It seems your `service io.SMECS.us.OneSignalNotificationExtender` did not get built into your APK.

If this crash is from an Android 4.4 device or older you may have not setup multidex correctly.
https://developer.android.com/studio/build/multidex
