### ISSUE TITLE
Will the update on 'OneSignal-Android-SDK' code eventually make it to 'OneSignal-Cordova-SDK'? 

### ISSUE THREAD

**Issue by upenr** [OneSignal/OneSignal-Cordova-SDK#623]
I see a new version 3.13.0 on 'OneSignal-Android-SDK' but only 2.8.4 in 'OneSignal-Cordova-SDK'. Can I expect an update soon? Thanks.

**Comment by mikechoch** [comment]
Update will be coming soon, be on the look Cordova SDK `2.9.0`!

**Comment by upenr** [comment]
Thanks again @mikechoch for your work on this new release. I take it that this contains the fix for the Google Play Store security prompt.
