### ISSUE TITLE
Apple app store NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription errors

### ISSUE THREAD

**Issue by p3v9d5ui** [OneSignal/OneSignal-Cordova-SDK#628]
**Description:**

After installing this plugin, the Apple app store rejects the build because it is missing these two purpose strings:

NSLocationAlwaysUsageDescription 
NSLocationWhenInUseUsageDescription

I do not use the OneSignal location features, and in fact call setLocationShared(false). Supposedly this should disable location services, so why are the two purpose keys above required?

**Environment**

cordova-lib@9.0.1
iOS 13

bcrplugin 1.0.0 "BcrPlugin"
com.intsig.ios.businesscardplugin 1.0.0 "com.intsig.ios.businesscardplugin"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-camera-preview 0.11.2 "cordova-plugin-camera-preview"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-keychain-touch-id 3.3.0 "TouchID and Keychain"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-qrscanner 3.0.1 "QRScanner"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-webviewcolor 2.2.0 "WebView background color plugin"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebview-file-xhr 2.1.4 "Cordova WKWebView File XHR Plugin"
cordova-sqlite-ext 4.0.0 "Cordova sqlite storage plugin - (...) with extra features"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.8.4 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

  1. Add the onesignal-cordova-plugin to your project
  2. Push to Apple app store

**Anything else:**

Note that these errors are NOT due to other plugins. I added the OneSignal plugin and this issue appeared. Without the plugin, this issue does not occur.

This other issue also raised this same issue: https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/496

But, it was closed without explanation. Adding the two purpose keys are NOT a solution, as this is misleading to the user.

**Comment by MsSaak** [comment]
Add this to config.xml work for me:

<config-file parent="NSLocationAlwaysUsageDescription" platform="ios" target="*-Info.plist">
      <string>One Signal Notifications</string>
</config-file>
<config-file parent="NSLocationWhenInUseUsageDescription" platform="ios" target="*-Info.plist">
      <string>One Signal Notifications</string>
</config-file>

**Comment by p3v9d5ui** [comment]
Yes, that does work, but it is misleading for the users. Those purpose strings tell the phone user why you are requesting access to location data. But, I am not using location data, and I don't want to mislead my users by asking for it.

**Comment by MsSaak** [comment]
I do not use location data either, but those lines do not ask me for permission. Have you tried it?

**Comment by p3v9d5ui** [comment]
Yes, you are right. I had assumed that since Apple required them to be defined, that they would also be used. But, I guess that the permission dialog is only shown if a location API is actually used.
