### ISSUE TITLE
Security alert  Your app contains exposed Google Cloud Platform (GCP) API keys. Please see this Google Help Center article for details.

### ISSUE THREAD

**Issue by sonugpc** [OneSignal/OneSignal-Cordova-SDK#629]
Today I got warning from Google Playstore 

Security alert your app contains exposed Google Cloud Platform (GCP) API keys. Please see this Google Help Center article for details.Vulnerable locations:com.onesignal.PushRegistratorFCM->getApiKeyAffects APK version 140004.Go to Manage releases
--
Please check it & Update the Fix.

**Comment by rgomezp** [comment]
Howdy,
This has been resolved in the latest release. Please update.
