### ISSUE TITLE
Right after updated to v1.13.0 in Android, many past notifications appear again

### ISSUE THREAD

**Issue by ricolo** [OneSignal/OneSignal-Cordova-SDK#63]
Hi Josh @jkasten2 , I noticed this behaviour while testing the version update. Some past notifications that appear again were probably sent a month ago and some were more recent.

I'm not sure if it has to do with the new feature in this version where notifications are restored if they're cleared by Android. However, it would seem like some kind of notification flood to users if they also get many past notifications right after updating the app.

Is there a way to suppress the restoration only once right after app update? Your email newsletter mentions two methods `clearOneSignalNotifications ` and `cancelNotification` are added in this version, however I guess I can't execute them once after app update before the app is opened? Thanks.

**Comment by jkasten2** [comment]
@ricolo Restoring notifications should only happen as far back as 1 week. After reviewing our native Android code it looks like this restriction isn't working. We will be fixing this and adding the `clearOneSignalNotifications` function in our next update.

**Comment by ricolo** [comment]
@jkasten2 Thanks it's good to know, look forward to the next update.

**Comment by jkasten2** [comment]
@ricolo Our 1.13.1 SDK is now available which fixes this issue.
https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/1.13.1
