### ISSUE TITLE
in ionic 2 apk build error while using oneSignal push plugin

### ISSUE THREAD

**Issue by jenoclement** [OneSignal/OneSignal-Cordova-SDK#630]
UP-TO-DATE
:generateDebugSources UP-TO-DATE
:incrementalDebugJavaCompilationSafeguard
 UP-TO-DATE
:compileDebugJavaWithJavac

:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

E:\ionic 2\demo\platforms\android\src\com\plugin\gcm\OneSignalPush.java:159: error: strings in switch are not supported in -source 1.6
    switch(action) {
          ^
  (use -source 7 or higher to enable strings in switch)

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

1 error

:compileDebugJavaWithJavac
FAILED

FAILURE: Build failed with an exception.

* What went wrong:

BUILD FAILED

Total time: 3 mins 29.41 secs

Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

(node:6828) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
E:\ionic 2\demo\platforms\android\src\com\plugin\gcm\OneSignalPush.java:159: error: strings in switch are not supported in -source 1.6
    switch(action) {
          ^
  (use -source 7 or higher to enable strings in switch)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by rgomezp** [comment]
Howdy, 
Please follow our issue template by opening a new issue. Thanks for your cooperation
