### ISSUE TITLE
type podspec is deprecated

### ISSUE THREAD

**Issue by widonwaker** [OneSignal/OneSignal-Cordova-SDK#632]
I'm not able to build with PGB.

Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "onesignal-cordova-plugin@2.9.0" via npm Installing "onesignal-cordova-plugin" at "2.9.0" for ios "framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag. Running command: pod install --verbose Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 1 at ChildProcess.whenDone (/private/tmp/gimlet/70160409855280/3847992/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23) at ChildProcess.emit (events.js:182:13) at maybeClose (internal/child_process.js:962:16) at Socket.stream.socket.on (internal/child_process.js:381:11) at Socket.emit (events.js:182:13) at Pipe._handle.close (net.js:611:12) pod: Command failed with exit code 1

**Comment by rgomezp** [comment]
Howdy,
Unfortunately, you won't be able to use PGB cloud build as this is currently not working correctly. Please see [this issue](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/468) for more info.
