### ISSUE TITLE
Notifications not received in Time To Live interval

### ISSUE THREAD

**Issue by SedCore** [OneSignal/OneSignal-Cordova-SDK#636]
Hi, I'm using OneSignal with Cordova, and notifications are well received when app is running. But if I send a notification when app is closed, once I start it, the app does not receive that notification even if it is within the Time To Live interval of the notification.
Is there any solution ? Thanks.

**Environment**
Cordova 9.0.0
Cordova-Android 7.1.4
OneSignal-Cordova-Plugin 2.9.1

Other plugins:
cordova-plugin-exit 1.0.3
cordova-plugin-file 6.0.2
cordova-plugin-market 1.2.0
cordova-plugin-whitelist 1.3.4
cordova-plugin-x-socialsharing 5.1.3
es6-promise-plugin 4.2.2

**Steps to Reproduce Issue:**
1. Open your app
2. Send a notification from OneSignal with any integer for Time To Live parameter
(At this step, you receive the notification)
3. Force-quit your android app
4. Send a notification from OneSignal, with any integer for Time To Live parameter
5. Open your app
(At this step, you don't receive the last notification even if you're in the Time To Live interval)

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience. This should not be happening. If you don't send a TTL parameter, what happens?

**Comment by SedCore** [comment]
It's the same, without a TTL parameter. In fact, when I observed that behaviour without a TTL parameter, then I tried to use a TTL parameter. Unfortunately, the result is the same: once I'm back in the app, it doesn't receive missed notifications.

**Comment by rgomezp** [comment]
Howdy,
Thank you for your patience. Please take a look at this article in the OneSigna [documentation](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#android-mobile-app-notifications-not-showing) for more info regarding this issue. 

As you will see in the documentation, it may depend on the device that you have and your OS. I have personally been unable to reproduce. I am testing on a Samsung S20 and I receive the notification just fine about 30 seconds after the app is re-opened. Maybe you need to wait a little longer but like I said, the behavior may be different depending on the device and operating system.

To clarify, the **Time To Live** parameter is by default 259,200 seconds (3 days) but can be any value from 0 to 2,419,200 seconds. The notification will expire if _the device_ remains offline for these number of seconds. 

It sounds like you may be trying to use the TTL parameter as a workaround for the limitation outlined in the article regarding force-killed apps. Unfortunately, this is just a limitation.

I hope this helps. Cheers
