### ISSUE TITLE
Please, could you release a version with Android SDK 3.14.0?

### ISSUE THREAD

**Issue by pedrofurtado** [OneSignal/OneSignal-Cordova-SDK#639]
Hey everyone!

The latest android sdk version 3.14.0 fixes some important bugs that occurs in our app.
Please, could you release asap a new version of plugin with this version of Android onesignal sdk? Then I will be able to release a new version of our app In Google Play.

Thank you so much guys for your hard work on it! :handshake:

**Comment by pedrofurtado** [comment]
@mikechoch 👍

**Comment by rgomezp** [comment]
Howdy Pedro,
Thanks for your patience. You should be able to hard-code the native SDK version in the local version of the package. Have you attempted to do this?

**Comment by pedrofurtado** [comment]
I made the change hard-code, for a while, in local plugin folder here 👍  thanks for feedback!

**Comment by rgomezp** [comment]
My pleasure. Enjoy!

**Comment by pedrofurtado** [comment]
But the issue was not resolved yet. I made a workaround, but the solution is to release an official release, right? From OneSignal team?

**Comment by rgomezp** [comment]
Yes, we will be releasing version 3.14.1 with the fixes. Enjoy
