### ISSUE TITLE
Disable Permission of Notification IOS via code 

### ISSUE THREAD

**Issue by tamsel12** [OneSignal/OneSignal-Cordova-SDK#650]
In my app I need to disable the notification permission via code, so in Which method in onesignal is used to disable permission for notification? Thanks in advance

I used KosAutomaticPropmpt as false , But getting notification permission getting enabled

**Comment by rgomezp** [comment]
Howdy,
Please follow our issue template and provide the full details or consider reaching out through our official support channel at OneSignal.com for these types of issues. Thank you.
