### ISSUE TITLE
ios device not showing notification when app is in foreground

### ISSUE THREAD

**Issue by csaptarshi26** [OneSignal/OneSignal-Cordova-SDK#651]
I am using "onesignal-cordova-plugin": "2.11.0" for push notification. app works fine in android no issues at all. but in ios app not showing the notification when app is in foreground though i set OSInFocusDisplayOption to notification. it is receiving notification i confirmed by adding alert on "handleNotificationReceived" method. here is my code.

iosSettings["kOSSettingsKeyAutoPrompt"] = false;
iosSettings["kOSSettingsKeyInAppLaunchURL"] = false;
window.plugins.OneSignal
    .startInit("APP_ID")
    .handleNotificationReceived(function(notificationData) {
      alert("Notification Received:\n" + notificationData);
      console.log('Notification Received: ' + JSON.stringify(notificationData));
    })
.endInit();
 window.plugins.OneSignal
    .startInit("APP_ID")
    .handleNotificationOpened(notificationOpenedCallback)
    .iOSSettings(iosSettings)
    .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.Notification)
    .endInit();

**Comment by rgomezp** [comment]
Howdy,
Please follow our issue template and provide the full details or consider reaching out through our official support channel at OneSignal.com for these types of issues. Thank you.
