### ISSUE TITLE
Android build error when using Cordova platform android@9.0.0 or newer

### ISSUE THREAD

**Issue by nationdata-it** [OneSignal/OneSignal-Cordova-SDK#657]
**Description:**

OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:28.+' -> 28 to prevent compile errors! Recommend updating your project's compileSdkVersion!

**Environment**

Ionic:

   Ionic CLI                     : 6.1.0 (/Users/.nvm/versions/node/v10.16.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.3.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 25 other plugins)

**Steps to Reproduce Issue:**

1.  ionic cordova build android

**Anything else:**

(crash stacktraces, as well as any other information here)
> Task :app:mergeDebugAssets
OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:28.+' -> 28 to prevent compile errors! Recommend updating your project's compileSdkVersion!

**Comment by nationdata-it** [comment]
after removing plugin
` ionic cordova plugin rm onesignal-cordova-plugin`
build is fine

**Comment by luanmnz** [comment]
i have the same problem, with android API 29

**Comment by rgomezp** [comment]
Also reported with other android API versions: 
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/658

**Comment by TraceDeTrail** [comment]
Hello,
Is a patch planned soon? The use of Api 29 is now required on Android...
Thank you !

**Comment by jpturski** [comment]
Any workaround available?

**Comment by FbPalmabit** [comment]
My temporary solution:

- downgrade Cordova Platforms at ^8
- remove/add platform and plugins
- in config.xml:
`<platform name="android">
        <preference name="android-targetSdkVersion" value="29" />
        ...
</platform>
`

Now APK has target 29

**Comment by jkasten2** [comment]
This is now fixed part of the [OneSignal-Gradle-Plugin 0.12.9](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.12.9) update used by this plugin. You may have to do a clean build for this new version to be pulled in.
