### ISSUE TITLE
onesignal cordova app handleNotificationOpened not fired when app is swiped away in ios

### ISSUE THREAD

**Issue by csaptarshi26** [OneSignal/OneSignal-Cordova-SDK#659]
**Description:**
When app is swiped away or killed on ios, and notification arrives it's not navigating users to specific page.  but works when app is in foreground.

**Environment**

1.  "cordova-ios": "5.1.1"
1. "onesignal-cordova-plugin": "2.11.0"

**Steps to Reproduce Issue:**

1. Add the onesignal-cordova-plugin to your project
1. Initialize the plugin with your app ID
1. Send notification from Onesignal dashboard with additional data
1. Add alert message on handleNotificationOpened and check whether alert is displayed when opening app opened from notification

**Comment by rgomezp** [comment]
Howdy,
Can you please provide us with logs with `setLogLevel` set to VERBOSE?

Thank you

**Comment by rgomezp** [comment]
Closing due to no response
