### ISSUE TITLE
iOS badge icon numbers not de-incrementing if..

### ISSUE THREAD

**Issue by NickyYo** [OneSignal/OneSignal-Cordova-SDK#66]
iOS badge icon numbers not de-incrementing if the user clears down all push notifications in one go.

If the user clears push notifications one-by-one it de-increments fine.

**Comment by jkasten2** [comment]
@NickyYo iOS does not change the badge based on the number of notification in the notification center. It will only be updated by OneSignal when the app is opened / resume (until disabled) or when you set a badge value when sending a notification.

Feel free to reopen this issue if I miss understood your question.
