### ISSUE TITLE
Unexpected message after starting the app for the first time

### ISSUE THREAD

**Issue by ovivascruz** [OneSignal/OneSignal-Cordova-SDK#660]
**Description:**

After starting the app for the first time, an onesignal message (type In-App Messaging) appears.
It only happens once after the user accepts the permissions and subscribes to the notifications.

**Environment**

Cordova 9
Onesignal 2.11.1

**Steps to Reproduce Issue:**

1. Install the app on the Android or iOS device
1. Start the app
1. After a few seconds the unexpected onesignal message is automatically displayed

**Anything else:**

The message only appears once and is after the user has successfully subscribed to the notifications. I have managed to hide it temporarily using this method **window.plugins.OneSignal.pauseInAppMessages (true)** but unfortunately it persists in showing in the next times I open the app.
How can I stop it from showing or remove it?

Below is a screenshot with the message
https://dirbiemar.pe/content/img/message.jpg

**Comment by rgomezp** [comment]
Howdy,
I think you might have an in-app message set live on your app. Please reach out to our support channel at OneSignal.com for help regarding this issue.

Cheers
