### ISSUE TITLE
[Bug] Cannot view In-App Messages when using cordova-plugin-inappbrowser

### ISSUE THREAD

**Issue by jagzmz** [OneSignal/OneSignal-Cordova-SDK#661]
**Description:**

I am implementing an app that opens an InAppBrowser to view a specific website. While sending In-App messages they are not being shown if the InAppbrowser is opened, but are when it's not opened.

How can I implement this so that In-App Messages from OneSignal will overlay on InAppBrowser(Cordova)

**Environment**

Cordova CLI Version: 10.0.0
Cordova Android Version: 9.0.0

**Steps to Reproduce Issue:**

1. Add the onesignal-cordova-plugin to your project
1. Add cordova-plugin-inappbrowser to your project
1. Initialize the plugin with your app ID
1. Open any URL with Cordova Inappbrowser
1. Attempt to receive an InApp message notification

**Comment by rgomezp** [comment]
Howdy,
Are you seeing this issue in Android? iOS? If you could also provide us with logs with `setLogLevel` set to VERBOSE that would help as well. ([reference](https://documentation.onesignal.com/docs/sdk-reference#setloglevel-method))

Cheers

**Comment by rgomezp** [comment]
Closing due to no response
