### ISSUE TITLE
How to target devices where the app is not currently being used

### ISSUE THREAD

**Issue by marcopierac** [OneSignal/OneSignal-Cordova-SDK#662]
**Description:**
Hello, i have a cordova app with your plugin installed to receive notifications from my backend. My backend is php + laravel + composer package `laravel-notification-channels/onesignal`.
I've tested my setup and it works correctly, my users receive the notifications i send from my backend.
I have notifications for multiple events, and one of them is the app's chat "received message" event. I'd like to have the device receive a notification of "new message received" **if and only if** the user is not currently chatting inside the app. How do i do that? 
So my question is: **how can i target only devices where the app is not currently being used?**

ps: just as info, a single user (identified by the `external user id` property already set via the SDK) can have multiple devices

**Environment**

```log
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebview-file-xhr 2.1.1 "Cordova WKWebView File XHR Plugin"
onesignal-cordova-plugin 2.11.1 "OneSignal Push Notifications"
```

**Steps to Reproduce Issue:**

1. setup frontend app with cordova plugin to receive notifications; build and install the app
1. setup backend to send notifications
1. **send notification only to users / devices where the app is not currently being used** (how?)

**Comment by rgomezp** [comment]
Howdy,
The best way wouldn't be to target users that aren't in use but rather to target devices normally and then only show the notification on the device if the app is not in use. This can be controlled client-side using the `inFocusDisplaying` functionality which you can learn more about [here](https://documentation.onesignal.com/docs/sdk-reference#initialization-settings).

Cheers

**Comment by marcopierac** [comment]
> Howdy,
> The best way wouldn't be to target users that aren't in use but rather to target devices normally and then only show the notification on the device if the app is not in use. This can be controlled client-side using the `inFocusDisplaying` functionality which you can learn more about [here](https://documentation.onesignal.com/docs/sdk-reference#initialization-settings).
> 
> Cheers

Hello, thank you for your reply and for pointing me in the right direction.
I guess i should set `inFocusDisplaying` to `None`, then work with `notification.isAppInFocus`.

But then what should i do, if i actually wanted to show the notification? Should i post a new notification `postNotification` (like rethrowing errors in a `try...catch` block) ?
Or is there some method to show the current notification?

Thank you

**Comment by rgomezp** [comment]
Howdy,
Currently there is no way to dynamically control whether the notification will show or not when the app is in foreground. If you set it to NONE it will never show if the app is open.

In the future, you _will_ be able to control this dynamically when the upcoming major-version release change is released.

You can read more about it [here](https://documentation.onesignal.com/docs/react-native-40-api-reference#foreground-notification-control) although this is for the React Native SDK. We will release the same thing for Cordova soon.

Thanks for your patience and your good questions.

Enjoy!

**Comment by marcopierac** [comment]
Thanks for the reference!

Doesn't setting it to `None` mean that I could hook into the notification **received** event and manage the notification there and, like, "re-launch" it?

Thanks for your attention and patience

**Comment by rgomezp** [comment]
These things have nothing to do with each other. In the future the `inFocusDisplaying` will no longer exist. Everything will be managed via the the `NotificationWillShowInForegroundHandler`
