### ISSUE TITLE
is it possible to ring user ringtone instead of custom sound ?

### ISSUE THREAD

**Issue by indraraj26** [OneSignal/OneSignal-Cordova-SDK#663]
**Description:**

I would like to ring user ringtone like whatsapp 

**Environment**

Cordova CLI       : 10.0.0
Cordova Platforms : android 9.0.0
onesignal-cordova-plugin 2.11.0 "OneSignal Push Notifications"

**Steps to Reproduce Issue:**

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
I suppose it's possible by using the [RingtoneManager](https://developer.android.com/reference/android/media/RingtoneManager.html) and the [OneSignal service extension](https://documentation.onesignal.com/docs/service-extensions) to set the URI of the sound file that you want in the `CompatBuilder`. That said, be prepared to write native code for your app.

This is an [old response](https://stackoverflow.com/questions/15809399/android-notification-sound) but should put you on the correct path.

Good luck!
