### ISSUE TITLE
Cannot set/overwrite external user ID after subscription reset

### ISSUE THREAD

**Issue by NoNameProvided** [OneSignal/OneSignal-Cordova-SDK#666]
**Description:**

When a OneSignal subscription is deleted from the dashboard, the client SDK will register a new one, but I guess it won't remove the locally cached external user ID so the external user ID cannot be registered again with the same content as the SDK will return:

```
WARNING: Attempted to set external user id, but 3 is already set
```

This warning is returned even when **no external ID 3 is assigned to any existing subscription**, checked on the console.

Workaround could have been to remove and reset the variable but it doesn't seem to work, as the called function returns immediately and I believe the reregistration of the same ID start faster than the first unregister removes the local ID, so this scenario returns the same warning above.

My working workaround is to call the REST API directly and register the ID through it not using the SDK.

**Environment**

The app is an Angular based Capacitor app. Our current version is `@capacitor/*@2.4.2.

List of installed plugins:

* cordova-plugin-inappbrowser (4.0.0)
* onesignal-cordova-plugin (2.11.1)

We are using OneSignal through the `@ionic-native/onesignal` package.

**Steps to Reproduce Issue:**
<!--
  Example:

1. Add the onesignal-cordova-plugin to your project
1. Initialize the plugin with your app ID
1. Set external user ID eg: `3`
1. Remove subscription from dashboard
1. Restart app and wait until SDK register a new subscription
1. Attempt to set new external user ID with the same content (`3`)
1. Observe the SDK won't allow (as probably the external user ID is still cached)

**Comment by rgomezp** [comment]
Howdy,
It looks like OneSignal doesn't remove the external user id when the subscription is removed manually via the dashboard. The ideal way to remove an external id is via the `removeExternalUserId` [function](https://documentation.onesignal.com/docs/sdk-reference#removeexternaluserid-method). However, this appears to just be a warning so I don't believe this should result in unwanted behavior.

**Comment by NoNameProvided** [comment]
Hi! 

Thanks for the reply!

> It looks like OneSignal doesn't remove the external user id when the subscription is removed manually via the dashboard.

Yes, but I would re-phrase this as the problem is that the SDK smart enough to register a new subscription but not smart enough to understand the external ID cached locally is invalid because it's subscription (the old one) is gone. I would expect either of these two scenarios:
- on new automatic re-subscription the locally set external user ID is removed by the SDK
- on new automatic re-subscription the locally set external user ID is automatically set for the new SDK

Small side note:  the documentation is misleading on this part, as it states when a subscription is removed via the dashboard the SDK wont register a new one until the app is not reinstalled. However in reality it detects if a subscription is removed from the server and automatically register a new one. (This is the better behavior IMO, but docs need to be updated.)

> The ideal way to remove an external id is via the removeExternalUserId function. 

There is two problem here so I split the reply into two.

A, I understand that I can remove the external user ID with that function, but the only workaround for the discussed case would be to remove and re-add the ID on every startup as I have no idea whether the subscription has been removed or not in the application code. That's why I said above that I would expect the ID is set automatically for a new subscription.

B, ~The problem with that is it doesn't work. The exposed function returns void, so there is no way to wait until it completes.~ Ohh, I see from the linked documentation that the original function accepts a callback, sadly this is not the case for the wrapper I use (` @ionic-native/onesignal`) which returns void and doesn't accept a callback, so there is no way in the code for me to see whether it's completed or not. (I need to open an issue there too.)

Your advice is what I tried originally but as said before because in the wrapper there is no way to wait until it's removed the second call will emit the warning (as the ID is still set, because the first call is still in progress) and won't update the ID to the new one. 

```js
OneSignal.removeExternalUserId();
OneSignal.setExternalUserId(id);
```

What I would expect from `setExternalUserId` command is that it always updates the ID even if when the SDK thinks the given value has been set already.

> However, this appears to just be a warning so I don't believe this should result in unwanted behavior.

It's not just a warning, the __SDK wont send the request when it thinks the same ID has been set already__. (At least seems this way from me from the logs from XCode when the loglevel is set to verbose.

**Comment by rgomezp** [comment]
I see. Thank you for the detailed response @NoNameProvided .

We will discuss internally and provide you with next steps.

**Comment by jkasten2** [comment]
@NoNameProvided Based on the behavior this seems like it is an issue in the OneSignal-iOS-SDK code base with caching as you noted. It most likely isn't clearing this cache when a new player record is created. It could be from the SDKs handling of getting a new player_id for the `on_session` call, or the SDK making a POST player to create a new one due to a PUT failing due to the player_id no longer existing.

Next steps would be to review the exiting OneSignal-iOS-SDK code to confirm this is due to a caching issue.

**Comment by NoNameProvided** [comment]
Just to clarify things, am I supposed to look for the bug and point out the faulty code snippet?

**Comment by rgomezp** [comment]
@NoNameProvided ,
Thanks for your patience.

No, we will review the code on our side.

Cheers

**Comment by rgomezp** [comment]
Howdy @NoNameProvided ,
Thanks for your patience. This has been resolved in the major release (currently in beta).

Cheers
