### ISSUE TITLE
Vibrate multiple times 

### ISSUE THREAD

**Issue by danielehrhardt** [OneSignal/OneSignal-Cordova-SDK#669]
Hi 
I am currently programming a call App and I want to ask if it is possible to send a push and then the Android Device should vibrate multiple times. 

I installed the App Ring from Amazon and there it is possible. 

Is this possible with One signal?
Best
Daniel

**Comment by rgomezp** [comment]
Howdy,
We allow you to specify whether the notification will vibrate or not using `enableVibrate` ([reference](https://documentation.onesignal.com/docs/cordova-sdk#enablevibrate)).

However, for Cordova if you want to do more fancy notification customization you would have to write native Android code and modify the notification via the [Extender Service](https://documentation.onesignal.com/docs/service-extensions).

Cheers
