### ISSUE TITLE
Priority on notifications

### ISSUE THREAD

**Issue by jorma16** [OneSignal/OneSignal-Cordova-SDK#67]
I have a problem, I'm trying to do heads up push notifications and is not possible for me, I think that is because the priority is not set fine.

I send the priority tag to 10 but don't setup the push correctly.

How can I did heads up push notifications?

Thanks in advice!

**Comment by jkasten2** [comment]
@jorma16 The priority option is the GCM send priority, it is used to wake the device up out of doze mode on Android 6.0+ devices. We will be adding the display priority to match up in the future. You can follow this Android issue for updates.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/10

**Comment by jkasten2** [comment]
@jorma16 Sorry about the delay, this was added in the 2.0.7 release of the Cordova SDK.
