### ISSUE TITLE
Support for Google Play Services 17.0.+

### ISSUE THREAD

**Issue by bikash8gupta** [OneSignal/OneSignal-Cordova-SDK#672]
**Description:**
While building the app, i get error - Dependency failing: com.onesignal:OneSignal:3.15.3 -> com.google.android.gms:play-services-base@[10.2.1, 16.1.99], but play-services-base version was 17.3.0.
Please add support for google play services 17.0.+ version

**Environment**
1. Cordova Android version - 9.0.0
2. Project dependencies - 
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 11.0.3 "Google Firebase Plugin"
cordova-plugin-googleplus 8.5. "Google SignIn"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-whitelist 1.3.4 "Whitelist"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.11.1 "OneSignal Push Notifications

**Comment by jkasten2** [comment]
@bikash8gupta Thanks for reporting, it seems there is a compatibility issue with `cordova-plugin-firebasex` and `onesignal-cordova-plugin`.

` com.onesignal:OneSignal:3.15.3` specifically sets `com.google.android.gms:play-services-base@[10.2.1, 16.1.99]` as any higher version of `play-services-base` includes AndroidX which `onesignal-cordova-plugin` 2.x.x hasn't switched to yet. However if you enable Jetifier a higher version can be used.

Normally the `OneSignal-Gradle-Plugin` also used by `onesignal-cordova-plugin` will auto bump the `play-services-base` max range. However there is a race condition with `cordova-plugin-firebasex`'s Gradle script and  `OneSignal-Gradle-Plugin`'s `disableGMSVersionChecks`.
Conflicts beelow:
* https://github.com/dpa99c/cordova-plugin-firebasex/blob/11.0.3/src/android/build.gradle#L43
* https://github.com/OneSignal/OneSignal-Gradle-Plugin/blob/0.12.9/src/main/groovy/com/onesignal/androidsdk/GradleProjectPlugin.groovy#L298-L302

**Comment by talyuk** [comment]
Is there any solution for now?

**Comment by jkasten2** [comment]
@bikash8gupta @talyuk We just released [OneSignal-Gradle-Plugin 0.12.10](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.12.10) that fixes the compatibility issue with `cordova-plugin-firebasex`. This new version should automatically be pulled in when you do a clean build of Android or manually sync Gradle. No update to `onesignal-cordova-plugin` is needed.

**Comment by talyuk** [comment]
@jkasten2 thanks, now it works fine!
