### ISSUE TITLE
Dependency fail on play-services-location

### ISSUE THREAD

**Issue by tmishutin** [OneSignal/OneSignal-Cordova-SDK#673]
**Description:**
When building android, failing on gradle dependency.

(your description here)

**Environment**
Cordova android 9.0.0
code-push 3.0.1 "CodePushAcquisition"
com.santinowu.cordova.imagedownloader 1.0.3 "ImageDownloader"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 3.0.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-appcenter-analytics 0.3.6 "App Center Analytics for Cordova"
cordova-plugin-appcenter-shared 0.3.6 "App Center shared code for Cordova"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-code-push 1.13.1 "CodePush"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-document-viewer 0.9.13 "SitewaertsDocumentViewer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-file-transfer 2.0.0-dev "File Transfer"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-intercom 9.2.1 "Intercom"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media 5.0.3 "Media"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-mediapicker-dmcsdk 2.4.5 "MediaPicker"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.3 "SocialSharing"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
eeschiavo-cordova-plugin-clipboard 1.0.2 "Clipboard"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.11.1 "OneSignal Push Notifications"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"

**Anything else:**

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
WARNING: The onesignal-gradle-plugin MUST be before com.android.application!
   Please put onesignal-gradle-plugin first OR update to com.android.tools.build:gradle:3.0.0 or newer!
OneSignalPlugin: WARNING: OneSignalPlugin: Downgraded 'com.android.support:27+' -> 28.+ to prevent compile errors! Recommend updating your project's compileSdkVersion!
Dependency resolved to an incompatible version: Dependency(fromArtifactVersion=ArtifactVersion(groupId=com.onesignal, artifactId=OneSignal, version=3.15.3), toArtifact=Artifact(groupId=com.google.android.gms, artifactId=play-services-location), toArtifactVersionString=[10.2.1, 16.0.99])

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[10.2.
  1, 16.0.99]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.onesignal:OneSignal:3.15.3 -> com.google.android.gms:play-services-location@[10.2.1, 16.0.99], b
  ut play-services-location version was 15.0.1.

  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto com.google.android.gms:play-services-location@{strictly 15.0.1}
  -- Project 'app' depends onto com.onesignal:OneSignal@3.15.3
  -- Project 'app' depends onto com.onesignal:OneSignal@{strictly 3.15.3}

  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience. You're on an old version of the gradle plugin. Please update your gradle plugin to the latest.

https://github.com/OneSignal/OneSignal-Gradle-Plugin/

Enjoy!
