### ISSUE TITLE
Security Issue and Best Practices

### ISSUE THREAD

**Issue by Cod3Guy** [OneSignal/OneSignal-Cordova-SDK#674]
**Description:**

We have found some security vulnerability in several codes, can admin provide enhancement or fixes on these?

1) SQL injection vulnerability allows an attacker to inject malicious input into an SQL statement

* com/onesignal/OneSignalDbHelper.java
* io/sqlc/SQLiteAndroidDatabase.java 

2) Almost all code can be reverse-engineered with enough skill, time and effort

* com/onesignal/OneSignalNotificationManager.java
* com/onesignal/GcmBroadcastReceiver.java 
* com/onesignal/OSInAppMessageController.java 
*  com/onesignal/WebViewManager.java 
*  com/onesignal/NotificationBundleProcessor.java 
*  com/onesignal/OSViewUtils.java 
*  com/microsoft/cordova/StatusReport.java 
*  com/microsoft/cordova/CodePushPreferences.java 
*  com/microsoft/cordova/CodePushPackageMetadata.java 
*  com/microsoft/aad/adal/CordovaAdalPlugin.java 
*  com/microsoft/aad/adal/ApplicationReceiver.java 
*  com/microsoft/aad/adal/AuthenticationParameters.java 
*  com/microsoft/aad/adal/AuthenticationConstants.java 
*  com/microsoft/aad/adal/Discovery.java 
*  com/plugin/gcm/OneSignalPush.java 
* de/appplant/cordova/plugin/badge/BadgeImpl.java 

3) Insecure Randomness occurs when a function that can produce predictable values is used as a source of randomness in security-sensitive context.

* com/onesignal/GenerateNotification.java 

**Environment**

"onesignal-cordova-plugin": "2.8.0",

**Steps to Reproduce Issue:**

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@Cod3Guy Thanks for reporting. If possible, could you share the raw report you have extract this list from?

---

> 1. SQL injection vulnerability allows an attacker to inject malicious input into an SQL statement
>* com/onesignal/OneSignalDbHelper.java

We can review for this but do you have more specific details?

> 2. Almost all code can be reverse-engineered with enough skill, time and effort

This does not apply to OneSignal. All SDKs are open source.

> 3. Insecure Randomness occurs when a function that can produce predictable values is used as a source of randomness in security-sensitive context.
> * com/onesignal/GenerateNotification.java

I don't believe this is a security issue here. The usage of the randomness here could result in a notification collision issue of replacing a notification is a very rare case at the worst.

**Comment by rgomezp** [comment]
Closing due to no response
