### ISSUE TITLE
Documentation Link throwing 500 Error

### ISSUE THREAD

**Issue by dhavalsoni2001** [OneSignal/OneSignal-Cordova-SDK#675]
**Description:**
https://documentation.onesignal.com/docs/cordova-sdk-setup - Opening thin link throws 500  Internal Server Error

**Environment**

MacOs
Chrome

**Steps to Reproduce Issue:**

1. Open this link - https://documentation.onesignal.com/docs/cordova-sdk-setup 

.

**Anything else:**

(crash stacktraces, as well as any other information here)

![Screenshot 2020-11-09 at 5 35 20 PM](https://user-images.githubusercontent.com/11704436/98539212-f7fc6080-22b1-11eb-93fa-7251a2e834b3.png)

**Comment by jfishman1** [comment]
Hello

This is an issue with readme.io and they are having some issues in India it seems: https://www.readmestatus.com/

It should be fixed soon, sorry for the inconvenience.
