### ISSUE TITLE
ionic ios app rejected from appstore - UIWebView issue

### ISSUE THREAD

**Issue by prabhashibuddhima** [OneSignal/OneSignal-Cordova-SDK#676]
**Description:**

After I add one signal to my ionic app, Appstore is rejecting my app due to Deprecated API Usage: New apps that use UIWebView are no longer accepted.

**Steps to Reproduce Issue:**

1. npm install
1. sudo gem install cocoapods
1. pod repo update
1. ionic cordova platform add ios@5.1.0
1. ionic cordova prepare ios
1. cordova build ios

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by gurwinder-macrew** [comment]
Any update on it? I'm also facing same issue.

**Comment by jkasten2** [comment]
This fix was included in [OneSignal-Cordova-SDK 2.10.2](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.6.0) released Sep. 16 2019.

Make sure you have this version or newer. If this is already updated I recommend doing a clean build. You can also check your `Podfile.lock` and confirm you have `OneSignal` [2.10.2](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.10.2) which is the native iOS SDK used by this Cordova SDK.

**Comment by gurwinder-macrew** [comment]
@jkasten2 I have installed latest version of OneSignal (onesignal-cordova-plugin 2.11.1 "OneSignal Push Notifications"). But I'm still facing this issue. I have also tried by removing and re-adding ios platform.

If I remove the OneSignal plugin and upload on Appstore then it works and when I upload build with OneSignal plugin then Apple rejects the build by saying "ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability"

@jkasten2 Should I need to downgrade the OneSignal version to 2.10.2 to resolve the issue?

FYI:
**ionic info**           

Ionic:

   Ionic CLI                     : 6.12.2 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.5.1
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.3.29
   @angular/cli                  : 8.3.29
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 8.1.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 10 other plugins)

Utility:

   cordova-res : 0.15.2
   native-run  : 1.2.2

System:

   Android SDK Tools : 26.1.1 (/Users/macrew/Library/Android/sdk)
   ios-deploy        : 1.11.1
   ios-sim           : 8.0.2
   NodeJS            : v10.16.1 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C505


**Podfile.lock**
PODS:
  - OneSignal (2.15.2)
  - razorpay-pod (1.1.10)

DEPENDENCIES:
  - OneSignal (= 2.15.2)
  - razorpay-pod

SPEC REPOS:
  trunk:
    - OneSignal
    - razorpay-pod

COCOAPODS: 1.10.0


@jkasten2 Please help me to resolve this issue.

Thanks.

**Comment by prabhashibuddhima** [comment]
Hi,

I have finally solved this issue by following these steps (in terminal)

`ionic cordova platform add ios@5.1.0`
`cordova plugin update cordova-plugin-ionic-webview@latest `

add to congig.xml under platform = ios

```
<feature name="CDVWKWebViewEngine">
<param name="ios-package" value="CDVWKWebViewEngine" />
</feature>
<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
<preference name="WKWebViewOnly" value="true" />
```


then again in terminal

```
ionic cordova prepare ios

cordova build ios
```


build was success and got approved from app store :)

**Comment by gurwinder-macrew** [comment]
> Hi @gurwinder-macrew,
> 
> I have finally solved this issue by following these steps (in terminal)
> 
> `ionic cordova platform add ios@5.1.0`
> `cordova plugin update cordova-plugin-ionic-webview@latest `
> 
> add to config.xml under platform = ios
> 
> ```
> <feature name="CDVWKWebViewEngine">
> <param name="ios-package" value="CDVWKWebViewEngine" />
> </feature>
> <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
> <preference name="WKWebViewOnly" value="true" />
> ```
> 
> then again in terminal
> 
> ```
> ionic cordova prepare ios
> 
> cordova build ios
> ```
> 
> build was success and got approved from app store :)
> 
> > Any update on it? I'm also facing same issue.

Works!
Thanks.
