### ISSUE TITLE
 get id not working in android 10 device?

### ISSUE THREAD

**Issue by prakashmp** [OneSignal/OneSignal-Cordova-SDK#677]
Am using this config..but am not getting player id..could you please suggest solution.. i already added 
    this.oneSignal.setLogLevel({logLevel: 6, visualLevel: 2});
My config: 

```
    "onesignal-cordova-plugin": "^2.11.1",
    "@ionic-native/onesignal": "^5.28.0",

```

**Comment by prakashmp** [comment]
Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 14 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.2.2) : 0.2.8

System:

   Android SDK Tools : 26.1.1 (/opt/adt-bundle-linux-x86_64-20140702/sdk)
   NodeJS            : v12.12.0 (/usr/local/bin/node)
   npm               : 6.10.3

**Comment by prakashmp** [comment]
you must initialize onesignal before modifying tags moving this operation to a pending task queue >> am getting this  response in onPushOpened

**Comment by rgomezp** [comment]
Howdy,
Please follow our full issue template so we can better assist you.

Cheers
