### ISSUE TITLE
iOS, badges not clearing.

### ISSUE THREAD

**Issue by NickyYo** [OneSignal/OneSignal-Cordova-SDK#69]
The iOS badge numbers are not clearing when close a push notification.  Anyone else experience this?

**Comment by jkasten2** [comment]
@NickyYo We made a large number of internal changes to our SDK in our 2.0 version. Can you try this new version and let us know if you are still seeing an issue.
https://documentation.onesignal.com/docs/cordova-sdk-setup

**Comment by NickyYo** [comment]
@jkasten2 Thank you for the update.  Do we know if we may experience any other issues in the future if we do not upgrade to this version? like deprecations etc?

**Comment by jkasten2** [comment]
@NickyYo To clarify, are you only clearing the notification from the iOS notification center? You need to go back to your app so our SDK can clear the badge count.

**Comment by jkasten2** [comment]
@NickyYo Feel free to reply and reopen this issue if you are seeing any issues.
