### ISSUE TITLE
Is it Possible to change default Floating Notification and Allow Sound settings?

### ISSUE THREAD

**Issue by Lungaville** [OneSignal/OneSignal-Cordova-SDK#690]
**Description:**
Hi, is it possible to change default notification settings (sound and floating notification) programmatically?

**Environment**
onesignal-cordova-plugin: 2.11.1

**Steps to Reproduce Issue:**

**Anything else:**
Screenshot of default notitification settings
![image](https://user-images.githubusercontent.com/36563652/107093867-9f991880-6838-11eb-9f89-3375e0657f1a.png)

**Comment by nguyenhuutinh** [comment]
hello ,did you find the answer?

**Comment by Vladeouz** [comment]
hello any solution ?

**Comment by jkasten2** [comment]
This is possible with Notification Category / Channels noted here:
https://documentation.onesignal.com/docs/android-notification-categories

**Comment by Vladeouz** [comment]
> This is possible with Notification Category / Channels noted here: https://documentation.onesignal.com/docs/android-notification-categories

Okay, thank you, i'll try it soon
