### ISSUE TITLE
Saving Onesignal setup when reinstalling iOS platform

### ISSUE THREAD

**Issue by July-** [OneSignal/OneSignal-Cordova-SDK#691]
We need to delete and re-add platform when debugging or upgrading. And every time we setup Onesignal in Xcode, which is quite time-consuming. Is there a way to save Onesignal settings in this case?

**Comment by Aarbel** [comment]
@July- have you found a way ?

**Comment by July-** [comment]
Not yet.
I tried to copy xcworkspace and xcodeproj files and then paste it back after reinstalling platform, this seemed to save settings but caused build error, probably because some of updated plugins were incompatible with old setup

**Comment by rgomezp** [comment]
@July- ,
Why do you need to delete and re-add the platform? To me that sounds more like something you should do once at initial set up only.

Your solution would be the only thing I would recommend, but you may need to fix the dependency management issues.

Cheers

**Comment by July-** [comment]
@rgomezp 
`Why do you need to delete and re-add the platform? To me that sounds more like something you should do once at initial set up only.`
Well, every time when we have build errors and search for solutions, there are always suggestions to re-add platform, it seems that re-adding platform is quite a common action during Cordova app development :D
