### ISSUE TITLE
I don't get notifications in the background

### ISSUE THREAD

**Issue by YotzinAlexander** [OneSignal/OneSignal-Cordova-SDK#692]
Hi, excuse me ... I can't receive notifications in the background, does anyone know if it is necessary to implement any special method?
i am using ionic 5..

**Comment by jkasten2** [comment]
@YotzinAlexander I recommend checking out this troubleshooting guide as it covers all the common scenarios:
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

Feel free to follow up with what you have tried if you're still stuck.

**Comment by rgomezp** [comment]
Closing due to no response
