### ISSUE TITLE
getPermissionSubscriptionState() is unreliable until startInit() finishes and startInit() has no event for when it finishes.

### ISSUE THREAD

**Issue by epetre** [OneSignal/OneSignal-Cordova-SDK#701]
**Description:**
Maybe I'm missing something but, but this issues is making the app think we don't have pushes in some situations described below.

When setting up `startInit`, it sometimes takes a while before the values of getPermissionSubscriptionState() are populated, I assume that this is because OneSignal sometimes takes a bit to initialize.

When this happens, the default values for when we check getPermissionSubscriptionState() are all wrong it seems and when they end up being correct (initialized I assume) there is no event fired (notificationPermissionChange also doesn't fire in that situation) because the values didn't change from what they actually are. This, in effect, makes those values incorrect for the duration of the session because we have no way of knowing what they are at the beginning or when they are set.

**Those values become unreliable untel the startInit() completes**
subscribed
pushToken
userId
permissionStatus

**Environment**
Latest

**Steps to Reproduce Issue:**
It happens sporadically on iOS, but possibly on Android too... as you can imagine it's not really easy for us to reproduce this.
  1. start the app that had given push permissions in a prevous session and where everything should be available.
  2. startInit() takes a while this session (not sure why, but it happens sporadically)
  3. while startInit() takes a while, if the app tries to call getPermissionSubscriptionState(), the app gets the wrong values.
  4. startInit() finishes, there's no indication it finished, so we don't know that we can now trust those values in getPermissionSubscriptionState().

Is there any solution you guys already have for this?
Am I missing an event to hook on to for when the initialization is complete?

**Comment by epetre** [comment]
It is similar to this: https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/622

**Comment by emawby** [comment]
Hello @epetre I apologize for not getting you a reply earlier. Is this still an issue in the 3.0.1 version?

**Comment by epetre** [comment]
Hello @emawby , I have no idea, we built workarounds that ensures it is done after in our case and we moved on, so I'm not sure about V3.

**Comment by emawby** [comment]
Ok closing for now. Feel free to reopen if this is an issue
