### ISSUE TITLE
Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.3, 0.99.99].

### ISSUE THREAD

**Issue by m4ur1c10** [OneSignal/OneSignal-Cordova-SDK#707]
**Description:**

I started having problems with my android development environment on windows with the version 2 capacitor. When I try to generate a project with onesignal-cordova-plugin, it generates the following errors:

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\mauma\ionic-projects\espresso-labs-app-bs-capacitor\tibox-app\android\app\capacitor.build.gradle' line: 21

* What went wrong:
A problem occurred evaluating script.
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not resolve gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.3, 0.99.99].
     Required by:
         unspecified:unspecified:unspecified
      > No matching variant of gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.13.2 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally but:
          - Variant 'apiElements' capability gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.13.2 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
          - Variant 'runtimeElements' capability gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.13.2 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8

(your description here)

**Environment**

Ionic:

   Ionic CLI                     : 6.9.1 (C:\Users\*\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.3.4
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 3.0.1
   @capacitor/core : 3.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : no whitelisted plugins (0 plugins total)

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run                             : 1.4.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\*\AppData\Local\Android\Sdk)
   NodeJS            : v12.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.14.4
   OS                : Windows 10

**Steps to Reproduce Issue:**

1. npx ionic build && npx cap update android && npx cap sync android && npx cap copy && npx cap open android
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
Thanks for reporting! Java 8 compatibility has been fully restored in the [onesignal-gradle-plugin 0.13.4](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.13.4) Release.

Re-sync gradle in Android Studio and /or performing a clean build should result in automatically upgrading.
