### ISSUE TITLE
inFocusDisplaying = OSInFocusDisplayOption.InAppAlert not working in Huawei/Cordova

### ISSUE THREAD

**Issue by rekony** [OneSignal/OneSignal-Cordova-SDK#711]
**Description:**
I have an existing Ionic Cordova app where i have set the inFocusDisplaying to use OSInFocusDisplayOption.InAppAlert and it works well in Android and IOS. However when i try to setup it for Huawei devices (non google service device), the InAppAlert doesn't work and it only shows the Notification Banner. 

I would like to know if the InAppAlert should work in Huawei devices as well ? 

**Environment**
Cordova v10.0.0
Cordova-Android v9.1.0
onesignal-cordova-plugin - tried up to the latest v2.11.4
@ionic-native/onesignal v5.33.1
@hmscore/ionic-native-hms-push v5.1.1-301
@hmscore/cordova-plugin-hms-push v5.1.1-301

**Steps to Reproduce Issue:**
OneSignal initialization code: 

this.oneSignal.startInit('myappid');
this.oneSignal.inFocusDisplaying(this.oneSignal.OSInFocusDisplayOption.InAppAlert);
this.oneSignal.handleNotificationOpened().subscribe('mycallback');
this.oneSignal.endInit();

**Comment by jkasten2** [comment]
@rekony By default OneSignal sends HMS notifications as a "message" type, instead of "data" as it does with FCM. This results in different behavior however it can be changed. More details in this comment:
https://github.com/OneSignal/react-native-onesignal/issues/1188#issuecomment-805464111
