### ISSUE TITLE
OneSignal Security Problems

### ISSUE THREAD

**Issue by georgealfredo** [OneSignal/OneSignal-Cordova-SDK#713]
Hi guys, one malicious user is copying my application and my project id from onesignal (he decoded my apk and get app id). The problem is he is making this request to onesignal:

![Image of Request](https://i.ibb.co/hgfGMf6/Request.jpg)

This request make my users as invalid_identifier = true and generate a new player id causing data mismatch and trouble with notifications.

Device example:
`{"id":"REMOVED","identifier":"cjB8rFjgN1o:APA91bHAah4wlbNoa-44rVREMOVED PARTIAL","session_count":6,"language":"pt","timezone":-14400,"game_version":"APP VERSION","device_os":"8.1.0","device_type":1,"device_model":"Twist 3","ad_id":"REMOVED","tags":REMOVED,"last_active":1625091294,"playtime":1437,"amount_spent":0.0,"created_at":1617737598,"invalid_identifier":true,"badge_count":0,"sdk":"031506","test_type":null,"ip":"REMOVED","external_user_id":null}`

**Comment by jkasten2** [comment]
@georgealfredo Please reach out to OneSignal support so they can help you address this issue since it is specific to your OneSignal account.
