### ISSUE TITLE
One Signal is blocked in Algeria 

### ISSUE THREAD

**Issue by AbbasGas** [OneSignal/OneSignal-Cordova-SDK#714]
(One signal service for android is blocked in Algeria
and i'm loosing many clients is there anything you can do please )

the blocking started in December 2020  sorry for my bad language

**Comment by jkasten2** [comment]
@AbbasGas Thanks for reporting. I recommend contacting OneSignal support at support@onesignal.com if you are not able to reach onesignal.com. I recommend also letting them know your ISP so they can also look into the block.

**Comment by faycal1** [comment]
HI any news on this topic , onesignal is still blocked in Algeria , thank you

**Comment by mghabdo** [comment]
still blocked in algeria 
but sometimes the notification work

**Comment by elouanesbg** [comment]
still blocked in algeria , no notification has been recived , i c'ant access my account , only by using a VPN

**Comment by zackAJ** [comment]
I just figured out that it's not the website itself, it is the google Oauth 2 service.

The SSL handshake fails when:

- Login or Register from Algerian ip.
- Being already logged in (via VPN or when it works sometimes without VPN) and then visiting the Dashboard (which goes through O Auth therefore fails again).
- visiting https://app.onesignal.com/users/auth/google_oauth2 .

**Comment by faycal1** [comment]
thx for the tip , i use directly firebase messaging , less headache

**Comment by AbbasGas** [comment]
the same thing happened again blocked
