### ISSUE TITLE
Failed to set external user id

### ISSUE THREAD

**Issue by nathanguigui** [OneSignal/OneSignal-Cordova-SDK#719]
**Description:**
Can't set external user id with hash verification

**Environment**
I'm using capacitor:
```
    "@capacitor/android": "^3.0.0",
    "@capacitor/app": "^1.0.2",
    "@capacitor/cli": "^3.0.0",
    "@capacitor/core": "^3.0.0",
    "@capacitor/device": "^1.0.2",
    "@capacitor/haptics": "^1.0.2",
    "@capacitor/ios": "^3.0.0",
    "@capacitor/network": "^1.0.2",
```
I'm using `"onesignal-cordova-plugin": "3.0.0-beta3"`

Here is my `npx cap ls android`:
```
[info] Found 7 Capacitor plugins for android:
       @capacitor/app@1.0.2
       @capacitor/device@1.0.2
       @capacitor/haptics@1.0.2
       @capacitor/network@1.0.2
       @capacitor/push-notifications@1.0.2
       @capacitor/splash-screen@1.0.2
[info] Found 1 Cordova plugin for android:
       onesignal-cordova-plugin@3.0.0-beta3
```

**Steps to Reproduce Issue:**

  1. Add the onesignal-cordova-plugin (beta 3) to your project
  2. Initialize the plugin with your app ID
  3. Set external userId with hash

**Anything else:**

When I call `OneSignal.setExternalUserId(userId, oneSignalUserIdHash, console.log)`, I have the following error:
`Error: The old format of this exec call has been removed (deprecated since 2.1). Change to: cordova.exec(null, null, 'Service', 'action', [ arg1, arg2 ]);`

**Comment by emawby** [comment]
@nathanguigui Hello I apologize for the very late response. Is this still an issue in the latest SDK version?

**Comment by nathanguigui** [comment]
Hello sorry I don't know.
I don't work anymore on the project where I saw the bug
