### ISSUE TITLE
Package com.onesignal does not exist

### ISSUE THREAD

**Issue by menshinobi** [OneSignal/OneSignal-Cordova-SDK#72]
When I install the latest cordova OneSignal plugin and then build the project, the build fails because package com.onesignal does not exist. How can I fix this issue? Thanks!

**Comment by jkasten2** [comment]
@menshinobi I recommend trying a clean build by removing all plugins, deleting the platform folder, and reinstalling the plugins. See the below link for more details.
https://documentation.onesignal.com/docs/cordova-troubleshooting

If you are still seeing the issue please attach your build log error.

**Comment by jkasten2** [comment]
@menshinobi Feel free to reopen this issue if you are still seeing this problem.
