### ISSUE TITLE
Error "lacks return" building Ionic Capacitor project

### ISSUE THREAD

**Issue by rts-kcole** [OneSignal/OneSignal-Cordova-SDK#726]
When I build the project after installing onsignal-cordova-plugin I get these errors

Error: node_modules/onesignal-cordova-plugin/types/OneSignalPlugin.d.ts:155:5 - error TS7010: 'deleteTags', which lacks return-type annotation, implicitly has an 'any' return type.

155     deleteTags(keys: string[]);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/onesignal-cordova-plugin/types/OneSignalPlugin.d.ts:170:5 - error TS7010: 'logoutEmail', which lacks return-type annotation, implicitly has an 'any' return type.

170     logoutEmail(handler?: Function);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/onesignal-cordova-plugin/types/OneSignalPlugin.d.ts:185:5 - error TS7010: 'logoutSMSNumber', which lacks return-type annotation, implicitly has an 'any' return type.

185     logoutSMSNumber(handler?: Function);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by dmitry-salnikov** [comment]
Same issue when using Cordova.

**Comment by nunoarruda** [comment]
I have the same issue when using `onesignal-cordova-plugin` v3.x on an Angular v13.x project:

```bash
Error: node_modules/onesignal-cordova-plugin/types/OneSignalPlugin.d.ts:157:5 - error TS7010: 'deleteTags', which lacks return-type annotation, implicitly has an 'any' return type.

157     deleteTags(keys: string[]);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/onesignal-cordova-plugin/types/OneSignalPlugin.d.ts:172:5 - error TS7010: 'logoutEmail', which lacks return-type annotation, implicitly has an 'any' return type.

172     logoutEmail(handler?: Function);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/onesignal-cordova-plugin/types/OneSignalPlugin.d.ts:187:5 - error TS7010: 'logoutSMSNumber', which lacks return-type annotation, implicitly has an 'any' return type.

187     logoutSMSNumber(handler?: Function);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

<img width="1305" alt="Screenshot 2021-12-10 at 15 20 10" src="https://user-images.githubusercontent.com/1189149/145606590-e676f32e-0c2b-4ba5-8505-880f7b904c1b.png">

This is breaking my build so I am forced to stay on `onesignal-cordova-plugin` v2.x for now.

OneSignal team, can you please fix this when you have a chance?

**Comment by dafi** [comment]
Any news about this annoying bug?

The only solution I found requires to turn off `noImplicitAny` in `tsconfig.json` but it is a bit drastic

```
  "compilerOptions": {
    ...
    "noImplicitAny": false,
   }
```

**Comment by nunoarruda** [comment]
One of the OneSignal team members already reviewed and approved PR #762 which fixes these issues. Hopefully, they will merge the PR soon.
