### ISSUE TITLE
Ionic 5 ERROR plugin_not_installed

### ISSUE THREAD

**Issue by Evanzsnr** [OneSignal/OneSignal-Cordova-SDK#728]
**Description:**

I have installed this plugin in ionic 5 and built the app  successfully. But when I run the app, I get the error below in the console.
```
main-es2015.26f1f1a75b39f0f13032.js:1 Native: tried calling OneSignal.startInit, but the OneSignal plugin is not installed.
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
main-es2015.26f1f1a75b39f0f13032.js:1 Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
main-es2015.26f1f1a75b39f0f13032.js:1 Native: tried calling OneSignal.inFocusDisplaying, but the OneSignal plugin is not installed.
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
main-es2015.26f1f1a75b39f0f13032.js:1 Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
main-es2015.26f1f1a75b39f0f13032.js:1 Native: tried calling OneSignal.handleNotificationReceived, but the OneSignal plugin is not installed.
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
main-es2015.26f1f1a75b39f0f13032.js:1 Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
main-es2015.26f1f1a75b39f0f13032.js:1 Native: tried calling OneSignal.handleNotificationOpened, but the OneSignal plugin is not installed.
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
main-es2015.26f1f1a75b39f0f13032.js:1 Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
main-es2015.26f1f1a75b39f0f13032.js:1 Native: tried calling OneSignal.endInit, but the OneSignal plugin is not installed.
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
main-es2015.26f1f1a75b39f0f13032.js:1 Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'
(anonymous) @ main-es2015.26f1f1a75b39f0f13032.js:1
2main-es2015.26f1f1a75b39f0f13032.js:1 ERROR plugin_not_installed
```

**Environment**

```
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-androidx-build 1.0.4 "cordova-androidx-build"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 3.0.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.1.2 "Permissions"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.8.0-20200709-2008 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 3.4.1 "NativeGeocoder"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-sms-retriever-manager 1.0.2 "Device"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
onesignal-cordova-plugin 3.0.0 "OneSignal Push Notifications"
```

**Steps to Reproduce Issue:**

1.  Add the onesignal-cordova-plugin to your project using ``` ionic cordova plugin add onesignal-cordova-plugin ``` and ```npm install @ionic-native/onesignal```
2. Build the project using the comand ```ionic cordova build android --prod```
3. Run the application on the device.

**Comment by iAmWillShepherd** [comment]
👋🏾  @Evanzsnr.

I just wanted to send an ACK. I'll report back with mitigation steps once I have an understanding of what's going on. Thanks for providing this context 🙌🏾

**Comment by Evanzsnr** [comment]
Okay @iAmWillShepherd, I will be waiting for feedback.

**Comment by jkasten2** [comment]
@Evanzsnr Thanks for reporting, are you following the OneSignal guide from Ionic Framework's docs?
* https://ionicframework.com/docs/native/onesignal

If so it is for the 2.x.x version of the OneSignal SDK, we will reach out to them to get them to update their docs to the 3.x.x version of the OneSignal SDK.

If you are setting OneSignal up for the first time I recommend removing `@ionic-native/onesignal` and the current OneSignal code and follow the OneSignal setup guide: 
* https://documentation.onesignal.com/docs/ionic-sdk-setup

If are attempting to upgrade OneSignal from 2.x.x to 3.x.x see the step-by-step migration guide:
* https://documentation.onesignal.com/docs/step-by-step-cordova-2x-to-300-upgrade-guide

**Comment by Evanzsnr** [comment]
I tried using the setup guide [here](https://documentation.onesignal.com/docs/ionic-sdk-setup) but I cannot see the setup that includes ionic + cordova, which I happen to be using. I can only go as far as installing onesignal using ```ionic cordova plugin add onesignal-cordova-plugin --save```. The rest of the code doesn't include cordova implementation so I'm unable to continue from there.

**Comment by RintuMondal06** [comment]
Having the same issue, please help !!

**Comment by Evanzsnr** [comment]
> Having the same issue, please help !!

@RintuMondal06 are you using ionic and cordova?

**Comment by Evanzsnr** [comment]
Previously I was using ionic and cordova when I got that error. I was advised that cordova is nolonger supported by onesignal, so I switched to capacitor and everything is fine now.

**Comment by Evanzsnr** [comment]
@ravimallya does your app receive push notifications when it is in the background and when closed? Mine only receives the notifications when in the foreground only. Push notifications are not received when closed or in the background. That is with the 2.11.4 version of the sdk.

**Comment by ravimallya** [comment]
I do receive when the app is running in the background as well, i.e. if the app is not terminated. Not checked after exiting. However, after I rolled back the version to 2.11.4, most of the people are complaining that they're not receiving notifications.

**Comment by Carlosps** [comment]
> * https://ionicframework.com/docs/native/onesignal

Where have you been advised that cordova is nolonger supported by onesignal?

**Comment by Evanzsnr** [comment]
That it's nolonger supported officially with ionic.

**Comment by sander-spruit** [comment]
Same issue

**Comment by Carlosps** [comment]
> Same issue

I am not using the Ionic wrapper anymore. 

I am using 

> window['plugins']['OneSignal']

**Comment by sander-spruit** [comment]
Okay, but that doesn't solve the issue

**Comment by Jay031** [comment]
As a simple fix, please use the following;

ionic cordova plugin add `onesignal-cordova-plugin@2.11`
npm install `@ionic-native/onesignal@5.27`

Then use this as import statement:
`import { OneSignal } from '@ionic-native/onesignal/ngx';`

Further you could just use the docs.
My setup works and is like this:

```
// OneSignal configuration
vm.oneSignal.startInit(appId, googleProjectNumber);
vm.oneSignal.inFocusDisplaying(vm.oneSignal.OSInFocusDisplayOption.Notification);

vm.oneSignal.handleNotificationReceived().subscribe(() => {
  // do something when notification is received
});

this.oneSignal.handleNotificationOpened().subscribe((payload) => {
  // do something when notification is opened
});

vm.oneSignal.endInit();
```

**Comment by jkasten2** [comment]
I believe the `plugin_not_installed` error has been solved, please provide more details and we can investigate further if this is not the case.

`@ionic-native/onesignal` is used to add TypeScript support to 2.x.x versions of `onesignal-cordova-plugin`. If you are using `onesignal-cordova-plugin` 3.0.0+ the TypeScript types are already built in so you should remove `@ionic-native/onesignal` from your project.

If you are seeing any other issues please search for related issues and provide your details or open a new issue and we can look into them. Thanks.

**Comment by Mr-Anonymous** [comment]
Thank you @[jkasten2](https://github.com/jkasten2) I had the same `plugin_not_installed` error and to resolve it I did these steps:

1. Uninstalled `@awesome-cordova-plugins/onesignal`:
```
npm uninstall  @awesome-cordova-plugins/onesignal
```

2. Removed the DI for the above from `app.module.ts` and `app.component.ts`.

3. Deleted the old codes from `app.component.ts` that used the `startInit()`, `inFocusDisplaying()`, `handleNotificationOpened()`, etc.

4. Followed the official documentation [here](https://documentation.onesignal.com/docs/ionic-sdk-setup) to add the OneSignal code but that did not help either. Since that was still giving me the error `Cannot read properties of undefined (reading 'setAppId')`. So I then added the below code without adding `import { OneSignal } from 'onesignal-cordova-plugin';` and it seem to work:

```
OneSignalInit() {
    if (!this.oneSignalAppId) { return; }
    
    // Uncomment to set OneSignal device logging to VERBOSE  
    // OneSignal.setLogLevel(6, 0);

    // NOTE: Update the setAppId value below with your OneSignal AppId.
    (window as any).plugins.OneSignal.setAppId(this.oneSignalAppId);
    (window as any).plugins.OneSignal.setNotificationOpenedHandler(function(jsonData) {
        console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
    });

    // iOS - Prompts the user for notification permissions.
    //    * Since this shows a generic native prompt, we recommend instead using an In-App Message to prompt for notification permission (See step 6) to better communicate to your users what notifications they will get.
    (window as any).plugins.OneSignal.promptForPushNotificationsWithUserResponse(function(accepted) {
        console.log("User accepted notifications: " + accepted);
    });
  }
```

This is my `ionic info`:
```
Ionic:

   Ionic CLI                     : 6.18.1 (/Users/neel/.nvm/versions/node/v17.4.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.0.5
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.1, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 9 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (/Users/neel/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v17.4.0 (/Users/neel/.nvm/versions/node/v17.4.0/bin/node)
   npm               : 8.3.1
   OS                : macOS Monterey
   Xcode             : Xcode 13.2.1 Build version 13C100

```

**Comment by jkasten2** [comment]
@Mr-Anonymous Thanks for the details on how you fix the issue!

In the OneSignal documentation on step 3.2 it has `import OneSignal from 'onesignal-cordova-plugin';` but you noted you put `import { OneSignal } from 'onesignal-cordova-plugin';`. Do both ways of importing work for you? Or did you specifically have to put curly braces `{}` around `OneSignal`?

**Comment by jackdaniel9** [comment]
I have this error with method off @Mr-Anonymous :

window.plugins.OneSignal.getIds is not a function... I need to get the phone id to send notification to specific user with Laravel Web App ?

With console.log(window.plugins.OneSignal):

```
OSNotificationPermission: {NotDetermined: 0, Authorized: 1, Denied: 2}
addEmailSubscriptionObserver: ƒ (callback)
addPermissionObserver: ƒ (callback)
addSMSSubscriptionObserver: ƒ (callback)
addSubscriptionObserver: ƒ (callback)
addTrigger: ƒ (key, value)
addTriggers: ƒ (triggers)
clearOneSignalNotifications: ƒ ()
completeNotification: ƒ (notification, shouldDisplay)
deleteTag: ƒ (key)
deleteTags: ƒ (keys)
disablePush: ƒ (disable)
getDeviceState: ƒ (deviceStateReceivedCallBack)
getTags: ƒ (tagsReceivedCallBack)
getTriggerValueForKey: ƒ (key, callback)
isLocationShared: ƒ (callback)
logoutEmail: ƒ (onSuccess, onFailure)
logoutSMSNumber: ƒ (onSuccess, onFailure)
pauseInAppMessages: ƒ (pause)
postNotification: ƒ (jsonData, onSuccess, onFailure)
promptForPushNotificationsWithUserResponse: ƒ (callback)
promptLocation: ƒ ()
provideUserConsent: ƒ (granted)
registerForProvisionalAuthorization: ƒ (provisionalAuthCallback)
removeExternalUserId: ƒ (externalUserIdCallback)
removeGroupedNotifications: ƒ (groupId)
removeNotification: ƒ (id)
removeTriggerForKey: ƒ (key)
removeTriggersForKeys: ƒ (keys)
requiresUserPrivacyConsent: ƒ (callback)
sendOutcome: ƒ (name, callback)
sendOutcomeWithValue: ƒ (name, value, callback)
sendTag: ƒ (key, value)
sendTags: ƒ (tags)
sendUniqueOutcome: ƒ (name, callback)
setAppId: ƒ (appId)
setEmail: ƒ (email, emailAuthToken, onSuccess, onFailure)
setExternalUserId: ƒ (externalId, varArg1, varArg2)
setInAppMessageClickHandler: ƒ (handler)
setLanguage: ƒ (language)
setLocationShared: ƒ (shared)
setLogLevel: ƒ (nsLogLevel, visualLogLevel)
setNotificationOpenedHandler: ƒ (handleNotificationOpenedCallback)
setNotificationWillShowInForegroundHandler: ƒ (handleNotificationWillShowInForegroundCallback)
setRequiresUserPrivacyConsent: ƒ (required)
setSMSNumber: ƒ (smsNumber, smsAuthToken, onSuccess, onFailure)
unsubscribeWhenNotificationsAreDisabled: ƒ (unsubscribe)
userProvidedPrivacyConsent: ƒ (callback)

```

**Comment by hallbird** [comment]
> As a simple fix, please use the following;
> 
> ionic cordova plugin add `onesignal-cordova-plugin@2.11` npm install `@ionic-native/onesignal@5.27`
> 
> Then use this as import statement: `import { OneSignal } from '@ionic-native/onesignal/ngx';`
> 
> Further you could just use the docs. My setup works and is like this:
> 
> ```
> this.platform.ready().then(() => {
>   // OneSignal configuration
>   this.oneSignal.startInit(appId, googleProjectNumber);
>   this.oneSignal.inFocusDisplaying(vm.oneSignal.OSInFocusDisplayOption.Notification);
>   
>   this.oneSignal.handleNotificationReceived().subscribe(() => {
>     // do something when notification is received
>   });
>   
>   this.oneSignal.handleNotificationOpened().subscribe((payload) => {
>     // do something when notification is opened
>   });
>   
>   this.oneSignal.endInit();
> });
> ```

Thank you, 

That works for me

**Comment by marcioramosilva1** [comment]
> m install `@ionic-n`

When i compile at Android 31+, it don't work, and when i upgrade to 3.0.0+ don't register at oneSignal.

Help me please

**Comment by enigcreator** [comment]
Just import onesignal from the plugin itself. 

`import OneSignal from 'onesignal-cordova-plugin';`


Use it like this: 

`  OneSignalInit(): void {
    // Uncomment to set OneSignal device logging to VERBOSE  
    // OneSignal.setLogLevel(6, 0);
  
    // NOTE: Update the setAppId value below with your OneSignal AppId.
    OneSignal.setAppId(this.config.oneSignalID);
    OneSignal.setNotificationOpenedHandler(function(jsonData) {
        console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
    });
  
    // Prompts the user for notification permissions.
    //    * Since this shows a generic native prompt, we recommend instead using an In-App Message to prompt for notification permission (See step 7) to better communicate to your users what notifications they will get.
    OneSignal.promptForPushNotificationsWithUserResponse(function(accepted) {
        console.log("User accepted notifications: " + accepted);
    });
    OneSignal.getDeviceState((resp) => {
      this.storage.set('push_id', resp.userId)
    })
  }`

**Comment by INARTECHSA** [comment]
@enigcreator it doesnt work on XCode build, it gives this error
![error](https://user-images.githubusercontent.com/105000467/188865265-ba9345fb-0bf5-4f4c-b61c-5caa7c7bcde8.png)

@hallbird i have tried yur code but on XCode it gives this error
![error2](https://user-images.githubusercontent.com/105000467/188865730-f113a814-ea6c-4dcd-bb70-a35e26478004.png)

**Comment by Shlok-IT** [comment]
> Thank you @[jkasten2](https://github.com/jkasten2) I had the same `plugin_not_installed` error and to resolve it I did these steps:
> 
> 1. Uninstalled `@awesome-cordova-plugins/onesignal`:
> 
> ```
> npm uninstall  @awesome-cordova-plugins/onesignal
> ```
> 
> 2. Removed the DI for the above from `app.module.ts` and `app.component.ts`.
> 3. Deleted the old codes from `app.component.ts` that used the `startInit()`, `inFocusDisplaying()`, `handleNotificationOpened()`, etc.
> 4. Followed the official documentation [here](https://documentation.onesignal.com/docs/ionic-sdk-setup) to add the OneSignal code but that did not help either. Since that was still giving me the error `Cannot read properties of undefined (reading 'setAppId')`. So I then added the below code without adding `import { OneSignal } from 'onesignal-cordova-plugin';` and it seem to work:
> 
> ```
> OneSignalInit() {
>     if (!this.oneSignalAppId) { return; }
>     
>     // Uncomment to set OneSignal device logging to VERBOSE  
>     // OneSignal.setLogLevel(6, 0);
> 
>     // NOTE: Update the setAppId value below with your OneSignal AppId.
>     (window as any).plugins.OneSignal.setAppId(this.oneSignalAppId);
>     (window as any).plugins.OneSignal.setNotificationOpenedHandler(function(jsonData) {
>         console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
>     });
> 
>     // iOS - Prompts the user for notification permissions.
>     //    * Since this shows a generic native prompt, we recommend instead using an In-App Message to prompt for notification permission (See step 6) to better communicate to your users what notifications they will get.
>     (window as any).plugins.OneSignal.promptForPushNotificationsWithUserResponse(function(accepted) {
>         console.log("User accepted notifications: " + accepted);
>     });
>   }
> ```
> 
> This is my `ionic info`:
> 
> ```
> Ionic:
> 
>    Ionic CLI                     : 6.18.1 (/Users/neel/.nvm/versions/node/v17.4.0/lib/node_modules/@ionic/cli)
>    Ionic Framework               : @ionic/angular 6.0.5
>    @angular-devkit/build-angular : 13.0.4
>    @angular-devkit/schematics    : 13.0.4
>    @angular/cli                  : 13.0.4
>    @ionic/angular-toolkit        : 5.0.3
> 
> Cordova:
> 
>    Cordova CLI       : 11.0.0
>    Cordova Platforms : android 10.1.1, ios 6.2.0
>    Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 9 other plugins)
> 
> Utility:
> 
>    cordova-res : 0.15.4
>    native-run  : 1.5.0
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (/Users/neel/Library/Android/sdk)
>    ios-sim           : 8.0.2
>    NodeJS            : v17.4.0 (/Users/neel/.nvm/versions/node/v17.4.0/bin/node)
>    npm               : 8.3.1
>    OS                : macOS Monterey
>    Xcode             : Xcode 13.2.1 Build version 13C100
> ```

Thank worked for me

**Comment by devsgtech** [comment]
I have upgraded onesignal-cordova-plugin to latest version and now I am not receiving any notification for my website but when I check in one signal website sent messaged panel is show that notification is delivered what should I do my app is running successfully.

**Comment by george19gt** [comment]
> I have upgraded onesignal-cordova-plugin to latest version and now I am not receiving any notification for my website but when I check in one signal website sent messaged panel is show that notification is delivered what should I do my app is running successfully.

Hello, I solved it as follows:

**1 Uninstall** 
```
cordova plugin rm onesignal-cordova-plugin

npm uninstall @ionic-native/onesignal --save
```

**2 Install**
```
cordova plugin add onesignal-cordova-plugin --save

npm install @ionic-native/onesignal --save
```

In my **OneSignal Service**:

```
import { Injectable } from '@angular/core';
import { ONESIGNAL_CONFIG } from '../config/onesignal.config';

import OneSignal from 'onesignal-cordova-plugin';

@Injectable({
  providedIn: 'root'
})
export class OnesignalService {

  uid: any;
  oneSignalConfig: any = ONESIGNAL_CONFIG;

  constructor() { }

  initConfig(){
    OneSignal.setAppId(this.oneSignalConfig.appId);

    OneSignal.setNotificationOpenedHandler((jsonData) => {
      console.log('setNotificationOpenedHandler: ' + JSON.stringify(jsonData));
    });

    OneSignal.promptForPushNotificationsWithUserResponse((accepted) => {
      console.log('promptForPushNotificationsWithUserResponse: ' + accepted);
    });

    OneSignal.getDeviceState((resp: any) => {
      const osUser: any = resp;
      this.uid = osUser.userId;
     });

  }

}

```

In **app.component.ts**

```
import { Component } from '@angular/core';

import { Platform } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';
import { OnesignalService } from './services/onesignal.service';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss']
})
export class AppComponent {

  constructor( private platform: Platform, private splashScreen: SplashScreen, private statusBar: StatusBar,
               private oneSignal: OnesignalService ) {

    this.initializeApp();

  }

  initializeApp() {

    this.platform.ready().then(() => {

      this.statusBar.styleDefault();
      this.splashScreen.hide();
      this.oneSignal.initConfig();

    });

  }

}

```

**Comment by NicolasPapp94** [comment]
Hi i can't solve the problem with Ionic 5 and Cordova (Plugin not installed). But when I downgrade to 2.11.4 notifications still not working. Someone have a solution for that?

**Comment by amirzaverify** [comment]
> As a simple fix, please use the following;
> 
> ionic cordova plugin add `onesignal-cordova-plugin@2.11` npm install `@ionic-native/onesignal@5.27`
> 
> Then use this as import statement: `import { OneSignal } from '@ionic-native/onesignal/ngx';`
> 
> Further you could just use the docs. My setup works and is like this:
> 
> ```
> this.platform.ready().then(() => {
>   // OneSignal configuration
>   this.oneSignal.startInit(appId, googleProjectNumber);
>   this.oneSignal.inFocusDisplaying(vm.oneSignal.OSInFocusDisplayOption.Notification);
>   
>   this.oneSignal.handleNotificationReceived().subscribe(() => {
>     // do something when notification is received
>   });
>   
>   this.oneSignal.handleNotificationOpened().subscribe((payload) => {
>     // do something when notification is opened
>   });
>   
>   this.oneSignal.endInit();
> });
> ```

Working fine Thanks

**Comment by MarkEcho** [comment]
> As a simple fix, please use the following;
> 
> ionic cordova plugin add `onesignal-cordova-plugin@2.11` npm install `@ionic-native/onesignal@5.27`
> 
> Then use this as import statement: `import { OneSignal } from '@ionic-native/onesignal/ngx';`
> 
> Further you could just use the docs. My setup works and is like this:
> 
> ```
> this.platform.ready().then(() => {
>   // OneSignal configuration
>   this.oneSignal.startInit(appId, googleProjectNumber);
>   this.oneSignal.inFocusDisplaying(vm.oneSignal.OSInFocusDisplayOption.Notification);
>   
>   this.oneSignal.handleNotificationReceived().subscribe(() => {
>     // do something when notification is received
>   });
>   
>   this.oneSignal.handleNotificationOpened().subscribe((payload) => {
>     // do something when notification is opened
>   });
>   
>   this.oneSignal.endInit();
> });
> ```

Working fine. Thanks brother

**Comment by timeisgolden** [comment]
> @enigcreator it doesnt work on XCode build, it gives this error ![error](https://user-images.githubusercontent.com/105000467/188865265-ba9345fb-0bf5-4f4c-b61c-5caa7c7bcde8.png)
> 
> @hallbird i have tried your code but on XCode it gives this error ![error2](https://user-images.githubusercontent.com/105000467/188865730-f113a814-ea6c-4dcd-bb70-a35e26478004.png)
> 
> Im using Ionic with Capacitor and i have followed onesignal's docs for the Ionic/Capacitor implementation

Hi, I am getting the same issue. 
```
⚡️  [warn] - Native: tried calling OneSignal.getTags, but the OneSignal plugin is not installed.
⚡️  [warn] - Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'
⚡️  [error] - ERROR plugin_not_installed
```
I installed the following packages.
```
"@awesome-cordova-plugins/onesignal": "^6.4.0",
"onesignal-cordova-plugin": "^5.0.0",
```
Anyone help me to solve this issue?
This is my ionic info:
```
Ionic:

   Ionic CLI                     : 7.1.1 (/Users/devteam/.nvm/versions/node/v16.14.2/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.4.0
   @angular-devkit/build-angular : 16.2.0
   @angular-devkit/schematics    : 16.2.0
   @angular/cli                  : 16.2.0
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.4.0
   @capacitor/android : 5.4.0
   @capacitor/core    : 5.4.0
   @capacitor/ios     : 5.4.0

Utility:

   cordova-res : 0.15.4
   native-run  : 1.7.2

System:

   NodeJS : v16.14.2 (/Users/devteam/.nvm/versions/node/v16.14.2/bin/node)
   npm    : 8.5.0
   OS     : macOS Unknown
```

**Comment by barart** [comment]
This is a very annoying puzzle, first @ionic-native is deprecated and its called now @awesome-cordova-plugins, however follow the documentation of awesome-cordova-plugis do not work because documentation its obsolete or it has missing information.

One signal documentation its obsolete too and they made breaking changes and both, onesignal and awesome-cordova-plugins are not in the same channel and both with misleading information, what i understand (trying to resolve the puzzle) is this:

1) @ionic-native and @awesome-cordova-plugins (talking about onesignal obviously) are based on onesignal 2.x
2) Both (@ionic-native and @awesome) are clients for onesignal sdk
3) Both needs onesignal sdk (thats why you need to install native onesignal sdk )
4) If you install onesignal sdk it will install v5 but @ionic-native and @awesome plugins are clients for onesignal sdk 2.x so they will not work (and thats its what is not mentioned on plugins documentation)
5) Both plugins are obsolete for new onesignal sdk so you need to install onesignal sdk 2.x, but.. who wants to install a old sdk?
6) Now, you need a skd plugin client that works with new onesignal 5.x sdk but there are none, so you must use native one sdk plugin and native onesignal sdk client BUT onesignal documentation is mixed, because they have TWO sdk clients (v9 and v11 version) v9 version is player_id based and v11 version is suscription_id based (new user id)
7) Native Onesignal plugin documentation examples are 2.x based too

So, with many changes with plugins and onesignal sdks, everything is mixed, and the lack of documentation and mixed documentation using onesignal with ionic its becomming annoying, i have been doing this puzzle for almost 12 hours and i have not been able to restore the notifications in my app using latest plugins or onesignal native plugins

The easiest way is to use @awesome and onesignal-cordova-plugin 2.x but you will be running years back sdk's that maybe will be out in a near future OR they are already out

If you want to use native onesignal client plugin and sdk you will be alone on your boat because there is not reliable documentation about it because the onesignal sdks changes and you will figure how to make it works on your project because the mixed documentation

So at the end this is annoying

**Comment by dukec2020** [comment]
> > As a simple fix, please use the following;
> > ionic cordova plugin add `onesignal-cordova-plugin@2.11` npm install `@ionic-native/onesignal@5.27`
> > Then use this as import statement: `import { OneSignal } from '@ionic-native/onesignal/ngx';`
> > Further you could just use the docs. My setup works and is like this:
> > ```
> > this.platform.ready().then(() => {
> >   // OneSignal configuration
> >   this.oneSignal.startInit(appId, googleProjectNumber);
> >   this.oneSignal.inFocusDisplaying(vm.oneSignal.OSInFocusDisplayOption.Notification);
> >   
> >   this.oneSignal.handleNotificationReceived().subscribe(() => {
> >     // do something when notification is received
> >   });
> >   
> >   this.oneSignal.handleNotificationOpened().subscribe((payload) => {
> >     // do something when notification is opened
> >   });
> >   
> >   this.oneSignal.endInit();
> > });
> > ```
> 
> Working fine. Thanks brother

CONFIRM this method works on IOS project and IOS only works on this version - but doesn't work on Android SDK  >=33.
The version of _onesignal-cordova-plugin@2.11_ is deprecated on Android. 
I still stuck on how to make it work on Android 
My project use ionic & capacitor

**Comment by dukec2020** [comment]
> As a simple fix, please use the following;
> 
> ionic cordova plugin add `onesignal-cordova-plugin@2.11` npm install `@ionic-native/onesignal@5.27`
> 
> Then use this as import statement: `import { OneSignal } from '@ionic-native/onesignal/ngx';`
> 
> Further you could just use the docs. My setup works and is like this:
> 
> ```
> this.platform.ready().then(() => {
>   // OneSignal configuration
>   this.oneSignal.startInit(appId, googleProjectNumber);
>   this.oneSignal.inFocusDisplaying(vm.oneSignal.OSInFocusDisplayOption.Notification);
>   
>   this.oneSignal.handleNotificationReceived().subscribe(() => {
>     // do something when notification is received
>   });
>   
>   this.oneSignal.handleNotificationOpened().subscribe((payload) => {
>     // do something when notification is opened
>   });
>   
>   this.oneSignal.endInit();
> });
> ```
CONFIRM this method works on IOS project and IOS only works on this version - but doesn't work on Android SDK >=33.
The version of onesignal-cordova-plugin@2.11 is deprecated on Android.
I still stuck on how to make it work on Android
My project use ionic & capacitor
