### ISSUE TITLE
[OneSignal setExternalUserId unrecognized selector sent to instance

### ISSUE THREAD

**Issue by parksmart-dev** [OneSignal/OneSignal-Cordova-SDK#729]
**Description:**

Working fine on Android, iOS I can trigger the permission prompt and then it seems to fail on setting the external Id.

[OneSignal setExternalUserId unrecognized selector sent to insance

**Environment**

"onesignal-cordova-plugin": "^3.0.0",
pod 'OneSignalXCFramework', '3.7.0'
iPhone6,2 - iOS (12.4.8)

2021-09-10 20:46:56.105018+0100 APP[318:12607] -[__NSCFNumber length]: unrecognized selector sent to instance 0xf1e424725be343f5
2021-09-10 20:46:56.109869+0100 APP[318:12607] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber length]: unrecognized selector sent to instance 0xf1e424725be343f5'
*** First throw call stack:
(0x1f2613180 0x1f17eb9f8 0x1f252f9bc 0x1f26189c8 0x1f261a65c 0x101ba4fcc 0x1009a2b94 0x1009a7040 0x1008a5d48 0x1008a5be8 0x1008a7d50 0x201c4e0cc 0x201db1744 0x201f1d0b8 0x201b3ee38 0x201cfe8a8 0x201b2f9a8 0x201b32568 0x1f97e5648 0x1f97e5908 0x1f25a4f1c 0x1f25a4e9c 0x1f25a4784 0x1f259f6c0 0x1f259efb4 0x*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber length]: unrecognized selector sent to instance 0xf1e424725be343f5'
terminating with uncaught exception of type NSException
1f47a079c 0x21ec46c38 0x100872104 0x1f20628e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by parksmart-dev** [comment]
ah ok, I was passing a number instead of string and iOS didn't like that.  Android didn't mind.

**Comment by bschelling** [comment]
even if you pass a STRING like in js  `18 +'' ` this _still_ happens. 
could you please reopen?  this really should get fixed.

**Comment by sdelrue** [comment]
I had the same issue, if you use an integer as externalId, the app crashes, with the above error. If you cast it to string, it works fine.
Tested with XCode 13.2.1
onesigna-cordova-plugin: ^3.3.0
iOS 12.4

**Comment by rL071** [comment]
thanks parksmart-dev for help
