### ISSUE TITLE
WARNING: appId set, but please call setLaunchOptions(launchOptions) to complete OneSignal init!

### ISSUE THREAD

**Issue by selected-pixel-jameson** [OneSignal/OneSignal-Cordova-SDK#732]
**Description:**
When launching my iOS App I'm getting this warning in the console.

`WARNING: appId set, but please call setLaunchOptions(launchOptions) to complete OneSignal init!`

**Environment**
Ionic Capacitor Version 3.0

**Comment by PeraDev7** [comment]
Did you solve this?

**Comment by selected-pixel-jameson** [comment]
@PeraDev7 @andreasbhansen Nope. OneSignal is MIA. They haven't responded to anything in this repo for a very long time.

**Comment by selected-pixel-jameson** [comment]
@andreasbhansen Yep, works on both Android and iOS.

**Comment by ermik** [comment]
__This warning is informative and does not affect the plugin functionality.__

You can find the code that generates this warning in `OneSignal.m` file of the OneSignal iOS framework that Plugin depends on. It happens either when the `appId` is [set repeatedly][1] or when the `appId` is being set, but [`launchOptions` object has not yet been initialized][2].

If you look at the Plugin source files and the initialization function, you will see that [it does call][3] `setLaunchOptions(launchOptions)` after setting `appId`:

https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/5372e152c5057c30f65bd3506f07995b50214015/src/ios/OneSignalPush.m#L99-L102

The code above triggers the warning at `[OneSignal setAppId:appIdStr]` but then immediately addresses it with `[OneSignal initWithLaunchOptions:launchOptions]` (which is the Objective-C function underlying the `setLaunchOptions(launchOptions)` Swift interface).


[1]: https://github.com/OneSignal/OneSignal-iOS-SDK/blob/fd06483b314f842c16e0a6f74dfb27a04dc7df66/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L632
[2]: https://github.com/OneSignal/OneSignal-iOS-SDK/blob/fd06483b314f842c16e0a6f74dfb27a04dc7df66/iOS_SDK/OneSignalSDK/Source/OneSignal.m#L644
[3]: https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/5372e152c5057c30f65bd3506f07995b50214015/src/ios/OneSignalPush.m#L99-L102

**Comment by emawby** [comment]
Closing for now. @ermik Is correct the warning is just informative. I will look into changing the log level of the message since it seems to be more confusing than helpful.
