### ISSUE TITLE
One signal plugin not work in capacitor ionic

### ISSUE THREAD

**Issue by riyazuddin-r** [OneSignal/OneSignal-Cordova-SDK#735]
cannot read properties of undefined (reading 'setappid') 
or
Cannot read properties of undefined (reading 'exec')

**Comment by riyazuddin-r** [comment]
issue come on runtime in android
![image](https://user-images.githubusercontent.com/59698323/147942158-5331cedd-fff6-46a0-bd5b-75bf90eff53f.png)

and here is my code
![image](https://user-images.githubusercontent.com/59698323/147942260-be73e189-7a22-4b78-9460-b0997b2423a3.png)

**Comment by jkasten2** [comment]
@riyazuddin-r Could you make sure you have correctly followed step 3 in the OneSignal setup guide?
https://documentation.onesignal.com/docs/ionic-sdk-setup#step-3-add-required-code

The important part here is that you call your `initializePushNotification()` function at the right time. Check step 3A, B or C depending on if you are using Vue, Rect, or Angular.

Please share your code where you are calling this if you are still seeing issues.

**Comment by riyazuddin-r** [comment]
I am calling my function in AppComponet.ts construct and I already followed theses steps 
And I am using latest ionic 6 with angular and capacitor 3

**Comment by riyazuddin-r** [comment]
Your response is tooo slowww.😔😔😔😔😔

**Comment by masaner** [comment]
how is this complete, please give details.

**Comment by nan-li** [comment]
Hi @masaner, are you also running into this issue?

**Comment by eranshmil** [comment]
I had the same issue, fixed it by changing the import:
```diff
-import { OneSignal } from 'onesignal-cordova-plugin';
+import OneSignal from 'onesignal-cordova-plugin';
```

**Comment by masaner** [comment]
I fixed it by following the instructions carefully.

```
export class AppComponent implements OnInit{
  title = 'OneSignal-Angular';

  constructor(
    private platform: Platform,
    private statusBar: StatusBar,
    public toastCtrl: ToastController,
    private splashScreen: SplashScreen,
    private ble: BLE,
    private backgroundMode: BackgroundMode,
    private ngZone: NgZone
  ) {
    this.initializeApp();
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.OneSignalInit();
      this.statusBar.styleDefault();
      this.splashScreen.hide();
      this.buffer();
    });
  }
```

I made sure to add  `this.OneSignalInit();`
right after `this.platform.ready().then(() => {`

I suggest carefully reading the instructions and make sure that the workers are all set in your project directory.
