### ISSUE TITLE
Falled to Install Onesignal Cordova Plugin in IOS for create ipa file

### ISSUE THREAD

**Issue by vinay198819-cpu** [OneSignal/OneSignal-Cordova-SDK#737]
I am working on an Ionic application which uses the oneSignal plugin. My project is developed under Windows and the plugin works very well. But when I recover my project on mac, the plugin refuses to install

**Comment by jkasten2** [comment]
@vinay198819-cpu Thanks for reporting. Could you copy the full error you are seeing and at what point in the build process you are getting the error?

**Comment by alextapia007** [comment]
did you install cocoa pods?

**Comment by jkasten2** [comment]
Closing do to inactivity.
