### ISSUE TITLE
Unregister push notifications

### ISSUE THREAD

**Issue by apparition47** [OneSignal/OneSignal-Cordova-SDK#74]
For my app, I require the ability to unregister from push notifications similar to `phonegap-plugin-push`. They've done it like this: [iOS](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/PushPlugin.m#L125), [Android](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/PushPlugin.java#L143). Any ideas on why this isn't in the SDK? Thanks.

**Comment by jkasten2** [comment]
@apparition47 This can be done with the [setSubscription](https://documentation.onesignal.com/docs/cordova-api-reference#setSubscription), set it it `false` to turn off OneSignal push notifications for your app for the user.

**Comment by apparition47** [comment]
Thanks for the prompt response; I believe that should work in my use case.

**Comment by rajithwijepura** [comment]
Is there a similar way when using ionic framework?

**Comment by rajithwijepura** [comment]
@jkasten2 Thanks. It worked.

on logout I set it to `window["plugins"].OneSignal.setSubscription(false);`
then on login `window["plugins"].OneSignal.setSubscription(true);`
