### ISSUE TITLE
5.4.16 install

### ISSUE THREAD

**Issue by deepaksoni0** [OneSignal/OneSignal-Cordova-SDK#741]
**Description:**

(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@deepaksoni0 It looks like we didn't get any of your details on the issue. Please create a new one with all the details in the template and we can follow up.
