### ISSUE TITLE
notificationOpenedCallback not work on ios

### ISSUE THREAD

**Issue by PeraDev7** [OneSignal/OneSignal-Cordova-SDK#743]
**Description:**
The notificationOpenedCallback not work on ios. I have the same code on Android and it works.
**Environment**
Cordova latest version.
Plugins : socialsharing, splashcreen
**Steps to Reproduce Issue:**
1. Launch notification on onesignal
2. Tap on notification
3. The notificationOpenedCallback not fire

**Comment by alextapia007** [comment]
Currently I am using the plugin version 3.0.1 and it works well on both android and iOS, although the initial configuration cost a bit because I currently use a macbook m1.

**Comment by PeraDev7** [comment]
Can you post your code?
Thanks

**Comment by emawby** [comment]
@PeraDev7 Hello is this still an issue for you? Are you using the latest OneSignal Cordova SDK version?
