### ISSUE TITLE
window.plugins.OneSignal object is empty

### ISSUE THREAD

**Issue by asgaraliyev** [OneSignal/OneSignal-Cordova-SDK#746]
**Description:**
window.plugins.OneSignal object is empty

![image](https://user-images.githubusercontent.com/47985813/141015186-09649c40-ed6e-4b56-8b60-eaa1e71d8b9d.png)

**Environment**

**Steps to Reproduce Issue:**
<!--
  Example:

  1. Add the onesignal-cordova-plugin to your project
  2. Initialize the plugin with your app ID
  3. Attempt to receive a push notification

  ` console.log('IS CORDOVA YES')
    console.log("window.plugins.length:",JSON.stringify(window.plugins))
    document.addEventListener('deviceready', function () {
      window.plugins.OneSignal.setLogLevel({logLevel: 6, visualLevel: 0});
      window.plugins.OneSignal.startInit('9923f010-514f-47cf-8dd4-88691db1bfae')
      window.plugins.OneSignal.getIds(function (ids) {
        console.log('SALAM window.plugins.OneSignal', ids)
        oneSignalIds = ids
      })
      window.plugins.OneSignal.endInit()
    })
    window.plugins.OneSignal.setLogLevel({logLevel: 6, visualLevel: 0});
    window.plugins.OneSignal.startInit('9923f010-514f-47cf-8dd4-88691db1bfae')
    window.plugins.OneSignal.getIds(function (ids) {
      console.log('SALAM window.plugins.OneSignal', ids)
      oneSignalIds = ids
    })
    window.plugins.OneSignal.endInit()`

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by doctorgoon** [comment]
Did you find the reason or a solution ?

**Comment by asgaraliyev** [comment]
> Did you find the reason or a solution ?

that was my mistake .I was checking it in browser .I was suppose to do in mobile application.In mobile application it works great now.
