### ISSUE TITLE
Using OneSignal webpush + cordova SDK API both together in one standalone hybrid app

### ISSUE THREAD

**Issue by appplumbr** [OneSignal/OneSignal-Cordova-SDK#75]
I am using webpush api as below:

OneSignal.push(["init", {
    /* Your other init options here */
    welcomeNotification: {
        "title": "My Custom Title",
        "message": "Thanks for subscribing!",
        // "url": "" /* Leave commented for the notification to not open a window on Chrome and Firefox (on Safari, it opens to your webpage) */
    }
}]);

Along with cordova configuration as below in my Cordova hybrid app, which is wrapped into same webapp codebase

window.plugins.OneSignal.init(“xxxxxx-xxxxx-xxxxx-xxxxxx-xxxxxxxx”,
                                   {googleProjectNumber: “00000000000”,autoRegister: true},
                                   notificationOpenedCallback);

window.plugins.OneSignal.enableInAppAlertNotification(true);

**I am not receiving push notifications, Can i use both SDK API together?**

**Comment by jkasten2** [comment]
@appplumbr The Cordova plugins object `window.plugins` can only be accessed from javascript / html files contained in your app. You will need to iframe a remote site from your mobile app keep the OneSignal Cordova plugin working.

Web push notifications do not work from webviews built into apps so the web push SDK could will say the browser is not supported.
