### ISSUE TITLE
Google Play Services Library Error after adding plugin to a clean project

### ISSUE THREAD

**Issue by 4i-helpynet** [OneSignal/OneSignal-Cordova-SDK#750]
**Description:**
Google Play Services Library Error with perfecly clean install of cordova android@9.0.0 or android@10.0.0 with plugin version 2.11.3 or 3.0.0 - tested in device SM-G970F with android 11

**Environment**

Cordova@9.0.0 || Cordova@10.0.0
onesignal-cordova-plugin 2.11.3 || onesignal-cordova-plugin 3.0.0

**Steps to Reproduce Issue:**

1. cordova create oneasignaltest
2. cd onesignaltest
3. cordova plugin add onesignal-cordova-plugin [2.11.3 or 3.0.0 - not any other plugin installed]
4. cordova platform add android [@9.0.0 or @10.0.0 - both tried sdk 29 and sdk 30]
5. Adding JS to js/index.js from the manual, with a valid app id
6. Starting app in device, not in emulator (SM-G970F with android 11)
7. In onesignal admin page with correct device details showed the Google Play Services Library Error message in 'subscribed' column

**Comment by 4i-helpynet** [comment]
[SOLVED] the cordova-plugin-firebasex install (with google-services.json) fixed the problem.
FYI: Onesignal 3.0.0 plugin works with 30 SDK, 3.0.1 works with 31 SDK.

**Comment by nan-li** [comment]
In version 3.0.1, if targeting an Android SDK less than 31, must specify a lower version of `androidx.work:work-runtime:2.6.0`. I will update release notes.

**Comment by jkasten2** [comment]
@4i-helpynet Thanks for reporting and following up with what fixed it for you. If happened to save the logcat from the device of the error with the stack trace that could be helpful.

**Comment by jkasten2** [comment]
Closing as this issue has been solved.
