### ISSUE TITLE
Build Issue - Android - Execution failed for task ':app:checkReleaseAarMetadata' - androidx.work:work-runtime:2.7.1

### ISSUE THREAD

**Issue by jeremywj** [OneSignal/OneSignal-Cordova-SDK#752]
Builds fail targeting sdk 30 @ android 10.1.1

`FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.work:work-runtime:2.7.1.
     AAR metadata file: /Users/agent04/.gradle/caches/transforms-3/73e09204760ea4755dc4d86cf2bf4d4f/transformed/work-runtime-2.7.1/META-INF/com/android/build/gradle/aar-metadata.properties.`

This started with version 3.0.1.  Had to downgrade to 9.0 to get build to work again.

**Comment by Fayozjon** [comment]
+

**Comment by jkasten2** [comment]
@jeremywj @Fayozjon This issue has been addressed in [OneSignal-Gradle-Plugin 0.14.0](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.14.0). This version should automatically be picked up if you do a clean build.
