### ISSUE TITLE
xCode crashes when building ipa 

### ISSUE THREAD

**Issue by qmarcos** [OneSignal/OneSignal-Cordova-SDK#760]
**Description:**

I was using Capacitor 2 with OneSignal Plugin 2, but in the last update we migrate to Capacitor 3 and OneSignal Plugin 3, I can test the application in xcode without problems, build, archive, but when I tried to generate a development ipa, xcode totally crashes. I'm sure the problem is related to OneSignal because If I remove OneSignal from the project, it compiles without problems.

I was adding steps following the official guides and compiling step by step to find where is the point that breaks the compilation process and I found is when I add the Notification Service Extension. 

> **💡 Note**
> If I skip the Notification Service Extension steps, the app compiles ok, so the problem is exactly when adding the service to the app in xcode.

The only step when I see a problem is in the step 4.9, when launching `pod install` when I get this message several times in the terminal:

```
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
```

but at the end I get this message and follow the instructions without problem, changing the suggested value with `$(inherited)`.

```
Analyzing dependencies
Downloading dependencies
Installing OneSignalXCFramework 3.9.1
Generating Pods project
Integrating client project
Pod installation complete! There are 9 dependencies from the Podfile and 9 total pods installed.

[!] The `OneSignalNotificationServiceExtension [Debug]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `OneSignalNotificationServiceExtension [Release]` target overrides the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` build setting defined in `Pods/Target Support Files/Pods-OneSignalNotificationServiceExtension/Pods-OneSignalNotificationServiceExtension.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Environment**

MacOS: BigSur 11.6
xcode version: 13
Capacitor version: 6.13.4
OneSignal SDK version: 3.9.1.

Plugins versions:
```
[info] Found 5 Capacitor plugins for ios:
       @capacitor/app@1.0.6
       @capacitor/geolocation@1.2.0
       @capacitor/share@1.0.7
       @capacitor/splash-screen@1.1.6
       @capacitor/status-bar@1.0.6
[info] Found 1 Cordova plugin for ios:
       onesignal-cordova-plugin@3.0.1
```

Plugins used in the project:

```
def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
end
```

**Steps to Reproduce Issue:**

1. Get up and running an app. Compiling successfully.
2. Add OneSignal Plugin and SDK iOS setup to work with push notifications following these guides:

https://documentation.onesignal.com/docs/ionic-sdk-setup
https://documentation.onesignal.com/docs/ios-sdk-setup#step-2-add-a-notification-service-extension (at step 4.4 of the previous guide) 
https://documentation.onesignal.com/docs/ios-sdk-app-groups-setup (at step 6 of notification service extension guide) 

3. Build 
4. Archive
5. Distribute
6. xcode Crashes when "Compiling bitcode..." 

**Anything else:**

- I have installed OneSignal SDK with the method: "Option 1. Swift Package Manager"

- The error that xcode shows in the terminal when crashes is the following:

```
/Applications/Xcode.app/Contents/MacOS/Xcode ; exit;

2021-12-14 14:33:35.474 Xcode[93901:628291] nil host used in call to allowsSpecificHTTPSCertificateForHost

2021-12-14 14:33:35.474 Xcode[93901:628291] nil host used in call to allowsAnyHTTPSCertificateForHost:
objc[93901]: Class ASVError is implemented in both /Applications/Xcode.app/Contents/SharedFrameworks/GPUToolsCore.framework/Versions/A/GPUToolsCore (0x14727f430) and /Applications/Xcode.app/Contents/PlugIns/GPUDebugger.ideplugin/Contents/Frameworks/GPUToolsASVC.framework/Versions/A/GPUToolsASVC (0x14671d8e8). One of the two will be used. Which one is undefined.
objc[93901]: Class DYShaderAnalyzerNextGPU is implemented in both /Applications/Xcode.app/Contents/SharedFrameworks/MTLToolsShaderProfiler.framework/Versions/A/MTLToolsShaderProfiler (0x147666c48) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/GPUTools/PlugIns/GLToolsShaderProfilerMobileSupport.gtplugin/Contents/MacOS/GLToolsShaderProfilerMobileSupport (0x153c3a9c0). One of the two will be used. Which one is undefined.

2021-12-14 14:33:38.848 Xcode[93901:628547] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called

2021-12-14 14:33:40.061 Xcode[93901:628188] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-19466/IDEKit/NavigableItems/IDENavigableItem.m:1269
Details:  No match from <IDEKeyDrivenNavigableItem 0x7f9ce8cc5110: (supports Any NSObject, represents: <Xcode3EditingGroup: 0x7f9ce94bbfa0>)> to <Xcode3Target:0x7f9ce8dc6b80:App>. Iterating the whole tree might have taken a significant amount of time.
Object:   <IDEKeyDrivenNavigableItem_Xcode3EditingGroup_Any: 0x7f9ce8cc5110>
Method:   -_descendantItemForRepresentedObject:stopAtClass:
Thread:   <NSThread: 0x7f9ce01072c0>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.

2021-12-14 14:33:43.011 Xcode[93901:628299]  IDESourceControlFileStatus: -[IDESourceControlWorkingTree _scheduleFileStatusOperationForWorkspace:serverStatus:authenticationOptions:completionBlock:]_block_invoke :: Operation count exceded; no completion block provided

2021-12-14 14:33:43.601 Xcode[93901:628188] +[NSSavePanel _warmUp] attempted warmup
```

**Comment by jkasten2** [comment]
@qmarcos Can you try updating to the latest Xcode 13.2?

If you are still able to reproduce the crash please provide an Xcode project so we can reproduce the issue and attempt to fix. I would also recommend reporting it to Apple since it may not be something OneSignal can fix.

**Comment by qmarcos** [comment]
Hi @jkasten2 ,

Thanks a lot for your quick response, as you requested I have tried with Xcode 13.2 but this doesn't solve the problem.

I've created a really simple capacitor 3 app and I added OneSignal plugin, then I've tried to create a distribution ipa for this sample app on 2 different computers with Xcode 13.0, 13.1 and 13.2 with no luck.

**Finally I've found the cause and I could solve the problem.**

It's related to step 3 at this guide: https://documentation.onesignal.com/docs/ios-sdk-setup#step-2-add-a-notification-service-extension and step 4.9 here: https://documentation.onesignal.com/docs/ionic-sdk-setup

🚫 If I choose "Option 1. Swift Package Manager" Xcode crashes when creating the ipa.
✅ If I choose "Option 3. CocoaPods" and it works without problems.

Please let me do some additional tests to isolate the precise miss-configuration to reproduce it (cause there are subtle differences in the guides between choosing option 1 and 3, and I think that could be the key).

When I detect the exact error (or errors) I'll update this issue with more info and the demo app repo link.

Thanks again!

**Comment by jkasten2** [comment]
@qmarcos Thanks for the update!
The difference makes sense but I would have expected some kind of build error. The reason being as the `onesignal-cordova-plugin` always brings in the OneSignalXCFramework from CocoaPods and adding it via SwiftPM would mean your project would have a 2nd copy of it.

The following from the [OneSignal iOS Ionic](https://documentation.onesignal.com/docs/ionic-sdk-setup#ios-service-extensions) doc says to only following step 2 from the Notification Service Extension.
> 4.4 Please follow the [Notification Service Extension](https://documentation.onesignal.com/docs/ios-sdk-setup#step-2-add-a-notification-service-extension) guide (only follow Steps 2).

This is a small but important detail, we are going to make this stand out a bit more so that isn't missed.
