### ISSUE TITLE
Build fails when targeting Android 12

### ISSUE THREAD

**Issue by gatelli** [OneSignal/OneSignal-Cordova-SDK#765]
**Description:**
Build failed with Android 12 : missing **android:exported** declaration in merged manifest

**Environment**
Cordova SDK 3.0.1

**Comment by AlexR1712** [comment]
Same here

**Comment by gatelli** [comment]
some news, please ?

**Comment by cruor99** [comment]
So turns out that if you do not get the particular AndroidManifest errors in android studio, you might need to update some gradle plugins - in my particular case it was migrating from the old appcompat to androidx stuff, which android studio did automatically. Then the following activity and receivers showed up, and had to be overwritten in the apps AndroidManifest.

```
<activity android:name="com.onesignal.NotificationOpenedActivityHMS" android:exported="false" tools:node="merge"/>

        <receiver android:name="com.onesignal.GcmBroadcastReceiver" android:exported="false" tools:node="merge" />
        
        <receiver android:name="com.onesignal.BootUpReceiver" android:exported="false" tools:node="merge" />
        
        <receiver android:name="com.onesignal.UpgradeReceiver" android:exported="false" tools:node="merge" />
        
```
Add those inside your <application> body and that *should* catch most of them with regards to  the OneSignal plugin at least :)

**Comment by jkasten2** [comment]
@cruor99 @gatelli @AlexR1712  [OneSignal version 3.0.1](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/3.0.1) fully supports Android 12. Can you double check that you have version 3.0.1 in your project? You can double check this by running `cordova plugin list`.

If you have this version you may need to remove and re-add it to get the gradle settings to refresh. See the details on how to do that below:

### Remove and re-add OneSignal
```
cordova plugin rm onesignal-cordova-plugin
cordova plugin add onesignal-cordova-plugin
```

You may need to fully remove and re-add the Android platform if the above doesn't work.
### Remove the Android platform and re-add it
```
cordova platform rm android
cordova platform add android
```

**Comment by emawby** [comment]
Closing for now. Feel free to reopen if this is still an issue on version 3.0.1

**Comment by GaneshMBabu21** [comment]
Hi @cruor99,  i used your code suggestion i could make a build, But the notification is not receiving, but if i make a build with the older sdk i could receive the notification(Just for your info that onesignal is configured correct). Can you guide me ? Thank you

**Comment by cruor99** [comment]
As per the above, the latest versions of OneSignal should have fixed these.

If you still have issues, refer to their documentations as it's probably some configuration issue on your end.
Note that if you're running it in emulators, you might not be getting anything.

**Comment by mhunesi** [comment]
Hello everyone! It's work for me. 

SDK 31 Android 12 Ionic 3. [OneSignal version 3.0.1](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/3.0.1) fully supports Android 12.

1. Android X enabled.
```
ionic cordova plugin add cordova-plugin-androidx
ionic cordova plugin add cordova-plugin-androidx-adapter
```
2. Add config.xml
```
<preference name="AndroidXEnabled" value="true" />
```

3. Add config.xml platform android.
```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application/activity" xmlns:android="http://schemas.android.com/apk/res/android">
     <activity android:exported="true" />
</edit-config>
```
4. Remove and re-add OneSignal
```
cordova plugin rm onesignal-cordova-plugin
cordova plugin add onesignal-cordova-plugin
```
5. Remove the Android platform and re-add it
```
cordova platform rm android
cordova platform add android
```
