### ISSUE TITLE
ionic3 iOS 15.3 handleNotificationReceived not working when app is in background

### ISSUE THREAD

**Issue by zubinraja** [OneSignal/OneSignal-Cordova-SDK#766]
**Description:**
Using ionc3 with cordova-ios 5.1.1 and OneSignal plugin 2.11.1
with iOS version 15.3 in iPhone, when app is in background and push notification is received. handleNotificationReceived even is not being called. Have already set two flags mutable_content: true, content_available: true
(your description here)

**Environment**

Ionic:

   Ionic CLI          : 6.16.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 27 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v14.17.0 (/usr/local/bin/node)
   npm        : 6.14.13
   OS         : macOS
   Xcode      : Xcode 13.2.1 Build version 13C100

**Steps to Reproduce Issue:**

1. add plugin onesignal-cordova-plugin@2.11.1 and install pods
2. Init OneSignal and handleNotificationReceived to receive notifications
3. When app is in foreground it works, when app is in background, it stops working

**Comment by jkasten2** [comment]
@zubinraja iOS has limits were background work can not be done if the app is swiped away. I recommend checking out this guide on events and your options:
https://documentation.onesignal.com/docs/sdk-notification-event-handlers

Please provide more details on your use case if the above doesn't help.

**Comment by emawby** [comment]
Closing for now. Feel free to reopen if this is not resolved
