### ISSUE TITLE
Best practices for using OneSignal in app with Auth Wall?

### ISSUE THREAD

**Issue by bradical1379** [OneSignal/OneSignal-Cordova-SDK#768]
I was looking for some recommendations on best practices for handling OneSignal push notification/subscriptions in an app that requires login/registration?

I'd prefer to have users whom have not registered or are currently logged out unsubscribed from push notifications. 

I had originally thought about using the `disablePush` method in conjunction with my authentication service to detect if a user is authenticated to set that method to `true` or `false`, but that seems that it would be counterproductive to having a push opt-in option in my apps settings that would allow for users to toggle for the same option. A user could toggle the preference off, then log out, and when they log back in, they will be registered for push notifications.

Is there a better approach for handling this?

**Comment by emawby** [comment]
We have a guide on how to handle multiuser login [here](https://documentation.onesignal.com/docs/users#managing-multiple-users-on-one-device). Please let me know if you still have questions
