### ISSUE TITLE
Push Notifications working on Android but not on iOS using Ionic 6 + Capacitor

### ISSUE THREAD

**Issue by PhantomLinker** [OneSignal/OneSignal-Cordova-SDK#770]
**Description:**

Hello,
I am currently working on a long-term project which was successfully using OneSignal for a long time. A while ago we noticed that we can't receive Push Notifications on iOS devices anymore, although the same code is working on Android. The iPhone 12, which is running iOS 15.2, does receive a Player ID and is also correctly listed in the Audience with all permissions granted. The usage duration and session counter is also working correctly.

We are using Ionic with Capacitor (Angular) and are building the same source code for both phones. When sending the same message to a group containing only these two phones, the Android phone receives the Push Notification and the iPhone does not receive it.

We followed the [official setup guide](https://documentation.onesignal.com/docs/ionic-sdk-setup) and also checked out the [iOS Troubleshootings](https://documentation.onesignal.com/docs/troubleshooting-ios).

We updated many of the used external packages and also updated Ionic and Angular some time ago. So maybe there are some problems with the versions we are running. 

Using 
`OneSignal.setLogLevel(6, 0);`
does not help that much, as nothing gets logged on the iPhone after sending the push messages to the phone. I hoped for some errors, but it looks like the iPhone does not receive anything.

We also have some older versions of the project which feature older versions of OneSignal, Ionic, Angular, etc. and there the push Notification does pop up on the iPhone, which should verify that we setup the iOS certificate correctly.

**Environment**

Ionic:

   Ionic CLI: 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework: @ionic/angular 6.0.0-rc.0
   @angular-devkit/build-angular: 0.1101.4
   @angular-devkit/schematics: 12.2.10
   @angular/cli: 12.2.10
   @ionic/angular-toolkit: 3.1.1

Capacitor:

   Capacitor CLI: 3.4.0
   @capacitor/android: 3.4.0
   @capacitor/core: 3.4.0
   @capacitor/ios: 3.4.0

Utility:

   cordova-res: 0.15.3
   native-run: 1.5.0

System:

   NodeJS: v14.17.1 (/usr/local/bin/node)
   npm: 2.15.12
   OS: macOS Monterey

Test Devices:

   iPhone 12 running iOS 15.2
   Xiaomi Mi 9T Pro running Android 10 

**Steps to Reproduce Issue:**

1. Follow the [official setup guide](https://documentation.onesignal.com/docs/ionic-sdk-setup) using Ionic 6 and Angular 12.2.10
2. Build and run the App on an iPhone and Android phone
3. Send a message to both devices and receive it on the Android phone, but not on the iPhone.

**Anything else:**

If you need further details regarding the OneSignal logs or my Environment, please reach out to me and I will provide them to you.
Thank you in advance =)

**Comment by PhantomLinker** [comment]
UPDATE: We did not change any push related code and we did not change any OneSignal settings in our project and now the iOS push notifications are suddenly working again.

We experienced a similar issue a couple of months ago, as some team member noticed that iOS push was not working for him, but as soon as I wanted to have a look at the issue I could not reproduce it as it was working on my device and on his device as well.

Was there some Server Side Bug which was resolve in the last 7 days and what shall we do if push on iOS does not work again on a now correctly working platform?

**Comment by mozhn** [comment]
Hello, unfortunately I am experiencing the same situation. The device is successfully registered to OneSignal but does not receive any notifications.

Versions:
onesignal-cordova-plugin: 3.3.0
Capacitor: 4
iOS 15 - 16

**Comment by nan-li** [comment]
Hi @mozhn,
Do any devices receive notifications or all of your test devices are not receiving push notifications?
Did you try some of jkasten2's suggestions above? Particularly, these two steps:

> If that wasn't the case then I recommend looking through the status of your notifications on the OneSignal to make sure they show up as successful. If not check that there isn't any iOS errors or warnings under the iOS platform in your OneSignal dashboard app settings.
