### ISSUE TITLE
Problems initializing app after version upgrade

### ISSUE THREAD

**Issue by uhmarc** [OneSignal/OneSignal-Cordova-SDK#779]
I just upgraded an app from **2.11.3** to **3.0.2**.

Previously, I initialized OneSignal with:

```
var iosSettings = {};
   iosSettings["kOSSettingsKeyAutoPrompt"] = false;
   iosSettings["kOSSettingsKeyInAppLaunchURL"] = false;
			       			       
 window.plugins.OneSignal.startInit("KEY")
   .iOSSettings(iosSettings)
   .handleNotificationOpened(notificationOpenedCallback)
   .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
   .endInit();
 }, false);
```

And everything worked fine. But since upgrading, it shows this error in the console and the app doesn't start:

`Uncaught TypeError: window.plugins.OneSignal.startInit is not a function`

I tried using the code in **"Step 3. Add Required Code"** at https://documentation.onesignal.com/docs/cordova-sdk-setup and it initializes the app, but then every code I have previously used like:

```
window.plugins.OneSignal.getPermissionSubscriptionState(function(status) {
```

suddenly throws an error like:

`window.plugins.OneSignal.getPermissionSubscriptionState is not a function`

I can't figure out what is wrong. And yes, I've searched everywhere in the open and closed issues. I feel like it's just a small stupid error. I would really appreciate it if someone could help me out here :)

**Comment by jkasten2** [comment]
@uhmarc It looks like you may have missed the [Step-by-Step Cordova 2.x to 3.0.0 Upgrade Guide](https://documentation.onesignal.com/docs/step-by-step-cordova-2x-to-300-upgrade-guide) and [Cordova - 3.0 API Reference](https://documentation.onesignal.com/docs/cordova-30-api-reference) that lists all the changes.

In your case with`getPermissionSubscriptionState`, it was [replaced](https://documentation.onesignal.com/docs/cordova-30-api-reference#getdevicestate-function) by `getDeviceState` in the 3.0.0 major release.

**Comment by uhmarc** [comment]
Whoops. Completely missed that. Thank you SO much!
