### ISSUE TITLE
Support for a security issue NotificationOpenedActivityHMS

### ISSUE THREAD

**Issue by nagdevbharat** [OneSignal/OneSignal-Cordova-SDK#783]
**Description:**

I have a support request for the following security issue:
As per the security report, one can access the NotificationOpenedActivityHMS activity by using any security testing tool to add a malware URL to this activity.

Then next time one clicks on any notification user will redirect to a URL that is mentioned in this malicious activity.

**Environment**

I am using Capacitor with Ionic 6
The onesignal SDK version is 2.11.4

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@nagdevbharat Thanks for the report, could you follow up with OneSignal support and provide the extra details on how to reproduce this security issue and the tools you used?
