### ISSUE TITLE
OneSignalPush.java:271: error: 'else' without 'if'

### ISSUE THREAD

**Issue by martinothamar** [OneSignal/OneSignal-Cordova-SDK#79]
The latest build released ~3 hours ago, 2.0.1, has [this little bug](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/a93ba0f5fb1fccf7fbfbdd75c182ab5866452e9f/src/android/com/plugin/gcm/OneSignalPush.java#L270). Not entirely sure what's supposed to happen inside there.

**Comment by JKalash** [comment]
Thanks for pointing that out! Fixed in [2.0.2](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.0.2)
