### ISSUE TITLE
Missing type InAppMessage on latest version 3.0.3

### ISSUE THREAD

**Issue by gunsha** [OneSignal/OneSignal-Cordova-SDK#791]
Hi there, just tried the latest version and fails to compile due to missing type for `InAppMessage`

`[ng] Error: node_modules/onesignal-cordova-plugin/types/InAppMessage.d.ts:16:50 - error TS2304: Cannot find name 'InAppMessage'.
[ng] 
[ng] 16     onDidDismissInAppMessage        ?: (message: InAppMessage) => void;`

**Comment by ludufre** [comment]
#787

**Comment by nunoarruda** [comment]
Yeah, this was fixed on #787 but the OneSignal team has not released a new version yet.

@nan-li @emawby when you have a chance, can you please release a new version?

**Comment by nan-li** [comment]
I am sorry for this bug, and the fix was just released in [version `3.0.4`](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/3.0.4).
