### ISSUE TITLE
Cannot build for iOS device in XCode

### ISSUE THREAD

**Issue by andutoptal** [OneSignal/OneSignal-Cordova-SDK#797]
**Description:**

I have installed the onesignal-cordova-plugin (v3.0.4) in a CapacitorJS project (v3.5.1) following the steps in the Ionic & Capacitor SDK Setup (https://documentation.onesignal.com/docs/ionic-sdk-setup) but when trying to build the application to run on an actual device in Xcode (v13.2.1) I get the following error: 
"Building for iOS, but linking in dylib file XXXXX built for iOS Simulator, file YYYYY for architecture arm64"

**Environment**

**Steps to Reproduce Issue:**

Configure CapacitorJS project to use onesignal-cordova-plugin according to official documentation and try to build in Xcode

**Comment by nan-li** [comment]
Hi @andutoptal,

Thank you for reporting and I apologize for the delayed response. Is this still an issue for you? If so, there are some things you can begin by trying:
- Deleting the DerivedData folder
- de-integrate the pod and re-install with `pod deintegrate && pod install`

**Comment by fitnexus** [comment]
hi @nan-li, i've tried this but i'm still getting the same error. @andutoptal have you managed to fix this?

**Comment by jennantilla** [comment]
Hello @andutoptal  and @fitnexus -- are you still experiencing this issue on the [latest version](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/3.3.1) of our Cordova SDK? Thanks for the update!

**Comment by jennantilla** [comment]
Closing due to no response.
