### ISSUE TITLE
Cannot get the FCM Token to receive notifications

### ISSUE THREAD

**Issue by sampaxk** [OneSignal/OneSignal-Cordova-SDK#816]
**Description**
Cannot get the FCM Token to receive notifications.
The app doesn't use any Firebase plugin.
The app doesn't use the OneSignal Gradle Plugin.

**Device**
Xiaomi Mi Note 10 Lite - M2002F4LG
Android 12SKQ1.210908.001
Miui 13.0.2 Stable

**Environment**
- @capacitor/android - 3.8.0
- @capacitor/core - 3.8.0

[info] Found 10 Capacitor plugins for android:
- @capacitor/app@1.1.1
- @capacitor/camera@1.3.1
- @capacitor/device@1.1.2
- @capacitor/filesystem@1.1.0
- @capacitor/geolocation@1.3.1
- @capacitor/keyboard@1.2.3
- @capacitor/network@1.0.7
- @capacitor/share@1.1.2
- @capacitor/splash-screen@1.2.2
- @capacitor-community/keep-awake@2.1.0

[info] Found 13 Cordova plugins for android:
- onesignal-cordova-plugin@3.1.1
- cordova-plugin-badge@0.8.8
- cordova-plugin-local-notification@0.9.0-beta.3
- cordova-plugin-mlenabled@1.0.0
- cordova-plugin-request-location-accuracy@2.3.0
- cordova-plugin-secure-storage-echo@5.1.1
- cordova-plugin-screen-orientation@3.0.2
- cordova-sqlcipher-adapter@0.5.4
- cordova.plugins.diagnostic@6.1.1
- cordova-plugin-device@2.1.0
- cordova-plugin-dialogs@2.0.2
- phonegap-plugin-barcodescanner@8.1.0
- phonegap-nfc@1.2.0

**Steps to Reproduce Issue**
The issue is not reproducible.
The issue appears to be only on the device "Xiaomi Mi Note 10 Lite - M2002F4LG". On other devices such as Samsung and Oppo smartphones this issue doesn't happen.
I install the app on the device and doesn't receive notifications, then I clear the app data from settings or uninstall then reinstall the app and then the device receives notifications. If I repeat these steps, maybe, the app won't receive notifications anymore. That's totally random.
When the device doesn't receive notifications the `getDeviceState` method returns `subscribed: true` but the OneSignal dashboard returns that the same device isn't subscribed. In this situation I've tried to disable push notifications and then re-enable them, but this didn't solve the issue.

**Anything else**
This is the log of the app unable to get the FCM Token at the startup: [OneSignal.log](https://github.com/OneSignal/OneSignal-Cordova-SDK/files/9600371/OneSignal.log).
I've looked on this repository and on "OneSignal/OneSignal-Android-SDK" repository for a similar issue and I've found this [Android-681](https://github.com/OneSignal/OneSignal-Android-SDK/issues/681), but nothing on this repository.

**Comment by jennantilla** [comment]
Hi @sampaxk 

Thanks for your patience!

Looking over your log, I see the following:

```
W/OneSignal: Failed last request. statusCode: 400
    response: {"errors":["Player not found. Request body did not contain a device_type field, so a new player could not be automatically created. (not a valid device_type)"]}
```

This would happen if you deleted a user without uninstalling the app, because the app still has the old player_id saved locally.

When you uninstall/reinstall the app, then a new Player ID will be created which should subscribe the new user.

If you are still experiencing issues, please:

1. uninstall the app
2. reinstall the app
3. generate new log attempting to subscribe device/send a push notification
4. share updated log here

Thank you!

**Comment by jennantilla** [comment]
Closing due to no response. Please feel free to comment if still having issues!
