### ISSUE TITLE
notificationReceivedCallback when app is closed

### ISSUE THREAD

**Issue by jantonso** [OneSignal/OneSignal-Cordova-SDK#82]
Hi,

Sorry if this has been asked elsewhere, but I can't seem to have found exactly what I'm looking for.

I'm using the 1.13.2 release of this plugin.

window.plugins.OneSignal.init('xxxxxxxxx',
				{googleProjectNumber: 'xxxxxxxxx'}, notificationOpenedCallback);

My notificationOpenedCallback works perfectly fine if the app is open or in the background. However, if the app is closed, then when i click on the notification, the callback does not run. I need to redirect users to a certain page based on additionalData keys, so I need to be able to access that data via the callback.

Thanks,
Josh

**Comment by jkasten2** [comment]
@jantonso Can you make sure OneSignal init is being called on the first page when your app loads? Also add if this is an issue on iOS or Android or both.

**Comment by jantonso** [comment]
@jkasten2

Hey,

This is an Android issue I think. I'm calling init and getting the ids and it's working perfectly fine when the app is open or in the background, the issue is only related to when the app is closed. When I click on the notification, it only is opening up the app, it doesn't seem to be doing what is in the notificationOpenedCallback. Ideally, I want to redirect the user to a certain page when they click on the notification, but it's always just going to the home page.

**Comment by jantonso** [comment]
@jkasten2 I think I got it working! I was under the impression that I only need to call init once and then anytime my user closes/opens the app it would work, but we actually have to call init everytime the user opens the app, correct?

**Comment by jkasten2** [comment]
Correct, you need to call init each time your app is opened. You also need to call it on every page load if you need handle the notification open event.

**Comment by Sundaybrian** [comment]
@jantonso `window.plugins.OneSignal
       .startInit("xxxxxxxxxxx")
       .handleNotificationReceived(function(jsonData) {
         // alert("Notification received: \n" + JSON.stringify(jsonData));
         // console.log('Did I receive a notification: ' + JSON.stringify(jsonData));
       })
       .handleNotificationOpened(function(jsonData) {
         alert("Notification opened: \n" + JSON.stringify(jsonData));
         console.log('didOpenRemoteNotificationCallBack: ' + JSON.stringify(jsonData));

         let additionalData=jsonData.notification.payload.additionalData;
         alert(additionalData);

         if (additionalData.welcome=="true") {

           window.location.href = ''+additionalData.goto;
         }


         //
       })
       .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
       .iOSSettings(iosSettings)
       .endInit();`
here is my snippet..can't redirect to the page i want.Please help

**Comment by noveweb** [comment]
I'm using the version 2.4.5 on IOS cordova app and when notification comes and the app is completly closed, i tap on the notification, the app opens, but NotificationOpened Callback don't fires.
