### ISSUE TITLE
[question]: How to get Device  Token  for iOS

### ISSUE THREAD

**Issue by gelinger777** [OneSignal/OneSignal-Cordova-SDK#821]
### How can we help?

So to count Device Uninstalls in AppsFlyer SDK we need to pass iOS  Device Token. 

Any idea how we can get it  in iOS inside the app ? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @gelinger777, thank you for your patience!

The latest major release of our SDK has the method [`getDeviceState`](https://documentation.onesignal.com/docs/sdk-reference#push-notification-properties) which will return push token. Is that what you are looking for?

Thanks!

**Comment by gelinger777** [comment]
yes, thank you
