### ISSUE TITLE
Onesignal/Onesignal.h file not found

### ISSUE THREAD

**Issue by martrix78** [OneSignal/OneSignal-Cordova-SDK#823]
**Description:**
Error when building app. I removed the platform/pod and re-added

**Environment**
**onesignal-cordova-plugin**: 3.2.0
**Xcode**: Version 13.2.1 (13C100),
**OS**:  macOS 11.6
**Cordova Platforms** : ios 5.1.1
 **Ionic Framework**               : @ionic/angular 5.6.5

**Steps to Reproduce Issue:**

1.run build on Xcode

**Comment by jpike88** [comment]
This started to be a problem with version 3.3.0 @jennantilla

**Comment by anatoly-spb** [comment]
> try to use only english letter (and without space) in widget.name inside config.xml

It must work with any characters, not latin1 only.

**Comment by anatoly-spb** [comment]
> > > try to use only english letter (and without space) in widget.name inside config.xml
> > 
> > 
> > It must work with any characters, not latin1 only. Here is the same bug [apache/cordova-ios#1289](https://github.com/apache/cordova-ios/issues/1289)
> 
> You can create a new blank project with chinese project name to test.

I have already simple test project https://github.com/anatoly-spb/cordova-hello . To see error it is enough to change name in config.xml to "Тестовой проект".

**Comment by jennantilla** [comment]
Hi @martrix78 just checking in on this. Were the previous responses helpful in resolving your issue?

**Comment by jennantilla** [comment]
Closing due to no response.
