### ISSUE TITLE
[question]: iOS Subscriptions

### ISSUE THREAD

**Issue by jeremywj** [OneSignal/OneSignal-Cordova-SDK#829]
### How can we help?

Is anyone else having sporadic issues with iOS users reporting as not subscribed even though they have push notifications enabled for the app?  One device it happened on had to be reset and then it worked for a day or two and then went unsubscribed again.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremywj** [comment]
Update: Turned out it was an app called 1Block that several iOS users were using.  It was blocking api.onesignal.com

**Comment by jennantilla** [comment]
Thank you for the update! If this is no longer an issue for you we will go ahead and close this issue but please let us know if you have any additional questions or concerns.
