### ISSUE TITLE
[Bug]: cannot access zzbfm / class file for com.google.android.gms.internal.zzbfm not found - Ionic 6

### ISSUE THREAD

**Issue by seltix5** [OneSignal/OneSignal-Cordova-SDK#831]
### What happened?

Incompatible with the background geolocation plugin `npm install cordova-background-geolocation-plugin`.
Both plugins work when running separatly but when installed at the same time it does not compile.

### Steps to reproduce?

```Markdown
( this is using Ionic 6 )

ionic start TEST --type angular --package-id=com.test.app blank
cd TEST

ionic cap add android


npm install cordova-background-geolocation-plugin

// apply this fix required for ionic 6 : https://github.com/HaylLtd/cordova-background-geolocation-plugin/issues/122#issuecomment-1271553737
// in android/app/src/main/res/values/strings.xml, add the following:
//   <string name="plugin_bgloc_account_name">@string/app_name</string>
//   <string name="plugin_bgloc_content_authority">$PACKAGE_NAME</string>
//   <string name="plugin_bgloc_account_type">$PACKAGE_NAME.account</string>


// compile test before installing second plugin
ionic cap sync && cd android && gradlew assembleDebug && cd ..


npm install onesignal-cordova-plugin


// compile test
ionic cap sync && cd android && gradlew assembleDebug && cd ..
// or open on android studio with:
ionic cap sync && ionic capacitor run android -l --external
```

### What did you expect to happen?

to compile =)

### OneSignal Cordova SDK version

onesignal-cordova-plugin@3.3.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Relevant log output

```Shell
\android\capacitor-cordova-android-plugins\src\main\java\com\marianhello\bgloc\data\BackgroundActivity.java:20: error: cannot access zzbfm
        confidence = activity.getConfidence();
                             ^
  class file for com.google.android.gms.internal.zzbfm not found
```

![image](https://user-images.githubusercontent.com/11258096/207222612-2a87cf64-dd58-4cee-b8c8-cb4be0ec68b5.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@seltix5 Thanks for reporting, can you confirm you are using the latest version of each SDK (`cordova-background-geolocation-plugin` and `onesignal-cordova-plugin`)?

The build error is coming from `com.marianhello.bgloc.data`. It looks like others are running into this same problem even without OneSignal.
https://github.com/mauron85/background-geolocation-android/issues/40

**Comment by seltix5** [comment]
hello
this is a fresh new project for testing so yes, it should be the latest one:
```
    "cordova-background-geolocation-plugin": "^2.0.7",
    "onesignal-cordova-plugin": "^3.3.0",
```

```
> npm list
...
+-- cordova-background-geolocation-plugin@2.0.7
+-- onesignal-cordova-plugin@3.3.0
....
```

The background geolocation plugin is this one https://github.com/HaylLtd/cordova-background-geolocation-plugin but it is based on https://github.com/mauron85/cordova-plugin-background-geolocation thus the problem may be the same.

I already try to to install `cordova-android-play-services-gradle-release` as sugested but it did not help.
I even created the same issue on the other plugin at https://github.com/HaylLtd/cordova-background-geolocation-plugin/issues/128 but the sugested solution did not work either.
Sadly I have no knowlage to try to find the problem myself and I dont know what else I can do.
As described on that issue discution I already created an new project to confirm that separatly both plugins work, only when both are installed at the same time I have the compilation error...
Any help is apreciated.
Thank you.

**Comment by seltix5** [comment]
I just updated the original post with the exact steps to create the project from zero.

**Comment by seltix5** [comment]
hello! any updates on this?

**Comment by seltix5** [comment]
I finally fixed the problem changing the default GOOGLE_PLAY_SERVICES_VERSION from 11+ to 15+ here :https://github.com/HaylLtd/cordova-background-geolocation-plugin/blob/033ee47d8473f568068a2161bed0350fa571f3c5/plugin.xml#L27.
Thank you

**Comment by seltix5** [comment]
I finally fixed the problem changing the default GOOGLE_PLAY_SERVICES_VERSION from 11+ to 15+ here : 
https://github.com/HaylLtd/cordova-background-geolocation-plugin/blob/033ee47d8473f568068a2161bed0350fa571f3c5/plugin.xml#L27
Thank you
