### ISSUE TITLE
[question]: Enable Critical Alerts

### ISSUE THREAD

**Issue by jeremywj** [OneSignal/OneSignal-Cordova-SDK#834]
### How can we help?

I don't believe this plugin will ask for or enable critical iOS push notifications.  If not, could this be added?  If it does support critical notifications, how do I enable them?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @jeremywj thank you for your patience!

You can set up Critical Alerts by following [this guide](https://documentation.onesignal.com/docs/ios-focus-modes-and-interruption-levels#critical-alerts).

Let us know if you have any additional questions or concerns!

**Comment by jennantilla** [comment]
Closing due to no response.
