### ISSUE TITLE
Show onesignal push notification in popup

### ISSUE THREAD

**Issue by jsBiztech** [OneSignal/OneSignal-Cordova-SDK#842]
Currently we are using one signal version 3.3.0 

With this our current requirement is to show notification in popup in android and ios.

How can we achieve that?

 OneSignal.setAppId(key);
 
 Actual Result: 
 
 Showing notification in popup in ios and android like below
 
<img width="404" alt="image" src="https://user-images.githubusercontent.com/43880269/210388920-74bff2cd-d676-4401-b793-232677a01acd.png">

Current Behaviour 

It was only provide alert . Not such banner.

There is are solution for this like provide in below link but those are for version 2.x.
https://github.com/OneSignal/react-native-onesignal/issues/918

**Comment by jennantilla** [comment]
Hello @jsBiztech thank you for your patience!

This is likely a device setting issue. On what type(s) of device(s) are you testing?

On both [Android](https://support.google.com/android/answer/9079661?hl=en) and [iOS](https://support.apple.com/en-us/HT201925), you can go to your app's Notification Settings and change the "pop-up", "pop on screen", or "banner" style.

Let us know if that helps!

**Comment by jennantilla** [comment]
Closing due to no response.
