### ISSUE TITLE
Adding a Changelog.md would be great

### ISSUE THREAD

**Issue by Inoverse** [OneSignal/OneSignal-Cordova-SDK#85]
Hi there,

it would be great if you will add an Changelog.md file with the change for every release.
I created the Ionic Native support for this plugin and it would be create if I can see all changes in a file.

Thanks!
Regards
Aaron

**Comment by jkasten2** [comment]
@Inoverse We have been noting our changes as github releases.
https://github.com/OneSignal/OneSignal-Cordova-SDK/releases

Could you base your notes off this list?

Thanks.
