### ISSUE TITLE
[question]: Ionic 5 - Cordova 11. Plugin not Installed

### ISSUE THREAD

**Issue by NicolasPapp94** [OneSignal/OneSignal-Cordova-SDK#850]
### How can we help?

Hello, good afternoon to everyone.

I'm trying to get the One Signal plugin to work with Ionic and Cordova. I am currently trying to use version 3.x but it doesn't work, giving the following error:

Native: tried calling OneSignal.getIds, but the OneSignal plugin is not installed.
Install the OneSignal plugin: 'ionic cordova plugin add onesignal-cordova-plugin'

I downgraded to version 2.11.4 and the notifications don't even reach me (Before I used Ionic 3 and everything worked correctly)

Can you recommend me something? Did you have a similar problem? How can I debug it? What versions for this environment can you recommend?

Thank you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NicolasPapp94** [comment]
Well, I bring an update but not the solution.

I started using oneSignal = window["plugins"].OneSignal

With this, I am using setAppId instead of startInit. The problem is that methods like inFocusDisplaying or handleNotificationReceived end up being undefined.

**Comment by marcusdiy** [comment]
Some method were changed or renamed. Read the docs about cordova platform on their site. For example:
`handleNotificationReceived` became `setNotificationOpenedHandler`
`handleNotificationOpened` became `setNotificationOpenedHandler`

**Comment by jennantilla** [comment]
Hi @NicolasPapp94, thanks for your patience. Are you still having issues here?

As @marcusdiy mentions, our method names have changed in the latest major release. You can see all updates [here](https://documentation.onesignal.com/docs/cordova-30-api-reference).

Let us know if you have any additional questions or concerns!

**Comment by jennantilla** [comment]
Closing due to no response.
