### ISSUE TITLE
[Bug]: in 3.3.0 we need to call `setAppId` twice in order to receive notifications

### ISSUE THREAD

**Issue by gabides** [OneSignal/OneSignal-Cordova-SDK#862]
### What happened?

Need to call `setAppId` twice in the code, or open the app a second time in order to receive push notifications on ios and android

### Steps to reproduce?

```Markdown
1. install onesignal-cordova-plugin v3.3.0 and setup the onesignal sdk
2. launch the app - notifications are not received
3. kill the app
4. reopen the app - notifications are received properly
```

### What did you expect to happen?

Receive push notifications after calling `setAppId` once

### OneSignal Cordova SDK version

3.3.0

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Relevant log output

```Shell
on android studio when debbuging we see this log on the first call of `setAppId`:

W/OneSignal: appId set, but please call initWithContext(appContext) with Application context to complete OneSignal init!
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mguarino88** [comment]
I have the same problem but only work if I kill the app and reopen it.
I tried to call setAppId twice but didn't work. 

`
[...]
public initializeApp()
	{
		this.platform.ready().then(() => {

			this.statusBar.styleDefault();
			this.splashScreen.hide();
[...]

			if ( this.isCordova ) {
[...]

                             window.plugins.OneSignal.setAppId( ENV.oneSignalAppId );
			
                             // nothing change if I call setAppId twice
                             window.plugins.OneSignal.setAppId( ENV.oneSignalAppId );

                             // nothing change if I call setAppId twice after timeout
			     setTimeout( () => {
					window.plugins.OneSignal.setAppId( ENV.oneSignalAppId );
			      }, 3000);

			     window.plugins.OneSignal.setNotificationOpenedHandler(notificationOpenedCallback);

                             // nothing change if I call setAppId twice after timeout
			     setTimeout( () => {
					window.plugins.OneSignal.setAppId( ENV.oneSignalAppId );
			      }, 3000);
[...]
`


@gabides , how do you call setAppId twice? 
Thanks

**Comment by gabides** [comment]
@mguarino88 I tried like you to do the 2 calls sequentially in javascript but didn't work as well. It is currently triggered by two user actions in our app, so i guess if there is enough time between both calls it will work.

**Comment by mguarino88** [comment]
I found a solution for my project.. and it was my fault, no need to call the function twice.

 in the previous version with onesignal 2.x.x, I used the function getIds to save the userId and everything works

`this.oneSignal.getIds().then(function(obj) {`
`    localStorage.setItem('push_token', obj.userId ); `
` }); `

so, in the new version i changed to:

`window.plugins.OneSignal.getDeviceState((obj) => { `
`    localStorage.setItem('push_token', obj.userId );`
` });`


it was wrong

I have to wait the Push Subscription to obtain the correct userId with this observer

`window.plugins.OneSignal.addSubscriptionObserver(function (state) {`
`   if (!state.from.isSubscribed && state.to.isSubscribed) {`
`        console.log("Subscribed for OneSignal push notifications!")`
`	// save user ID`
`	localStorage.setItem('push_token', state.to.userId );`
`    }`
`    console.log("Push Subscription state changed: " + JSON.stringify(state));`
`});`

**Comment by jennantilla** [comment]
Thanks for the update @mguarino88--glad you were able to find a solution!

@gabides are you still having issues?
