### ISSUE TITLE
[question]: service extensions on Android

### ISSUE THREAD

**Issue by bmcfarlin** [OneSignal/OneSignal-Cordova-SDK#865]
### How can we help?

I'm developing with Cordova.  I was previously using the 2.0 version of the SDK and service extensions work fine.  However when upgrading to the 3.0 version, I can't get the service extension to send the data notification to the Javascript.  There used to be a handler for that, but now it seems to have disappeared?  Here's my code.

`
@SuppressWarnings("unused")
public class OneSignalNotificationExtender implements OSRemoteNotificationReceivedHandler {

  private static final String TAG = "OneSignalNotificationExtender";

  public OneSignalNotificationExtender(){
    super();
    Log.d(TAG, "OneSignalNotificationExtender - Constructor");
  }

  @Override
  public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent notificationReceivedEvent) {

    Log.d(TAG, "remoteNotificationReceived - BEGIN");

    OSNotification notification = notificationReceivedEvent.getNotification();

    String title = notification.getTitle();
    String body = notification.getBody();
    String sound = notification.getSound();

    Log.d(TAG, String.format("title:%s", title));
    Log.d(TAG, String.format("body:%s", body));
    Log.d(TAG, String.format("sound:%s", sound));

    Log.d(TAG, "remoteNotificationReceived - END");

   // this code sends the notification to the Javascript if the app is in focus
   // if it is not in focus, the code shows the notification icon (along with vibration); this is not the desired behavior
   // I would like the data notification to always be consumed quietly (no notification)
   // if the app is in focus, pass the data to the Javascript so it can update the UI
   
    notificationReceivedEvent.complete(notification);
  }
}

`
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @bmcfarlin, in 3.x.x there are 2 [notification received handlers](https://documentation.onesignal.com/docs/sdk-notification-event-handlers), depending on the state of the application:

1. Calling `window.plugins.OneSignal.setNotificationWillShowInForegroundHandler` within your javascript, which will get control whenever a notification is received while your app is in the foreground.  You have the ability to suppress the notification from being displayed by calling `complete` with `null`:

```
window.plugins.OneSignal.setNotificationWillShowInForegroundHandler(function(notificationReceivedEvent) {
  notificationReceivedEvent.complete(null);
});
```

2.  [A notification service extension ](https://documentation.onesignal.com/docs/service-extensions), which is called regardless of the app state.  From an Android perspective, this needs to be written in Java or Kotlin and is a native concept.  I do not believe there is a direct way to "get to javascript" from this native extension.  But you should be able to have business logic which will show/not show the notification.

I hope this helps, please let me know if you have any follow up questions!

**Comment by brismithers** [comment]
HI @bmcfarlin just checking in, if there are any other questions please let me know.  Otherwise will close, thanks!

**Comment by recoiladam** [comment]
> Hi @bmcfarlin, in 3.x.x there are 2 [notification received handlers](https://documentation.onesignal.com/docs/sdk-notification-event-handlers), depending on the state of the application:
> 
>     1. Calling `window.plugins.OneSignal.setNotificationWillShowInForegroundHandler` within your javascript, which will get control whenever a notification is received while your app is in the foreground.  You have the ability to suppress the notification from being displayed by calling `complete` with `null`:
> 
> 
> ```
> window.plugins.OneSignal.setNotificationWillShowInForegroundHandler(function(notificationReceivedEvent) {
>   notificationReceivedEvent.complete(null);
> });
> ```
> 
>     2. [A notification service extension ](https://documentation.onesignal.com/docs/service-extensions), which is called regardless of the app state.  From an Android perspective, this needs to be written in Java or Kotlin and is a native concept.  I do not believe there is a direct way to "get to javascript" from this native extension.  But you should be able to have business logic which will show/not show the notification.
> 
> 
> I hope this helps, please let me know if you have any follow up questions!

This does NOT help any of us! Especially those of us that are not JAVA developers. What used to work is now no longer working with your service and has all our apps broken beyond repair from the looks of it. This is just bad business practice all around.

**Comment by emawby** [comment]
@recoiladam Can you clarify which workflow is not supported and how we could help? Thank you!

**Comment by recoiladam** [comment]
> @recoiladam Can you clarify which workflow is not supported and how we could help? Thank you!

We have already moved to using Firebase directly for both Android and iOS and it is working much better than OneSignal.
