### ISSUE TITLE
[Looking for Feedback] OneSignal SDK 5.0.0-beta-01 Released!

### ISSUE THREAD

**Issue by jennantilla** [OneSignal/OneSignal-Cordova-SDK#868]
In this major version beta release for the OneSignal SDK, we are making a significant shift from a device-centered model to a user-centered model. A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.

For more information please see the [migration guide](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/user_model/main/MIGRATION_GUIDE.md).

🚧 Beta release. It is not recommended to use in production. 🚧

Please post any feedback related to the beta here!

**Comment by nunoarruda** [comment]
How about a dedicated OneSignal plugin for [Capacitor](https://capacitorjs.com/)?

Yes, this OneSignal Cordova plugin mostly works on Capacitor-based projects but there has been some [friction](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues?q=is%3Aissue+is%3Aopen+capacitor).

Plus, it looks like that [Capacitor installs/usage already surpasses Cordova](https://twitter.com/maxlynch/status/1626222957013131267). So it might be a good time for the OneSignal to have a dedicated Capacitor plugin.

You folks can find more info on creating Capacitor plugins here 👉 https://capacitorjs.com/docs/plugins/tutorial/introduction

Cheers 👍

**Comment by jennantilla** [comment]
Hi @nunoarruda, a dedicated Capacitor plugin is on our radar and something we're hoping to explore further within the next few quarters. Please feel free to leave any additional feedback and we'll be sure to consider it!

**Comment by selcuk-sahin** [comment]
Thanks for this version!

The logout functionality in this version should be really useful for us.

I'm using Ionic Capacitor, but I can't seem to work with the request `OneSignal.Notifications.canRequestPermission`
according to the migration guide usage is this, but the types suggest using a handler here. Also, neither of the solutions did return a result.

let canRequest = window.plugins.OneSignal.Notifications.canRequestPermission(); | Whether attempting to request notification permission will show a prompt. Returns true if the device has not been prompted for push notification permission already.
-- | --


What I tried:
```typescript
    let canRequest = OneSignal.Notifications.canRequestPermission();
    console.log(canRequest); // undefined
    OneSignal.Notifications.canRequestPermission((canRequestPerm) => {
      console.log(canRequestPerm) // never logged
    })
```
