### ISSUE TITLE
android_background_layout with large_icon

### ISSUE THREAD

**Issue by AdrienDC** [OneSignal/OneSignal-Cordova-SDK#87]
Hi team,
thanks for the amazing work so far !

I noticed a bug in the plugin for android. When I put an android_background_layout (let's say {"image": "https://domain.com/background_image.jpg", "headings_color": "FFFF0000", "contents_color": "FF00FF00"}) , I'm no longer able to see the large_icon I configured. 

Without android_background_layout, no problem.

**Comment by jkasten2** [comment]
@AdrienDC This is a limitation of the `android_background_layout` is part of our [OneSignal-Android-SDK](https://github.com/OneSignal/OneSignal-Android-SDK). You will need to bake your icon into the background image for the time being.

**Comment by AdrienDC** [comment]
Thanks @jkasten2 
However I'm using dynamic background so in the meantime I can't do this ..
Shall I repost to the android-sdk section?

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
