### ISSUE TITLE
[question]: Need clarifications regarding "Subscription reports version update" for In-App Purchase

### ISSUE THREAD

**Issue by daminiverv** [OneSignal/OneSignal-Cordova-SDK#870]
### How can we help?

Today my client shared the below message and asked me if should I update something on the code side regarding In-App purchases. He got this email from Apple.

**"We’re reaching out to let you know that, starting March 1, 2023, subscription reports version 1.2 will no longer be available. If you automatically download subscription reports using the App Store Connect API or Reporter, please update your query parameter to version 1.3 if you haven’t already done so.Version 1.3 builds on version 1.2, and includes additional data to help you understand subscription offer code redemptions. With version 1.3, you’ll have access to the number of active subscribers using your offer codes and the number of offer code redemptions for your service. You can also find out if subscribers convert to paid renewal when the offer period ends.To learn how to specify a version when downloading reports, visit Download Sales and Trends Reports for the App Store Connect API or the Reporter User Guide for Reporter."**

I didn't use any App Store Connect API to download subscription reports. 
So, Should I be concerned about this and need to change anything on the code side? please help 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @daminiverv this would apply if you use App Store Connect API to download subscription reports. You should not need to update anything from the OneSignal side. Let us know if you have any additional questions or concerns!
