### ISSUE TITLE
[question]: Users subscriptions

### ISSUE THREAD

**Issue by marshall86** [OneSignal/OneSignal-Cordova-SDK#873]
### How can we help?

Is it possible to prevent multiple entries , in the "Subscriptions" page, for the same user and the same device?
Plus if i had an external id and an email to that user i have 2 different entries one with only the external user id and one with both external user id and email.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Closing due to no response.

**Comment by marshall86** [comment]
HI, I have another question please. I managed to integrate your Ionic plugin with Capacitor and Angular. I correctly receive the notifications and when my app is in foreground or background (not closed) I have some logic in place to store those notifications thanks to the events "setNotificationWillShowInForegroundHandler" and "setNotificationOpenedHandler".

Unfortunately, when the app is closed, I have no trigger and if a user dismiss these notifications I have no way to get these data.

On iOS I have implemented the service extension as per your guide but yet nothing change.

Can you help me with this issue please?
