### ISSUE TITLE
[question]: OneSignal: remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification

### ISSUE THREAD

**Issue by anatoly-spb** [OneSignal/OneSignal-Cordova-SDK#875]
### How can we help?

Hello! I use the latest onesignal-cordova-plugin@3.3.1 in my Ionic@6/Cordova@11 application. 

I try to send the following message to mobile application on Android:
```
{
  "app_id": "XXXX",
  "include_player_ids": ["YYYY"],
  "data": {
     "action": "refresh"
  },
  "content_available": true
}
```

But I only see in a log on my device:  
```
W/OneSignal: remoteNotificationReceivedHandler not setup, displaying normal OneSignal notification
```

And none of my handlers setNotificationWillShowInForegroundHandler, setNotificationOpenedHandler is not fired.

How to catch a message with only payload data without notification?

Thanks in advance!

BR,
Anatoly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marshall86** [comment]
I'm using Ionic with Capacitor and Angular and in my case I get the notifications when the app is both in foreground and background (not closed) and yet I can see the same warning in Android studio.

My problem is that on both iOS and Android, when the app is completely closed, I can't get any info related to the notifications a device receive. Any idea on how to fix it?

**Comment by anatoly-spb** [comment]
> I'm using Ionic with Capacitor and Angular and in my case I get the notifications when the app is both in foreground and background (not closed) and yet I can see the same warning in Android studio.
> 
> My problem is that on both iOS and Android, when the app is completely closed, I can't get any info related to the notifications a device receive. Any idea on how to fix it?

Background message is a message without visible content like the following:
```
{
  "app_id": "XXXX",
  "include_player_ids": ["YYYY"],
  "data": {
     "action": "refresh"
  },
  "content_available": true
}
```
OneSignal-Cordova 3 does not support such message.

**Comment by marshall86** [comment]
i found a solution for Android. For iOS the problem is that after a few second that the app is in background (completely closed or just in background but opened) the app goes in a state where you don't get any info in capacitor. 
I tried to play with the extension service but i didn't manage to get any data to capacitor. I even tried to open the app when it's in background but iOS doesn't allow it ..

**Comment by emawby** [comment]
Hello I apologize for the late reply. Notification opened is not fired for content available notifications
