### ISSUE TITLE
different between onesignal version 2.11 vs 3.3.0

### ISSUE THREAD

**Issue by vietmaki** [OneSignal/OneSignal-Cordova-SDK#878]
### How can we help?

Before i use onesignal version 2.11, when I push message notification, if app is focus, 1 alert popup show in center app, but when i update onesignal version 3.3.0, not show alert popup, just show in notification bar. How can i show message notification popup alert when app focus

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello the documentation reference for this is [here](https://documentation.onesignal.com/docs/sdk-notification-event-handlers#foreground-notification-received-event)

**Comment by vietmaki** [comment]
i mean alert message with view now button

**Comment by emawby** [comment]
Were you doing something like this in your notificationReceivedHandler?
`alert("Notification Received:\n" + JSON.stringify(notificationData));`

You can do something similar using the `setNotificationWillShowInForegroundHandler `

**Comment by vietmaki** [comment]
android ok, but ios not working

**Comment by xJosee** [comment]
any solution?
I have the same issue

**Comment by emawby** [comment]
Can you describe the issue? Is the alert not displaying or the json not parseable?

**Comment by xJosee** [comment]
> Can you describe the issue? Is the alert not displaying or the json not parseable?

In Android if I get the push notification but I do not get the preview or sounds, only the icon remains in the notification bar, I want to show the preview of the push notification.

**Comment by vietmaki** [comment]
what kind of message popup use in version 2.11.

**Comment by emawby** [comment]
Hello I apologize for the late follow up is this still an issue in the latest versions?
