### ISSUE TITLE
[android] notificationOpenedCallback api does not match current documentation

### ISSUE THREAD

**Issue by veloce** [OneSignal/OneSignal-Cordova-SDK#88]
In version 2.0.4, the arg received in `notificationOpenedCallback` does not match documented params as seen here: https://documentation.onesignal.com/docs/cordova-sdk#section--notificationopenedcallback-

Instead of the 3 args `message, additionalData, isActive` there is a unique arg received of type `OSNotificationOpenedResult`.

**Comment by JKalash** [comment]
Hi there,

Thank you for pointing that out. We're working on updating this section of the docs to reflect the new 2.+ SDK.
