### ISSUE TITLE
[question]: Ionic setNotificationOpenedHandler not working as expected

### ISSUE THREAD

**Issue by milikamel** [OneSignal/OneSignal-Cordova-SDK#883]
**Goal**: we want to create deep-linking within the App when a user clicks on notification in background he should be redirected to a specific route.
 
**Problem**: as you can see below we are trying to get a message when both function are called, it seems that they are not trigged we even tried couple of other function it doesn't seem to work for unknown reasons.

**What's working so far**
- notification are working as expected in background so we receive the notification, the problem is when y user clicks on it outside the app

```
OneSignalInit(): void {
		// Uncomment to set OneSignal device logging to VERBOSE  
		// OneSignal.setLogLevel(6, 0);
		// NOTE: Update the setAppId value below with your OneSignal AppId.
		this.platform.ready().then(() => {
			this.network.onDisconnect().subscribe(async () => {
				alert('network was disconnected :-(');
				 const toast = await this.toastController.create({
				  message: 'You are appear to be offline. Please try again!.',
				});
				toast.present();
			});
			OneSignal.setAppId("3aa94940-51af-4a89-8d2d-02dc12ae5b8e");
			OneSignal.setNotificationOpenedHandler(function(jsonData) {
				console.log('notificationOpenedCallback: ' + JSON.stringify(jsonData));
						 const toast = await this.toastController.create({
				  message: 'test 2',
				});
				toast.present();
			});
			OneSignal.promptForPushNotificationsWithUserResponse(function(accepted) {
				console.log("User accepted notifications: " + accepted);
						 const toast = await this.toastController.create({
				  message: 'test 1',
				});
				toast.present();
			});
		})
	  }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@milikamel So it sounds like you want deep links from your push notifications and your `setNotificationOpenedHandler` is not being fired? I recommend looking at [this document](https://documentation.onesignal.com/docs/links#no-linking). Is this an issue on both iOS and Android? What version of the SDK are you using?

**Comment by jennantilla** [comment]
@milikamel just following up to see if you received our previous response and whether you are still having issues?

**Comment by milikamel** [comment]
we are using "onesignal-cordova-plugin": "3.3.0" and we are still investigating the issue as it seems to not work on android we didn't check yet on ios but we even tried to throw an exception to crash the app if one function setNotificationOpenedHandler and addListoner to work but nothing happened, sorry for the late reply.

**Comment by jennantilla** [comment]
Hi @milikamel! Are you still having this issue? Were you able to test on iOS and/or get a log from the device reproducing this behavior.

Rereading your issue, it sounds like you want to specifically handle the linking when the app is in the background--is that correct? If so, have you set up the NotificationServiceExtension? 

More information [here](https://documentation.onesignal.com/docs/sdk-notification-event-handlers#background-notification-received-event).

Thanks for the update!

**Comment by jennantilla** [comment]
Closing due to no response. @milikamel please feel free to let us know if you're still having issues!
