### ISSUE TITLE
[Bug]: Android manifestplaceholders are overridden by plugin

### ISSUE THREAD

**Issue by leonluc-dev** [OneSignal/OneSignal-Cordova-SDK#889]
### What happened?

Our Ionic/Capacitor Androidproject has a few manifestPlaceholder values defines in it's build.gradle like this:

```
android {
    defaultConfig {
         // ...
         manifestPlaceholders = [ alternativeAppName: "MyTestAppName" ]
    }
}
```

However, it seems our manifest placeholders are overriden by the plugin.
If the plugin is added the manifestPlaceholders array is replaced by an array containing `onesignal_app_id` and `onesignal_google_project_number`.

This causes any usage of the alternativeAppName placeholder to break:

`Error: Attribute application@label at AndroidManifest.xml:7:9-35 requires a placeholder substitution but no value for <alternativeAppName> is provided`

### Steps to reproduce?

```Markdown
1. Add the manifestPlaceholders property to the android projects build.gradle and assign some placeholders.
2. Use the placeholder(s) in the Android Manifest
3. Add the plugin to the Ionic/Capacitor project (and run `npx cap sync` etc)
4. Observe that the project placeholders are overriden by the plugin placeholders and therefore the manifest parsing fails
```

### What did you expect to happen?

The placeholders provided by the plugin to be additive rather than replacing the placeholders in the project.

### OneSignal Cordova SDK version

3.3.1

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@leonluc-dev Hello I apologize for the late reply is this still an issue in the latest version?

**Comment by leonluc-dev** [comment]
@emawby As of v5.0.3 this seems to no longer be an issue.
