### ISSUE TITLE
Cannot read property 'Notification' of undefined

### ISSUE THREAD

**Issue by oggyindahouse** [OneSignal/OneSignal-Cordova-SDK#89]
The line with "OneSignal.OSInFocusDisplayOption.Notification" in the init function throws an error. My snippet:

        var iosSettings = {};
        iosSettings["kOSSettingsKeyAutoPrompt"] = true;
        
        window.plugins.OneSignal
        .startInit('635983dd-655b-491b-a0e8-7e061ceed42d', '729816255877')
        .iOSSettings(iosSettings)
        .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
        .handleNotificationOpened(App.push_received)
        .endInit();

**Comment by JKalash** [comment]
Hi there,

You should replace `OneSignal.OSInFocusDisplayOption.Notification` with `window.plugins.OneSignal.OSInFocusDisplayOption.Notification `

We'll update our docs to reflect that. Thanks for pointing it out!
