### ISSUE TITLE
[question]: NewMember.vue:131 onesignal error:  TypeError: Cannot read properties of undefined (reading 'exec')     at OneSignalPlugin2.sendTag 

### ISSUE THREAD

**Issue by cdr-asraf** [OneSignal/OneSignal-Cordova-SDK#890]
### How can we help?

`export const addTag = function (tagId: any) {
  console.log("tag: ", tagId);
  OneSignal.sendTag("teamId", tagId);
};`
This above code has given the above error. what can be the reason. I was trying to send tags to onesignal, is there anything I am doing wrong or there is some alternate solutions please let me know. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @cdr-asraf! For Cordova, you'll want to use this syntax to send tags:
`window.plugins.OneSignal.sendTag("key", "value");`

Note that both key and value should be of type String.

Does that work for you?
