### ISSUE TITLE
[question]: How do I retrieve the userId after relaunching the application?

### ISSUE THREAD

**Issue by nmbiyu** [OneSignal/OneSignal-Cordova-SDK#893]
### Environment

Observations below are from testing on Android 8.
Plugin version: 3.3.1

### Summary

I migrated from version ^2.11.3 to version ^3.3.1. The former had a `window.plugins.OneSignal.getIds` function one could use to retrieve the player id. The latter now has a subscription model which works well when the application is first launched and the plugin is initialised.

#### Launching the application the first time

Below are the relevant blocks of code used to initialise the plugin.
```
var oneSignalPlayerId;

onDeviceReady: function() {
  initializeOneSignal();
}

function initializeOneSignal() {
   window.plugins.OneSignal.addSubscriptionObserver(function(stateChanges) {
      if (stateChanges.to.userId) {
          oneSignalPlayerId = stateChanges.to.userId;
      }
  });
}

// Once all initialisation is complete, load the URL
```
When the user navigates to another app, Cordova goes through the tear down lifecycle functions which clear the `inAppBrowserRef`. However, the plugin is still set up. This is expected since we'd want to keep receiving push messages even when the application is in the background.

#### Launching the application the second time

When the user resumes the application, the `inAppBrowserRef` is recreated and the `onDeviceReady` lifecycle function is invoked. This sets up the observer once more. However, the handler is not invoked. I presume this is because no subscription changes were received.

The app is unable to load the URL because one of the prerequisites for this operation is the player id.

### Question

Is there a persistent storage of the player id in the plugin environment that can be accessed after the subscription changes have been received the first time?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nmbiyu** [comment]
I found [this issue](https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/825) that mentioned the [getDeviceState function](https://documentation.onesignal.com/docs/sdk-reference#push-notification-properties). Using the pattern below, I have been able to resolve the issue.

```
var oneSignalPlayerId;

onDeviceReady: function() {
  initializeOneSignal();
  startApp();
}

function initializeOneSignal() {
   window.plugins.OneSignal.addSubscriptionObserver(function(stateChanges) {
      if (stateChanges.to.userId) {
          oneSignalPlayerId = stateChanges.to.userId;
      }
  });
}

function startApp() {
    waitForOneSignalPlayerId(loadWebAppUrl);
}

function waitForOneSignalPlayerId(callback) {
    waitForOneSignalPlayerIdIntervalId = setInterval(function() {
        if (oneSignalPlayerId) {
            clearInterval(waitForOneSignalPlayerIdIntervalId);
            callback();
        } else {
            window.plugins.OneSignal.getDeviceState(function(stateChanges) {
                console.log('OneSignal getDeviceState: ' + JSON.stringify(stateChanges));
                if (stateChanges.userId) {
                    oneSignalPlayerId = stateChanges.userId;
                    clearInterval(waitForOneSignalPlayerIdIntervalId);
                    callback();
                }
            });
        }
    }, 300);
}
```
I was of the opinion that using `getDeviceState` was enough and that I could do away with the subscription observer. However, I noted that when the app was first launched, the state changes in the `getDeviceState` callback did not include the user id. As I see it, I need both functions.

1. The subscription observer to get the user id when the app is first launched.
2. The `getDeviceState` function to get the user id when the application is resumed.

**Comment by jennantilla** [comment]
Hi @nmbiyu! Thanks for your patience here.

I'm glad you were able to resolve your issue! Regarding `getDeviceState`, if it is called too early, it will be null or not available. There is a server call to register the device and get a playerID.

As you mentioned, you would use the the [addSubscriptionObserver method](https://documentation.onesignal.com/docs/sdk-reference#handling-subscription-state-changes) to get a playerID from OneSignal when a notification subscription property changes.

Let us know if you have any additional questions or concerns!
