### ISSUE TITLE
Android 13 - SDK 3.3.1 - Cordova 12,  promptForPushNotificationsWithUserResponse has no effect.

### ISSUE THREAD

**Issue by epetre** [OneSignal/OneSignal-Cordova-SDK#894]
**_promptForPushNotificationsWithUserResponse_** has no effect when being run, it generates no errors.

Just upgraded to Cordova 12 in order to support API 33 for Android and have the latest OneSignal features, including being able to prompt Android 13 users for pushes later than the first moment the open the app.

`FirebaseX.grantPermission()` works and requests the notifications permissions properly.

`OneSignal.getDeviceState((a) => console.log(a));`

**Returns**
```javascript
OSDeviceState {hasNotificationPermission: false, notificationPermissionStatus: undefined, pushDisabled: false, subscribed: false, emailSubscribed: false, …}

emailAddress: undefined
emailSubscribed: false
emailUserId: undefined
hasNotificationPermission: false
notificationPermissionStatus: undefined
pushDisabled: false
pushToken: "e-2Yji6XSMCpqp68q...KFau6HF0rIl99aoWkgXLrx5"
smsNumber: undefined
smsSubscribed: false
smsUserId: undefined
subscribed: false
userId: "fce08f.....a2764d"
```

**Environment**

**Steps to Reproduce Issue:**
  1. Add the onesignal-cordova-plugin to your project
  2. Initialize the plugin with your app ID
  3. I attempt to call promptForPushNotificationsWithUserResponse
  4. Nothing happens

**Anything else:**
`FirebaseX.grantPermission()` works, it requests the permission properly and from that point on,  everything else in OneSignal seems to work correctly.

**Comment by jennantilla** [comment]
Hi @epetre thanks for reaching out! We'll attempt to reproduce this and get back to you as soon as possible.

**Comment by epetre** [comment]
Thx for the update and quick response 💪

**Comment by jennantilla** [comment]
Hi @epetre just an update, I have not been able to reproduce this. Would you be able to attach a [log](https://documentation.onesignal.com/docs/capturing-a-debug-log) from your device when attempting to call `promptForPushNotificationsWithUserResponse`? 

Thanks!

**Comment by epetre** [comment]
Thank you @jennantilla. 
Very sorry about this. It does indeed seem to work.

_I think that the build was silently failing and using an older version. I didn't catch that in the long list of console logs as it continues. Appologies about the distraction and thank you for your help._
