### ISSUE TITLE
[question]: Ionic background notification receive

### ISSUE THREAD

**Issue by mahdi-above** [OneSignal/OneSignal-Cordova-SDK#896]
### How can we help?

I read the documentation for receiving notification on background, it says, it requires native code. Isn't there any other way to implement this without native code? 

I thought there is a listener for this obvious thing.

Currently I set two listeners in my Ionic React App:

setNotificationOpenedHandler and setNotificationWillShowInForegroundHandler.

But I also need a listener for when the app is in background. 

![image](https://github.com/OneSignal/OneSignal-Cordova-SDK/assets/103260743/2ec3ba15-cc51-4ec4-a209-75ad9d6519a6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @mahdi-above thanks for your patience!

That is correct--you will need to use native code for handling background notifications. The NotificationServiceExtension class is needed to receive data in the background. 

Let us know if you have any additional questions or concerns!
