### ISSUE TITLE
[question]: Deeplinks in idle iOS app are not registred

### ISSUE THREAD

**Issue by swebSi** [OneSignal/OneSignal-Cordova-SDK#897]
### How can we help?

Hi,

we are using angular + capacitor and onesignal-cordova-plugin 3.3.1

We followed instructions for setting up deeplinks and we handle our logic in notificationOpenHandler. The issue is that when iOS app is idle for at least a day, launch url seems to be disregarded and app opens on the last page. 

Links are working correctly on android and when app is not in background for a longer period of time on iOS. Are there any other settings required to handle push notification when in idle mode? It seems to work when app is force closed as well. 

Working:
Android in background ✅
Android in background after 1 day ✅
Android force closed ✅
iOS in background ✅
iOS force closed ✅
iOS in background after 1 day ❌

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@swebSi I apologize for the delay in response. Is this still an issue for you? I am not aware of any settings that would fix this outright. If it is still an issue some kind could you let us know if the opened handler is being called?

**Comment by shepherd-l** [comment]
We have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information.
