### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jtejederabit** [OneSignal/OneSignal-Cordova-SDK#899]
### What happened?

Using React + Capacitor fails on OneSignal init. I have been using it on a Vue project (not this package, the one related to Vue) and now I want to follow the same approach/logic within a React + Capacitor app. I've been following the official documentation, online examples and Youtube videos but in my case is not working.

- "@capacitor/core": "^5.2.1",
-  "onesignal-cordova-plugin": "^3.3.1"

```
import OneSignal from 'onesignal-cordova-plugin';
function App() {
    const OneSignalInit = () => {
        OneSignal.setAppId(XXXXXXX);
    }

    OneSignalInit();

    return ( <h1>Hello</>);
}
```

When I run the app, it crash and in console log I can see the next error:
![image](https://github.com/OneSignal/OneSignal-Cordova-SDK/assets/130762129/ee0816e1-2aa9-4bbf-9747-2c9cdb5f9ec9)

### Steps to reproduce?

```Markdown
1. Install React + Capacitor + onesignal plugin
2. Create a simple react app and add Capacitor.
3. Copy code example and run the app
```

### What did you expect to happen?

I expected the app to run normally and initialize Onesignal plugin as described in docs.

### OneSignal Cordova SDK version

3.3.1

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@jtejederabit Hello I apologize for the late response is this still an issue with the latest version?

**Comment by jennantilla** [comment]
Closing due to no response. Feel free to comment here if this is still an issue for you!
