### ISSUE TITLE
ios not registering user

### ISSUE THREAD

**Issue by ThodorisElissaios** [OneSignal/OneSignal-Cordova-SDK#90]
hello im building with phonegap and users not registering.
iOS:10.0.2
phonegap :cli.6.3.0

**Comment by JKalash** [comment]
Hi there,

You should make sure to have the _**push capability**_ turned on from Xcode. Refer to the section [here](https://documentation.onesignal.com/docs/cordova-sdk-setup#section-5-ios).

Thanks.

**Comment by ThodorisElissaios** [comment]
and what if i am not using Xcode ?
