### ISSUE TITLE
[Bug]: 'OneSignal/OneSignal.h' file not found

### ISSUE THREAD

**Issue by Mr-Anonymous** [OneSignal/OneSignal-Cordova-SDK#900]
### What happened?

When I try to build ios app, I always get this fatal error: 

`platforms/ios/App/Plugins/onesignal-cordova-plugin/OneSignalPush.h:32:9: fatal error: 
      'OneSignal/OneSignal.h' file not found`

If I remove the OneSignal plugin, it builds fine.

Android builds fine, the issue is only with the iOS.

My Mac version is: macOS Monterey 12.6.3 and Xcode version is: 14.2

### Steps to reproduce?

```Markdown
1. Tried running `ionic cordova build ios --prod --release`

2. Also tried other recommended steps like opening the workspace in Xcode and then run build command.

3. Tried running pod update and same issue is there.

4. Tried removing platform and re-adding doesn't help either.
 
```

### What did you expect to happen?

It is suppose to build with no issue.

### OneSignal Cordova SDK version

3.3.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
Ionic:

   Ionic CLI         : 6.18.1 (/Users/me/.nvm/versions/node/v11.12.0/lib/node_modules/@ionic/cli)
   Ionic Framework   : ionic1 1.3.3
   @ionic/v1-toolkit : 1.0.9

Cordova:

   Cordova CLI       : 8.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, (and 18 other plugins)

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.2) : 1.7.1

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v11.12.0 (/Users/me/.nvm/versions/node/v11.12.0/bin/node)
   npm               : 6.14.7
   OS                : macOS Monterey
   Xcode             : Xcode 14.2 Build version 14C18


  ────────────────────────────────────────────────
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lidslira** [comment]
Any updates? Facing this same issue

**Comment by emawby** [comment]
Hello these issues are typical problems with cocoapods cache or outdated versions.  Which versions of cocoapods are you using? I would try cleaning the pod cache and doing install with --repo-update

**Comment by jennantilla** [comment]
Hello there! We have not had any further reports of this issue. Please update to our latest SDK version and if you are still having trouble please open a new issue. Here is our [migration guide](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/main/MIGRATION_GUIDE.md) for details on upgrading. Thanks!
