### ISSUE TITLE
Problems with the OneSignal plugin, please help!

### ISSUE THREAD

**Issue by EncoreSpec** [OneSignal/OneSignal-Cordova-SDK#905]
### How can we help?

There was a problem with onesignal-cordova-plugin 5.0.0-beta-02. Project under android targetSdkVersion 33

What do I do:
I add onesignal-cordova-plugin" spec="5.0.0-beta-02 to the project, then through NODE.JS I assemble the project for Android Studio, through the cordova platform add android.
In Androyd Studio, I update the gradle plugins to version 7.2.2, build and sign the application, everything goes without errors.
But when I launch an already finished application, the application starts, but immediately hangs on a black screen.

Tried the onesignal-cordova-plugin 3.0.0 and 3.3.1 but the result is the same.
Previously, I did everything the same way under API 29 and used onesignal-cordova-plugin 2.4.1 and everything worked.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @EncoreSpec thank you for your patience. Are you still having issues?

Cordova major release is now live. Please try updating to the non-beta 5.0.0. If you are still experiencing this, please also provide the [log](https://documentation.onesignal.com/docs/capturing-a-debug-log) from the device. 

Thanks!
