### ISSUE TITLE
Not running on Android 12,13 using target SDK 33 in IONIC 3.

### ISSUE THREAD

**Issue by deepakpapney** [OneSignal/OneSignal-Cordova-SDK#909]
### What happened?

 it's showing plugin is not installed on runtime and when I downgrade the plugin version to **2. x.x** it runs with **targetSDK30** but on upgrading targetSDK33 it gives a manifest error. If anyone knows the solution please help me out with this. 
Thanks in advance

### Steps to reproduce?

```Markdown
1. checked by upgrading the plugin version to the latest (nothing happened).
2. I am using it for mobile push notification IONIC 3
```

### What did you expect to happen?

not sure

### OneSignal Cordova SDK version

5.0.0-beta-02 

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepakpapney** [comment]
waiting for the quick response and guidance

**Comment by deepakpapney** [comment]
Anyone help please

**Comment by selcuk-sahin** [comment]
Hi,

what is your cordova / capacitor version?

Also, have you tried installing the latest version? (5.0.0)

**Comment by emawby** [comment]
@deepakpapney I apologize for the lack of reply. Are you still experiencing this issue using the released versions?

**Comment by deepakpapney** [comment]
@emawby it's ok now i configured it
