### ISSUE TITLE
Hello i have installed this plugin and code according to setup but then also it shows that plugin not installed in ionic 3 so can you please answer my question how it is possible to run this version of plugin in ionic 3 project specified some information as below  ("@ionic-native/onesignal": "^4.20.0",, "onesignal-cordova-plugin": "^2.11.4",)

### ISSUE THREAD

**Issue by akshayatina** [OneSignal/OneSignal-Cordova-SDK#912]
### How can we help?

Hello i have installed this plugin and code according to setup but then also it shows that plugin not installed in ionic 3 so can you please answer my question how it is possible to run this version of plugin in ionic 3 project specified some information as below  ("@ionic-native/onesignal": "^4.20.0",, "onesignal-cordova-plugin": "^2.11.4",)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @akshayatina thank you for reaching out! 

If you are adding OneSignal to your project for the first time, please follow [these steps](https://documentation.onesignal.com/docs/ionic-sdk-setup) to add the latest version of our SDK. There are some specific steps for Ionic 3 that you can follow there.

If you are still having trouble, please follow up with some more information and we'll be happy to help!

**Comment by akshayatina** [comment]
> Hi @akshayatina thank you for reaching out!
> 
> If you are adding OneSignal to your project for the first time, please follow [these steps](https://documentation.onesignal.com/docs/ionic-sdk-setup) to add the latest version of our SDK. There are some specific steps for Ionic 3 that you can follow there.
> 
> If you are still having trouble, please follow up with some more information and we'll be happy to help!

Hello @jennantilla thanks for the reply on my issue i have tried your solution as you have instructed but facing the same issue now also i have inspect the app and installed the plugin as well according to steps.
Please see the attached file below 
![Onesignal_issue](https://github.com/OneSignal/OneSignal-Cordova-SDK/assets/144653144/b7c9aada-c699-4dff-90a0-8a497969e99e)

**Comment by oobi** [comment]
I'm seeing the same error -- trying to get mine running in Ionic 7 / Angular.  The docs seem a bit incomplete.

**Comment by jennantilla** [comment]
Hello everyone, apologies that this issue has gone stale. I'm going to close this out since we have not received any more reports of this. If there are any concerns after upgrading to our latest SDK, please open a new ticket and we'll be happy to assist. Thanks!
