### ISSUE TITLE
[question]:  release 5.0.0 NotificationServiceExtension

### ISSUE THREAD

**Issue by alextapia007** [OneSignal/OneSignal-Cordova-SDK#913]
### How can we help?

In NotificationServiceExtension 

before public void remoteNotificationReceived(Context context, OSNotificationReceivedEvent notificationReceivedEvent) works
but now public void onNotificationReceived(INotificationReceivedEvent event) how do i get app context?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @alextapia007 thank you for your patience!

The new Notification Service Extension documentation can be found [here](https://documentation.onesignal.com/docs/service-extensions#step-1-create-a-class-for-the-service-extension).

Let us know if you have any further questions or concerns!
