### ISSUE TITLE
[question]: "cordova prepare ios" keeps changing target in Podfile

### ISSUE THREAD

**Issue by julia-fix** [OneSignal/OneSignal-Cordova-SDK#917]
### How can we help?

Every time after I run 'cordova prepare ios' I get error in XCode: 'OneSignalExtension/OneSignalExtension.h' file not found
So after this command every time I have to do following steps:
Adding lines to Podfile
```
target 'OneSignalNotificationServiceExtension' do
	pod 'OneSignalXCFramework', '>= 5.0', '< 6.0'
end
```
Running command 'pod install'

On the next "cordova prepare ios" OneSignalNotificationServiceExtension target gets replaced with main app target and I have to start over again. My Podfile gets changed like that:
 ```
target 'MyMainTarget' do
	pod 'OneSignalXCFramework', '>= 5.0', '< 6.0'
end
```

Plugins in my project:
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-background-geolocation-plugin 2.0.7 "cordova-background-geolocation-plugin"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 3.3.1 "Advanced HTTP plugin"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 6.0.1-dev "Camera"
cordova-plugin-chooser 1.3.1 "Chooser"
cordova-plugin-cocoapod-support 1.6.2 "Cordova CocoaPods Dependency Support"
cordova-plugin-cookie-manager 0.0.1 "CookieManagementPlugin"
cordova-plugin-customurlscheme 5.0.1 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file-opener2 3.0.5 "File Opener2"
cordova-plugin-file-transfer 2.0.0 "File Transfer"
cordova-plugin-file 8.0.0 "File"
cordova-plugin-filepath 1.5.8 "cordova-plugin-filepath"
cordova-plugin-filepicker 1.1.6 "File Picker"
cordova-plugin-idfa 2.1.0 "cordova-plugin-idfa"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-localization-strings 5.0.5 "Localization"
cordova-plugin-media-capture 5.0.1-dev "Capture"
cordova-plugin-media 7.0.0 "Media"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-preview-any-file 0.1.6 "PreviewAnyFile"
cordova-plugin-splashscreen 6.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-wkwebview-cookie-sync 1.1.4 "WKWebViewCookieSync"
cordova-plugin-x-socialsharing 6.0.4 "SocialSharing"
cordova-support-android-plugin 2.0.4 "cordova-support-android-plugin"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 5.0.0 "OneSignal Push Notifications"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Apologies that this issue was missed! Due to the amount of time that has passed, I will close this issue. If this is still a problem for you, please open a new issue and we will be sure to help! Thanks!
