### ISSUE TITLE
[question] Docs are not accurate?

### ISSUE THREAD

**Issue by julia-fix** [OneSignal/OneSignal-Cordova-SDK#924]
### How can we help?

I upgrade Onesignal in my Cordova project from v.3 to v.5 and following this guide: https://documentation.onesignal.com/docs/mobile-sdk. However, I get errors in console saying methods described in docs are not defined.

E.g. I try to use "window.plugins.OneSignal.Notifications.permission" to get permission state and get undefined. In console I see window.plugins.OneSignal.Notifications has _permission property (prefixed with underscore). Does it mean the plugin was initialized the wrong way? Or it is just not mentioned in docs?

Some other methods described in docs are not defined even with underscore, e.g. window.plugins.OneSignal.Notifications.addPermissionObserver.

<img width="685" alt="2023-09-27" src="https://github.com/OneSignal/OneSignal-Cordova-SDK/assets/9879609/fd05a3a3-c64e-4f21-acf3-51b10fee5d91">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @julia-fix, thanks for reporting this, 

The method to access permission is `let permission = OneSignal.Notifications.hasPermission()`. We will update the docs at https://documentation.onesignal.com/docs/mobile-sdk to show the correct way to get permission.

[This guide](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/user_model/main/MIGRATION_GUIDE.md) is the most updated and accurate list of methods and properties available for the OneSignal-Cordova-SDK.

As for your question about methods that are prefixed by an underscore (`_`), those are internal methods the SDK uses and not meant to be used by app developers.

**Comment by jennantilla** [comment]
Closing issue-- @julia-fix let us know if you have any additional questions or concerns!
