### ISSUE TITLE
[Bug]: hasPermission() always initially returns false

### ISSUE THREAD

**Issue by terreng** [OneSignal/OneSignal-Cordova-SDK#925]
### What happened?

`window.plugins.OneSignal.Notifications.hasPermission()` always returns `false` when called immediately within the Cordova `deviceready` event, even if permission has been granted. This method may need to be made a promise.

### Steps to reproduce?

```Markdown
Observe that this code logs `false` even if permission is granted.

document.addEventListener("deviceready", function() {
  console.log(window.plugins.OneSignal.Notifications.hasPermission())
});


If you put this inside a short setTimeout then it returns the expected value (true if granted).
```

### What did you expect to happen?

It should return true if permission has been granted.

### OneSignal Cordova SDK version

5.0.1

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @terreng thank you so much for your patience. We're investigating this and will get back to you as soon as possible.

**Comment by kpturner** [comment]
Update?

**Comment by aledebla03** [comment]
same here

**Comment by jennantilla** [comment]
Apologies that we missed updating this ticket! This issue should now be resolved by using the new method, `getPermissionAsync`. Please see our [Migration Guide](https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/main/MIGRATION_GUIDE.md) for more details. `hasPermission` is now deprecated.

Let us know if you have any questions or concerns!
