### ISSUE TITLE
[Feedback]: Can we have the functionality to change the default message that asks users to give permission to send notifications?

### ISSUE THREAD

**Issue by talha7t** [OneSignal/OneSignal-Cordova-SDK#929]
### What's on your mind?

I am working on an app and the clients want to change the message that appears to allow the app to send notifications. Can we have any method that would allow us to do that?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @talha7t thanks for reaching out! For iOS and Android 13+, a native prompt is required to opt in to push notifications. This prompt is not customizable through OneSignal.

However, we recommend adding an [in-app "soft" prompt](https://documentation.onesignal.com/docs/how-to-prompt-for-push-permissions-with-an-in-app-message) to precede the native prompt. This allows you to customize your messaging to users.

Please let us know if you have any additional questions or concerns!
