### ISSUE TITLE
[Bug]: Android device not registered on initialization (Android v12 and older)

### ISSUE THREAD

**Issue by swebSi** [OneSignal/OneSignal-Cordova-SDK#931]
### What happened?

We are using Angular + Capacitor v5 with OneSignal 5.0.2.
After calling OneSignal.initialize  - Android devices are not visible under subscriptions. 
With the same codebase iOS devices are correctly registered. 

Reverting the library to v3.3.1 works as expected. 

### Steps to reproduce?

```Markdown
1. Upgrade to v5.0.2
2. Call OneSignal.initialize as per documentation
3. Observe subscription list in oneSignal dashboard
```

### What did you expect to happen?

I expect to see my client registered in order to send push notifications. 

### OneSignal Cordova SDK version

5.0.2

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@swebSi thanks for reaching out! 

Are you prompting your users at all?

In your initialization code, we suggest either including our [`requestPermission` method](https://documentation.onesignal.com/docs/mobile-sdk#prompting-for-push-notification-permissions) or using an [In-App Message](https://documentation.onesignal.com/docs/how-to-prompt-for-push-permissions-with-an-in-app-message) to prompt for notification permission.

If you are still having issues, can you please send over your [device logs](https://documentation.onesignal.com/docs/capturing-a-debug-log) so we can take a closer look?

Thanks!

**Comment by swebSi** [comment]
Hi @jennantilla,

yes, of course I am prompting the users after Onesignal. initialize. Also, we are testing on devices without Android 13 which have automatically subscribed notifications. Reverting back to v3.3.1 with the same codebase (- the naming changes) devices are registered without an issue.

**Comment by swebSi** [comment]
Hi @jennantilla ,
this seems to be an issue only on Android devices prior to Android 13. Testing the same flow with Android 13 device works as expected.

**Comment by swebSi** [comment]
On devices with android 12 or older, its was required to call OneSignal.User.setLanguage();

[DefaultDispatcher-worker-6] HttpClient: POST RECEIVED JSON: {"errors":[{"title":"The provided language value is not a supported ISO 639-1 value"}]}
