### ISSUE TITLE
[Bug]: Android: Notifications.requestPermission hangs (capacitor) and hasPermissions() always returns false

### ISSUE THREAD

**Issue by kpturner** [OneSignal/OneSignal-Cordova-SDK#932]
### What happened?

Using version 5.0.2 - when an app is installed for the first time on Android and runs 
`Notifications.requestPermission(true)`
The user is prompted to allow notifications.  

In previous versions of the SDK, you could call `Notifications.requestPermissions` with impunity.  If you do so when the user has already agreed, then the request is ignored.  Now, if you do so, the request just hangs causing the app to become unresponsive.  You cannot  even condition the call to `Notifications.requestPermissions` because `Notifications.hasPermission()` always returns `false`.

### Steps to reproduce?

```Markdown
1. Install 5.0.2
2. Call Notifications.requestPermission(true) while running on Android
3. Respond to the prompt
4. Restart the app 
5. Notifications.requestPermission(true) will hang
```

### What did you expect to happen?

 Notifications.requestPermission(true) should behave as it did before.  Prompt the user only if necessary and do not hang.
 hasPermissions()  should return the correct value

### OneSignal Cordova SDK version

5.0.2

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kpturner** [comment]
I have worked around this issue by wrapping this requestPermission prompt in a call to `Notifications.canRequestPermission()` for the time being.

**Comment by kpturner** [comment]
Another workaround is to not `await` but use a `.then()` chain
```
if (await OneSignal.Notifications.canRequestPermission()) {
      OneSignal.Notifications.requestPermission(true).then(
        (accepted) => {
            ....
        },
        (error) => {
           ....
        }
      )
 }
```

**Comment by nan-li** [comment]
Hi @kpturner, we have implemented a fix for `requestPermission` that will be in the next release. However, I am concerned about this:

> You cannot even condition the call to Notifications.requestPermissions because Notifications.hasPermission() always returns false.

Can you tell me more about this? Is it always `false` on all devices and use cases?

**Comment by kpturner** [comment]
I do not think I am in a position to test "all devices and use cases".   Perhaps you can tell me a device (simulator and API version) where it correctly returns `true` and I can verify that?

**Comment by nan-li** [comment]
Hi @kpturner, just in your own testing if this was the case 100% of the time?

I most recently tried to reproduce in an Android emulator Nexus S API 33 using a minimal app:
1. New app installation and call `OneSignal.initialize`
2. Wait a few secons.
3. Check `hasPermission` returns `false`
4. Prompt for push with `OneSignal.Notifications.requestPermission(true)`
5. Press accept
6. Check `hasPermission` returns `true` now

**Comment by kpturner** [comment]
Here are the dependencies in use:
```
    "@capacitor/android": "^5.0.5",
    "@capacitor/app": "^5.0.6",
    "@capacitor/cli": "^5.0.5",
    "@capacitor/core": "^5.0.5",
    "@capacitor/device": "^5.0.6",
    "@capacitor/ios": "^5.0.5",
    "@capacitor/preferences": "^5.0.6",
    "@capacitor/splash-screen": "^5.0.6",
    "@gifsa/core": "^1.0.0",
    "appsflyer-capacitor-plugin": "6.12.1-alpha-monorepo",
    "capacitor-plugin-app-tracking-transparency": "^2.0.4",
    "capacitor-set-version": "^2.0.13",
    "googleapis": "^128.0.0",
    "onesignal-cordova-plugin": "^5.0.1"
```

`On a Pixel 7 Pro API 33`, `OneSignal.Notifications.hasPermission()` always returns false.   That is after accepting permission and also after the app restarts.
