### ISSUE TITLE
No function to set language for a device.

### ISSUE THREAD

**Issue by joturako** [OneSignal/OneSignal-Cordova-SDK#94]
I've notice that you can push in different languages, and create segments based on Country value of a customer.

Unfortunately, while the init process does recognize the country i'm in (**VN**), it still lists my device language as **English**. I've tried to change the language of the phone to **Vietnamese**, but it didn't help.
I want to confirm that the init process already detects the device language, and not default to **English**. Anyway, I think we should have a function to update the device language however we wanted (based on app language preference of an user).

Example scenario this is needed: I wanted to target all users in **VN** but some of them can only read **English**.

**Comment by jkasten2** [comment]
@joturako I just checked your OneSignal account and our SDK is correctly detecting the system langue as Vietnamese for your Android device.

We do not plan on adding an option override this detection from the application itself. You can however use tags instead if you want to not use the system language.

**Comment by joturako** [comment]
@jkasten2 If you see my device language is Vietnamese, it's because i override it using REST api function (edit device). If in fact there is already detection i will test again to be sure its working, but this is a relief, atleast i can worry about other thíng first.FYI, I'm using android 7 with dual language added, Vietnamese first, then English.

In anycase, i plan to let user change my app interface language and i will use Rest API call from my server to reflect the change in OneSignal server.
