### ISSUE TITLE
[Bug]: Has Permission showing false when it's not.

### ISSUE THREAD

**Issue by RZR666** [OneSignal/OneSignal-Cordova-SDK#948]
### What happened?

let permission = window.plugins.OneSignal.Notifications.hasPermission();

I can see that I have push notifications enabled but the above returns false.

"@angular/core": "^15.2.8",
"@ionic/angular": "^7.0.4",
"cordova-android": "11.0.0",
"onesignal-cordova-plugin": "^5.0.3",

### Steps to reproduce?

```Markdown
initOneSignal()
{
   window.plugins.OneSignal.initialize(oneSignalAppId);
}

enablePush()
{
this.androidPermissions.checkPermission(PERMISSION.POST_NOTIFICATIONS).then(
          result => this.requestPushPermission(result.hasPermission),
          err => this.androidPermissions.requestPermission(PERMISSION.POST_NOTIFICATIONS));
}

requestPushPermission(hasPermission)
{
  if (hasPermission)
  {
    this.optInToPush();
  }
}

optInToPush()
{
    window.plugins.OneSignal.User.pushSubscription.optIn();

    let permission = window.plugins.OneSignal.Notifications.hasPermission();
    console.log(permission);
}
```

### What did you expect to happen?

It should show true.

### OneSignal Cordova SDK version

5.0.3

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RZR666** [comment]
So it worked by going through,

window.plugins.OneSignal.Notifications.requestPermission(true).then((accepted: boolean) => {

but it's weird it didn't work the above way, since it had actually also enabled push permission.

**Comment by jennantilla** [comment]
Hi @RZR666 apologies for the delay. `hasPermission` has been deprecated and replaced with `getPermissionAsync` which will return the correct value. Please update to the [latest SDK](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.1.2) and let us know if you are still facing any issues.

Thanks!
