### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by sjorsroelofs** [OneSignal/OneSignal-Cordova-SDK#95]
I'm using Ionic 2 RC0, when I use the code below (replaced my project keys with) inside this.platform.ready I get the following error message in the Safari console when running on my iPhone: 
`Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'Co(window,t.pluginRef)[e].apply')
`

My code:
```
OneSignal.init('xxxxx', {
  googleProjectNumber: 'xxxxx',
  autoRegister: true
}).subscribe(jsonData => {
  console.log('didReceiveRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
});

OneSignal.enableInAppAlertNotification(true);
```

**Comment by danielehrhardt** [comment]
Same Problem here!!

**Comment by sjorsroelofs** [comment]
I just found out this is probably a problem with ionic-native, not specifically with OneSignal: https://github.com/driftyco/ionic-native/issues/649
