### ISSUE TITLE
[question]: Why is my subscription id always different than the OneSignal portal?

### ISSUE THREAD

**Issue by RZR666** [OneSignal/OneSignal-Cordova-SDK#950]
### How can we help?

So, I'm sending the below to my database,

window.plugins.OneSignal.User.pushSubscription.id

and I recieve "2e42c94b-d8e8-4b98-8f3b-c7e4947e22ca" which is completely different to my Subscription ID that gets created on the OneSignal portal.

I've tried uninstalling and re-installing the app but I'm just getting the same issue.

Any help appreciated.

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RZR666** [comment]
ok for anyone else that's having the same issue ...

window.plugins.OneSignal.User.pushSubscription.id

I've no idea what that returns, its nothing shown in the OneSignal portal.

Instead I use the external id that I set in the cordova plugin, to get the one player id on the api side, which strangely doesn't return any subscriptions even though one gets created on the One Signal portal and this is the only user i have.

$url = "https://onesignal.com/api/v1/apps/" . $one_signal_app_id . "/users/by/external_id/" . $user_uid;

and I can send push notifications using that.

I can only suspect that there change from being device centric has left a lot of inconsistencies with the data.

**Comment by jennantilla** [comment]
Hi @RZR666 apologies for any confusion here. OneSignal.User.pushSubscription.id should indeed match the Subscription ID field found in the dashboard. Would you be able to share the [logs](https://documentation.onesignal.com/docs/capturing-a-debug-log#get-the-logs) from your device so we can dig into this deeper? Thanks!

**Comment by RZR666** [comment]
I've sent them to one signal support, Ive not heard nothing back since.

It's returning the wrong subscription id from the api too, its a subscription id that doesn't exist on the one signal portal.  So it's not an sdk issue, since the api is returning the same unknown id.

**Comment by josephvoxone** [comment]
Indeed I have the same issue, In the past, OneSignal used to operate based on UUID or IMEI, which were derived from the device being used. However, now the UUID tends to change dynamically.

**Comment by jennantilla** [comment]
Hello everyone, apologies that this issue has gone stale. If this is still an issue for anyone, please feel free to provide the [logs](https://documentation.onesignal.com/docs/capturing-a-debug-log#get-the-logs) from your device so we can dig into this deeper. Thank you!

**Comment by AdarshJais** [comment]
📱 Final subscription state: {"hasPushToken": true, "isOptedIn": true, "onesignalId": "0a686ba0-95c7-4b65-92e7-c37a316f69cb", "subscriptionId": "0f7414a8-321f-4ff1-b352-e15526aecaf8"}

```
export async function registerForPushNotifications(): Promise<string | null> {
  // if (!Device.isDevice) {
  //   console.log('Must use a physical device for push notifications');
  //   return null;
  // }

  try {
    const { data: { session } } = await supabase.auth.getSession();
    
    // This is crucial for multi-device support
    if (session?.user?.id) {
      console.log('Setting OneSignal external user ID:', session.user.id);
      
      // Check if OneSignal already has the correct external user ID
      const currentExternalUserId = await OneSignal.User.getExternalId();
      console.log('Current OneSignal external user ID:', currentExternalUserId);
      
      // Only logout/login if the external user ID doesn't match
      if (currentExternalUserId !== session.user.id) {
        console.log('OneSignal user ID mismatch, clearing session and re-logging in...');
        
        // Clear any existing OneSignal session
        OneSignal.logout();
        
        // Wait a moment for logout to complete
        await new Promise(resolve => setTimeout(resolve, 500));
        
        // Now login with the correct user ID
        OneSignal.login(session.user.id);
     
        console.log('OneSignal user session established for:', session.user.id);
      } else {
        console.log('OneSignal already has correct user ID, no need to re-login');
      }
    }
    // Request push notification permission
    const permissionResponse = await OneSignal.Notifications.requestPermission(true);
    
    if (!permissionResponse) {
      console.log('Permission for notifications was denied');
      return null;
    }
    const pushToken = await OneSignal.User.pushSubscription.getTokenAsync();
    const isOptedIn = await OneSignal.User.pushSubscription.getOptedInAsync();
    
    console.log('OneSignal push token:', pushToken);
    console.log('OneSignal opted in:', isOptedIn);
    
    if (!pushToken || !isOptedIn) {
      console.log('🔄 Need to create/fix subscription - calling optIn()');
      OneSignal.User.pushSubscription.optIn();
    } else {
      console.log('✅ Valid subscription exists - skipping optIn() to prevent duplicates');
    }
    
    // Get OneSignal User ID (this is what we'll use as our push token)
    const deviceState = await OneSignal.User.getOnesignalId();
    const deviceSubscriptionState = await OneSignal.User.pushSubscription.getIdAsync();
    
    console.log('📱 Final subscription state:', {
      onesignalId: deviceState,
      subscriptionId: deviceSubscriptionState,
      hasPushToken: !!pushToken,
      isOptedIn: isOptedIn
    });

    if (!deviceState) {
      console.log('Could not get OneSignal ID');
      return null;
    }

    return deviceState;
  } catch (error) {
    console.error('Error registering for push notifications:', error);
    return null;
  }
}
```

<img width="932" alt="Image" src="https://github.com/user-attachments/assets/b26efe28-5eef-4905-b7ca-d92a177461e8" />
