### ISSUE TITLE
[Bug]: requestPermission with fallback true does not work correctly on Android 12 devices

### ISSUE THREAD

**Issue by kpturner** [OneSignal/OneSignal-Cordova-SDK#951]
### What happened?

If push notification permission has been denied, then when you use the `requestPermission` method passing `true` to fallback to the settings, the native settings prompt pops up. You can then give permission via the settings and return to the app.  The `requestPermission` promise then resolves returning `true` (the user gave permission).  However, on an Android 12 device (in this case a Nexus 6 running API 31) it always returns `false`.  

To work around this, you can call `hasPermission` to get the correct value immediately after the `requestPermission` has resolved.  However, if you call that method again for any other reason, it will always return false.   Only by restarting the app will `requestPermission` return the correct value. 

### Steps to reproduce?

```Markdown
Use a Nexus 6 API 31 Android 12 emulator and test the requestPermission method with fallback enabled.
```

### What did you expect to happen?

Should work as with later versions of Android. 

### OneSignal Cordova SDK version

Release 5.0.4

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Thank you for this report--we'll investigate further!

**Comment by jennantilla** [comment]
Hello there--apologies that this issue has gone stale. We have made many improvements to our SDK since this was reported that could resolve this issue. Please update to our [latest version](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.2.8) and if you still have any problems, feel free to create a new issue. Thanks!
