### ISSUE TITLE
[question]: Custom push notification icon in Ionic Capacitor

### ISSUE THREAD

**Issue by ayokay123** [OneSignal/OneSignal-Cordova-SDK#956]
### How can we help?

I'm currently encountering an issue while attempting to add the `ic_stat_onesignal_default` icon in a Capacitor project for Android. The [documentation](https://documentation.onesignal.com/docs/customize-notification-icons#option-b-manually-create-icons) provides information on manually creating icons but does not specifically cover the Capacitor case.

I initially attempted to include the default icon inside `capacitor-cordova-android-plugins`, but after running `npm run build && npm run sync`, the updates I made were not reflected.

Now, I'm seeking guidance on the appropriate location to add the default icon for Capacitor. I've considered placing it either in `app->src->main->AndroidManifest.xml` or `app->src->main->xml->config.xml`. However, I'm unsure of the correct approach.

Has anyone encountered a similar situation with Capacitor and successfully resolved it? Some guidance would be appreciated.

Folder structure:
<img width="504" alt="image" src="https://github.com/OneSignal/OneSignal-Cordova-SDK/assets/47676265/09c39952-f315-4828-9d4a-f1ef3d6f3dac">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kpturner** [comment]
I followed the same documentation and have the icons in the folder structure defined here:
![image](https://github.com/OneSignal/OneSignal-Cordova-SDK/assets/308646/22cdb955-ec83-4e0c-805f-6191971fe5fb)

I have not even got a `capacitor-cordova-android-plugins` folder. 

I have not tested this yet as the documentation also refers to updating `config.xml` file that does not exist either.

**Comment by kpturner** [comment]
OK this is now working as expected.  I created a monochrome `.png` as [er the docs and used 
https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_onesignal_default
to generate the required folders/images.   These folders can just be dropped straight into `android/app/src/main/res`.

I then put a full colour 256x256 png into `drawable-xxxhdpi` called `ic_onesignal_large_icon_default.png` (this gets displayed in the message body).

I then specified an `accent-color` for the small icon.  You can pass this on the `createNotification` REST API call or via the method described here https://documentation.onesignal.com/docs/customize-notification-icons#set-default-small-icon-and-accent-colors 

Seemed to work just fine with no other config.

**Comment by ayokay123** [comment]
Yup worked for me as well 🙌
