### ISSUE TITLE
Read a title of OneSignal Notification in PhoneGap

### ISSUE THREAD

**Issue by wap4444** [OneSignal/OneSignal-Cordova-SDK#96]
I use PhoneGap Build and OneSignal. How can I read a title of notification in PhoneGap Project. There is my code
`......
receivedEvent: function(id) {
    var iosSettings = {};
    iosSettings["kOSSettingsKeyAutoPrompt"] = true;
    iosSettings["kOSSettingsKeyInAppLaunchURL"] = false;

    window.plugins.OneSignal.startInit( "*************************", "************")
                            .handleNotificationReceived(didReceiveRemoteNotificationCallBack)
                            .handleNotificationOpened(didOpenRemoteNotificationCallBack)
                            .inFocusDisplaying(window.plugins.OneSignal.OSInFocusDisplayOption.None)
                            .iOSSettings(iosSettings)
                            .endInit();
}
};

function didReceiveRemoteNotificationCallBack(jsonData) {
alert('RECEIVE: ' + JSON.stringify(jsonData));
}
function didOpenRemoteNotificationCallBack (jsonData) {
alert('OPEN: ' + JSON.stringify(jsonData));
}

app.initialize();`

How to get a TITLE when Notification receive in **didReceiveRemoteNotificationCallBack**?

**Comment by jkasten2** [comment]
You can get it by calling `jsonData.payload.title` in the function. See [NotificationReceivedHandler](https://documentation.onesignal.com/v3.0/docs/cordova-sdk#section--notificationreceivedhandler-) for a full list of properties.

Thanks.
