### ISSUE TITLE
[FEATURE]: Add required `Privacy Manifest` file for iOS

### ISSUE THREAD

**Issue by edshkliaruk** [OneSignal/OneSignal-Cordova-SDK#978]
### How can we help?

**Description**

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file (similar to the privacy nutrition labels in the store). Apple specifically lists Capacitor as one of the SDKs that must include this manifest otherwise any App that includes it is not allowed to release an update (or new app) to the store.

https://developer.apple.com/support/third-party-SDK-requirements/

**Platform(s)**

iOS

**Additional Context**
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
https://developer.apple.com/videos/play/wwdc2023/10060/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@edshkliaruk This has been added to the [Release 5.0.4](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/5.0.4). See the [OneSignal-iOS-SDK 5.0.5](https://github.com/OneSignal/OneSignal-iOS-SDK/pull/1334) release notes.
