### ISSUE TITLE
'OneSignalFramework/OneSignalFramework.h' file not found - IOS 

### ISSUE THREAD

**Issue by codingwithashu** [OneSignal/OneSignal-Cordova-SDK#979]
**Description:**

'OneSignalFramework/OneSignalFramework.h' file not found
The following build commands failed:
        CompileC /var/root/Library/Developer/Xcode/DerivedData/app-djugkxegcmyvmddowkdvtljpzopj/Build/Intermediates.noindex/app\ Lite.build/Debug-iphonesimulator/app\ Lite.build/Objects-normal/arm64/OneSignalPush.o /Users/appmac/Documents/app/platforms/ios/app\ Lite/Plugins/onesignal-cordova-plugin/OneSignalPush.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'app Lite' from project 'app Lite')
(1 failure)
while building app this error is coming 

**Environment**

Ionic:

   Ionic CLI                     : 5.4.16 (/Users/mac/node_modules/ionic)
   Ionic Framework               : @ionic/angular 6.1.11
   @angular-devkit/build-angular : 14.2.13
   @angular-devkit/schematics    : 14.0.3
   @angular/cli                  : 14.0.3
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 12.0.0 (cordova-lib@12.0.1)
   Cordova Platforms : android 12.0.1, ios 7.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 19 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 2.0.1) : 1.7.2

System:

   ios-deploy : 1.12.2
   ios-sim    : 8.0.2
   NodeJS     : v21.6.2 (/usr/local/bin/node)
   npm        : 10.2.4
   OS         : macOS Unknown
   Xcode      : Xcode 15.0.1 Build version 15A507

com.ourcodeworld.appinstalled 1.0.0 "Our Code World App Installed"
cordova-background-geolocation-lt 4.14.3 "BackgroundGeolocation"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-android-permissions 1.1.3 "Permissions"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.14 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 7.2.1 "CDVBackgroundFetch"
cordova-plugin-camera-preview 0.12.3 "cordova-plugin-camera-preview"
cordova-plugin-camera 6.0.1-dev "Camera"
cordova-plugin-cszbar 1.3.2 "ZBar barcode scanner"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-devoptionschecker 1.0.0 "DevOptionsChecker"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file-opener2 3.0.5 "File Opener2"
cordova-plugin-file-transfer 2.0.0 "File Transfer"
cordova-plugin-file 8.0.1-dev "File"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-unique-device-id2 2.0.0 "UniqueDeviceID"
cordova-plugin-x-socialsharing 6.0.4 "SocialSharing"
cordova.plugins.diagnostic 7.1.4 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.22 "Ionic Deeplink Plugin"
onesignal-cordova-plugin 5.0.6 "OneSignal Push Notifications"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.6 "Launch Navigator"
wifiwizard2 3.1.1 "WifiWizard2"

**Comment by jkasten2** [comment]
@codingwithashu do you get the same error if you build from the CLI from Xcode?
* If you build from Xcode make sure to open the `.xcworkspace` (not the `.xcodeproj`)
