### ISSUE TITLE
[question]:  About 24 hours later IOS users status change  from OK to  Apns Bad Device Token

### ISSUE THREAD

**Issue by bahadir1981** [OneSignal/OneSignal-Cordova-SDK#981]
### How can we help?

I am using OneSignal in my Ionic project as shown in the link below:

https://documentation.onesignal.com/docs/ionic-capacitor-cordova-sdk-setup

It works flawlessly on Android. On iOS, users are able to register and receive notifications without any issues initially. However, after approximately 24 hours, some users' status changes to 'Apns Bad Device Token', resulting in the inability to receive notifications. Reinstalling the application resolves the issue for some users, while others do not encounter any problems. This issue is occurring specifically on iOS, and I am unable to determine the root cause. Can you assist in identifying the problem?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@bahadir1981 Did the device show push notifications before it went to the "Apns Bad Device Token" status?

Also in the 24 hour period, when did the status become "Apns Bad Device Token"? After re-opening the app or after sending a notification?

**Comment by jennantilla** [comment]
Closing due to no response. @bahadir1981 if this is still a concern please comment here and we can resume investigation!
