### ISSUE TITLE
[question]: 5.1.0 version doesn't work on ionic7

### ISSUE THREAD

**Issue by comboi-app** [OneSignal/OneSignal-Cordova-SDK#984]
### How can we help?

Version 5.1.0   . Ionic 7 with Angular   

 OneSignal.initialize('XXXXXX');
 OneSignal.login(UID);
let id=await OneSignal.User.getOnesignalId();

returns null !! . In Onesignal Subscriptions doesn't exists 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @comboi-app apologies for the delay. Are you still having issues? 5.1.0 should work with Ionic; if you are still having difficulty can you please provide the [full log](https://documentation.onesignal.com/docs/capturing-a-debug-log) from your device so we can take a closer look? Thanks!

**Comment by jennantilla** [comment]
Closing due to no response.
