### ISSUE TITLE
[NSNull intValue]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by deceadmin** [OneSignal/OneSignal-Cordova-SDK#99]
Hi,
I've just upgraded both your SDK and XCode. So I do not know which one causes this error. 
My code is as follows : 
      window.plugins.OneSignal
        .startInit("xxx", "yyy")
        .handleNotificationReceived(function(jsonData) {
          alert("Notification received:\n" + JSON.stringify(jsonData));
          console.log('didReceiveRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
        })
        .endInit();

I get following error in XCode : 
[NSNull intValue]: unrecognized selector sent to instance 0x1b5771ef8
2016-10-10 16:29:03.934705 xxxx *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull intValue]: unrecognized selector sent to instance 0x1b5771ef8

**Comment by JKalash** [comment]
Hi @deceadmin,

This issue has been solved as of the latest version of the Cordova plugin. Make sure to update to see the change. The error occurred when not passing an InFocusDisplayOption on init.
